//! Stage-0 PBC anchors: lattice-summed pair FT at G=0 vs an INDEPENDENT
//! libint2 overlap construction, nonzero-G pair FT vs PySCF `ft_aopair`,
//! Ewald E_nn and Madelung vs PySCF, Ewald ω-independence, and the
//! singular-lattice error path.
//!
//! References: `testdata/reference/pbc_*.json`, generated by
//! `OPENBLAS_NUM_THREADS=1 python3 scripts/gen_pyscf_pbc_refs.py`.
//!
//! Artifact hypotheses (what a construction bug would look like):
//! * Wrong primitive/contraction normalisation or cart→sph scaling: P(0) ≠
//!   S_latt by a per-AO factor on the diagonal — caught by the G=0 anchor on
//!   EVERY element (no calibration is applied anywhere in `pair_ft`).
//! * Wrong `(−iG)^t` sign, wrong E_t for t>0, or a conjugated phase: invisible
//!   at G=0 (only E_0 survives), so the nonzero-G PySCF comparison is the
//!   test for those; it includes an off-lattice G so a result that is only
//!   right modulo reciprocal-lattice symmetry also fails.
//! * Ewald roundoff/truncation: shows up as ω-dependence.

use ferric_core::basis::bundled;
use ferric_core::elements::symbol_to_z;
use ferric_core::mol::{Atom, Molecule};
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::oneelectron::overlap;
use ferric_pbc::ewald::{ewald_nuclear_repulsion, madelung_constant};
use ferric_pbc::lattice::Cell;
use ferric_pbc::pair_ft::pair_ft;
use serde_json::Value;

const SYSTEMS: [&str; 3] = [
    "h2_sto3g_triclinic",
    "lih_sto3g_monoclinic",
    "h2o_ccpvdz_triclinic",
];

fn load_ref(name: &str) -> Value {
    let path = format!(
        "{}/../../testdata/reference/pbc_{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read {path}: {e}\nrun `python3 scripts/gen_pyscf_pbc_refs.py` first")
    });
    serde_json::from_str(&text).expect("parse pbc reference JSON")
}

fn v3(v: &Value) -> [f64; 3] {
    let a = v.as_array().expect("3-vector");
    [
        a[0].as_f64().unwrap(),
        a[1].as_f64().unwrap(),
        a[2].as_f64().unwrap(),
    ]
}

fn atom(symbol: &str, r: [f64; 3], ghost: bool) -> Atom {
    Atom {
        symbol: symbol.to_string(),
        z: symbol_to_z(symbol).expect("known element"),
        x: r[0],
        y: r[1],
        zpos: r[2],
        ghost,
        n_core_ecp: 0,
    }
}

fn cell_from_ref(r: &Value) -> Cell {
    let lat = r["lattice"].as_array().unwrap();
    let lattice = [v3(&lat[0]), v3(&lat[1]), v3(&lat[2])];
    let atoms = r["atoms"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| atom(a["symbol"].as_str().unwrap(), v3(&a["xyz_bohr"]), false))
        .collect();
    let mol = Molecule {
        atoms,
        charge: 0,
        multiplicity: 1,
    };
    Cell::new(mol, lattice).expect("valid cell")
}

/// Lattice-summed overlap Σ_L ⟨φ_m(cell 0) | φ_n(image L)⟩ built ONLY from
/// libint2 molecular overlaps: for each image, a two-cell molecule (cell 0 +
/// ghost copy shifted by L) and its off-diagonal block. The image list is a
/// brute-force integer box filtered by atom distance — no ferric-pbc code.
fn libint_lattice_overlap(cell: &Cell, basis: &str, rcut: f64) -> Vec<Vec<f64>> {
    let bs = bundled(basis).unwrap();
    let mol0 = cell.mol().clone();
    let prep0 = PreparedBasis::new(&mol0, &bs).unwrap();
    let nao = prep0.nbasis();
    let s0 = overlap(&prep0);
    let mut s = vec![vec![0.0; nao]; nao];
    for m in 0..nao {
        for n in 0..nao {
            s[m][n] = s0[(m, n)];
        }
    }
    let a = *cell.lattice();
    // |n_j| <= (rcut + ext) |b_j| / 2π, with b_j the reciprocal vectors.
    let b = cell.reciprocal();
    let pos: Vec<[f64; 3]> = mol0.atoms.iter().map(|t| [t.x, t.y, t.zpos]).collect();
    let mut ext = 0.0_f64;
    for p in &pos {
        for q in &pos {
            ext = ext.max(
                ((p[0] - q[0]).powi(2) + (p[1] - q[1]).powi(2) + (p[2] - q[2]).powi(2)).sqrt(),
            );
        }
    }
    let nmax: Vec<i64> = (0..3)
        .map(|j| {
            let bn = (b[j][0].powi(2) + b[j][1].powi(2) + b[j][2].powi(2)).sqrt();
            ((rcut + ext) * bn / (2.0 * std::f64::consts::PI)).ceil() as i64 + 1
        })
        .collect();
    let mut nimg = 0usize;
    for n0 in -nmax[0]..=nmax[0] {
        for n1 in -nmax[1]..=nmax[1] {
            for n2 in -nmax[2]..=nmax[2] {
                if n0 == 0 && n1 == 0 && n2 == 0 {
                    continue;
                }
                let l: Vec<f64> = (0..3)
                    .map(|k| n0 as f64 * a[0][k] + n1 as f64 * a[1][k] + n2 as f64 * a[2][k])
                    .collect();
                let mut dmin = f64::INFINITY;
                for p in &pos {
                    for q in &pos {
                        let d = ((p[0] - q[0] - l[0]).powi(2)
                            + (p[1] - q[1] - l[1]).powi(2)
                            + (p[2] - q[2] - l[2]).powi(2))
                        .sqrt();
                        dmin = dmin.min(d);
                    }
                }
                if dmin > rcut {
                    continue;
                }
                nimg += 1;
                let mut atoms = mol0.atoms.clone();
                for t in &mol0.atoms {
                    atoms.push(atom(
                        &t.symbol,
                        [t.x + l[0], t.y + l[1], t.zpos + l[2]],
                        true,
                    ));
                }
                let pair = Molecule {
                    atoms,
                    charge: 0,
                    multiplicity: 1,
                };
                let prep = PreparedBasis::new(&pair, &bs).unwrap();
                assert_eq!(prep.nbasis(), 2 * nao);
                let sp = overlap(&prep);
                for m in 0..nao {
                    for n in 0..nao {
                        s[m][n] += sp[(m, nao + n)];
                    }
                }
            }
        }
    }
    assert!(nimg > 0);
    s
}

fn min_exponent(basis: &str, cell: &Cell) -> f64 {
    let bs = bundled(basis).unwrap();
    cell.mol()
        .atoms
        .iter()
        .flat_map(|t| bs.for_element(t.z).unwrap().iter())
        .flat_map(|sh| sh.exponents.iter().copied())
        .fold(f64::INFINITY, f64::min)
}

/// EXACTNESS ANCHOR: P(G=0) is the lattice-summed overlap, element by element.
#[test]
fn pair_ft_at_g0_equals_independent_libint_lattice_overlap() {
    for name in SYSTEMS {
        let r = load_ref(name);
        let basis = r["basis"].as_str().unwrap();
        let cell = cell_from_ref(&r);
        let bs = bundled(basis).unwrap();
        let prep = PreparedBasis::new(cell.mol(), &bs).unwrap();
        let nao = prep.nbasis();
        assert_eq!(
            nao as u64,
            r["nao"].as_u64().unwrap(),
            "{name}: AO count vs PySCF"
        );

        let p = pair_ft(&cell, &prep, &[[0.0; 3]]).unwrap();
        // Independent image range: 2 Bohr beyond the one pair_ft derives.
        let amin = min_exponent(basis, &cell);
        let rcut = (2.0 * (1e3_f64 / 1e-15).ln() / amin).sqrt() + 4.0;
        let s = libint_lattice_overlap(&cell, basis, rcut);
        let s_pyscf = r["ovlp_latt"].as_array().unwrap();

        let (mut err, mut err_im, mut err_py) = (0.0_f64, 0.0_f64, 0.0_f64);
        for m in 0..nao {
            for n in 0..nao {
                let z = p[[m, n, 0]];
                err = err.max((z.re - s[m][n]).abs());
                err_im = err_im.max(z.im.abs());
                let sp = s_pyscf[m].as_array().unwrap()[n].as_f64().unwrap();
                err_py = err_py.max((s[m][n] - sp).abs());
            }
        }
        eprintln!(
            "{name}: nao={nao} max|Re P(0) - S_latt(libint)| = {err:.2e}, max|Im P(0)| = {err_im:.2e}, \
             max|S_latt(libint) - S_latt(PySCF)| = {err_py:.2e}"
        );
        assert!(
            err < 1e-10,
            "{name}: P(0) vs libint lattice overlap {err:.3e}"
        );
        assert!(err_im < 1e-12, "{name}: Im P(0) {err_im:.3e}");
        assert!(
            err_py < 1e-10,
            "{name}: libint S_latt vs PySCF pbc_intor {err_py:.3e}"
        );
    }
}

/// Nonzero G (reciprocal-lattice AND off-lattice) vs PySCF ft_aopair — the
/// only check that sees the (−iG)^t sign, E_{t>0} and the phase convention.
#[test]
fn pair_ft_at_nonzero_g_matches_pyscf_ft_aopair() {
    for name in SYSTEMS {
        let r = load_ref(name);
        let basis = r["basis"].as_str().unwrap();
        let cell = cell_from_ref(&r);
        let bs = bundled(basis).unwrap();
        let prep = PreparedBasis::new(cell.mol(), &bs).unwrap();
        let nao = prep.nbasis();
        let gv: Vec<[f64; 3]> = r["gvectors"].as_array().unwrap().iter().map(v3).collect();
        assert!(
            gv.iter().all(|g| g.iter().any(|x| x.abs() > 1e-3)),
            "all G nonzero"
        );
        let p = pair_ft(&cell, &prep, &gv).unwrap();
        let re = r["pair_ft_re"].as_array().unwrap();
        let im = r["pair_ft_im"].as_array().unwrap();
        let mut err = 0.0_f64;
        let mut big = 0.0_f64;
        for g in 0..gv.len() {
            for m in 0..nao {
                for n in 0..nao {
                    let want_re = re[g][m][n].as_f64().unwrap();
                    let want_im = im[g][m][n].as_f64().unwrap();
                    let z = p[[m, n, g]];
                    err = err.max((z.re - want_re).abs()).max((z.im - want_im).abs());
                    big = big.max(want_im.abs());
                }
            }
        }
        eprintln!(
            "{name}: max|P - P_pyscf| over {} G = {err:.2e} (max|Im P_pyscf| = {big:.2e})",
            gv.len()
        );
        // The reference must actually exercise the imaginary part.
        assert!(
            big > 1e-3,
            "{name}: reference has no imaginary part; test is vacuous"
        );
        assert!(err < 1e-10, "{name}: pair FT vs PySCF {err:.3e}");
    }
}

#[test]
fn ewald_matches_pyscf_and_is_omega_independent() {
    for name in SYSTEMS {
        let r = load_ref(name);
        let cell = cell_from_ref(&r);
        let want = r["energy_nuc"].as_f64().unwrap();
        let es: Vec<f64> = [0.8, 1.5, 3.0]
            .iter()
            .map(|&w| ewald_nuclear_repulsion(&cell, w).unwrap())
            .collect();
        let spread = es.iter().cloned().fold(f64::NEG_INFINITY, f64::max)
            - es.iter().cloned().fold(f64::INFINITY, f64::min);
        eprintln!("{name}: E_nn(ω=0.8,1.5,3) = {es:?}, PySCF {want:.14}, ω-spread {spread:.2e}");
        assert!(spread < 1e-12, "{name}: Ewald ω-dependence {spread:.3e}");
        for e in &es {
            assert!((e - want).abs() < 1e-10, "{name}: E_nn {e} vs PySCF {want}");
        }
    }
}

#[test]
fn madelung_matches_pyscf() {
    for name in SYSTEMS {
        let r = load_ref(name);
        let cell = cell_from_ref(&r);
        let want = r["madelung"].as_f64().unwrap();
        let got = madelung_constant(&cell).unwrap();
        eprintln!("{name}: madelung {got:.14} vs PySCF {want:.14}");
        assert!(
            (got - want).abs() < 1e-11,
            "{name}: madelung {got} vs {want}"
        );
    }
    // Textbook anchor independent of PySCF bookkeeping: simple cubic with a
    // neutralising background, E = −1.4186487397/a per unit charge, so
    // v_M = 2.8372974794806/a (PySCF printed 2.8372974794806196 at a = 3).
    let mol = Molecule {
        atoms: vec![atom("H", [0.0; 3], false)],
        charge: 0,
        multiplicity: 2,
    };
    let a = 3.0;
    let sc = Cell::new(mol, [[a, 0.0, 0.0], [0.0, a, 0.0], [0.0, 0.0, a]]).unwrap();
    let got = madelung_constant(&sc).unwrap() * a;
    assert!(
        (got - 2.837_297_479_480_619_6).abs() < 1e-11,
        "sc madelung*a = {got}"
    );
}

#[test]
fn singular_or_nonfinite_lattice_is_an_error() {
    let mol = Molecule {
        atoms: vec![atom("H", [0.0; 3], false)],
        charge: 0,
        multiplicity: 2,
    };
    // a3 = a1 + a2: exactly coplanar.
    assert!(Cell::new(
        mol.clone(),
        [[4.0, 0.0, 0.0], [0.8, 4.2, 0.0], [4.8, 4.2, 0.0]]
    )
    .is_err());
    // A zero lattice vector.
    assert!(Cell::new(mol.clone(), [[4.0, 0.0, 0.0], [0.0; 3], [0.0, 0.0, 4.0]]).is_err());
    // Nearly coplanar (sine ~1e-13).
    assert!(Cell::new(
        mol.clone(),
        [[4.0, 0.0, 0.0], [0.0, 4.0, 0.0], [1.0, 1.0, 4e-13]]
    )
    .is_err());
    // Non-finite.
    assert!(Cell::new(
        mol.clone(),
        [[f64::NAN, 0.0, 0.0], [0.0, 4.0, 0.0], [0.0, 0.0, 4.0]]
    )
    .is_err());
    // Control: the same molecule in a valid cell is accepted.
    assert!(Cell::new(mol, [[4.0, 0.0, 0.0], [0.0, 4.0, 0.0], [0.0, 0.0, 4.0]]).is_ok());
}

#[test]
fn pair_ft_rejects_a_basis_not_on_the_cell_atoms() {
    let r = load_ref("h2_sto3g_triclinic");
    let cell = cell_from_ref(&r);
    let mut moved = cell.mol().clone();
    moved.atoms[1].x += 0.5;
    let bs = bundled("sto-3g").unwrap();
    let prep = PreparedBasis::new(&moved, &bs).unwrap();
    assert!(pair_ft(&cell, &prep, &[[0.0; 3]]).is_err());
}
