[package]
name = "ferric-mp2"
version = "0.1.0"
edition = "2021"

[dependencies]
ferric-core = { path = "../ferric-core" }
ferric-integrals = { path = "../ferric-integrals" }
ferric-scf = { path = "../ferric-scf" }
ferric-tensors = { path = "../ferric-tensors" }
ferric-quadrature = { path = "../ferric-quadrature" }
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
rayon = { workspace = true }
mpi = { version = "0.7", optional = true }

[features]
default = []
mpi = ["dep:mpi"]

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
