[package]
name = "ferric-gw"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ferric-core = { path = "../ferric-core" }
ferric-integrals = { path = "../ferric-integrals" }
ferric-scf = { path = "../ferric-scf" }
ferric-mp2 = { path = "../ferric-mp2" }
ferric-rpa = { path = "../ferric-rpa" }
ferric-quadrature = { path = "../ferric-quadrature" }
ferric-dft = { path = "../ferric-dft" }
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
num-complex = "0.4"
openblas-src = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
