//! wB97X-V end-to-end validation against PySCF.
//!
//! Exercises the full RSH-with-VV10 path:
//!   * RI-J for Coulomb (df_j_aux)
//!   * RI-K for short- and long-range exact exchange (df_k_aux) via
//!     Operator::erfc(ω) / Operator::erf(ω)
//!   * Hybrid GGA semilocal (HYB_GGA_XC_WB97X_V via libxc)
//!   * VV10 nonlocal correlation (C=0.01, b=6.0)
//!
//! References generated by `scripts/gen_pyscf_dft_refs.py wb97x-v`.

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::rhf::{solve_rhf, RhfConfig};
use ferric_scf::screening::SchwarzBounds;
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Ref {
    e_total: f64,
    #[serde(default)]
    converged: bool,
}

/// wB97X-V stacks four numerical sources of µHa-scale error:
///   1. Main-grid integration of the hybrid semilocal piece (~3e-6 like LDA/PBE)
///   2. Two RI-K builds (erf + erfc) with the JK-fit aux basis
///   3. NLC grid (50, 50) integration of the VV10 nonlocal piece
///   4. O(N²) VV10 pair sum at single precision in the kernel
///      5e-5 Ha gives a comfortable single-µHa-scale margin over all of these.
const TOL: f64 = 5e-5;

fn ref_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/reference")
        .join(name)
}

fn run_case(label: &str, xyz: &str, expected_file: &str) {
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let bs = basis::bundled("cc-pvdz").unwrap();
    let obs = PreparedBasis::new(&mol, &bs).unwrap();
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let ctx = ParallelContext::default();

    let cfg = RhfConfig {
        xc: Some("wB97X-V".into()),
        df_j_aux: Some("def2-universal-jkfit".into()),
        df_k_aux: Some("def2-universal-jkfit".into()),
        energy_conv: 1e-10,
        density_conv: 1e-8,
        ..Default::default()
    };
    let res = solve_rhf(&ctx, &mol, &obs, op, &bounds, &cfg).unwrap();

    let r: Ref =
        serde_json::from_str(&fs::read_to_string(ref_path(expected_file)).unwrap()).unwrap();
    assert!(r.converged, "PySCF reference {} not converged", expected_file);

    let err = (res.energy - r.e_total).abs();
    eprintln!(
        "[{label}] ferric = {:.10} Ha,  PySCF = {:.10} Ha,  err = {err:.2e}",
        res.energy, r.e_total
    );
    // Full-precision print for bit-level cross-run comparison.
    eprintln!("[{label}] ferric full precision = {:.17e} Ha", res.energy);
    assert!(
        err < TOL,
        "wB97X-V E_total mismatch for {label}: err = {err:.2e} (ferric={:.10}, pyscf={:.10})",
        res.energy, r.e_total
    );
}

#[test]
fn wb97xv_h2() {
    run_case("H2", "2\nH2\nH 0 0 0\nH 0 0 0.74\n", "h2_cc-pvdz_wb97x_v.json");
}

#[test]
fn wb97xv_water() {
    run_case(
        "H2O",
        "3\nH2O\nO 0 0 0\nH 0 0.7572 0.5868\nH 0 -0.7572 0.5868\n",
        "h2o_cc-pvdz_wb97x_v.json",
    );
}

#[test]
fn wb97xv_methane() {
    let xyz = "5\nCH4\nC 0 0 0\n\
               H 0.6276 0.6276 0.6276\n\
               H -0.6276 -0.6276 0.6276\n\
               H -0.6276 0.6276 -0.6276\n\
               H 0.6276 -0.6276 -0.6276\n";
    run_case("CH4", xyz, "methane_cc-pvdz_wb97x_v.json");
}
