//! Validate ferric KS gradient against PySCF reference at cc-pVDZ.
//!
//! References generated by `scripts/gen_pyscf_dft_grad_refs.py`. PySCF is run
//! with the same ferric-matching settings as the energy refs (RI-J via
//! density_fit, (75,110) grid, prune=None, Becke 1988 radii_adjust) plus
//! `Gradients.grid_response = False` — matching ferric's no-grid-response
//! analytical formula.

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::ks_gradient::ks_gradient_closed;
use ferric_scf::rhf::{solve_rhf, RhfConfig};
use ferric_scf::screening::SchwarzBounds;
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct GradRef {
    grad: Vec<[f64; 3]>,
    #[serde(default)]
    converged: bool,
}

fn ref_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/reference")
        .join(name)
}

fn run_case(label: &str, xyz: &str, xc: &str, hybrid: bool, ref_file: &str, tol: f64) {
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let bs = basis::bundled("cc-pvdz").unwrap();
    let prep = PreparedBasis::new(&mol, &bs).unwrap();
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &prep).unwrap();

    let cfg = RhfConfig {
        xc: Some(xc.into()),
        df_j_aux: Some("def2-universal-jkfit".into()),
        df_k_aux: if hybrid { Some("def2-universal-jkfit".into()) } else { None },
        energy_conv: 1e-10,
        density_conv: 1e-8,
        ..Default::default()
    };
    let res = solve_rhf(&ParallelContext::default(), &mol, &prep, op, &bounds, &cfg).unwrap();
    let g_ferric = ks_gradient_closed(&mol, &prep, &bs, op, &bounds, xc, &res).unwrap();

    let r: GradRef =
        serde_json::from_str(&fs::read_to_string(ref_path(ref_file)).unwrap()).unwrap();
    assert!(r.converged, "PySCF reference {ref_file} not converged");

    eprintln!("=== {label} {xc} ferric vs PySCF (cc-pVDZ) ===");
    let mut max_diff = 0.0_f64;
    for a in 0..mol.atoms.len() {
        for c in 0..3 {
            let diff = (g_ferric[(a, c)] - r.grad[a][c]).abs();
            if diff > max_diff { max_diff = diff; }
            eprintln!(
                "  atom={a} coord={c}: ferric={:+.6e} pyscf={:+.6e} diff={:.2e}",
                g_ferric[(a, c)], r.grad[a][c], diff
            );
        }
    }
    eprintln!("  max diff: {max_diff:.2e}, tol: {tol:.0e}");
    for a in 0..mol.atoms.len() {
        for c in 0..3 {
            let diff = (g_ferric[(a, c)] - r.grad[a][c]).abs();
            assert!(diff < tol, "{label} {xc}: atom={a} coord={c} diff={diff:.2e}");
        }
    }
}

#[test]
fn lda_h2_ccpvdz_vs_pyscf_grad() {
    run_case("H2", "2\nH2\nH 0 0 0\nH 0 0 0.74\n",
             "LDA", false, "h2_cc-pvdz_lda_grad.json", 1e-4);
}

#[test]
fn lda_h2o_ccpvdz_vs_pyscf_grad() {
    run_case("H2O",
             "3\nH2O\nO 0 0 0\nH 0 0.7572 0.5868\nH 0 -0.7572 0.5868\n",
             "LDA", false, "h2o_cc-pvdz_lda_grad.json", 1e-4);
}

#[test]
fn pbe_h2_ccpvdz_vs_pyscf_grad() {
    run_case("H2", "2\nH2\nH 0 0 0\nH 0 0 0.74\n",
             "PBE", false, "h2_cc-pvdz_pbe_grad.json", 1e-4);
}

#[test]
fn pbe_h2o_ccpvdz_vs_pyscf_grad() {
    run_case("H2O",
             "3\nH2O\nO 0 0 0\nH 0 0.7572 0.5868\nH 0 -0.7572 0.5868\n",
             "PBE", false, "h2o_cc-pvdz_pbe_grad.json", 1e-4);
}

#[test]
fn b3lyp_h2_ccpvdz_vs_pyscf_grad() {
    run_case("H2", "2\nH2\nH 0 0 0\nH 0 0 0.74\n",
             "B3LYP", true, "h2_cc-pvdz_b3lyp_grad.json", 1e-4);
}

#[test]
fn b3lyp_h2o_ccpvdz_vs_pyscf_grad() {
    run_case("H2O",
             "3\nH2O\nO 0 0 0\nH 0 0.7572 0.5868\nH 0 -0.7572 0.5868\n",
             "B3LYP", true, "h2o_cc-pvdz_b3lyp_grad.json", 1e-4);
}

#[test]
fn wb97xv_h2_ccpvdz_vs_pyscf_grad() {
    run_case("H2", "2\nH2\nH 0 0 0\nH 0 0 0.74\n",
             "wB97X-V", true, "h2_cc-pvdz_wb97x_v_grad.json", 2e-4);
}

#[test]
fn wb97xv_h2o_ccpvdz_vs_pyscf_grad() {
    run_case("H2O",
             "3\nH2O\nO 0 0 0\nH 0 0.7572 0.5868\nH 0 -0.7572 0.5868\n",
             "wB97X-V", true, "h2o_cc-pvdz_wb97x_v_grad.json", 2e-4);
}
