//! Meta-GGA (SCAN / r2SCAN) SCF energy validation against PySCF references.
//!
//! Phase A: single-point energy only. Exercises the τ (kinetic-energy density)
//! path through `KsXc` — `eval_tau_closed`, the meta-GGA libxc evaluation
//! (`eval_mgga_unpolarized`), and the τ-dependent V_xc assembly branch in
//! `semilocal_vxc_closed_scratch`.
//!
//! References generated by `scripts/gen_pyscf_mgga_refs.py` with the same
//! ferric-matching settings as the LDA/PBE tests (RI-J Coulomb via
//! def2-universal-jkfit, Becke-1988 partition, flat (75, 110) Lebedev grid,
//! conv_tol 1e-10). This is the first meta-GGA reference in the suite.

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::rhf::{solve_rhf, RhfConfig};
use ferric_scf::screening::SchwarzBounds;
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Ref {
    e_total: f64,
    #[serde(default)]
    converged: bool,
}

/// Meta-GGA grid integration is more sensitive than GGA (τ adds first-MO-
/// derivative structure to the integrand), so this first-ever meta-GGA test
/// uses a slightly looser tolerance than the 2e-5 GGA/PBE bar. The MEASURED
/// worst-case (all four cases) is ~1.4e-8 Ha vs PySCF — far inside this 1e-4
/// bar; the margin is deliberate headroom for the first meta-GGA reference, not
/// a masked disagreement. Do NOT silently widen further — drift indicates a
/// real regression.
const TOL: f64 = 1e-4;

/// Meta-GGA SCF is stiffer than LDA/GGA — the τ-dependent Fock amplifies the
/// grid-integration noise, so the total energy parks on a ~1e-8 Ha noise floor
/// that a 1e-10 energy criterion can never clear (it limit-cycles). These are
/// the meta-GGA-appropriate thresholds (energy 1e-8, density 1e-7); combined
/// with solve_rhf's default meta-GGA level shift they converge in ~10-12 iters.
const ENERGY_CONV: f64 = 1e-8;
const DENSITY_CONV: f64 = 1e-7;

fn ref_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/reference")
        .join(name)
}

fn run_case(label: &str, xyz: &str, xc: &str, expected_file: &str) {
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let bs = basis::bundled("cc-pvdz").unwrap();
    let obs = PreparedBasis::new(&mol, &bs).unwrap();
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let ctx = ParallelContext::default();

    let cfg = RhfConfig {
        xc: Some(xc.into()),
        df_j_aux: Some("def2-universal-jkfit".into()),
        energy_conv: ENERGY_CONV,
        density_conv: DENSITY_CONV,
        ..Default::default()
    };
    let res = solve_rhf(&ctx, &mol, &obs, op, &bounds, &cfg).unwrap();

    let r: Ref =
        serde_json::from_str(&fs::read_to_string(ref_path(expected_file)).unwrap()).unwrap();
    assert!(r.converged, "PySCF reference {} not converged", expected_file);
    assert!(res.converged, "ferric {xc} SCF for {label} did not converge");

    let err = (res.energy - r.e_total).abs();
    eprintln!(
        "[{label}/{xc}] ferric = {:.10} Ha,  PySCF = {:.10} Ha,  err = {err:.2e}",
        res.energy, r.e_total
    );
    assert!(
        err < TOL,
        "{xc} E_total mismatch for {label}: err = {err:.2e} (ferric={:.10}, pyscf={:.10})",
        res.energy, r.e_total
    );
}

const H2: &str = "2\nH2\nH 0 0 0\nH 0 0 0.74\n";
const H2O: &str = "3\nH2O\nO 0 0 0\nH 0 0.7572 0.5868\nH 0 -0.7572 0.5868\n";
const CH4: &str = "5\nCH4\nC 0 0 0\n\
                   H 0.6276 0.6276 0.6276\n\
                   H -0.6276 -0.6276 0.6276\n\
                   H -0.6276 0.6276 -0.6276\n\
                   H 0.6276 -0.6276 -0.6276\n";

#[test]
fn scan_h2() {
    run_case("H2", H2, "SCAN", "h2_cc-pvdz_scan.json");
}

#[test]
fn scan_water() {
    run_case("H2O", H2O, "SCAN", "h2o_cc-pvdz_scan.json");
}

#[test]
fn scan_methane() {
    run_case("CH4", CH4, "SCAN", "methane_cc-pvdz_scan.json");
}

#[test]
fn r2scan_h2() {
    run_case("H2", H2, "r2SCAN", "h2_cc-pvdz_r2scan.json");
}

#[test]
fn r2scan_water() {
    run_case("H2O", H2O, "r2SCAN", "h2o_cc-pvdz_r2scan.json");
}

#[test]
fn r2scan_methane() {
    run_case("CH4", CH4, "r2SCAN", "methane_cc-pvdz_r2scan.json");
}

/// Phase A is energy-only: a meta-GGA nuclear gradient must be a CLEAN error
/// (not a panic and not a silently-wrong number that drops the τ term). The
/// τ-dependent gradient is Phase B.
#[test]
fn scan_gradient_is_rejected_cleanly() {
    use ferric_scf::ks_gradient::ks_gradient_closed;

    let mol = Molecule::parse_xyz(H2, 0, 1).unwrap();
    let bs = basis::bundled("cc-pvdz").unwrap();
    let obs = PreparedBasis::new(&mol, &bs).unwrap();
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let ctx = ParallelContext::default();

    let cfg = RhfConfig {
        xc: Some("SCAN".into()),
        df_j_aux: Some("def2-universal-jkfit".into()),
        energy_conv: ENERGY_CONV,
        density_conv: DENSITY_CONV,
        ..Default::default()
    };
    let res = solve_rhf(&ctx, &mol, &obs, op, &bounds, &cfg).unwrap();

    let grad = ks_gradient_closed(&mol, &obs, &bs, op, &bounds, "SCAN", &res, None);
    let err = grad.expect_err("meta-GGA gradient must be rejected, not returned");
    let msg = format!("{err:?}");
    assert!(
        msg.contains("meta-GGA") && msg.to_lowercase().contains("gradient"),
        "unexpected error message for rejected meta-GGA gradient: {msg}"
    );
}
