//! PBE validation against PySCF reference energies.
//!
//! Exercises the GGA path through `KsXc`: density gradient, σ = |∇ρ|²,
//! GGA libxc evaluation, and the gradient-dependent V_xc assembly.
//! References generated by `scripts/gen_pyscf_dft_refs.py pbe` with the
//! same ferric-matching settings as the LDA test (RI-J, Becke partition,
//! Lebedev-110).

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::ladder::{default_ladder_from, solve_rhf_ladder};
use ferric_scf::rhf::RhfConfig;
use ferric_scf::screening::SchwarzBounds;
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Ref {
    e_total: f64,
    #[serde(default)]
    converged: bool,
}

/// Tolerance is set just above the measured worst-case for LDA (~3e-6 Ha).
/// GGA gradient terms add modest extra numerical noise versus LDA, so 2e-5
/// gives a small margin. Do NOT silently widen — drift indicates regression.
const TOL: f64 = 2e-5;

fn ref_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/reference")
        .join(name)
}

fn run_case(label: &str, xyz: &str, expected_file: &str) {
    run_case_basis(label, xyz, "cc-pvdz", expected_file);
}

fn run_case_basis(label: &str, xyz: &str, basis_name: &str, expected_file: &str) {
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let bs = basis::bundled(basis_name).unwrap();
    let obs = PreparedBasis::new(&mol, &bs).unwrap();
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let ctx = ParallelContext::default();

    // SCF ladder, not plain solve_rhf: matches the CLI's actual ksdft path
    // and is needed for correctness, not just speed -- measured that plain
    // DIIS from the default guess lands NH3/PBE in a wrong SCF solution
    // (err=7.16e-3 Ha vs PySCF) while the ladder reaches the true ground
    // state (err ~2.7e-9 Ha). See dft_lda.rs's module doc for the fuller
    // writeup (same fix applied there for a different failure mode).
    //
    // NOT gating on lr.converged: NH3/def2-SVP and H2O/def2-SVP reach the
    // correct energy (err ≤2.1e-8 Ha) but still report converged=false at
    // the ladder's final rung -- the same benign density-oscillation floor
    // documented in dft_lda.rs, here appearing on def2-SVP specifically
    // rather than being LDA-specific. The energy comparison below is the
    // real correctness gate.
    let cfg = RhfConfig {
        xc: Some("PBE".into()),
        df_j_aux: Some("def2-universal-jkfit".into()),
        energy_conv: 1e-10,
        density_conv: 1e-8,
        ..Default::default()
    };
    let ladder = default_ladder_from(&cfg);
    let lr = solve_rhf_ladder(&ctx, &mol, &obs, op, &bounds, &ladder).unwrap();
    let res = lr.result;

    let r: Ref =
        serde_json::from_str(&fs::read_to_string(ref_path(expected_file)).unwrap()).unwrap();
    assert!(r.converged, "PySCF reference {} not converged", expected_file);

    let err = (res.energy - r.e_total).abs();
    eprintln!(
        "[{label}] ferric = {:.10} Ha,  PySCF = {:.10} Ha,  err = {err:.2e}, ladder_converged={}, rung={}",
        res.energy, r.e_total, lr.converged, lr.rung_reached
    );
    assert!(
        err < TOL,
        "PBE E_total mismatch for {label}: err = {err:.2e} (ferric={:.10}, pyscf={:.10})",
        res.energy, r.e_total
    );
}

#[test]
fn pbe_h2() {
    run_case("H2", "2\nH2\nH 0 0 0\nH 0 0 0.74\n", "h2_cc-pvdz_pbe.json");
}

#[test]
fn pbe_water() {
    run_case(
        "H2O",
        "3\nH2O\nO 0 0 0\nH 0 0.7572 0.5868\nH 0 -0.7572 0.5868\n",
        "h2o_cc-pvdz_pbe.json",
    );
}

#[test]
fn pbe_methane() {
    let xyz = "5\nCH4\nC 0 0 0\n\
               H 0.6276 0.6276 0.6276\n\
               H -0.6276 -0.6276 0.6276\n\
               H -0.6276 0.6276 -0.6276\n\
               H 0.6276 -0.6276 -0.6276\n";
    run_case("CH4", xyz, "methane_cc-pvdz_pbe.json");
}

const NH3_XYZ: &str = "4\nNH3\n\
    N 0.000000 0.000000 0.116489\n\
    H 0.000000 0.939731 -0.271808\n\
    H 0.813831 -0.469865 -0.271808\n\
    H -0.813831 -0.469865 -0.271808\n";

/// Fourth molecule (widens past H2/H2O/CH4): NH3, C3v.
#[test]
fn pbe_nh3() {
    run_case("NH3", NH3_XYZ, "nh3_cc-pvdz_pbe.json");
}

/// Second basis (widens past cc-pVDZ-only) across all four molecules.
#[test]
fn pbe_h2_def2svp() {
    run_case_basis("H2", "2\nH2\nH 0 0 0\nH 0 0 0.74\n", "def2-svp", "h2_def2-svp_pbe.json");
}

#[test]
fn pbe_water_def2svp() {
    run_case_basis(
        "H2O",
        "3\nH2O\nO 0 0 0\nH 0 0.7572 0.5868\nH 0 -0.7572 0.5868\n",
        "def2-svp",
        "h2o_def2-svp_pbe.json",
    );
}

#[test]
fn pbe_methane_def2svp() {
    let xyz = "5\nCH4\nC 0 0 0\n\
               H 0.6276 0.6276 0.6276\n\
               H -0.6276 -0.6276 0.6276\n\
               H -0.6276 0.6276 -0.6276\n\
               H 0.6276 -0.6276 -0.6276\n";
    run_case_basis("CH4", xyz, "def2-svp", "methane_def2-svp_pbe.json");
}

#[test]
fn pbe_nh3_def2svp() {
    run_case_basis("NH3", NH3_XYZ, "def2-svp", "nh3_def2-svp_pbe.json");
}
