//! Atomic ionization-potential anchor for the HeNe⁺ cDFT-ET lane.
//!
//! # Why this test exists
//!
//! Every assertion currently made about the HeNe⁺ charge-transfer diabats is
//! *internal*: self-consistency conditions, identities, and comparisons of
//! ferric against ferric. None of them is referenced to anything outside the
//! code, so none of them can catch a systematic error.
//!
//! The one quantity in that lane which is both (a) load-bearing and (b)
//! trivially checkable against an independent program is the **asymptote** of
//! the diabatic gap:
//!
//! ```text
//!   ΔE(R → ∞)  =  ΔIP  =  [E(He⁺) + E(Ne)] − [E(He) + E(Ne⁺)]
//! ```
//!
//! At infinite separation the two diabats are just non-interacting atoms, the
//! constraint does no work, and the gap is a pure difference of atomic
//! ionization potentials. That number needs **four isolated-atom UHF runs and
//! no cDFT at all**, and PySCF computes exactly the same thing.
//!
//! So this file pins ferric's four atomic energies — and their ΔIP combination
//! — against PySCF UHF/def2-SVP. If ferric and PySCF disagree on an isolated
//! two-electron atom, nothing downstream in the HeNe⁺ lane is interpretable,
//! and this test says so loudly before any cDFT number is trusted.
//!
//! # Reference data
//!
//! PySCF 2.13.0, `scf.UHF`, basis `def2-svp`, `conv_tol = 1e-12`,
//! `conv_tol_grad = 1e-9`. Generated by
//! `scripts/gen_pyscf_atomic_ip_refs.py`. Multiplicities: He and Ne are
//! singlets (`spin = 0`), He⁺ and Ne⁺ are doublets (`spin = 1`).
//!
//! # Scope
//!
//! This is the *method-consistent* ΔIP, not the experimental one. The
//! experimental atomic difference is IP(He) − IP(Ne) = 24.587 − 21.565 =
//! 3.022 eV; UHF/def2-SVP lands near 3.63 eV. That ~0.6 eV offset is the
//! expected signature of a correlation-free method in a basis with no diffuse
//! functions, and it is the number a cDFT gap computed with the *same* method
//! must asymptote to — the experimental value is not the target here.

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::rhf::RhfConfig;
use ferric_scf::screening::SchwarzBounds;
use ferric_scf::uhf::solve_uhf;

/// Hartree → electron-volt (CODATA 2018, as used elsewhere in ferric).
const HA2EV: f64 = 27.211_386_245_988;

/// PySCF 2.13.0 UHF/def2-SVP total energies for the isolated atoms (Hartree).
/// See the module docs for the exact PySCF settings.
const E_HE_PYSCF: f64 = -2.855_160_479_347;
const E_HE_CATION_PYSCF: f64 = -1.993_623_160_423;
const E_NE_PYSCF: f64 = -128.376_406_810_031;
const E_NE_CATION_PYSCF: f64 = -127.648_287_776_274;

/// Agreement bar against PySCF. Both programs converge the same variational
/// problem in the same basis, so the only residual is SCF convergence and
/// arithmetic ordering — this bar is met with room to spare, and the
/// `..._tolerance_is_violable` test below shows it is not vacuous.
const TOL_HA: f64 = 1e-6;

/// Run isolated-atom UHF/def2-SVP.
///
/// `charge` and `multiplicity` are passed straight through to `Molecule`, so
/// the caller is responsible for a physical pairing — He⁺ is a doublet, not a
/// singlet. A mis-paired (charge, multiplicity) still converges smoothly to
/// the *wrong* energy, which is precisely the failure mode the PySCF
/// cross-check exists to catch.
fn atom_uhf(symbol: &str, charge: i32, multiplicity: usize) -> f64 {
    let xyz = format!("1\n{symbol} atom\n{symbol} 0.0 0.0 0.0\n");
    let mol = Molecule::parse_xyz(&xyz, charge, multiplicity).unwrap();
    let bs = basis::bundled("def2-svp").unwrap();
    let prep = PreparedBasis::new(&mol, &bs).unwrap();
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &prep).unwrap();
    let config = RhfConfig {
        energy_conv: 1e-11,
        density_conv: 1e-9,
        max_iter: 200,
        ..Default::default()
    };
    let ctx = ParallelContext::default();
    let res = solve_uhf(&ctx, &mol, &prep, &bounds, &config).unwrap();
    assert!(
        res.converged,
        "UHF/def2-SVP did not converge for {symbol} (charge {charge}, mult {multiplicity}): {:?}",
        res.exit
    );
    res.energy
}

/// The four atomic energies, in the order (He, He⁺, Ne, Ne⁺).
fn atomic_energies() -> [f64; 4] {
    [
        atom_uhf("He", 0, 1),
        atom_uhf("He", 1, 2),
        atom_uhf("Ne", 0, 1),
        atom_uhf("Ne", 1, 2),
    ]
}

/// **The anchor.** ferric's four isolated-atom UHF/def2-SVP energies match
/// PySCF to 1e-6 Ha, and the resulting ΔIP — the R → ∞ limit of the HeNe⁺
/// diabatic gap — is positive and matches PySCF's ΔIP to the same bar.
///
/// ΔIP > 0 is the physically required sign: helium is harder to ionize than
/// neon (IP 24.587 vs 21.565 eV experimentally), so the state carrying the
/// hole on He lies *above* the state carrying it on Ne.
#[test]
fn hene_plus_atomic_ip_difference_anchor() {
    let [e_he, e_he_cat, e_ne, e_ne_cat] = atomic_energies();

    let refs = [
        ("He ", e_he, E_HE_PYSCF),
        ("He+", e_he_cat, E_HE_CATION_PYSCF),
        ("Ne ", e_ne, E_NE_PYSCF),
        ("Ne+", e_ne_cat, E_NE_CATION_PYSCF),
    ];
    for (label, ferric, pyscf) in refs {
        let diff = ferric - pyscf;
        eprintln!("{label}  ferric = {ferric:.12}  pyscf = {pyscf:.12}  diff = {diff:+.3e} Ha");
        assert!(
            diff.abs() < TOL_HA,
            "{label} UHF/def2-SVP: ferric {ferric:.12} vs PySCF {pyscf:.12}, \
             diff {diff:+.3e} Ha exceeds {TOL_HA:.1e}. \
             A disagreement on an ISOLATED ATOM invalidates every downstream \
             HeNe+ diabat number — fix this before interpreting any cDFT result."
        );
    }

    // ΔIP = [E(He+) + E(Ne)] − [E(He) + E(Ne+)], the R → ∞ diabatic gap.
    let dip = (e_he_cat + e_ne) - (e_he + e_ne_cat);
    let dip_ref = (E_HE_CATION_PYSCF + E_NE_PYSCF) - (E_HE_PYSCF + E_NE_CATION_PYSCF);
    eprintln!(
        "dIP  ferric = {dip:.12} Ha ({:.6} eV)   pyscf = {dip_ref:.12} Ha ({:.6} eV)   diff = {:+.3e} Ha",
        dip * HA2EV,
        dip_ref * HA2EV,
        dip - dip_ref
    );
    eprintln!(
        "     experimental IP(He)-IP(Ne) = 3.022 eV; method offset = {:+.3} eV",
        dip * HA2EV - 3.022
    );

    assert!(
        dip > 0.0,
        "dIP must be positive (He is harder to ionize than Ne), got {dip:.12} Ha"
    );
    assert!(
        (dip - dip_ref).abs() < TOL_HA,
        "dIP: ferric {dip:.12} vs PySCF {dip_ref:.12} Ha, diff {:+.3e} exceeds {TOL_HA:.1e}",
        dip - dip_ref
    );

    // Magnitude sanity: O(3-4 eV). This is a loose bracket, not a precision
    // claim — it exists so that a sign-preserving but grossly wrong dIP (e.g.
    // from a mis-assigned multiplicity) still fails rather than sliding past
    // the `> 0` check above.
    let dip_ev = dip * HA2EV;
    assert!(
        (3.0..4.0).contains(&dip_ev),
        "dIP = {dip_ev:.4} eV is outside the expected 3-4 eV window for UHF/def2-SVP"
    );
}

/// Reachability check for the 1e-6 Ha bar: the tolerance must be both
/// *meetable* (the anchor above) and *violable*. Here a deliberately wrong
/// reference — PySCF's He energy shifted by 1e-5 Ha — is shown to exceed it,
/// so `TOL_HA` is a real constraint rather than a number no realistic error
/// could ever trip.
#[test]
fn atomic_energy_tolerance_is_violable() {
    let e_he = atom_uhf("He", 0, 1);
    let wrong_ref = E_HE_PYSCF + 1e-5;
    let diff = (e_he - wrong_ref).abs();
    eprintln!("violability probe: |E(He) - (pyscf + 1e-5)| = {diff:.3e} Ha vs bar {TOL_HA:.1e}");
    assert!(
        diff > TOL_HA,
        "a 1e-5 Ha reference offset must break the {TOL_HA:.1e} bar, got {diff:.3e} — \
         the tolerance would be unfalsifiable"
    );
}

/// The multiplicity assignment is load-bearing, and a wrong one converges
/// *smoothly to the wrong answer*. He⁺ as a doublet (one electron) must not
/// equal He⁺ forced through the neutral-He singlet path, and the neutral
/// energies must lie below the cations: ionization costs energy.
#[test]
fn atomic_charge_and_multiplicity_ordering() {
    let [e_he, e_he_cat, e_ne, e_ne_cat] = atomic_energies();
    eprintln!(
        "IP(He) = {:.6} eV   IP(Ne) = {:.6} eV",
        (e_he_cat - e_he) * HA2EV,
        (e_ne_cat - e_ne) * HA2EV
    );
    assert!(
        e_he_cat > e_he,
        "E(He+) = {e_he_cat:.9} must exceed E(He) = {e_he:.9}: ionization costs energy"
    );
    assert!(
        e_ne_cat > e_ne,
        "E(Ne+) = {e_ne_cat:.9} must exceed E(Ne) = {e_ne:.9}: ionization costs energy"
    );
    // The ordering that makes dIP positive, stated independently of dIP itself.
    assert!(
        e_he_cat - e_he > e_ne_cat - e_ne,
        "IP(He) = {:.9} must exceed IP(Ne) = {:.9} Ha",
        e_he_cat - e_he,
        e_ne_cat - e_ne
    );
}

// ---------------------------------------------------------------------------
// Promolecule reference populations
// ---------------------------------------------------------------------------

/// The natural (promolecule) Becke population of He in diabat B is **not**
/// 2.000 at bonding separation.
///
/// Diabat B is "neutral He beside Ne⁺". Its promolecule density is built from
/// two fragments each converged in the *full dimer AO basis* (ghost partner, so
/// the basis is identical to the supermolecule's and the comparison is
/// counterpoise-clean): D_promol^B = D(He, ghost Ne) + D(Ne⁺, ghost He).
///
/// Integrating that density against the driver's own (99,302) Becke weight
/// operator for the He cell gives N_He^B(2.0 Å) ≈ 1.954, not 2.000. Roughly
/// 0.046 e of the neutral helium's density sits outside its own fuzzy cell.
///
/// This matters because the lane's diabats were built with **integer** targets
/// (N_He = 2.000 for B, 1.000 for A). A target of 2.000 is therefore ~0.046 e
/// past the natural diabat, and the constraint has to do real work — and pay
/// real energy — to drag the density there. That mis-targeting, not a physical
/// charge-transfer effect, is the leading candidate for the large Lagrange
/// multiplier and the energy penalty that were previously attributed to physics.
///
/// The number is the *unconstrained* SCF population to within 1e-3 e, which is
/// the sharper statement: the unconstrained state already **is** diabat B.
#[test]
fn promolecule_diabat_b_population_is_not_integer_at_bonding_separation() {
    use ferric_dft::ao_grid::eval_basis_on_points;
    use ferric_dft::cdft::{build_weight_matrix, population, SpinChannel};
    use ferric_dft::grid::{build_atomic_grid, AtomicGridConfig};

    const R: f64 = 2.0; // Å, the separation the lane's diabats were built at

    let bs = basis::bundled("def2-svp").unwrap();
    let ctx = ParallelContext::default();
    let config = RhfConfig {
        energy_conv: 1e-11,
        density_conv: 1e-9,
        max_iter: 300,
        ..Default::default()
    };

    // Atom order is fixed to (He, Ne) in every geometry so that the AO ordering
    // — and hence the density matrices — are directly summable.
    let dimer = format!("2\nHeNe\nHe 0.0 0.0 0.0\nNe 0.0 0.0 {R}\n");
    let he_g = format!("2\nHe + ghost Ne\nHe 0.0 0.0 0.0\n@Ne 0.0 0.0 {R}\n");
    let ne_g = format!("2\nghost He + Ne\n@He 0.0 0.0 0.0\nNe 0.0 0.0 {R}\n");

    let densities = |xyz: &str, charge: i32, mult: usize| {
        let mol = Molecule::parse_xyz(xyz, charge, mult).unwrap();
        let prep = PreparedBasis::new(&mol, &bs).unwrap();
        let op = Operator::coulomb();
        let bounds = SchwarzBounds::compute(op, &prep).unwrap();
        let res = solve_uhf(&ctx, &mol, &prep, &bounds, &config).unwrap();
        assert!(
            res.converged,
            "fragment {xyz} (q={charge}) did not converge"
        );
        let da = res.density_alpha.clone();
        let db = res.density_beta.clone().unwrap_or_else(|| da.clone());
        (da, db)
    };

    // W^He on the driver's own grid, over the real dimer geometry.
    let mol_dimer = Molecule::parse_xyz(&dimer, 0, 1).unwrap();
    let grid = build_atomic_grid(
        &mol_dimer,
        &AtomicGridConfig {
            n_radial: 99,
            n_angular: 302,
            ..Default::default()
        },
    );
    let pts: Vec<[f64; 3]> = grid.iter().map(|g| g.xyz).collect();
    let chi = eval_basis_on_points(&mol_dimer, &bs, &pts).unwrap();
    let w_he = build_weight_matrix(&mol_dimer, &grid, &chi, &[0]);
    let w_ne = build_weight_matrix(&mol_dimer, &grid, &chi, &[1]);

    let (he0_a, he0_b) = densities(&he_g, 0, 1); // neutral He, ghost Ne
    let (nep_a, nep_b) = densities(&ne_g, 1, 2); // Ne cation, ghost He

    // Promolecule B = He + Ne⁺.
    let d_b_a = &he0_a + &nep_a;
    let d_b_b = &he0_b + &nep_b;

    let n_he_b = population(&w_he, &d_b_a, &d_b_b, &SpinChannel::Total);
    let n_ne_b = population(&w_ne, &d_b_a, &d_b_b, &SpinChannel::Total);
    eprintln!(
        "N_He^B({R} A) = {n_he_b:.6}   N_Ne^B = {n_ne_b:.6}   sum = {:.6}",
        n_he_b + n_ne_b
    );
    eprintln!(
        "deviation from the integer target 2.000 = {:+.6} e",
        n_he_b - 2.0
    );

    // Grid-completeness: the Becke cells must partition all 11 electrons of
    // promolecule B (He 2e + Ne⁺ 9e). This is a check on the quadrature, not an
    // independent physics result — but if it fails, N_He^B means nothing.
    assert!(
        (n_he_b + n_ne_b - 11.0).abs() < 1e-4,
        "Becke cells do not partition 11 e: N_He + N_Ne = {:.6}",
        n_he_b + n_ne_b
    );

    // The finding: the natural population is measurably below the integer.
    assert!(
        n_he_b < 1.99,
        "N_He^B = {n_he_b:.6} — expected a NON-integer natural population near 1.95. \
         If this is ~2.00, Becke-cell spill cannot explain the constraint penalty and \
         the lane must return to the state-identity question."
    );
    assert!(
        n_he_b > 1.90,
        "N_He^B = {n_he_b:.6} is implausibly far below 2 — suspect a broken fragment \
         density sum or an AO-ordering mismatch between the ghost geometries"
    );
}

/// The unconstrained HeNe⁺ SCF at 2.0 Å already sits at the natural diabat-B
/// population, to under 1e-2 e.
///
/// This is the sharp form of the previous test's claim. If the unconstrained
/// state *is* diabat B, then constraining N_He to the integer 2.000 is not
/// preparing a diabat — it is pushing an already-correct state 0.046 e away
/// from where it wants to be, and every Hartree of constraint work that follows
/// is an artifact of the target, not a charge-transfer energy.
#[test]
fn unconstrained_hene_cation_already_sits_at_the_natural_diabat_b_population() {
    use ferric_dft::ao_grid::eval_basis_on_points;
    use ferric_dft::cdft::{build_weight_matrix, population, SpinChannel};
    use ferric_dft::grid::{build_atomic_grid, AtomicGridConfig};

    const R: f64 = 2.0;
    let bs = basis::bundled("def2-svp").unwrap();
    let ctx = ParallelContext::default();
    let config = RhfConfig {
        energy_conv: 1e-11,
        density_conv: 1e-9,
        max_iter: 300,
        ..Default::default()
    };

    let dimer = format!("2\nHeNe+\nHe 0.0 0.0 0.0\nNe 0.0 0.0 {R}\n");
    let he_g = format!("2\nHe + ghost Ne\nHe 0.0 0.0 0.0\n@Ne 0.0 0.0 {R}\n");
    let ne_g = format!("2\nghost He + Ne\n@He 0.0 0.0 0.0\nNe 0.0 0.0 {R}\n");

    let densities = |xyz: &str, charge: i32, mult: usize| {
        let mol = Molecule::parse_xyz(xyz, charge, mult).unwrap();
        let prep = PreparedBasis::new(&mol, &bs).unwrap();
        let op = Operator::coulomb();
        let bounds = SchwarzBounds::compute(op, &prep).unwrap();
        let res = solve_uhf(&ctx, &mol, &prep, &bounds, &config).unwrap();
        assert!(
            res.converged,
            "{xyz} (q={charge}) did not converge: {:?}",
            res.exit
        );
        let da = res.density_alpha.clone();
        let db = res.density_beta.clone().unwrap_or_else(|| da.clone());
        (da, db)
    };

    let mol_dimer = Molecule::parse_xyz(&dimer, 0, 1).unwrap();
    let grid = build_atomic_grid(
        &mol_dimer,
        &AtomicGridConfig {
            n_radial: 99,
            n_angular: 302,
            ..Default::default()
        },
    );
    let pts: Vec<[f64; 3]> = grid.iter().map(|g| g.xyz).collect();
    let chi = eval_basis_on_points(&mol_dimer, &bs, &pts).unwrap();
    let w_he = build_weight_matrix(&mol_dimer, &grid, &chi, &[0]);

    // Promolecule B.
    let (he0_a, he0_b) = densities(&he_g, 0, 1);
    let (nep_a, nep_b) = densities(&ne_g, 1, 2);
    let n_promol_b = population(
        &w_he,
        &(&he0_a + &nep_a),
        &(&he0_b + &nep_b),
        &SpinChannel::Total,
    );

    // The real, unconstrained HeNe⁺ cation.
    let (dim_a, dim_b) = densities(&dimer, 1, 2);
    let n_unconstrained = population(&w_he, &dim_a, &dim_b, &SpinChannel::Total);

    let gap = (n_unconstrained - n_promol_b).abs();
    eprintln!(
        "N_He: unconstrained = {n_unconstrained:.6}   promolecule B = {n_promol_b:.6}   |diff| = {gap:.3e}"
    );
    eprintln!(
        "distance of each from the integer target 2.000: unconstrained {:+.6}, promolecule B {:+.6}",
        n_unconstrained - 2.0,
        n_promol_b - 2.0
    );

    assert!(
        gap < 1e-2,
        "unconstrained N_He = {n_unconstrained:.6} differs from the natural diabat-B \
         population {n_promol_b:.6} by {gap:.3e} e — the claim that the unconstrained \
         state already is diabat B does NOT hold"
    );
    // And both are far from the integer that was actually targeted: the gap to
    // the target is at least an order of magnitude larger than the gap between
    // the two independent estimates of the natural diabat.
    assert!(
        (n_unconstrained - 2.0).abs() > 10.0 * gap,
        "the distance to the integer target ({:+.6}) is not clearly larger than the \
         unconstrained-vs-promolecule spread ({gap:.3e}); the two cannot be separated",
        n_unconstrained - 2.0
    );
}
