//! Cross-code validation of QM/MM electrostatic embedding against PySCF.
//!
//! `tests/qmmm.rs` proves the layer is exact in the trivial limit, responds
//! with the right sign, and agrees with a finite difference of ferric's OWN
//! energy. None of that catches a systematic error shared by the energy and
//! the force (a wrong constant folded into hcore reproduces perfectly in FD).
//! This file pins the absolute numbers against an independent implementation
//! of the same model, `pyscf.qmmm.mm_charge` — energy, dipole, force on each
//! MM charge, and the gradient on each QM nucleus in the field.
//!
//! References: `testdata/reference/*_qmmm_*.json`, generated by
//! `scripts/gen_pyscf_qmmm_refs.py` (PySCF 2.13.1, conv_tol 1e-12). The
//! geometry there is built from the same Bohr recipe as the reference files'
//! `atoms[].xyz_bohr`, which this test reads back verbatim so no unit
//! conversion can drift between the two codes.

use ferric_core::basis;
use ferric_core::mol::{Atom, Molecule};
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::oneelectron;
use ferric_integrals::operator::Operator;
use ferric_scf::gradient::{rhf_gradient, uhf_gradient};
use ferric_scf::qmmm::{mm_forces, QmSelection, QmmmAtom, QmmmSystem};
use ferric_scf::rhf::{solve_rhf, RhfConfig};
use ferric_scf::screening::SchwarzBounds;
use ferric_scf::uhf::solve_uhf;
use ndarray::Array2;
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct RefAtom {
    symbol: String,
    xyz_bohr: [f64; 3],
}

#[derive(Deserialize)]
struct RefCharge {
    q: f64,
    xyz_bohr: [f64; 3],
}

#[derive(Deserialize)]
struct QmmmRef {
    method: String,
    atoms: Vec<RefAtom>,
    charge: i32,
    multiplicity: usize,
    mm_charges: Vec<RefCharge>,
    energy: f64,
    energy_gas_phase: f64,
    dipole: [f64; 3],
    qm_gradient: Vec<[f64; 3]>,
    mm_gradient: Vec<[f64; 3]>,
    converged: bool,
}

fn load(name: &str) -> QmmmRef {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/reference")
        .join(name);
    let r: QmmmRef = serde_json::from_str(&fs::read_to_string(&p).unwrap()).unwrap();
    assert!(r.converged, "reference {name} is not converged");
    r
}

fn z_of(symbol: &str) -> i32 {
    match symbol {
        "H" => 1,
        "O" => 8,
        s => panic!("unexpected element {s}"),
    }
}

/// Total dipole about the origin (a.u.): nuclear − Tr(D·r).
fn dipole(mol: &Molecule, prep: &PreparedBasis, d_total: &Array2<f64>) -> [f64; 3] {
    let mu_ao = oneelectron::dipole(prep, [0.0, 0.0, 0.0]).unwrap();
    let mut out = [0.0_f64; 3];
    for (axis, m) in mu_ao.iter().enumerate() {
        let elec: f64 = d_total.iter().zip(m.iter()).map(|(d, x)| d * x).sum();
        let nuc: f64 = mol
            .atoms
            .iter()
            .map(|a| a.effective_z() as f64 * [a.x, a.y, a.zpos][axis])
            .sum();
        out[axis] = nuc - elec;
    }
    out
}

/// Build the QM/MM system exactly as a user would: the full structure is the
/// QM atoms (with dummy MM charges that must be ignored) followed by the MM
/// charge sites, and the QM selection is the leading atom indices.
fn system_from_ref(r: &QmmmRef) -> QmmmSystem {
    let mut atoms: Vec<QmmmAtom> = r
        .atoms
        .iter()
        .map(|a| QmmmAtom::new(a.symbol.clone(), z_of(&a.symbol), a.xyz_bohr[0], a.xyz_bohr[1], a.xyz_bohr[2], 99.0))
        .collect();
    for c in &r.mm_charges {
        atoms.push(QmmmAtom::new("X", 0, c.xyz_bohr[0], c.xyz_bohr[1], c.xyz_bohr[2], c.q));
    }
    let qm: Vec<usize> = (0..r.atoms.len()).collect();
    QmmmSystem::new(&atoms, QmSelection::Indices(qm), r.charge, r.multiplicity).unwrap()
}

struct Run {
    energy: f64,
    energy_gas: f64,
    dipole: [f64; 3],
    qm_gradient: Array2<f64>,
    mm_forces: Vec<[f64; 3]>,
}

fn run(r: &QmmmRef) -> Run {
    let sys = system_from_ref(r);
    let mol = sys.to_qm_molecule();
    // The QM molecule must be exactly the reference's atoms — a QmmmAtom with
    // a nonzero dummy charge in the QM region must not leak into the
    // potential, and the MM sites must not become nuclei.
    assert_eq!(mol.atoms.len(), r.atoms.len());
    let ep = sys.to_external_potential().expect("reference has MM charges");
    assert_eq!(ep.point_charges.len(), r.mm_charges.len());

    let bs = basis::bundled("sto-3g").unwrap();
    let prep = PreparedBasis::new(&mol, &bs).unwrap();
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &prep).unwrap();
    let ctx = ParallelContext::default();

    let cfg = RhfConfig { external_potential: Some(ep), density_conv: 1e-10, ..Default::default() };
    let gas_cfg = RhfConfig { density_conv: 1e-10, ..Default::default() };

    let (scf, gas, grad) = match r.method.as_str() {
        "rhf" => {
            let s = solve_rhf(&ctx, &mol, &prep, op, &bounds, &cfg).unwrap();
            let g = solve_rhf(&ctx, &mol, &prep, op, &bounds, &gas_cfg).unwrap();
            let grad = rhf_gradient(&mol, &prep, op, &bounds, &s, cfg.external_potential.as_ref()).unwrap();
            (s, g, grad)
        }
        "uhf" => {
            let s = solve_uhf(&ctx, &mol, &prep, &bounds, &cfg).unwrap();
            let g = solve_uhf(&ctx, &mol, &prep, &bounds, &gas_cfg).unwrap();
            let grad = uhf_gradient(&mol, &prep, op, &bounds, &s, cfg.external_potential.as_ref()).unwrap();
            (s, g, grad)
        }
        m => panic!("unknown method {m}"),
    };
    assert!(scf.converged && gas.converged);

    Run {
        energy: scf.energy,
        energy_gas: gas.energy,
        dipole: dipole(&mol, &prep, scf.density_total()),
        qm_gradient: grad,
        mm_forces: mm_forces(&sys, &mol, &prep, scf.density_total()).unwrap(),
    }
}

/// Absolute energies to 5e-8 Ha: ferric's mean-field total sits a constant
/// ~2.4e-8 Ha below PySCF on water/STO-3G (the same floor the CAS-CI
/// cross-check records), so the absolute bar has to clear it. The embedding
/// SHIFT is held to 1e-8 — the floor cancels in the difference, and the shift
/// is the quantity this layer exists to produce. Dipole to 1e-6 a.u., both
/// gradients to 1e-6 Ha/Bohr.
fn check(name: &str) {
    let r = load(name);
    let out = run(&r);

    let de_gas = (out.energy_gas - r.energy_gas_phase).abs();
    assert!(de_gas < 5e-8, "{name}: gas-phase energy off by {de_gas:.3e}");
    let de = (out.energy - r.energy).abs();
    assert!(
        de < 5e-8,
        "{name}: embedded energy ferric {:.10} vs PySCF {:.10} (Δ {de:.3e})",
        out.energy,
        r.energy
    );
    // The embedding SHIFT is the quantity the whole layer exists to produce;
    // check it explicitly so a shared gas-phase offset could not mask it.
    let shift_f = out.energy - out.energy_gas;
    let shift_p = r.energy - r.energy_gas_phase;
    assert!((shift_f - shift_p).abs() < 1e-8, "{name}: embedding shift {shift_f:.3e} vs {shift_p:.3e}");

    for k in 0..3 {
        let d = (out.dipole[k] - r.dipole[k]).abs();
        assert!(d < 1e-6, "{name}: dipole[{k}] ferric {} vs PySCF {} (Δ {d:.3e})", out.dipole[k], r.dipole[k]);
    }

    assert_eq!(out.mm_forces.len(), r.mm_gradient.len());
    for (i, (f, g)) in out.mm_forces.iter().zip(r.mm_gradient.iter()).enumerate() {
        for k in 0..3 {
            // ferric returns the FORCE; PySCF's grad_*_mm is dE/dR.
            let d = (f[k] + g[k]).abs();
            assert!(d < 1e-6, "{name}: MM force[{i}][{k}] ferric {} vs PySCF −grad {} (Δ {d:.3e})", f[k], -g[k]);
        }
    }

    assert_eq!(out.qm_gradient.nrows(), r.qm_gradient.len());
    for (a, g) in r.qm_gradient.iter().enumerate() {
        for k in 0..3 {
            let d = (out.qm_gradient[(a, k)] - g[k]).abs();
            assert!(d < 1e-6, "{name}: QM gradient[{a}][{k}] ferric {} vs PySCF {} (Δ {d:.3e})", out.qm_gradient[(a, k)], g[k]);
        }
    }

    eprintln!(
        "[qmmm-vs-pyscf] {name}: ΔE {de:.2e}, shift ferric {shift_f:+.8} / PySCF {shift_p:+.8}, \
         max|ΔF_mm| {:.2e}",
        out.mm_forces.iter().zip(r.mm_gradient.iter()).flat_map(|(f, g)| (0..3).map(move |k| (f[k] + g[k]).abs())).fold(0.0, f64::max)
    );
}

#[test]
fn water_plus_charge_on_lone_pair_side_matches_pyscf() {
    check("water_sto-3g_qmmm_plus_lonepair.json");
}

#[test]
fn water_plus_charge_on_hydrogen_side_matches_pyscf() {
    check("water_sto-3g_qmmm_plus_hside.json");
}

#[test]
fn water_two_opposite_charges_match_pyscf() {
    check("water_sto-3g_qmmm_two_charges.json");
}

/// Off-axis fractional charges: no symmetry zeros anywhere, so every
/// component of both gradients is a live comparison.
#[test]
fn water_offaxis_fractional_charges_match_pyscf() {
    check("water_sto-3g_qmmm_offaxis.json");
}

/// Open shell: the same embedding through solve_uhf/uhf_gradient.
#[test]
fn oh_doublet_uhf_embedding_matches_pyscf() {
    check("oh_sto-3g_uqmmm_plus_lonepair.json");
}

/// Guard the harness itself: an `Atom` built the way `to_qm_molecule` builds
/// it must carry the reference coordinates untouched (no Å↔Bohr conversion
/// sneaks in via `Molecule::parse_xyz`, which this path never calls).
#[test]
fn reference_atoms_round_trip_in_bohr() {
    let r = load("water_sto-3g_qmmm_offaxis.json");
    let mol = system_from_ref(&r).to_qm_molecule();
    for (a, ra) in mol.atoms.iter().zip(r.atoms.iter()) {
        let Atom { x, y, zpos, .. } = a;
        assert_eq!([*x, *y, *zpos], ra.xyz_bohr);
    }
}
