//! Screening-exactness anchors for the direct J/K and LinK exchange builders.
//!
//! # Why this file exists
//!
//! The LinK correctness tests that live in `crates/ferric-scf/src/link_k.rs`
//! all build K at `thresh = 1e-14` on water (3 atoms) and CH4 (5 atoms). At
//! that threshold on molecules that small, `SignificantPairs::build` retains
//! effectively the FULL `nsh*(nsh+1)/2` pair list, so no shell quartet is ever
//! screened away: LinK and the dense reference walk the same quartets and of
//! course agree. Those assertions pass for reasons that have nothing to do
//! with screening — they are decorative. Separately,
//! `tests/mpi_direct_jk_correctness.rs` anchors the direct-path RHF energy to
//! a value ferric measured from itself, which pins behaviour but not physics.
//!
//! This file supplies what was missing — and, in doing so, turned up two real
//! defects that the decorative tests could not see (both pinned by name below).
//!
//! * a **threshold sweep** on a system large enough that screening genuinely
//!   fires (alkane_8 = C8H18, 26 atoms, 202 cc-pVDZ basis functions),
//!   measuring `max|K_LinK(t) - K_dense(t)|` across five thresholds. Both
//!   builders run at the SAME `t`, which holds the screen they share fixed and
//!   isolates LinK's own pair-list approximation.
//!
//! * a **reachable-pass-condition check** (repo rule: "a test you have never
//!   seen fail is an assumption", and its sibling, "check the pass condition
//!   is REACHABLE"). At a loose threshold screening must have discarded a
//!   substantial fraction of the pair list — not merely one pair. That exact
//!   strengthening came out of mutation testing: a "retain everything" mutant
//!   still left 5202 of 5253 pairs, passing a naive `< full_triangle` check.
//!
//! * **cross-code J/K references** from PySCF's direct SCF path (generated by
//!   `scripts/gen_pyscf_directjk_refs.py`; see that file's header for the
//!   comparison protocol, the `mf._eri is None` direct-path guarantee, and why
//!   the reference Mole is built from ferric's OWN basis JSON).
//!
//! # What was found
//!
//! Both defects trace to one cause: `SchwarzBounds::compute` builds its Q
//! table from libint2 engines at a hardcoded 1e-14 precision, so shell pairs
//! whose true (ij|ij) falls below that get Q = 0.0 and are then unreachable at
//! ANY threshold, including 0. On alkane_8 that is 1049 of 5253 pairs (20%).
//!
//! 1. `link_k_cannot_reach_the_dense_answer_alkane_8` — LinK fails its own
//!    trivial-limit exactness anchor: at `thresh = 0` it still differs from
//!    the dense build by 2e-3.
//! 2. `known_defect_screening_shifts_coulomb_energy_with_size` — screening at
//!    the default threshold shifts the Coulomb energy by 5e-9 Ha on alkane_4
//!    but ~1.8e-4 Ha on alkane_8, and the shift is signed (energies come out
//!    spuriously LOW, mimicking a better SCF solution).
//!
//! Neither is visible on water or CH4, which have no underflowed pairs — which
//! is precisely why the pre-existing tests passed while proving nothing.
//!
//! With screening OFF, ferric reproduces PySCF's J/K on the same density to
//! 8.5e-11 and its energy functional to 4.8e-11 (alkane_4) / 7.0e-9
//! (alkane_8). The integrals, the J/K builders, and the energy expression are
//! all correct; the screen is what is wrong.
//!
//! # Bound-type parameterization
//!
//! Every screening assertion runs through [`BoundKind`], which selects the
//! `Bound` implementation at run time. Today only [`BoundKind::Schwarz`] is
//! exercised in the default gate; the QQR arm is present and compiling so
//! that a later PR can enable `BoundKind::Qqr` against the SAME harness and
//! the SAME assertions, rather than forking a parallel copy of this file.
//!
//! # Running
//!
//! Default gate (alkane_4 + alkane_8):
//!
//! ```text
//! OPENBLAS_NUM_THREADS=1 FERRIC_MEM_BUDGET_GB=2 \
//!   scripts/ferric-limited --max=4G --high=3600M -- \
//!   cargo test -p ferric-scf --test screening_exactness --release
//! ```
//!
//! The `#[ignore]`d alkane_12 case (38 atoms, 298 basis functions) runs the
//! dense O(N^4) reference build five times and takes far longer than a gate
//! should; run it explicitly with:
//!
//! ```text
//! OPENBLAS_NUM_THREADS=1 FERRIC_MEM_BUDGET_GB=2 \
//!   scripts/ferric-limited --max=4G --high=3600M -- \
//!   cargo test -p ferric-scf --test screening_exactness --release \
//!   -- --ignored --nocapture link_k_thresh_sweep_alkane_12
//! ```

use ferric_core::basis::{self, BasisSet};
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::fock::KBuilder;
use ferric_scf::link_k::LinkK;
use ferric_scf::pairs::SignificantPairs;
use ferric_scf::qqr::QqrBounds;
use ferric_scf::rhf::{build_jk, solve_rhf, RhfConfig};
use ferric_scf::screening::{Bound, SchwarzBounds};
use ndarray::Array2;

/// Which `Bound` implementation the screening harness should drive.
///
/// This is the parameterization hook: adding `BoundKind::Qqr` to a sweep's
/// case list re-runs the identical assertions against QQR bounds. It exists so
/// the follow-up QQR PR extends a list instead of copying this file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum BoundKind {
    Schwarz,
    #[allow(dead_code)] // exercised by the follow-up QQR PR; constructed in `qqr_bound_arm_is_wired`
    Qqr,
}

impl BoundKind {
    fn label(self) -> &'static str {
        match self {
            BoundKind::Schwarz => "Schwarz",
            BoundKind::Qqr => "QQR",
        }
    }
}

/// A constructed bound, kept as an owned enum so callers can hand out a
/// `&dyn Bound` without the two arms needing the same concrete type.
enum AnyBound {
    Schwarz(SchwarzBounds),
    Qqr(Box<QqrBounds>),
}

impl AnyBound {
    fn as_dyn(&self) -> &dyn Bound {
        match self {
            AnyBound::Schwarz(b) => b,
            AnyBound::Qqr(b) => b.as_ref(),
        }
    }
}

fn make_bound(
    kind: BoundKind,
    mol: &Molecule,
    bs: &BasisSet,
    prep: &PreparedBasis,
    op: Operator,
) -> AnyBound {
    let schwarz = SchwarzBounds::compute(op, prep).expect("Schwarz bounds");
    match kind {
        BoundKind::Schwarz => AnyBound::Schwarz(schwarz),
        BoundKind::Qqr => AnyBound::Qqr(Box::new(QqrBounds::new(schwarz, mol, bs, prep, op))),
    }
}

/// Load a testdata molecule by stem, e.g. `"alkane_8"`.
fn load_mol(stem: &str) -> Molecule {
    Molecule::load_xyz(&format!("../../testdata/molecules/{stem}.xyz"))
        .unwrap_or_else(|e| panic!("cannot load {stem}.xyz: {e}"))
}

/// Converge RHF and return `(density_total, PreparedBasis-owning inputs)`.
///
/// The density is the contraction input for every J/K comparison below; it is
/// deliberately NOT rebuilt per threshold, so a sweep varies exactly one thing
/// (the screening threshold) and nothing else.
fn converged_density(mol: &Molecule, bs: &BasisSet, prep: &PreparedBasis) -> Array2<f64> {
    let op = Operator::coulomb();
    let _ = bs;
    let bounds = SchwarzBounds::compute(op, prep).expect("Schwarz bounds");
    // Stock convergence settings on purpose. What the sweep needs from this
    // density is only that it be FIXED and physically sensible — every
    // threshold in the sweep contracts the SAME matrix, so the density's own
    // convergence level cancels out of the LinK-vs-dense comparison entirely.
    //
    // An earlier version forced density_conv = 1e-9 / integral_thresh = 1e-12
    // here. That bought nothing and cost enormously: on alkane_8 (202 basis
    // functions, hcore guess) the SCF ground on past 60 minutes without
    // finishing, which is also what the repo's own note
    // ("energy_conv is a sanity bound, not a target") warns about. Do not
    // re-tighten these without measuring the alkane_8 wall time first.
    let config = RhfConfig::default();
    let res = solve_rhf(&ParallelContext::default(), mol, prep, op, &bounds, &config)
        .expect("RHF solve");
    assert!(
        res.converged,
        "RHF did not converge for the screening anchor — refusing to measure screening error \
         against an unconverged density"
    );
    res.density_total
}

/// Dense reference K: the canonical screened quartet loop at `thresh`.
fn dense_k(prep: &PreparedBasis, d: &Array2<f64>, thresh: f64) -> Array2<f64> {
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, prep).expect("Schwarz bounds");
    let n = prep.nbasis();
    let mut j = Array2::zeros((n, n));
    let mut k = Array2::zeros((n, n));
    build_jk(
        &ParallelContext::default(),
        prep,
        &bounds,
        thresh,
        d,
        &mut j,
        &mut k,
    )
    .expect("dense build_jk");
    k
}

/// LinK K at `thresh` under the selected bound type.
fn link_k(
    kind: BoundKind,
    mol: &Molecule,
    bs: &BasisSet,
    prep: &PreparedBasis,
    d: &Array2<f64>,
    thresh: f64,
) -> Array2<f64> {
    let op = Operator::coulomb();
    let bound = make_bound(kind, mol, bs, prep, op);
    let ctx = ParallelContext::default();
    let n = prep.nbasis();
    let mut k = Array2::zeros((n, n));
    match &bound {
        AnyBound::Schwarz(b) => {
            let mut link = LinkK::new(&ctx, prep, b, op, thresh, usize::MAX);
            link.update_density(d);
            link.build(d, &mut k).expect("LinK build");
        }
        AnyBound::Qqr(b) => {
            let mut link = LinkK::new(&ctx, prep, b.as_ref(), op, thresh, usize::MAX);
            link.update_density(d);
            link.build(d, &mut k).expect("LinK build");
        }
    }
    k
}

fn max_abs_diff(a: &Array2<f64>, b: &Array2<f64>) -> f64 {
    assert_eq!(a.dim(), b.dim(), "shape mismatch in max_abs_diff");
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f64, f64::max)
}

/// Thresholds swept, loosest first. The sequence must be strictly decreasing
/// so "error decreases monotonically" is a meaningful statement.
const THRESH_SWEEP: [f64; 5] = [1e-6, 1e-8, 1e-10, 1e-12, 1e-14];

/// Bar for LinK vs the dense build at the SAME threshold.
///
/// A flat constant, not a multiple of `thresh`, because the measured error is
/// essentially INDEPENDENT of the threshold — it is dominated by the shared
/// Q-underflow floor (`link_k_cannot_reach_the_dense_answer_alkane_8`), not by
/// the threshold. Measured on alkane_8/cc-pVDZ:
///
/// | thresh | max\|K_LinK - K_dense(thresh)\| |
/// |--------|--------------------------------|
/// | 1e-6   | 4.83e-3                        |
/// | 1e-8   | 2.54e-3                        |
/// | 1e-10  | 1.92e-3                        |
/// | 1e-12  | 1.94e-3                        |
/// | 1e-14  | 1.94e-3                        |
///
/// Tying the bar to `thresh` would make it unreachable by construction at the
/// tight end, which is the failure mode this file exists to prevent. This
/// constant pins the measured behaviour instead; it should drop by orders of
/// magnitude once the underflow defect is fixed.
const LINK_VS_DENSE_BAR: f64 = 1e-2;

/// The `integral_thresh` a production SCF run uses.
const PRODUCTION_INTEGRAL_THRESH: f64 = 1e-14;

/// Bar for the J/K deviation vs PySCF at [`PRODUCTION_INTEGRAL_THRESH`].
///
/// Deliberately looser than the unscreened bar, and NOT a fudge: see the long
/// note in `check_directjk_vs_pyscf`. ferric's libint2 engines are built at
/// precision 1e-14, so shell pairs whose true (ij|ij) falls below that are
/// assigned Q = 0 and screened out; PySCF computes them. Measured deviation on
/// alkane_4 is 5.08e-6 (J) / 1.57e-6 (K), alkane_8 is 1.54e-3 (J) / 3.68e-5
/// (K) — the growth with size is the defect, not noise. The same comparison
/// with screening OFF agrees to ~1e-11, which is what proves the builders
/// themselves are correct.
const SCREENED_JK_BAR: f64 = 1e-2;

/// Shared body of the threshold sweep, so alkane_8 (gated) and alkane_12
/// (ignored) run byte-identical logic rather than two drifting copies.
fn run_thresh_sweep(kind: BoundKind, stem: &str, basis_name: &str) {
    let mol = load_mol(stem);
    let bs = basis::bundled(basis_name).expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let nbf = prep.nbasis();
    let d = converged_density(&mol, &bs, &prep);

    eprintln!(
        "\n=== LinK thresh sweep: {stem}/{basis_name}, bound={}, natm={}, nsh={nsh}, nbf={nbf} ===",
        kind.label(),
        mol.atoms.len()
    );
    eprintln!("{:>10}  {:>14}  {:>14}", "thresh", "max|dK|", "retained_pairs");

    let full_triangle = nsh * (nsh + 1) / 2;
    let mut errs: Vec<(f64, f64)> = Vec::new();

    // REFERENCE: the dense canonical quartet build at the SAME threshold.
    //
    // This measures what LinK's own approximation costs — its pair-list
    // restriction of the ket loop — with the Häser-Ahlrichs/Schwarz screen
    // that BOTH builders share held constant between them. That shared screen
    // is not exact (see `link_k_cannot_reach_the_dense_answer_alkane_8`), so
    // subtracting it out is the only way to isolate the quantity this sweep is
    // about.
    //
    // The alternative, a single fixed reference at thresh = 0, was MEASURED
    // and does NOT work here: LinK's error against the exact K falls
    // 4.83e-3 -> 2.54e-3 -> 1.93e-3 and then RISES to 1.959e-3 and plateaus,
    // because LinK inherits the Q-underflow floor and simply cannot converge
    // to the exact answer. Asserting monotonicity against that target would be
    // asserting something false about a defect that lives elsewhere. The
    // exactness failure itself is pinned separately, by name, below.
    for &thresh in THRESH_SWEEP.iter() {
        let k_ref = dense_k(&prep, &d, thresh);
        let op = Operator::coulomb();
        let bound = make_bound(kind, &mol, &bs, &prep, op);
        // `SignificantPairs::build` stores the FULL square (both (i,j) and
        // (j,i)); halve to compare against the unique-pair triangle. Diagonal
        // entries appear once, so the exact unique count is (total + ndiag)/2;
        // we take the conservative floor, which only ever makes the strict-less
        // assertion HARDER to pass.
        let sp = SignificantPairs::build(bound.as_dyn(), nsh, thresh);
        let retained = sp.total_pairs() / 2;

        let k_link = link_k(kind, &mol, &bs, &prep, &d, thresh);
        let err = max_abs_diff(&k_link, &k_ref);
        eprintln!("{thresh:>10.0e}  {err:>14.3e}  {retained:>7} / {full_triangle}");
        errs.push((thresh, err));
    }

    // --- LinK vs the dense build at the SAME threshold ---------------------
    // Bounds LinK's deviation across the whole sweep. See LINK_VS_DENSE_BAR
    // for why this is a flat constant rather than a multiple of `thresh`: the
    // measured error barely moves with the threshold because it is dominated
    // by the shared Q-underflow floor, so a threshold-proportional bar would
    // be unreachable at the tight end by construction.
    for &(thresh, err) in errs.iter() {
        assert!(
            err < LINK_VS_DENSE_BAR,
            "{stem}/{basis_name} [{}]: at thresh={thresh:.0e} LinK differs from the dense build \
             AT THE SAME THRESHOLD by max|dK| = {err:.6e}, above the {LINK_VS_DENSE_BAR:.0e} bar.",
            kind.label()
        );
    }

    // --- The sweep must still SHOW the error falling as the screen loosens --
    // Not a full monotonicity claim: the tail is flat (1.92e-3 -> 1.94e-3 ->
    // 1.94e-3) because it has hit the Q-underflow floor, and asserting
    // monotonicity there would be asserting something false about a defect
    // that lives elsewhere. What IS true, and what makes the sweep a
    // measurement rather than five unrelated numbers, is that loosening the
    // threshold measurably COSTS accuracy: the loosest point must be clearly
    // worse than the tightest.
    let (t_loose, e_loose) = errs[0];
    let (t_tight, e_tight) = *errs.last().expect("sweep is non-empty");
    assert!(
        e_loose > 2.0 * e_tight,
        "{stem}/{basis_name} [{}]: max|dK| is {e_loose:.6e} at the loosest threshold \
         ({t_loose:.0e}) and {e_tight:.6e} at the tightest ({t_tight:.0e}) — less than a factor \
         of 2 apart. The sweep spans no measurable range, so it is not observing the screening \
         tradeoff at all.",
        kind.label()
    );

    // --- (b) REACHABILITY: the screening path must actually be exercised ---
    // The assertions above are only meaningful if screening genuinely removed
    // work. If the pair list were complete at every threshold, LinK and the
    // dense build would walk the same quartets and agree trivially — which is
    // exactly the vacuous regime the pre-existing water/CH4 tests sat in.
    // Require the loosest threshold to have discarded a real fraction.
    let sp_loose = SignificantPairs::build(
        make_bound(kind, &mol, &bs, &prep, Operator::coulomb()).as_dyn(),
        nsh,
        THRESH_SWEEP[0],
    );
    let retained_loose = sp_loose.total_pairs() / 2;
    assert!(
        retained_loose < full_triangle,
        "{stem}/{basis_name} [{}]: at thresh={:.0e} SignificantPairs retained {retained_loose} of \
         {full_triangle} unique shell pairs — NOTHING was screened, so every assertion in this \
         sweep compares the unscreened loop against itself.",
        kind.label(),
        THRESH_SWEEP[0]
    );
}

/// (a) THRESH -> 0 anchor on an extended system, plus (b) the reachability check.
///
/// alkane_8 (C8H18, 26 atoms, 202 cc-pVDZ functions) is long enough that
/// Schwarz screening removes a real fraction of the shell-pair triangle at
/// loose thresholds — unlike the water/CH4 cases the old in-module tests use.
#[test]
fn link_k_thresh_sweep_alkane_8_schwarz() {
    run_thresh_sweep(BoundKind::Schwarz, "alkane_8", "cc-pvdz");
}

/// (a) The same sweep on alkane_12 (C12H26, 38 atoms, 298 cc-pVDZ functions).
///
/// `#[ignore]`d because it runs the dense O(N^4) `build_jk` reference five
/// times; that is minutes of work, too slow for the default gate. Invocation
/// is in this file's module doc comment.
#[test]
#[ignore = "expensive: 5x dense O(N^4) build_jk on 298 basis functions; see module doc for invocation"]
fn link_k_thresh_sweep_alkane_12() {
    run_thresh_sweep(BoundKind::Schwarz, "alkane_12", "cc-pvdz");
}

/// (b) REACHABLE-PASS-CONDITION check, standalone and explicit.
///
/// This is the assertion whose absence made the existing LinK tests vacuous.
/// At a loose threshold on the largest gated system, `SignificantPairs` MUST
/// retain strictly fewer than the full `nsh*(nsh+1)/2` unique shell pairs —
/// otherwise the screening path is not exercised at all and every "LinK
/// matches dense" assertion in the repo is measuring the unscreened loop
/// against itself.
///
/// It also pins the OTHER end: at `thresh = 0` the pair list must be complete.
/// That is the trivial-limit exactness anchor for the pair builder itself (a
/// screen that does nothing must retain everything), and it makes the strict
/// inequality above a measurement of screening rather than of an off-by-one.
#[test]
fn significant_pairs_actually_screens_alkane_8() {
    let mol = load_mol("alkane_8");
    let bs = basis::bundled("cc-pvdz").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let op = Operator::coulomb();
    let bound = make_bound(BoundKind::Schwarz, &mol, &bs, &prep, op);

    let full_square = nsh * nsh;
    let full_triangle = nsh * (nsh + 1) / 2;

    // Working regime: at 1e-6 screening must genuinely remove pairs.
    let sp = SignificantPairs::build(bound.as_dyn(), nsh, 1e-6);
    let retained = sp.total_pairs() / 2;
    let frac = retained as f64 / full_triangle as f64;
    eprintln!(
        "alkane_8/cc-pVDZ nsh={nsh}: retained {retained} of {full_triangle} unique shell pairs \
         at thresh=1e-6 ({:.1}% kept)",
        100.0 * frac
    );
    // A bare `retained < full_triangle` is too weak to be the reachability
    // guard: a builder that dropped a single pair would satisfy it while
    // screening essentially nothing. MEASURED under a deliberate
    // "retain every pair" mutation of SignificantPairs::build, retention went
    // to 5202 / 5253 (99.0%) — still strictly less than the triangle, because
    // halving the ordered-pair count floors below it. So require screening to
    // have removed a SUBSTANTIAL fraction. Real value here is 60.2% kept.
    assert!(
        frac < 0.9,
        "alkane_8/cc-pVDZ: SignificantPairs retained {retained} of {full_triangle} unique shell \
         pairs at thresh=1e-6 ({:.1}% kept) — essentially NOTHING was screened. Every \
         LinK-vs-dense assertion in this repo is then comparing the unscreened loop against \
         itself and proves nothing about screening.",
        100.0 * frac
    );

    // Trivial-limit exactness anchor for the pair builder itself: a screen
    // that does nothing must retain everything.
    //
    // The threshold must be NEGATIVE, not zero. `SignificantPairs::build`
    // keeps a pair when `estimate(..) > threshold` — a STRICT comparison — and
    // on a 26-atom chain the Schwarz bound for well-separated shell pairs
    // underflows to exactly 0.0 in f64. At `threshold = 0.0` those pairs are
    // therefore (correctly) dropped: 8306 of 10404 survive, not all 10404.
    // That is the screen working as designed on a genuinely negligible pair,
    // so `0.0` is NOT the vacuous limit. Any negative threshold is, since
    // every bound is non-negative.
    let sp_all = SignificantPairs::build(bound.as_dyn(), nsh, -1.0);
    assert_eq!(
        sp_all.total_pairs(),
        full_square,
        "alkane_8/cc-pVDZ: at thresh=-1 (the vacuous screen — every non-negative bound passes a \
         negative threshold) SignificantPairs must retain ALL {full_square} ordered shell pairs, \
         got {}",
        sp_all.total_pairs()
    );

    // Documents the f64-underflow behaviour the anchor above had to route
    // around, so a future reader does not "fix" the negative threshold back to
    // zero: at thresh=0 the strict `>` already discards the pairs whose bound
    // underflowed, which is a real (and desirable) screening effect.
    let sp_zero = SignificantPairs::build(bound.as_dyn(), nsh, 0.0);
    assert!(
        sp_zero.total_pairs() < full_square,
        "alkane_8/cc-pVDZ: expected some shell-pair Schwarz bounds to underflow to exactly 0.0 \
         and be dropped by the strict `>` at thresh=0, but all {full_square} pairs survived"
    );
}

// ---------------------------------------------------------------------------
// (c) Cross-code DirectJK references
// ---------------------------------------------------------------------------

/// One PySCF direct-SCF reference record, as written by
/// `scripts/gen_pyscf_directjk_refs.py`. Matrices are stored row-major in
/// PYSCF AO order.
#[derive(serde::Deserialize)]
struct DirectJkRef {
    /// Layout tag for the packed matrices. Guards against silently misreading
    /// a reference written by an older generator that stored full squares.
    storage: String,
    nbf: usize,
    converged: bool,
    eri_cached: bool,
    direct_scf: bool,
    e_tot: f64,
    ao_permutation: Vec<usize>,
    // Absent for "energy_only" references (see the CASES note in
    // scripts/gen_pyscf_directjk_refs.py: alkane_8's dense matrices ran to
    // 1.4 MB, far outside this repo's 35 KB-largest reference convention).
    #[serde(default)]
    density: Vec<f64>,
    #[serde(default)]
    j: Vec<f64>,
    #[serde(default)]
    k: Vec<f64>,
    #[serde(default)]
    overlap: Vec<f64>,
}

impl DirectJkRef {
    fn load(tag: &str) -> Self {
        let path = format!("../../testdata/reference/{tag}_ccpvdz_directjk.json");
        let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "cannot read {path}: {e}\nRegenerate with: \
                 OPENBLAS_NUM_THREADS=1 python3 scripts/gen_pyscf_directjk_refs.py"
            )
        });
        let rec: DirectJkRef = serde_json::from_str(&text).expect("parse reference JSON");
        // The reference is only a reference if PySCF actually took the direct
        // path (repo memory: pyscf-caches-eri-benchmark-trap). The generator
        // refuses to write a record otherwise; re-assert here so a hand-edited
        // or stale file cannot slip past.
        assert!(rec.converged, "{tag}: PySCF reference is not converged");
        assert!(!rec.eri_cached, "{tag}: PySCF reference was built with a CACHED in-core ERI tensor — not a direct-path reference");
        assert!(rec.direct_scf, "{tag}: PySCF reference was not built with direct_scf=True");
        assert!(
            matches!(rec.storage.as_str(), "lower_triangle_rowmajor" | "energy_only"),
            "{tag}: reference uses unknown storage layout {:?}. Regenerate with \
             scripts/gen_pyscf_directjk_refs.py.",
            rec.storage
        );
        rec
    }

    /// Rebuild a full symmetric matrix from the reference's packed lower
    /// triangle (row-major, i >= j). The generator stores only the triangle
    /// because all four matrices are symmetric to <= 4.5e-16, and the full
    /// square pushed the alkane_8 file past the repo's 500 KB limit.
    /// Whether this reference carries the density/J/K/overlap matrices, or
    /// only energies.
    fn has_matrices(&self) -> bool {
        self.storage == "lower_triangle_rowmajor"
    }

    fn square(&self, tri: &[f64]) -> Array2<f64> {
        let n = self.nbf;
        assert_eq!(
            tri.len(),
            n * (n + 1) / 2,
            "packed lower triangle should hold n(n+1)/2 = {} elements for nbf = {n}, got {}",
            n * (n + 1) / 2,
            tri.len()
        );
        let mut m = Array2::zeros((n, n));
        let mut idx = 0usize;
        for i in 0..n {
            for j in 0..=i {
                m[(i, j)] = tri[idx];
                m[(j, i)] = tri[idx];
                idx += 1;
            }
        }
        m
    }
}

/// Permute a ferric-ordered matrix into PySCF AO order using `perm`, where
/// `perm[i]` is the PySCF index of ferric AO `i`.
fn permute_to_pyscf(m: &Array2<f64>, perm: &[usize]) -> Array2<f64> {
    let n = m.nrows();
    assert_eq!(perm.len(), n, "permutation length must equal nbf");
    let mut out = Array2::zeros((n, n));
    for i in 0..n {
        for j in 0..n {
            out[(perm[i], perm[j])] = m[(i, j)];
        }
    }
    out
}

/// Full cross-code check for one molecule: energy, then J and K at a SINGLE
/// shared density.
///
/// Comparing each code's J/K at its OWN converged density would compare SCF
/// solutions, not J/K builders; the deviation would be dominated by how the
/// two codes' densities differ at the convergence floor. So ferric contracts
/// PySCF's converged density (read from the reference file) and the two J/K
/// matrices are then directly comparable.
///
/// `unscreened` selects whether the (expensive) `thresh = 0.0` builder check
/// runs. Disabling screening entirely means walking EVERY shell quartet with
/// no early-out, which is affordable on alkane_4 (106 basis functions, ~30 s)
/// but not on alkane_8 (202 functions) — a measured run there exceeded 69
/// minutes without finishing and was abandoned, so alkane_8 gets the
/// screened-path check in the default gate and an `#[ignore]`d unscreened
/// variant for when someone wants the stricter number.
fn check_directjk_vs_pyscf(tag: &str, e_bar: f64, jk_bar: f64, unscreened: bool) {
    let rec = DirectJkRef::load(tag);
    let mol = load_mol(tag);
    let bs = basis::bundled("cc-pvdz").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nbf = prep.nbasis();
    assert_eq!(
        nbf, rec.nbf,
        "{tag}: ferric has {nbf} basis functions, PySCF reference has {} — different basis, \
         not comparable",
        rec.nbf
    );

    // --- AO-identity guard (load-bearing; this one has already fired) ------
    // Before trusting any J/K number, prove the two codes are using the SAME
    // AO functions in the SAME order, via a matrix neither code can get wrong:
    // the overlap.
    //
    // This is not a formality. The first version of the reference generator
    // built its Mole with PySCF's built-in "ccpvdz", and this assert failed at
    // 2.9e-1. Cause: PySCF stores carbon's s block as an 8-primitive/2-column
    // general contraction plus a separate 1-primitive shell, while ferric's
    // bundled cc-pvdz.json stores all 9 s primitives in one 3-column block and
    // splits each column into its own segmented shell. Same span (PySCF's own
    // energy moves only 3.2e-12 Ha between the two layouts), same AO ordering,
    // same sparsity pattern — but DIFFERENT AO functions, so J and K were not
    // elementwise comparable. The generator now builds the Mole from ferric's
    // own JSON and the overlaps agree to ~1e-15.
    //
    // Without this guard the J/K assertions below would have failed with a
    // large deviation and no indication of why — or worse, been "fixed" by
    // loosening the tolerance until they passed.
    if rec.has_matrices() {
    let s_ferric = permute_to_pyscf(
        &ferric_integrals::oneelectron::overlap(&prep),
        &rec.ao_permutation,
    );
    let s_ref = rec.square(&rec.overlap);
    let s_dev = max_abs_diff(&s_ferric, &s_ref);
    assert!(
        s_dev < 1e-10,
        "{tag}: AO overlap matrices disagree by {s_dev:.3e} after applying ao_permutation — the \
         two codes' AO orderings (or basis definitions) do not match, so the J/K comparison \
         below would be meaningless"
    );
    }

    // --- Energy: each code's own converged E_tot ---------------------------
    // Tightened past the stock defaults because this comparison IS about the
    // absolute energy (PySCF's side ran at conv_tol = 1e-12), so ferric must
    // be converged well inside the 1e-8 bar. `density_conv` is the gate that
    // matters (see the repo note on energy_conv being a sanity bound); 1e-8
    // is enough for a 1e-8 energy comparison and, unlike the 1e-9 this
    // originally used, it converges on alkane_8 in reasonable time.
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &prep).expect("Schwarz bounds");
    let config = RhfConfig {
        density_conv: 1e-8,
        integral_thresh: PRODUCTION_INTEGRAL_THRESH,
        ..Default::default()
    };
    let res = solve_rhf(&ParallelContext::default(), &mol, &prep, op, &bounds, &config)
        .expect("RHF solve");
    assert!(res.converged, "{tag}: ferric RHF did not converge");
    let de = (res.energy - rec.e_tot).abs();
    eprintln!(
        "\n=== {tag}/cc-pVDZ DirectJK vs PySCF ===\n  E_ferric = {:.12} Ha\n  E_pyscf  = {:.12} Ha\n  |dE|     = {de:.3e} Ha",
        res.energy, rec.e_tot
    );
    assert!(
        de < e_bar,
        "{tag}: ferric E_tot {:.12} vs PySCF {:.12}, |dE| = {de:.3e} Ha exceeds {e_bar:.0e}",
        res.energy,
        rec.e_tot
    );

    // Matrix-level checks need the stored matrices; "energy_only" references
    // (alkane_8 — see the CASES note in the generator) stop here, having
    // already made their energy comparison above.
    if !rec.has_matrices() {
        eprintln!("  (energy-only reference: no stored J/K matrices to compare)");
        return;
    }

    // --- J/K at the SHARED density ----------------------------------------
    // PySCF's density comes in PySCF order; invert the permutation to express
    // it in ferric order before handing it to ferric's builder.
    let d_pyscf = rec.square(&rec.density);
    let mut d_ferric = Array2::<f64>::zeros((nbf, nbf));
    for i in 0..nbf {
        for j in 0..nbf {
            d_ferric[(i, j)] = d_pyscf[(rec.ao_permutation[i], rec.ao_permutation[j])];
        }
    }

    // PySCF's `get_jk` returns K as the raw exchange contraction and ferric's
    // build_jk uses the same convention (both contract a factor-2 RHF density,
    // with the 0.5 applied by the caller when forming F), so the matrices are
    // directly comparable. A convention divergence would show up as a clean
    // factor rather than as noise.
    let build_at = |thresh: f64| -> (f64, f64) {
        let mut j_f = Array2::zeros((nbf, nbf));
        let mut k_f = Array2::zeros((nbf, nbf));
        build_jk(
            &ParallelContext::default(),
            &prep,
            &bounds,
            thresh,
            &d_ferric,
            &mut j_f,
            &mut k_f,
        )
        .expect("ferric build_jk");
        (
            max_abs_diff(&permute_to_pyscf(&j_f, &rec.ao_permutation), &rec.square(&rec.j)),
            max_abs_diff(&permute_to_pyscf(&k_f, &rec.ao_permutation), &rec.square(&rec.k)),
        )
    };

    // --- UNSCREENED: the actual J/K BUILDER check -------------------------
    // thresh = 0.0 disables the Häser-Ahlrichs screen entirely (the test is
    // `bound_product < thresh`, and no non-negative product is < 0), so this
    // compares the contraction machinery itself against PySCF with nothing
    // approximated on either side. This is where a real builder defect would
    // show, and it is held to a tight bar.
    if unscreened {
        let (j_dev, k_dev) = build_at(0.0);
        eprintln!("  UNSCREENED (thresh=0):  max|dJ| = {j_dev:.3e}  max|dK| = {k_dev:.3e}");
        assert!(
            j_dev < jk_bar,
            "{tag}: UNSCREENED max|J_ferric - J_pyscf| = {j_dev:.3e} exceeds {jk_bar:.0e}. Both \
             codes contracted the SAME density with NO screening, so this is a J-BUILDER \
             deviation — not an SCF difference and not a screening-policy difference."
        );
        assert!(
            k_dev < jk_bar,
            "{tag}: UNSCREENED max|K_ferric - K_pyscf| = {k_dev:.3e} exceeds {jk_bar:.0e}. Both \
             codes contracted the SAME density with NO screening, so this is a K-BUILDER \
             deviation — not an SCF difference and not a screening-policy difference."
        );
    }

    // --- PRODUCTION SCREENING: documents the accuracy actually shipped ----
    // At the production `integral_thresh` the deviation is MUCH larger than
    // the unscreened one, and the reason is neither code being wrong. ferric
    // builds its libint2 engines at precision 1e-14 (hardcoded at every
    // `EnginePool::new` call site). For 22 of alkane_4's 2916 shell pairs the
    // true (ij|ij) is 1e-13..3e-17, and at precision 1e-14 libint2 declines to
    // compute those quartets AT ALL — so `SchwarzBounds::compute` records
    // Q = 0.0 for them, and `build_jk`'s `bound_product < thresh` screen then
    // discards every quartet built from such a pair (32439 of 1103355 on
    // alkane_4). PySCF computes them. Their summed contribution is the gap.
    //
    // MEASURED (alkane_4, PySCF's converged density, unscreened build, Schwarz
    // table rebuilt at the matching precision):
    //
    //     engine precision   max|dJ|     max|dK|
    //     1e-14 (production) 8.50e-11    9.70e-11
    //     1e-20              9.92e-13    1.10e-13
    //     1e-25              9.92e-13    1.10e-13
    //     1e-30              9.92e-13    1.10e-13
    //
    // i.e. tightening the engine drives ferric onto PySCF and then saturates —
    // the builders agree, and 1e-14 is a deliberate speed/accuracy choice.
    // This assertion therefore pins the SHIPPED behaviour at a bar the
    // production configuration can actually meet, so a genuine regression in
    // the screened path is still caught while the known precision policy is
    // not reported as a failure.
    let (j_dev_s, k_dev_s) = build_at(PRODUCTION_INTEGRAL_THRESH);
    eprintln!("  SCREENED (thresh=1e-14): max|dJ| = {j_dev_s:.3e}  max|dK| = {k_dev_s:.3e}");
    assert!(
        j_dev_s < SCREENED_JK_BAR && k_dev_s < SCREENED_JK_BAR,
        "{tag}: at the production integral threshold max|dJ| = {j_dev_s:.3e}, max|dK| = \
         {k_dev_s:.3e}, exceeding {SCREENED_JK_BAR:.0e}. The unscreened build above passed, so \
         the J/K contraction itself is fine and this is a SCREENING regression."
    );
}

/// (c) DirectJK vs the PySCF reference on alkane_4 — the GO/NO-GO gate for the
/// whole screening campaign. A failure of the ENERGY bar, or of the UNSCREENED
/// J/K bar, is a live accuracy defect in the direct J/K path rather than a
/// tolerance question.
///
/// Measured at the time of writing: |dE| = 5.145e-9 Ha; unscreened
/// max|dJ| = 8.50e-11, max|dK| = 9.70e-11.
#[test]
fn directjk_matches_pyscf_alkane_4() {
    check_directjk_vs_pyscf("alkane_4", 1e-8, 1e-9, true);
}

/// (c) The same cross-code check on the larger alkane_8, which is also the
/// system the threshold sweep above runs on.
///
/// Energy + screened-path J/K only. The unscreened builder check is the
/// `#[ignore]`d variant below: with screening off there is no early-out at
/// all, and a measured attempt on alkane_8 ran past 69 minutes without
/// finishing. alkane_4 carries the unscreened check in the default gate.
///
/// # The energy bar here is 1e-3, and that is a KNOWN DEFECT, not slack
///
/// ferric's screened alkane_8 RHF energy is -313.451984590 vs PySCF's
/// -313.451838457 — ferric is 1.46e-4 Ha LOWER, which looks like a better
/// variational solution but is not one. Measured decomposition on ferric's
/// OWN converged density (so no SCF-basin question is involved):
///
/// | quantity                                   | alkane_4   | alkane_8   |
/// |--------------------------------------------|------------|------------|
/// | E_tot, screening at 1e-14                   | -157.307058536411 | -313.451984590444 |
/// | E_tot, screening OFF (thresh = 0)           | -157.307058531341 | -313.451806106075 |
/// | screening-induced shift                     | -5.07e-9   | -1.78e-4   |
/// | unscreened E vs PySCF on the SAME density   |  4.8e-11   |  7.0e-9    |
///
/// Read the last row first: with screening off, ferric reproduces PySCF's
/// energy functional on the identical density to 4.8e-11 / 7.0e-9. The
/// integrals, the J/K builders and the 0.5·Tr[D(H+F)] + Vnn expression are all
/// correct. The entire discrepancy is the SCREEN, and it lands in EJ:
/// 528.692031257 (screened) vs 528.692211350 (unscreened).
///
/// Cause: `SchwarzBounds::compute` builds its Q table from libint2 engines at
/// the hardcoded 1e-14 precision. For shell pairs whose true (ij|ij) is below
/// that, libint2 returns nothing and Q is recorded as exactly 0.0; every
/// quartet built from such a pair then fails `bound_product < thresh` for ANY
/// positive threshold and is dropped. On alkane_4 that is 32439 of 1103355
/// quartets worth 5e-9 Ha — invisible. On alkane_8 the same mechanism is worth
/// 1.78e-4 Ha. The error grew ~35000x for a 2x size increase, so it is
/// size-DIVERGENT and this bar cannot simply be widened for bigger systems.
///
/// It is also signed: dropping positive Coulomb contributions makes the energy
/// spuriously LOW, so it mimics a better SCF solution rather than announcing
/// itself as an error.
///
/// This test therefore pins the CURRENT behaviour with an explicit bar and this
/// explanation attached, so the defect is recorded rather than hidden. When the
/// underlying issue is fixed (raising the Schwarz-table engine precision above
/// the screening threshold is the obvious candidate), tighten this to 1e-8 —
/// the same bar alkane_4 already meets.
#[test]
fn directjk_matches_pyscf_alkane_8() {
    check_directjk_vs_pyscf("alkane_8", 1e-3, 1e-8, false);
}

/// (c) alkane_8 WITH the unscreened builder check.
///
/// `#[ignore]`d on cost, not on doubt: `thresh = 0.0` disables every early-out
/// so the build walks all ~10^7 shell quartets of a 202-function basis.
/// Measured: still running at 69 minutes when abandoned. Run it deliberately:
///
/// ```text
/// OPENBLAS_NUM_THREADS=1 FERRIC_MEM_BUDGET_GB=2 \
///   scripts/ferric-limited --max=4G --high=3600M -- \
///   cargo test -p ferric-scf --test screening_exactness --release \
///   -- --ignored --nocapture directjk_matches_pyscf_alkane_8_unscreened
/// ```
#[test]
#[ignore = "expensive: unscreened (thresh=0) J/K on 202 basis functions; >69 min measured"]
fn directjk_matches_pyscf_alkane_8_unscreened() {
    check_directjk_vs_pyscf("alkane_8", 1e-8, 1e-8, true);
}

/// KNOWN DEFECT, pinned: LinK CANNOT reproduce the dense K even in its own
/// trivial limit.
///
/// This is the exactness anchor the repo's protocol demands ("every
/// approximation has a trivial limit where it does nothing — write the
/// `matches_exact_in_the_trivial_limit` test BEFORE measuring anything"), and
/// on alkane_8 it FAILS: at `thresh = 0`, where the screen is supposed to
/// discard nothing at all, LinK still differs from the dense build by ~2e-3.
///
/// MEASURED (alkane_8/cc-pVDZ, ferric's converged density, dense reference
/// built at thresh = 0):
///
/// | thresh | max\|K_LinK - K_dense\| | significant pairs |
/// |--------|------------------------|-------------------|
/// | 1e-10  | 1.9298e-3              | 3987 / 5253       |
/// | 1e-12  | 1.9586e-3              | 4145 / 5253       |
/// | 1e-14  | 1.9586e-3              | 4153 / 5253       |
/// | 1e-16  | 1.9586e-3              | 4153 / 5253       |
/// | **0**  | **1.9586e-3**          | **4153 / 5253**   |
///
/// The pair count plateaus at 4153 and never reaches 5253: exactly 1049 of
/// alkane_8's 5253 shell pairs have a Schwarz Q of exactly 0.0, and
/// `SignificantPairs::build` keeps a pair only when `estimate(..) > threshold`
/// — a STRICT comparison that 0.0 fails even against a threshold of 0.0. Those
/// 20% of pairs are unreachable at any threshold.
///
/// Same root cause as the energy defect below: Q is built from libint2 engines
/// at the hardcoded 1e-14 precision, so pairs whose true (ij|ij) lies under
/// that get Q = 0. Raising ONLY that precision moves both numbers together,
/// which is what identifies it as the cause rather than a correlate:
///
/// | Schwarz-table precision | Q == 0 pairs | LinK(thresh=0) max\|dK\| |
/// |-------------------------|--------------|-------------------------|
/// | 1e-14 (production)      | 1049 / 5253  | 1.96e-3                 |
/// | 1e-20                   |  529 / 5253  | 5.44e-4                 |
/// | 1e-26                   |  226 / 5253  | 2.11e-4                 |
/// | 1e-32                   |  133 / 5253  | 9.03e-5                 |
///
/// Note this is invisible on the molecules the pre-existing `link_k.rs` tests
/// use: water and CH4 have NO underflowed pairs, so LinK is exact there and
/// those tests pass while proving nothing about this.
///
/// Assertion shape matches the energy defect below: an upper bound that
/// catches regression, and a lower bound that FAILS ONCE FIXED so the claim
/// cannot go stale.
#[test]
fn link_k_cannot_reach_the_dense_answer_alkane_8() {
    let mol = load_mol("alkane_8");
    let bs = basis::bundled("cc-pvdz").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let full_triangle = nsh * (nsh + 1) / 2;
    let d = converged_density(&mol, &bs, &prep);

    // The trivial limit: screening disabled on BOTH sides.
    let k_dense = dense_k(&prep, &d, 0.0);
    let k_link = link_k(BoundKind::Schwarz, &mol, &bs, &prep, &d, 0.0);
    let err = max_abs_diff(&k_link, &k_dense);

    let bound = make_bound(BoundKind::Schwarz, &mol, &bs, &prep, Operator::coulomb());
    let retained = SignificantPairs::build(bound.as_dyn(), nsh, 0.0).total_pairs() / 2;

    eprintln!(
        "alkane_8/cc-pVDZ LinK trivial limit (thresh=0): max|K_link - K_dense| = {err:.4e}, \
         significant pairs {retained} / {full_triangle}"
    );

    assert!(
        err < 1e-2,
        "alkane_8: LinK-vs-dense error at thresh=0 is {err:.4e}, worse than the ~1.96e-3 recorded \
         when this test was written — the exactness defect has regressed"
    );
    assert!(
        err > 1e-4,
        "alkane_8: LinK now reproduces the dense K at thresh=0 to {err:.4e}. If the Schwarz \
         Q-underflow defect has been FIXED, this test has done its job: delete it, restore a real \
         `link_k_matches_dense_in_the_trivial_limit` assertion (err < 1e-10) in its place, and \
         tighten LINK_VS_DENSE_SLACK/the energy bars accordingly."
    );
    assert!(
        retained < full_triangle,
        "alkane_8: SignificantPairs now retains all {full_triangle} pairs at thresh=0 — the \
         underflow defect appears fixed; see the message above for what to do."
    );
}

/// KNOWN DEFECT, pinned: screening at the default `integral_thresh` shifts the
/// Coulomb energy by an amount that GROWS with system size.
///
/// This is the finding that came out of building the anchors in this file, and
/// it is recorded as an executable fact rather than a comment so that a fix
/// (or a regression) is detected rather than argued about.
///
/// What is measured, on ONE fixed density per molecule (PySCF's converged
/// density, read from the reference file), contracted twice — once with the
/// production screen and once with screening disabled:
///
///   alkane_4:  |E(1e-14) - E(0)| ~ 5.0e-9   (negligible)
///   alkane_8:  |E(1e-14) - E(0)| ~ 1.8e-4   (35000x larger)
///
/// (alkane_4 contracts PySCF's density, alkane_8 ferric's own — see the code.
/// The choice is immaterial: each shift is a ferric-vs-ferric difference at
/// two thresholds on ONE fixed density. On PySCF's density alkane_8 gives
/// 1.14e-4 rather than 1.79e-4; same phenomenon, same order.)
///
/// Using one fixed density for both builds removes the SCF entirely from the
/// comparison: any difference is the screen and nothing else.
///
/// Mechanism (see `directjk_matches_pyscf_alkane_8`): Q entries that underflow
/// to exactly 0.0 at libint2's hardcoded 1e-14 engine precision cause every
/// quartet on that shell pair to be screened at any positive threshold.
///
/// The assertion is deliberately two-sided. The upper bound catches the defect
/// getting WORSE. The lower bound FAILS ONCE THE DEFECT IS FIXED — that is
/// intentional, so nobody fixes the screen and leaves this test quietly
/// asserting a stale claim; the fix should delete this test (or invert it) and
/// tighten `directjk_matches_pyscf_alkane_8`'s energy bar to 1e-8.
#[test]
fn known_defect_screening_shifts_coulomb_energy_with_size() {
    let mut shifts = Vec::new();
    for tag in ["alkane_4", "alkane_8"] {
        let rec = DirectJkRef::load(tag);
        let mol = load_mol(tag);
        let bs = basis::bundled("cc-pvdz").expect("basis");
        let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
        let nbf = prep.nbasis();
        let op = Operator::coulomb();
        let bounds = SchwarzBounds::compute(op, &prep).expect("Schwarz bounds");

        // Use PySCF's density when the reference carries it (so the two
        // molecules' numbers are directly comparable to the cross-code test
        // above), and ferric's own converged density otherwise. Either works:
        // the comparison here is ferric-vs-ferric at two thresholds on ONE
        // fixed density, so the density's provenance is irrelevant as long as
        // it is the same on both sides of the subtraction.
        let d = if rec.has_matrices() {
            let d_pyscf = rec.square(&rec.density);
            let mut d = Array2::<f64>::zeros((nbf, nbf));
            for i in 0..nbf {
                for j in 0..nbf {
                    d[(i, j)] = d_pyscf[(rec.ao_permutation[i], rec.ao_permutation[j])];
                }
            }
            d
        } else {
            converged_density(&mol, &bs, &prep)
        };

        let h = ferric_integrals::oneelectron::hcore(&prep);
        let vnn = mol.nuclear_repulsion();
        let energy_at = |thresh: f64| -> f64 {
            let mut j = Array2::zeros((nbf, nbf));
            let mut k = Array2::zeros((nbf, nbf));
            build_jk(
                &ParallelContext::default(),
                &prep,
                &bounds,
                thresh,
                &d,
                &mut j,
                &mut k,
            )
            .expect("build_jk");
            let f = &h + &j - &(0.5 * &k);
            0.5 * (&d * &(&h + &f)).sum() + vnn
        };

        let e_screened = energy_at(PRODUCTION_INTEGRAL_THRESH);
        let e_exact = energy_at(0.0);
        let shift = (e_screened - e_exact).abs();
        eprintln!(
            "{tag}: E(thresh=1e-14) = {e_screened:.12}, E(thresh=0) = {e_exact:.12}, \
             |shift| = {shift:.3e} Ha"
        );
        shifts.push((tag, shift));
    }

    let (_, s4) = shifts[0];
    let (_, s8) = shifts[1];

    assert!(
        s4 < 1e-7,
        "alkane_4 screening shift {s4:.3e} Ha is larger than the ~5e-9 recorded when this test \
         was written — the screening defect has gotten worse on SMALL systems too"
    );
    assert!(
        s8 < 1e-3,
        "alkane_8 screening shift {s8:.3e} Ha exceeds the ~1.8e-4 recorded when this test was \
         written — the screening defect has gotten worse"
    );
    assert!(
        s8 > 1e-5,
        "alkane_8 screening shift is only {s8:.3e} Ha, far below the 1.8e-4 this test was written \
         to pin. If the Q-underflow screening defect has been FIXED, that is good news and this \
         test has done its job: delete it and tighten the energy bar in \
         directjk_matches_pyscf_alkane_8 from 1e-3 to 1e-8."
    );
    assert!(
        s8 > s4 * 100.0,
        "the screening shift is no longer strongly size-divergent (alkane_4 {s4:.3e} vs alkane_8 \
         {s8:.3e}); re-derive the mechanism before trusting either bar"
    );
}

/// The QQR arm of [`BoundKind`] must stay constructible and usable, so the
/// follow-up PR that turns on QQR screening extends the case lists above
/// rather than discovering that the generic plumbing rotted.
///
/// Deliberately tiny (water/STO-3G): this checks WIRING, not physics — the
/// physics assertions for QQR are the sweep above, once it is enabled.
#[test]
fn qqr_bound_arm_is_wired() {
    let mol = Molecule::parse_xyz(
        "3\nwater\nO 0.000000 0.000000 0.117790\nH 0.000000 0.755453 -0.471161\nH 0.000000 -0.755453 -0.471161\n",
        0,
        1,
    )
    .unwrap();
    let bs = basis::bundled("sto-3g").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let op = Operator::coulomb();

    for kind in [BoundKind::Schwarz, BoundKind::Qqr] {
        let bound = make_bound(kind, &mol, &bs, &prep, op);
        // Negative threshold = the vacuous screen; see the longer note in
        // `significant_pairs_actually_screens_alkane_8` for why 0.0 is not it.
        let sp = SignificantPairs::build(bound.as_dyn(), nsh, -1.0);
        assert_eq!(
            sp.total_pairs(),
            nsh * nsh,
            "{}: a negative threshold must retain every ordered shell pair",
            kind.label()
        );
    }
}
