//! Screening-exactness anchors for the direct J/K and LinK exchange builders.
//!
//! # Why this file exists
//!
//! The LinK correctness tests that live in `crates/ferric-scf/src/link_k.rs`
//! all build K at `thresh = 1e-14` on water (3 atoms) and CH4 (5 atoms). At
//! that threshold on molecules that small, `SignificantPairs::build` retains
//! effectively the FULL `nsh*(nsh+1)/2` pair list, so no shell quartet is ever
//! screened away: LinK and the dense reference walk the same quartets and of
//! course agree. Those assertions pass for reasons that have nothing to do
//! with screening — they are decorative. Separately,
//! `tests/mpi_direct_jk_correctness.rs` anchors the direct-path RHF energy to
//! a value ferric measured from itself, which pins behaviour but not physics.
//!
//! This file supplies what was missing — and, in doing so, turned up two real
//! defects that the decorative tests could not see (both pinned by name below).
//!
//! * a **threshold sweep** on a system large enough that screening genuinely
//!   fires (alkane_8 = C8H18, 26 atoms, 202 cc-pVDZ basis functions),
//!   measuring `max|K_LinK(t) - K_dense(t)|` across five thresholds. Both
//!   builders run at the SAME `t`, which holds the screen they share fixed and
//!   isolates LinK's own pair-list approximation.
//!
//! * a **reachable-pass-condition check** (repo rule: "a test you have never
//!   seen fail is an assumption", and its sibling, "check the pass condition
//!   is REACHABLE"). At a loose threshold screening must have discarded a
//!   substantial fraction of the pair list — not merely one pair. That exact
//!   strengthening came out of mutation testing: a "retain everything" mutant
//!   still left 5202 of 5253 pairs, passing a naive `< full_triangle` check.
//!
//! * **cross-code J/K references** from PySCF's direct SCF path (generated by
//!   `scripts/gen_pyscf_directjk_refs.py`; see that file's header for the
//!   comparison protocol, the `mf._eri is None` direct-path guarantee, and why
//!   the reference Mole is built from ferric's OWN basis JSON).
//!
//! # What was found: an INVALID BOUND, not lost significant integrals
//!
//! (This section is written in the past tense: the defect it describes is
//! FIXED. It is kept because these tests exist to stop it returning, and the
//! reasoning is what makes the current bars defensible rather than arbitrary.)
//!
//! Both defects traced to one cause, and it is important to state that cause
//! precisely, because the obvious reading of it is wrong.
//!
//! `SchwarzBounds::compute` built its Q table from libint2 engines at a
//! hardcoded 1e-14 precision — the SAME value later used as the screening
//! threshold. libint2 therefore declined to compute shell pairs whose value
//! sat below its stated precision, and ferric recorded Q = 0.0 for them.
//!
//! **Most of those pairs are genuinely tiny — but not all of them.** The true
//! `sqrt(max|(ij|ij)|)` per shell pair was measured in PySCF via
//! `mol.intor('int2e_sph', shls_slice=...)`, on a Mole built from ferric's own
//! basis JSON so the shell decomposition MATCHES (102 shells, 5253 pairs) and
//! the counts are directly comparable:
//!
//! ```text
//! ferric Q == 0.0                                     1049 / 5253
//! true Q == 0.0 (genuinely zero)                       121 / 5253
//! ferric Q < true Q  (bound invariant VIOLATED)       1794 / 5253
//!   ... of which ferric Q is exactly 0.0               928
//!
//! Of the 1049 pairs ferric zeroes, their TRUE Q:
//!   < 1e-7  (= sqrt(1e-14), the screening scale)       763
//!   < 1e-10                                            342
//!   < 1e-14                                            139
//!   smallest nonzero                              3.50e-15
//!   LARGEST                                       6.51e-05   <-- not tiny
//! ```
//!
//! An independent measurement on a 94-shell decomposition of the same molecule
//! gave 1079 of 4465 pairs below 1e-7, 417 exact zeros, and a smallest nonzero
//! true Q of 2.200e-15 — the same picture at a different shell partitioning.
//!
//! Two things follow, and BOTH matter:
//!
//! 1. libint2 is largely doing what it documents — 763 of the 1049 zeroed
//!    pairs really are below the 1e-7 screening scale. So the defect is NOT
//!    simply "libint2 throws away big integrals".
//! 2. But the zeroing is not confined to negligible pairs: the largest true Q
//!    among them is 6.51e-05, some 600x ABOVE the screening scale, and 1794
//!    pairs in total carry a stored Q below their true value.
//!
//! Either way the fatal property is the same. **A Schwarz bound must always
//! OVERESTIMATE the true integral — that is what makes it a bound** (PySCF
//! screening paper, arXiv:2302.11307). A stored `Q = 0` for a pair whose true
//! (ij|ij) is nonzero UNDERestimates it, breaking that invariant. And because
//! `SignificantPairs::build` keeps a pair only when `estimate(..) > threshold`
//! — a STRICT comparison — a zero entry fails even against a threshold of 0.
//! Those pairs become unreachable at EVERY threshold, which is what destroys
//! the trivial-limit exactness anchor: there is no setting of `thresh` at
//! which the screen does nothing.
//!
//! The standard remedy is to build the screening table TIGHTER than the
//! threshold it will enforce, with a floor. PySCF builds `q_cond` at
//! `direct_scf_tol**2` with a 1e-100 floor (verified in source); Molpro,
//! NWChem, Q-Chem, ORCA and Psi4 all do the equivalent. ferric using one
//! hardcoded 1e-14 for BOTH the table and the screen was the outlier.
//!
//! # THE DEFECT IS FIXED — what this file now pins
//!
//! `crates/ferric-integrals/src/schwarz.rs` builds the table at
//! `SCHWARZ_TABLE_PRECISION = 0.0` (libint2 prescreening off for the table
//! build) and floors every entry at `SCHWARZ_Q_FLOOR = 1e-100`. Everything
//! above is retained as the RECORD OF THE DEFECT, because these tests exist to
//! stop it coming back, and a bare assertion with no history behind it invites
//! exactly the "just widen the bar" response that created it.
//!
//! Measured across the fix:
//!
//! ```text
//!                                            before      after
//! LinK vs dense at thresh=0 (alkane_8)       1.9586e-3   3.1086e-15
//! Q == 0.0 table entries (alkane_8)          1049/5253   0/5253
//! Q == 0.0 table entries (alkane_16)         9977/19701  0/19701
//! smallest nonzero stored Q (alkane_8)       4.632e-07   1.302e-60
//! significant pairs at thresh=0 (alkane_8)   4153/5253   5202/5253
//! energy shift from screening (alkane_4)     5.0e-9      0.0 (bit-identical)
//! energy shift from screening (alkane_8)     1.8e-4      0.0 (bit-identical)
//! E vs PySCF, screened (alkane_8)            1.46e-4     6.963e-9
//! Schwarz table build time (alkane_8)        0.0262 s    0.0412 s
//! Schwarz table build time (alkane_16)       0.0452 s    0.1328 s
//! ```
//!
//! The pre-fix smallest nonzero Q of 4.632e-07 is `sqrt(~1e-13)` — the
//! fingerprint of the engine's precision cliff rather than of any property of
//! octane, which is the cleanest single piece of evidence that the cause was
//! the table precision and not the molecule.
//!
//! The standing assertions are:
//!
//! 1. `link_k_matches_dense_in_the_trivial_limit` — at `thresh = 0` the screen
//!    must do nothing, so LinK must reproduce the dense build to machine
//!    precision, and no table entry may be exactly 0.0.
//! 2. `screening_does_not_shift_the_energy_at_production_thresh` — at 1e-14 on
//!    these systems the screened and unscreened energies are bit-identical.
//!    This is NOT a claim that Schwarz screening is exact in general:
//!    truncation errors are EXTENSIVE, scaling linearly with system size
//!    (Hollman, Schaefer & Valeev, Mol. Phys. 115, 2065-2076 (2017),
//!    DOI 10.1080/00268976.2017.1346312), so a large enough system at a loose
//!    enough threshold will legitimately show a shift.
//! 3. The invariant at its source lives in `schwarz.rs` itself
//!    (`schwarz_table_never_stores_a_zero_alkane_8`).
//!
//! None of this is visible on water or CH4, which have no pairs under the
//! precision cliff — which is precisely why the pre-existing tests passed
//! while proving nothing.
//!
//! With screening OFF, ferric reproduces PySCF's J/K on the same density to
//! 8.5e-11 and its energy functional to 4.8e-11 (alkane_4) / 7.0e-9
//! (alkane_8). The integrals, the J/K builders, and the energy expression were
//! always correct; the screen was the sole defect, and the screened numbers
//! have now converged onto these unscreened ones.
//!
//! # Bound-type parameterization
//!
//! Every screening assertion runs through [`BoundKind`], which selects the
//! `Bound` implementation at run time. BOTH arms are now exercised in the
//! default gate: [`BoundKind::Schwarz`] and [`BoundKind::Qqr`] run the same
//! threshold sweep and the same trivial-limit anchor, against the same bars,
//! rather than a forked copy of this file.
//!
//! Note that QQR passing this harness establishes CORRECTNESS, not benefit.
//! The cost measurement (`tests/qqr_link_cost.rs`) found QQR screens only
//! 0.009% more quartets than Schwarz inside LinK — because both LinK pair-list
//! builders screen on the diagonal quartet `(ij|ij)`, where QQR's distance
//! envelope is identically 1 (`tests/qqr_diagonal_noop.rs`). QQR is therefore
//! NOT wired into the production path; these arms keep it correct for the
//! non-LinK callers and for any future use.
//!
//! # Running
//!
//! Default gate (alkane_4 + alkane_8):
//!
//! ```text
//! OPENBLAS_NUM_THREADS=1 FERRIC_MEM_BUDGET_GB=2 \
//!   scripts/ferric-limited --max=4G --high=3600M -- \
//!   cargo test -p ferric-scf --test screening_exactness --release
//! ```
//!
//! The `#[ignore]`d alkane_12 case (38 atoms, 298 basis functions) runs the
//! dense O(N^4) reference build five times and takes far longer than a gate
//! should; run it explicitly with:
//!
//! ```text
//! OPENBLAS_NUM_THREADS=1 FERRIC_MEM_BUDGET_GB=2 \
//!   scripts/ferric-limited --max=4G --high=3600M -- \
//!   cargo test -p ferric-scf --test screening_exactness --release \
//!   -- --ignored --nocapture link_k_thresh_sweep_alkane_12
//! ```

use ferric_core::basis::{self, BasisSet};
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::fock::KBuilder;
use ferric_scf::link_k::LinkK;
use ferric_scf::pairs::SignificantPairs;
use ferric_scf::qqr::QqrBounds;
use ferric_scf::rhf::{build_jk, solve_rhf, RhfConfig};
use ferric_scf::screening::{Bound, SchwarzBounds};
use ndarray::Array2;

/// Which `Bound` implementation the screening harness should drive.
///
/// This is the parameterization hook: adding `BoundKind::Qqr` to a sweep's
/// case list re-runs the identical assertions against QQR bounds. It exists so
/// the follow-up QQR PR extends a list instead of copying this file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum BoundKind {
    Schwarz,
    Qqr,
}

impl BoundKind {
    fn label(self) -> &'static str {
        match self {
            BoundKind::Schwarz => "Schwarz",
            BoundKind::Qqr => "QQR",
        }
    }
}

/// A constructed bound, kept as an owned enum so callers can hand out a
/// `&dyn Bound` without the two arms needing the same concrete type.
enum AnyBound {
    Schwarz(Box<SchwarzBounds>),
    Qqr(Box<QqrBounds>),
}

impl AnyBound {
    fn as_dyn(&self) -> &dyn Bound {
        match self {
            AnyBound::Schwarz(b) => b.as_ref(),
            AnyBound::Qqr(b) => b.as_ref(),
        }
    }
}

fn make_bound(
    kind: BoundKind,
    mol: &Molecule,
    bs: &BasisSet,
    prep: &PreparedBasis,
    op: Operator,
) -> AnyBound {
    let schwarz = SchwarzBounds::compute(op, prep).expect("Schwarz bounds");
    match kind {
        BoundKind::Schwarz => AnyBound::Schwarz(Box::new(schwarz)),
        BoundKind::Qqr => AnyBound::Qqr(Box::new(QqrBounds::new(schwarz, mol, bs, prep, op))),
    }
}

/// Load a testdata molecule by stem, e.g. `"alkane_8"`.
fn load_mol(stem: &str) -> Molecule {
    Molecule::load_xyz(&format!("../../testdata/molecules/{stem}.xyz"))
        .unwrap_or_else(|e| panic!("cannot load {stem}.xyz: {e}"))
}

/// Converge RHF and return `(density_total, PreparedBasis-owning inputs)`.
///
/// The density is the contraction input for every J/K comparison below; it is
/// deliberately NOT rebuilt per threshold, so a sweep varies exactly one thing
/// (the screening threshold) and nothing else.
fn converged_density(mol: &Molecule, bs: &BasisSet, prep: &PreparedBasis) -> Array2<f64> {
    let op = Operator::coulomb();
    let _ = bs;
    let bounds = SchwarzBounds::compute(op, prep).expect("Schwarz bounds");
    // Stock convergence settings on purpose. What the sweep needs from this
    // density is only that it be FIXED and physically sensible — every
    // threshold in the sweep contracts the SAME matrix, so the density's own
    // convergence level cancels out of the LinK-vs-dense comparison entirely.
    //
    // An earlier version forced density_conv = 1e-9 / integral_thresh = 1e-12
    // here. That bought nothing and cost enormously: on alkane_8 (202 basis
    // functions, hcore guess) the SCF ground on past 60 minutes without
    // finishing, which is also what the repo's own note
    // ("energy_conv is a sanity bound, not a target") warns about. Do not
    // re-tighten these without measuring the alkane_8 wall time first.
    let config = RhfConfig::default();
    let res = solve_rhf(&ParallelContext::default(), mol, prep, op, &bounds, &config)
        .expect("RHF solve");
    assert!(
        res.converged,
        "RHF did not converge for the screening anchor — refusing to measure screening error \
         against an unconverged density"
    );
    res.density_total
}

/// Dense reference K: the canonical screened quartet loop at `thresh`.
fn dense_k(prep: &PreparedBasis, d: &Array2<f64>, thresh: f64) -> Array2<f64> {
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, prep).expect("Schwarz bounds");
    let n = prep.nbasis();
    let mut j = Array2::zeros((n, n));
    let mut k = Array2::zeros((n, n));
    build_jk(
        &ParallelContext::default(),
        prep,
        &bounds,
        thresh,
        d,
        &mut j,
        &mut k,
    )
    .expect("dense build_jk");
    k
}

/// LinK K at `thresh` under the selected bound type.
fn link_k(
    kind: BoundKind,
    mol: &Molecule,
    bs: &BasisSet,
    prep: &PreparedBasis,
    d: &Array2<f64>,
    thresh: f64,
) -> Array2<f64> {
    let op = Operator::coulomb();
    let bound = make_bound(kind, mol, bs, prep, op);
    let ctx = ParallelContext::default();
    let n = prep.nbasis();
    let mut k = Array2::zeros((n, n));
    match &bound {
        AnyBound::Schwarz(b) => {
            let mut link = LinkK::new(&ctx, prep, b.as_ref(), op, thresh, usize::MAX);
            link.update_density(d);
            link.build(d, &mut k).expect("LinK build");
        }
        AnyBound::Qqr(b) => {
            let mut link = LinkK::new(&ctx, prep, b.as_ref(), op, thresh, usize::MAX);
            link.update_density(d);
            link.build(d, &mut k).expect("LinK build");
        }
    }
    k
}

fn max_abs_diff(a: &Array2<f64>, b: &Array2<f64>) -> f64 {
    assert_eq!(a.dim(), b.dim(), "shape mismatch in max_abs_diff");
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f64, f64::max)
}

/// Thresholds swept, loosest first. The sequence must be strictly decreasing
/// so "error decreases monotonically" is a meaningful statement.
const THRESH_SWEEP: [f64; 5] = [1e-6, 1e-8, 1e-10, 1e-12, 1e-14];

/// Bar for LinK vs the dense build at the SAME threshold.
///
/// A flat constant, not a multiple of `thresh`. Measured on alkane_8/cc-pVDZ,
/// before and after the invalid-Schwarz-bound fix:
///
/// | thresh | max\|K_LinK - K_dense(thresh)\| | after fix |
/// |--------|--------------------------------|-----------|
/// | 1e-6   | 4.83e-3                        | 4.822e-3  |
/// | 1e-8   | 2.54e-3                        | 2.593e-3  |
/// | 1e-10  | 1.92e-3                        | 1.492e-3  |
/// | 1e-12  | 1.94e-3                        | 1.317e-3  |
/// | 1e-14  | 1.94e-3                        | 8.047e-4  |
///
/// Before the fix the error PLATEAUED at 1.94e-3 from 1e-10 down, because it
/// was dominated by the shared invalid-bound floor rather than by the
/// threshold. It now decreases monotonically all the way to the tight end, and
/// what remains is LinK's OWN approximation — its density-weighted restriction
/// of the ket loop, which is a real and intended part of the method, not a
/// defect. Note this is LinK vs dense at the SAME threshold, so the shared
/// Schwarz screen cancels between the two sides; the quantity that went to
/// machine precision is the trivial limit at thresh = 0, asserted in
/// `link_k_matches_dense_in_the_trivial_limit`.
///
/// Tying the bar to `thresh` would make it unreachable by construction at the
/// tight end, which is the failure mode this file exists to prevent. The 1e-2
/// constant still clears the largest measured value (4.8e-3 at the loose end,
/// where LinK legitimately approximates most) with roughly 2x headroom.
const LINK_VS_DENSE_BAR: f64 = 1e-2;

/// The `integral_thresh` a production SCF run uses.
const PRODUCTION_INTEGRAL_THRESH: f64 = 1e-14;

/// Bar for the J/K deviation vs PySCF at [`PRODUCTION_INTEGRAL_THRESH`].
///
/// Deliberately looser than the unscreened bar, and NOT a fudge: see the long
/// note in `check_directjk_vs_pyscf`. ferric's libint2 engines are built at
/// precision 1e-14, so shell pairs whose true (ij|ij) falls below that are
/// assigned Q = 0 and screened out; PySCF computes them. Measured deviation on
/// alkane_4 is 5.08e-6 (J) / 1.57e-6 (K), alkane_8 is 1.54e-3 (J) / 3.68e-5
/// (K) — the growth with size is the defect, not noise. The same comparison
/// with screening OFF agrees to ~1e-11, which is what proves the builders
/// themselves are correct.
const SCREENED_JK_BAR: f64 = 1e-2;

/// Shared body of the threshold sweep, so alkane_8 (gated) and alkane_12
/// (ignored) run byte-identical logic rather than two drifting copies.
fn run_thresh_sweep(kind: BoundKind, stem: &str, basis_name: &str) {
    let mol = load_mol(stem);
    let bs = basis::bundled(basis_name).expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let nbf = prep.nbasis();
    let d = converged_density(&mol, &bs, &prep);

    eprintln!(
        "\n=== LinK thresh sweep: {stem}/{basis_name}, bound={}, natm={}, nsh={nsh}, nbf={nbf} ===",
        kind.label(),
        mol.atoms.len()
    );
    eprintln!("{:>10}  {:>14}  {:>14}", "thresh", "max|dK|", "retained_pairs");

    let full_triangle = nsh * (nsh + 1) / 2;
    let mut errs: Vec<(f64, f64)> = Vec::new();

    // REFERENCE: the dense canonical quartet build at the SAME threshold.
    //
    // This measures what LinK's own approximation costs — its pair-list
    // restriction of the ket loop — with the Häser-Ahlrichs/Schwarz screen
    // that BOTH builders share held constant between them, so the shared screen
    // cancels and this sweep isolates LinK's contribution alone.
    //
    // HISTORICAL NOTE, kept because it explains the shape of this harness: the
    // alternative of a single fixed reference at thresh = 0 was MEASURED and did
    // NOT work while the invalid-bound defect stood. LinK's error against the
    // exact K fell 4.83e-3 -> 2.54e-3 -> 1.93e-3 and then ROSE to 1.959e-3 and
    // plateaued, because LinK inherited the bound's invalid floor and could not
    // converge to the exact answer at all. That defect is fixed (the trivial
    // limit is now exact to 3.1e-15, see
    // `link_k_matches_dense_in_the_trivial_limit`) and the same-threshold
    // reference is no longer forced on us — but it is still the RIGHT reference
    // for this particular sweep, because the question here is what LinK's
    // pair-list restriction costs, not what the shared screen costs.
    for &thresh in THRESH_SWEEP.iter() {
        let k_ref = dense_k(&prep, &d, thresh);
        let op = Operator::coulomb();
        let bound = make_bound(kind, &mol, &bs, &prep, op);
        // `SignificantPairs::build` stores the FULL square (both (i,j) and
        // (j,i)); halve to compare against the unique-pair triangle. Diagonal
        // entries appear once, so the exact unique count is (total + ndiag)/2;
        // we take the conservative floor, which only ever makes the strict-less
        // assertion HARDER to pass.
        let sp = SignificantPairs::build(bound.as_dyn(), nsh, thresh);
        let retained = sp.total_pairs() / 2;

        let k_link = link_k(kind, &mol, &bs, &prep, &d, thresh);
        let err = max_abs_diff(&k_link, &k_ref);
        eprintln!("{thresh:>10.0e}  {err:>14.3e}  {retained:>7} / {full_triangle}");
        errs.push((thresh, err));
    }

    // --- LinK vs the dense build at the SAME threshold ---------------------
    // Bounds LinK's deviation across the whole sweep. See LINK_VS_DENSE_BAR
    // for why this is a flat constant rather than a multiple of `thresh`: the
    // measured error barely moves with the threshold because it is dominated
    // by the shared invalid-bound floor, so a threshold-proportional bar would
    // be unreachable at the tight end by construction.
    for &(thresh, err) in errs.iter() {
        assert!(
            err < LINK_VS_DENSE_BAR,
            "{stem}/{basis_name} [{}]: at thresh={thresh:.0e} LinK differs from the dense build \
             AT THE SAME THRESHOLD by max|dK| = {err:.6e}, above the {LINK_VS_DENSE_BAR:.0e} bar.",
            kind.label()
        );
    }

    // --- The sweep must still SHOW the error falling as the screen loosens --
    // Not a full monotonicity claim: the tail is flat (1.92e-3 -> 1.94e-3 ->
    // 1.94e-3) because it has hit the invalid-bound floor, and asserting
    // monotonicity there would be asserting something false about a defect
    // that lives elsewhere. What IS true, and what makes the sweep a
    // measurement rather than five unrelated numbers, is that loosening the
    // threshold measurably COSTS accuracy: the loosest point must be clearly
    // worse than the tightest.
    let (t_loose, e_loose) = errs[0];
    let (t_tight, e_tight) = *errs.last().expect("sweep is non-empty");
    assert!(
        e_loose > 2.0 * e_tight,
        "{stem}/{basis_name} [{}]: max|dK| is {e_loose:.6e} at the loosest threshold \
         ({t_loose:.0e}) and {e_tight:.6e} at the tightest ({t_tight:.0e}) — less than a factor \
         of 2 apart. The sweep spans no measurable range, so it is not observing the screening \
         tradeoff at all.",
        kind.label()
    );

    // --- (b) REACHABILITY: the screening path must actually be exercised ---
    // The assertions above are only meaningful if screening genuinely removed
    // work. If the pair list were complete at every threshold, LinK and the
    // dense build would walk the same quartets and agree trivially — which is
    // exactly the vacuous regime the pre-existing water/CH4 tests sat in.
    // Require the loosest threshold to have discarded a real fraction.
    let sp_loose = SignificantPairs::build(
        make_bound(kind, &mol, &bs, &prep, Operator::coulomb()).as_dyn(),
        nsh,
        THRESH_SWEEP[0],
    );
    let retained_loose = sp_loose.total_pairs() / 2;
    assert!(
        retained_loose < full_triangle,
        "{stem}/{basis_name} [{}]: at thresh={:.0e} SignificantPairs retained {retained_loose} of \
         {full_triangle} unique shell pairs — NOTHING was screened, so every assertion in this \
         sweep compares the unscreened loop against itself.",
        kind.label(),
        THRESH_SWEEP[0]
    );
}

/// (a) THRESH -> 0 anchor on an extended system, plus (b) the reachability check.
///
/// alkane_8 (C8H18, 26 atoms, 202 cc-pVDZ functions) is long enough that
/// Schwarz screening removes a real fraction of the shell-pair triangle at
/// loose thresholds — unlike the water/CH4 cases the old in-module tests use.
#[test]
fn link_k_thresh_sweep_alkane_8_schwarz() {
    run_thresh_sweep(BoundKind::Schwarz, "alkane_8", "cc-pvdz");
}

/// (a) The SAME sweep, same system, same assertions, driven by `QqrBounds`.
///
/// This is the arm the `BoundKind` parameterization was built for. QQR screens
/// strictly MORE than Schwarz (it multiplies the Schwarz estimate by a decay
/// factor <= 1), so it can only ever discard additional quartets — and this
/// sweep is what proves those discards stay below the threshold's own error
/// rather than removing anything that matters.
///
/// It shares `LINK_VS_DENSE_BAR` with the Schwarz arm deliberately: a QQR-
/// specific, looser bar would let a genuine QQR over-screening regression pass.
#[test]
fn link_k_thresh_sweep_alkane_8_qqr() {
    run_thresh_sweep(BoundKind::Qqr, "alkane_8", "cc-pvdz");
}

/// (a) The same sweep on alkane_12 (C12H26, 38 atoms, 298 cc-pVDZ functions).
///
/// `#[ignore]`d because it runs the dense O(N^4) `build_jk` reference five
/// times; that is minutes of work, too slow for the default gate. Invocation
/// is in this file's module doc comment.
#[test]
#[ignore = "expensive: 5x dense O(N^4) build_jk on 298 basis functions; see module doc for invocation"]
fn link_k_thresh_sweep_alkane_12() {
    run_thresh_sweep(BoundKind::Schwarz, "alkane_12", "cc-pvdz");
}

/// (b) REACHABLE-PASS-CONDITION check, standalone and explicit.
///
/// This is the assertion whose absence made the existing LinK tests vacuous.
/// At a loose threshold on the largest gated system, `SignificantPairs` MUST
/// retain strictly fewer than the full `nsh*(nsh+1)/2` unique shell pairs —
/// otherwise the screening path is not exercised at all and every "LinK
/// matches dense" assertion in the repo is measuring the unscreened loop
/// against itself.
///
/// It also pins the OTHER end: at `thresh = 0` the pair list must be complete.
/// That is the trivial-limit exactness anchor for the pair builder itself (a
/// screen that does nothing must retain everything), and it makes the strict
/// inequality above a measurement of screening rather than of an off-by-one.
#[test]
fn significant_pairs_actually_screens_alkane_8() {
    let mol = load_mol("alkane_8");
    let bs = basis::bundled("cc-pvdz").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let op = Operator::coulomb();
    let bound = make_bound(BoundKind::Schwarz, &mol, &bs, &prep, op);

    let full_square = nsh * nsh;
    let full_triangle = nsh * (nsh + 1) / 2;

    // Working regime: at 1e-6 screening must genuinely remove pairs.
    let sp = SignificantPairs::build(bound.as_dyn(), nsh, 1e-6);
    let retained = sp.total_pairs() / 2;
    let frac = retained as f64 / full_triangle as f64;
    eprintln!(
        "alkane_8/cc-pVDZ nsh={nsh}: retained {retained} of {full_triangle} unique shell pairs \
         at thresh=1e-6 ({:.1}% kept)",
        100.0 * frac
    );
    // A bare `retained < full_triangle` is too weak to be the reachability
    // guard: a builder that dropped a single pair would satisfy it while
    // screening essentially nothing. MEASURED under a deliberate
    // "retain every pair" mutation of SignificantPairs::build, retention went
    // to 5202 / 5253 (99.0%) — still strictly less than the triangle, because
    // halving the ordered-pair count floors below it. So require screening to
    // have removed a SUBSTANTIAL fraction. Real value here is 60.2% kept.
    assert!(
        frac < 0.9,
        "alkane_8/cc-pVDZ: SignificantPairs retained {retained} of {full_triangle} unique shell \
         pairs at thresh=1e-6 ({:.1}% kept) — essentially NOTHING was screened. Every \
         LinK-vs-dense assertion in this repo is then comparing the unscreened loop against \
         itself and proves nothing about screening.",
        100.0 * frac
    );

    // Trivial-limit exactness anchor for the pair builder itself: a screen
    // that does nothing must retain everything.
    //
    // A NEGATIVE threshold is the unconditionally vacuous screen, since every
    // stored bound is non-negative and `SignificantPairs::build` keeps a pair
    // when `estimate(..) > threshold`.
    let sp_all = SignificantPairs::build(bound.as_dyn(), nsh, -1.0);
    assert_eq!(
        sp_all.total_pairs(),
        full_square,
        "alkane_8/cc-pVDZ: at thresh=-1 (the vacuous screen — every non-negative bound passes a \
         negative threshold) SignificantPairs must retain ALL {full_square} ordered shell pairs, \
         got {}",
        sp_all.total_pairs()
    );

    // thresh = 0 must ALSO be vacuous, and that is the load-bearing half.
    //
    // `build` uses a STRICT `estimate(..) > threshold`, so any pair whose
    // stored Q is exactly 0.0 fails even against 0.0 and becomes unreachable at
    // every threshold — no setting of `thresh` would make the screen do
    // nothing. That was the state of the world before the Schwarz table gained
    // SCHWARZ_TABLE_PRECISION / SCHWARZ_Q_FLOOR: 8306 of 10404 ordered pairs
    // survived here, and this assertion was inverted, requiring the shortfall.
    //
    // It now requires the opposite, which is the real invariant: with a bound
    // that never stores a zero, threshold 0 retains everything. That makes this
    // a genuine second witness to the same property
    // `link_k_matches_dense_in_the_trivial_limit` checks through LinK's output,
    // one level lower down at the pair list itself.
    let sp_zero = SignificantPairs::build(bound.as_dyn(), nsh, 0.0);
    assert_eq!(
        sp_zero.total_pairs(),
        full_square,
        "alkane_8/cc-pVDZ: at thresh=0 only {} of {full_square} ordered shell pairs survive. \
         Because the comparison is a strict `>`, a stored Q of exactly 0.0 makes its pair \
         unreachable at EVERY threshold, so the screen has no off switch and the trivial limit \
         does not exist. Check SCHWARZ_TABLE_PRECISION and SCHWARZ_Q_FLOOR in \
         crates/ferric-integrals/src/schwarz.rs.",
        sp_zero.total_pairs()
    );
}

// ---------------------------------------------------------------------------
// (c) Cross-code DirectJK references
// ---------------------------------------------------------------------------

/// One PySCF direct-SCF reference record, as written by
/// `scripts/gen_pyscf_directjk_refs.py`. Matrices are stored row-major in
/// PYSCF AO order.
#[derive(serde::Deserialize)]
struct DirectJkRef {
    /// Layout tag for the packed matrices. Guards against silently misreading
    /// a reference written by an older generator that stored full squares.
    storage: String,
    nbf: usize,
    converged: bool,
    eri_cached: bool,
    direct_scf: bool,
    e_tot: f64,
    ao_permutation: Vec<usize>,
    // Absent for "energy_only" references (see the CASES note in
    // scripts/gen_pyscf_directjk_refs.py: alkane_8's dense matrices ran to
    // 1.4 MB, far outside this repo's 35 KB-largest reference convention).
    #[serde(default)]
    density: Vec<f64>,
    #[serde(default)]
    j: Vec<f64>,
    #[serde(default)]
    k: Vec<f64>,
    #[serde(default)]
    overlap: Vec<f64>,
}

impl DirectJkRef {
    fn load(tag: &str) -> Self {
        let path = format!("../../testdata/reference/{tag}_ccpvdz_directjk.json");
        let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "cannot read {path}: {e}\nRegenerate with: \
                 OPENBLAS_NUM_THREADS=1 python3 scripts/gen_pyscf_directjk_refs.py"
            )
        });
        let rec: DirectJkRef = serde_json::from_str(&text).expect("parse reference JSON");
        // The reference is only a reference if PySCF actually took the direct
        // path (repo memory: pyscf-caches-eri-benchmark-trap). The generator
        // refuses to write a record otherwise; re-assert here so a hand-edited
        // or stale file cannot slip past.
        assert!(rec.converged, "{tag}: PySCF reference is not converged");
        assert!(!rec.eri_cached, "{tag}: PySCF reference was built with a CACHED in-core ERI tensor — not a direct-path reference");
        assert!(rec.direct_scf, "{tag}: PySCF reference was not built with direct_scf=True");
        assert!(
            matches!(rec.storage.as_str(), "lower_triangle_rowmajor" | "energy_only"),
            "{tag}: reference uses unknown storage layout {:?}. Regenerate with \
             scripts/gen_pyscf_directjk_refs.py.",
            rec.storage
        );
        rec
    }

    /// Rebuild a full symmetric matrix from the reference's packed lower
    /// triangle (row-major, i >= j). The generator stores only the triangle
    /// because all four matrices are symmetric to <= 4.5e-16, and the full
    /// square pushed the alkane_8 file past the repo's 500 KB limit.
    /// Whether this reference carries the density/J/K/overlap matrices, or
    /// only energies.
    fn has_matrices(&self) -> bool {
        self.storage == "lower_triangle_rowmajor"
    }

    fn square(&self, tri: &[f64]) -> Array2<f64> {
        let n = self.nbf;
        assert_eq!(
            tri.len(),
            n * (n + 1) / 2,
            "packed lower triangle should hold n(n+1)/2 = {} elements for nbf = {n}, got {}",
            n * (n + 1) / 2,
            tri.len()
        );
        let mut m = Array2::zeros((n, n));
        let mut idx = 0usize;
        for i in 0..n {
            for j in 0..=i {
                m[(i, j)] = tri[idx];
                m[(j, i)] = tri[idx];
                idx += 1;
            }
        }
        m
    }
}

/// Permute a ferric-ordered matrix into PySCF AO order using `perm`, where
/// `perm[i]` is the PySCF index of ferric AO `i`.
fn permute_to_pyscf(m: &Array2<f64>, perm: &[usize]) -> Array2<f64> {
    let n = m.nrows();
    assert_eq!(perm.len(), n, "permutation length must equal nbf");
    let mut out = Array2::zeros((n, n));
    for i in 0..n {
        for j in 0..n {
            out[(perm[i], perm[j])] = m[(i, j)];
        }
    }
    out
}

/// Full cross-code check for one molecule: energy, then J and K at a SINGLE
/// shared density.
///
/// Comparing each code's J/K at its OWN converged density would compare SCF
/// solutions, not J/K builders; the deviation would be dominated by how the
/// two codes' densities differ at the convergence floor. So ferric contracts
/// PySCF's converged density (read from the reference file) and the two J/K
/// matrices are then directly comparable.
///
/// `unscreened` selects whether the (expensive) `thresh = 0.0` builder check
/// runs. Disabling screening entirely means walking EVERY shell quartet with
/// no early-out, which is affordable on alkane_4 (106 basis functions, ~30 s)
/// but not on alkane_8 (202 functions) — a measured run there exceeded 69
/// minutes without finishing and was abandoned, so alkane_8 gets the
/// screened-path check in the default gate and an `#[ignore]`d unscreened
/// variant for when someone wants the stricter number.
fn check_directjk_vs_pyscf(tag: &str, e_bar: f64, jk_bar: f64, unscreened: bool) {
    let rec = DirectJkRef::load(tag);
    let mol = load_mol(tag);
    let bs = basis::bundled("cc-pvdz").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nbf = prep.nbasis();
    assert_eq!(
        nbf, rec.nbf,
        "{tag}: ferric has {nbf} basis functions, PySCF reference has {} — different basis, \
         not comparable",
        rec.nbf
    );

    // --- AO-identity guard (load-bearing; this one has already fired) ------
    // Before trusting any J/K number, prove the two codes are using the SAME
    // AO functions in the SAME order, via a matrix neither code can get wrong:
    // the overlap.
    //
    // This is not a formality. The first version of the reference generator
    // built its Mole with PySCF's built-in "ccpvdz", and this assert failed at
    // 2.9e-1. Cause: PySCF stores carbon's s block as an 8-primitive/2-column
    // general contraction plus a separate 1-primitive shell, while ferric's
    // bundled cc-pvdz.json stores all 9 s primitives in one 3-column block and
    // splits each column into its own segmented shell. Same span (PySCF's own
    // energy moves only 3.2e-12 Ha between the two layouts), same AO ordering,
    // same sparsity pattern — but DIFFERENT AO functions, so J and K were not
    // elementwise comparable. The generator now builds the Mole from ferric's
    // own JSON and the overlaps agree to ~1e-15.
    //
    // Without this guard the J/K assertions below would have failed with a
    // large deviation and no indication of why — or worse, been "fixed" by
    // loosening the tolerance until they passed.
    if rec.has_matrices() {
    let s_ferric = permute_to_pyscf(
        &ferric_integrals::oneelectron::overlap(&prep),
        &rec.ao_permutation,
    );
    let s_ref = rec.square(&rec.overlap);
    let s_dev = max_abs_diff(&s_ferric, &s_ref);
    assert!(
        s_dev < 1e-10,
        "{tag}: AO overlap matrices disagree by {s_dev:.3e} after applying ao_permutation — the \
         two codes' AO orderings (or basis definitions) do not match, so the J/K comparison \
         below would be meaningless"
    );
    }

    // --- Energy: each code's own converged E_tot ---------------------------
    // Tightened past the stock defaults because this comparison IS about the
    // absolute energy (PySCF's side ran at conv_tol = 1e-12), so ferric must
    // be converged well inside the 1e-8 bar. `density_conv` is the gate that
    // matters (see the repo note on energy_conv being a sanity bound); 1e-8
    // is enough for a 1e-8 energy comparison and, unlike the 1e-9 this
    // originally used, it converges on alkane_8 in reasonable time.
    let op = Operator::coulomb();
    let bounds = SchwarzBounds::compute(op, &prep).expect("Schwarz bounds");
    let config = RhfConfig {
        density_conv: 1e-8,
        integral_thresh: PRODUCTION_INTEGRAL_THRESH,
        ..Default::default()
    };
    let res = solve_rhf(&ParallelContext::default(), &mol, &prep, op, &bounds, &config)
        .expect("RHF solve");
    assert!(res.converged, "{tag}: ferric RHF did not converge");
    let de = (res.energy - rec.e_tot).abs();
    eprintln!(
        "\n=== {tag}/cc-pVDZ DirectJK vs PySCF ===\n  E_ferric = {:.12} Ha\n  E_pyscf  = {:.12} Ha\n  |dE|     = {de:.3e} Ha",
        res.energy, rec.e_tot
    );
    assert!(
        de < e_bar,
        "{tag}: ferric E_tot {:.12} vs PySCF {:.12}, |dE| = {de:.3e} Ha exceeds {e_bar:.0e}",
        res.energy,
        rec.e_tot
    );

    // Matrix-level checks need the stored matrices; "energy_only" references
    // (alkane_8 — see the CASES note in the generator) stop here, having
    // already made their energy comparison above.
    if !rec.has_matrices() {
        eprintln!("  (energy-only reference: no stored J/K matrices to compare)");
        return;
    }

    // --- J/K at the SHARED density ----------------------------------------
    // PySCF's density comes in PySCF order; invert the permutation to express
    // it in ferric order before handing it to ferric's builder.
    let d_pyscf = rec.square(&rec.density);
    let mut d_ferric = Array2::<f64>::zeros((nbf, nbf));
    for i in 0..nbf {
        for j in 0..nbf {
            d_ferric[(i, j)] = d_pyscf[(rec.ao_permutation[i], rec.ao_permutation[j])];
        }
    }

    // PySCF's `get_jk` returns K as the raw exchange contraction and ferric's
    // build_jk uses the same convention (both contract a factor-2 RHF density,
    // with the 0.5 applied by the caller when forming F), so the matrices are
    // directly comparable. A convention divergence would show up as a clean
    // factor rather than as noise.
    let build_at = |thresh: f64| -> (f64, f64) {
        let mut j_f = Array2::zeros((nbf, nbf));
        let mut k_f = Array2::zeros((nbf, nbf));
        build_jk(
            &ParallelContext::default(),
            &prep,
            &bounds,
            thresh,
            &d_ferric,
            &mut j_f,
            &mut k_f,
        )
        .expect("ferric build_jk");
        (
            max_abs_diff(&permute_to_pyscf(&j_f, &rec.ao_permutation), &rec.square(&rec.j)),
            max_abs_diff(&permute_to_pyscf(&k_f, &rec.ao_permutation), &rec.square(&rec.k)),
        )
    };

    // --- UNSCREENED: the actual J/K BUILDER check -------------------------
    // thresh = 0.0 disables the Häser-Ahlrichs screen entirely (the test is
    // `bound_product < thresh`, and no non-negative product is < 0), so this
    // compares the contraction machinery itself against PySCF with nothing
    // approximated on either side. This is where a real builder defect would
    // show, and it is held to a tight bar.
    if unscreened {
        let (j_dev, k_dev) = build_at(0.0);
        eprintln!("  UNSCREENED (thresh=0):  max|dJ| = {j_dev:.3e}  max|dK| = {k_dev:.3e}");
        assert!(
            j_dev < jk_bar,
            "{tag}: UNSCREENED max|J_ferric - J_pyscf| = {j_dev:.3e} exceeds {jk_bar:.0e}. Both \
             codes contracted the SAME density with NO screening, so this is a J-BUILDER \
             deviation — not an SCF difference and not a screening-policy difference."
        );
        assert!(
            k_dev < jk_bar,
            "{tag}: UNSCREENED max|K_ferric - K_pyscf| = {k_dev:.3e} exceeds {jk_bar:.0e}. Both \
             codes contracted the SAME density with NO screening, so this is a K-BUILDER \
             deviation — not an SCF difference and not a screening-policy difference."
        );
    }

    // --- PRODUCTION SCREENING: documents the accuracy actually shipped ----
    // The screened and unscreened deviations are now essentially IDENTICAL on
    // alkane_4 — MEASURED 8.488e-11 (screened) vs 8.496e-11 (unscreened) for J,
    // and 9.711e-11 for K either way. That is the post-fix state and it is the
    // point: the Schwarz screen no longer contributes error of its own.
    //
    // It used to. The Schwarz TABLE was built from libint2 engines at a
    // hardcoded 1e-14, and for 22 of alkane_4's 2916 shell pairs the true
    // (ij|ij) is 1e-13..3e-17, so libint2 declined to compute them — correct,
    // documented behaviour on its part — and ferric recorded Q = 0.0, an
    // INVALID bound that UNDERestimates. `build_jk`'s `bound_product < thresh`
    // screen then discarded every quartet built from such a pair (32439 of
    // 1103355 on alkane_4) while PySCF computed them. See
    // `link_k_matches_dense_in_the_trivial_limit` for the invariant and the fix
    // (SCHWARZ_TABLE_PRECISION / SCHWARZ_Q_FLOOR in
    // crates/ferric-integrals/src/schwarz.rs).
    //
    // The ~8.5e-11 that REMAINS is a different and deliberate thing, and the
    // distinction matters for anyone reading this bar: it comes from the
    // precision of the engines that compute the J/K quartets themselves
    // (1e-14, hardcoded at every `EnginePool::new` call site), NOT from the
    // screening table. That is why fixing the table left it unchanged.
    //
    // MEASURED (alkane_4, PySCF's converged density, unscreened build, with the
    // QUARTET engine precision varied):
    //
    //     engine precision   max|dJ|     max|dK|
    //     1e-14 (production) 8.50e-11    9.70e-11
    //     1e-20              9.92e-13    1.10e-13
    //     1e-25              9.92e-13    1.10e-13
    //     1e-30              9.92e-13    1.10e-13
    //
    // i.e. tightening that engine drives ferric onto PySCF and then saturates —
    // the builders agree, and 1e-14 is a deliberate speed/accuracy choice.
    // This assertion therefore pins the SHIPPED behaviour at a bar the
    // production configuration can actually meet, so a genuine regression in
    // the screened path is still caught while the known precision policy is
    // not reported as a failure.
    let (j_dev_s, k_dev_s) = build_at(PRODUCTION_INTEGRAL_THRESH);
    eprintln!("  SCREENED (thresh=1e-14): max|dJ| = {j_dev_s:.3e}  max|dK| = {k_dev_s:.3e}");
    assert!(
        j_dev_s < SCREENED_JK_BAR && k_dev_s < SCREENED_JK_BAR,
        "{tag}: at the production integral threshold max|dJ| = {j_dev_s:.3e}, max|dK| = \
         {k_dev_s:.3e}, exceeding {SCREENED_JK_BAR:.0e}. The unscreened build above passed, so \
         the J/K contraction itself is fine and this is a SCREENING regression."
    );
}

/// (c) DirectJK vs the PySCF reference on alkane_4 — the GO/NO-GO gate for the
/// whole screening campaign. A failure of the ENERGY bar, or of the UNSCREENED
/// J/K bar, is a live accuracy defect in the direct J/K path rather than a
/// tolerance question.
///
/// Measured at the time of writing: |dE| = 5.145e-9 Ha; unscreened
/// max|dJ| = 8.50e-11, max|dK| = 9.70e-11.
#[test]
fn directjk_matches_pyscf_alkane_4() {
    check_directjk_vs_pyscf("alkane_4", 1e-8, 1e-9, true);
}

/// (c) The same cross-code check on the larger alkane_8, which is also the
/// system the threshold sweep above runs on.
///
/// Energy + screened-path J/K only. The unscreened builder check is the
/// `#[ignore]`d variant below: with screening off there is no early-out at
/// all, and a measured attempt on alkane_8 ran past 69 minutes without
/// finishing. alkane_4 carries the unscreened check in the default gate.
///
/// # This bar was 1e-3 for a KNOWN DEFECT; it is now 1e-8
///
/// ferric's screened alkane_8 RHF energy used to be -313.451984590 vs PySCF's
/// -313.451838457 — 1.46e-4 Ha LOWER, which looked like a better variational
/// solution but was not one. It is now -313.451838450, a deviation of
/// **6.963e-9 Ha**, so this test holds the same 1e-8 bar alkane_4 does.
///
/// Measured decomposition on ferric's OWN converged density (so no SCF-basin
/// question is involved), before and after the fix:
///
/// | quantity                                  | alkane_4   | alkane_8   |
/// |-------------------------------------------|------------|------------|
/// | screening-induced shift, BEFORE           | -5.07e-9   | -1.78e-4   |
/// | screening-induced shift, AFTER            |  0.0       |  0.0       |
/// | E vs PySCF (screened), BEFORE             |  ~3e-11    |  1.46e-4   |
/// | E vs PySCF (screened), AFTER              |  3.41e-11  |  6.96e-9   |
/// | unscreened E vs PySCF on the SAME density |  4.8e-11   |  7.0e-9    |
///
/// Read the bottom two rows together: with screening off, ferric always
/// reproduced PySCF's energy functional on the identical density to
/// 4.8e-11 / 7.0e-9 — the integrals, the J/K builders and the
/// 0.5·Tr[D(H+F)] + Vnn expression were never in question. The entire
/// discrepancy was the SCREEN, and the screened result has now converged onto
/// the unscreened one (6.96e-9 vs 7.0e-9), which is what a valid bound is
/// supposed to deliver.
///
/// Cause of the old gap: `SchwarzBounds::compute` built its Q table from
/// libint2 engines at the hardcoded 1e-14 precision — the same value later
/// enforced as the screening threshold. libint2 declines to compute pairs
/// below its stated precision (correct, documented behaviour), and ferric
/// recorded Q = 0.0 for them. A zero bound on a nonzero integral
/// UNDERestimates, breaking the always-overestimates invariant that makes a
/// Schwarz bound a bound (arXiv:2302.11307); every quartet on such a pair then
/// failed `bound_product < thresh` at ANY threshold, including 0. On alkane_4
/// that was 32439 of 1103355 quartets worth 5e-9 Ha — invisible. On alkane_8
/// the same mechanism was worth ~1.8e-4 Ha.
///
/// The growth with size was the expected shape: Schwarz-truncation energy
/// errors are extensive, scaling linearly with system size (Hollman, Schaefer
/// & Valeev, Mol. Phys. 115, 2065-2076 (2017)). That is also why the old 1e-3
/// bar could not simply have been widened for bigger systems, and why fixing
/// the bound rather than the bar was the only real option. The fix is in
/// `crates/ferric-integrals/src/schwarz.rs` (`SCHWARZ_TABLE_PRECISION` and
/// `SCHWARZ_Q_FLOOR`); see `link_k_matches_dense_in_the_trivial_limit`.
///
/// The old note about the shift's sign being negative on both systems is moot
/// now that the shift is zero, and was only ever reported as measured on two
/// systems rather than as a general property.
#[test]
fn directjk_matches_pyscf_alkane_8() {
    check_directjk_vs_pyscf("alkane_8", 1e-8, 1e-8, false);
}

/// (c) alkane_8 WITH the unscreened builder check.
///
/// `#[ignore]`d on cost, not on doubt: `thresh = 0.0` disables every early-out
/// so the build walks all ~10^7 shell quartets of a 202-function basis.
/// Measured: still running at 69 minutes when abandoned. Run it deliberately:
///
/// ```text
/// OPENBLAS_NUM_THREADS=1 FERRIC_MEM_BUDGET_GB=2 \
///   scripts/ferric-limited --max=4G --high=3600M -- \
///   cargo test -p ferric-scf --test screening_exactness --release \
///   -- --ignored --nocapture directjk_matches_pyscf_alkane_8_unscreened
/// ```
#[test]
#[ignore = "expensive: unscreened (thresh=0) J/K on 202 basis functions; >69 min measured"]
fn directjk_matches_pyscf_alkane_8_unscreened() {
    check_directjk_vs_pyscf("alkane_8", 1e-8, 1e-8, true);
}

/// TRIVIAL-LIMIT ANCHOR: at `thresh = 0` the LinK screen must do NOTHING, so
/// LinK's K must reproduce the dense build to machine precision.
///
/// This is the exactness anchor the repo protocol requires of every
/// approximation ("every approximation has a trivial limit where it does
/// nothing"), and for a long time ferric did not satisfy it. It replaces the
/// RED anchor `link_k_bound_validity_violated_alkane_8`, which pinned the
/// defect while it stood.
///
/// # The defect this test now guards against returning
///
/// A Schwarz bound must ALWAYS OVERESTIMATE the true integral — that property
/// is what makes it a bound at all, and what lets a screen discard a quartet
/// without changing the answer beyond the threshold (PySCF screening paper,
/// arXiv:2302.11307). ferric used to violate it: `SchwarzBounds::compute` built
/// its Q table from libint2 engines at a hardcoded 1e-14 precision, libint2
/// declines to compute pairs below the precision it is given, and ferric stored
/// `Q = 0.0` for them. A zero bound on a pair with a nonzero true `(ij|ij)` is
/// an UNDERestimate.
///
/// The consequence was not a slightly-too-aggressive screen; it was a screen
/// with no off switch. `SignificantPairs::build` keeps a pair only when
/// `estimate(..) > threshold`, a STRICT comparison, so a Q of exactly 0.0 fails
/// even against `threshold = 0.0`. Those pairs were unreachable at EVERY
/// threshold, and this trivial limit did not exist.
///
/// # What was measured, before and after
///
/// alkane_8/cc-pVDZ, ferric's converged density, dense reference at thresh = 0.
/// True `sqrt(max|(ij|ij)|)` per shell pair came from PySCF via
/// `mol.intor('int2e_sph', shls_slice=...)` on a Mole built from ferric's own
/// basis JSON so the 102-shell decomposition matches exactly:
///
/// ```text
///                                      before        after
/// max|K_LinK - K_dense| at thresh=0    1.9586e-3  -> 3.1086e-15
/// Q == 0.0 table entries               1049/5253  -> 0/5253
/// significant pairs at thresh=0        4153/5253  -> 5202/5253
/// smallest nonzero stored Q            4.632e-07  -> 1.302e-60
/// ```
///
/// Of the 1049 pairs ferric used to zero, 763 had a true Q below the 1e-7
/// screening scale — but the LARGEST was 6.51e-05, ~600x above it, so this was
/// never purely a sub-precision-tail issue. Only 121 of the 5253 pairs have a
/// genuinely zero `(ij|ij)`, so at least 928 stored entries were invalid
/// bounds. The pre-fix smallest nonzero Q of 4.632e-07 is `sqrt(~1e-13)`: the
/// fingerprint of the engine's precision cliff, not of anything about octane.
///
/// That the cause was the table precision and not merely a correlate was
/// established by moving ONLY that knob and watching both columns move
/// together: 1e-14 -> 1049 pairs / 1.96e-3; 1e-20 -> 529 / 5.44e-4;
/// 1e-26 -> 226 / 2.11e-4; 1e-32 -> 133 / 9.03e-5.
///
/// # The fix
///
/// `crates/ferric-integrals/src/schwarz.rs` now builds the screening table at
/// `SCHWARZ_TABLE_PRECISION = 0.0` (libint2 prescreening disabled for the table
/// build) and floors every stored entry at `SCHWARZ_Q_FLOOR = 1e-100`, so no
/// entry is ever exactly zero. This is what every production code does: build
/// the table TIGHTER than the threshold it enforces. PySCF builds `q_cond` at
/// `direct_scf_tol**2` with a 1e-100 floor; Molpro, NWChem, Q-Chem, ORCA and
/// Psi4 (via its own `eps * thresh`) do the equivalent. Using one hardcoded
/// 1e-14 for both roles was the outlier. Measured one-time table-build cost:
/// alkane_8 0.031 s -> 0.060 s, alkane_16 0.036 s -> 0.149 s.
///
/// # Why alkane_8
///
/// This is invisible on the molecules the pre-existing `link_k.rs` tests use:
/// water and CH4 have NO pairs under the cliff, so LinK was exact there and
/// those tests passed while proving nothing about this. The molecule has to be
/// large enough for distant shell pairs to fall below the engine's precision.
///
/// The 5202-of-5253 figure is this test's conservative `total_pairs() / 2`
/// halving of the ORDERED pair count, not a residual defect: all 10404 ordered
/// pairs are retained. It is asserted as a floor rather than an equality for
/// that reason.
#[test]
fn link_k_matches_dense_in_the_trivial_limit() {
    let mol = load_mol("alkane_8");
    let bs = basis::bundled("cc-pvdz").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let full_triangle = nsh * (nsh + 1) / 2;
    let d = converged_density(&mol, &bs, &prep);

    // The trivial limit: screening disabled on BOTH sides.
    let k_dense = dense_k(&prep, &d, 0.0);
    let k_link = link_k(BoundKind::Schwarz, &mol, &bs, &prep, &d, 0.0);
    let err = max_abs_diff(&k_link, &k_dense);

    let bound = make_bound(BoundKind::Schwarz, &mol, &bs, &prep, Operator::coulomb());
    let retained = SignificantPairs::build(bound.as_dyn(), nsh, 0.0).total_pairs() / 2;

    let schwarz = SchwarzBounds::compute(Operator::coulomb(), &prep).expect("Schwarz bounds");
    let zero_entries = (0..nsh)
        .flat_map(|i| (0..=i).map(move |j| (i, j)))
        .filter(|&(i, j)| schwarz.q[(i, j)] == 0.0)
        .count();

    eprintln!(
        "alkane_8/cc-pVDZ trivial limit (thresh=0): max|K_link - K_dense| = {err:.4e}, \
         significant pairs {retained} / {full_triangle}, Q == 0.0 table entries \
         {zero_entries} / {full_triangle}"
    );

    // The anchor itself. 1e-10 is far above the 3.1e-15 measured and far below
    // the 1.96e-3 the defect produced, so it discriminates cleanly rather than
    // being tuned to whatever the code currently emits.
    assert!(
        err < 1e-10,
        "alkane_8: LinK at thresh=0 differs from the dense K by {err:.4e}, but at threshold 0 the \
         screen must do NOTHING. Measured 3.1086e-15 when this anchor was written; the defect it \
         replaced gave 1.9586e-3. Check that the Schwarz table is still built at \
         SCHWARZ_TABLE_PRECISION with the SCHWARZ_Q_FLOOR applied \
         (crates/ferric-integrals/src/schwarz.rs)."
    );

    // The mechanism, asserted directly so a regression names its own cause
    // rather than only showing up as a number that drifted.
    assert_eq!(
        zero_entries, 0,
        "alkane_8: {zero_entries} Schwarz table entries are exactly 0.0. Each is a bound that \
         UNDERestimates a nonzero integral, and since SignificantPairs uses a strict \
         `estimate(..) > threshold` it makes that pair unreachable at every threshold including \
         0 — which is what breaks the trivial limit asserted above."
    );

    assert!(
        retained >= 5202,
        "alkane_8: only {retained} of {full_triangle} shell pairs survive at thresh=0, below the \
         5202 measured. At threshold 0 every pair with a nonzero bound must be reachable."
    );
}

/// TRIVIAL-LIMIT ANCHOR for QQR: at `thresh = 0`, LinK driven by `QqrBounds`
/// must reproduce the dense K exactly, just as the Schwarz arm does.
///
/// This is the non-negotiable exactness anchor for the QQR bound, and it is
/// strictly stronger than the Schwarz one. QQR multiplies the Schwarz estimate
/// by a decay factor, so it has TWO ways to break the trivial limit where
/// Schwarz has one:
///
/// * the inherited Schwarz floor (a stored `Q == 0` making a pair unreachable
///   at every threshold — the defect PR #34 fixed), and
/// * its own envelope driving a genuinely significant quartet's estimate to
///   zero, or below the strict `> threshold` comparison, at long range.
///
/// At `thresh = 0` neither may fire: a decay factor is a positive multiplier of
/// a positive Schwarz entry, so the product must stay strictly positive and the
/// quartet must survive. If this ever fails with the Schwarz arm still passing,
/// the cause is in the envelope (`SAFETY_FACTOR`, the `r_eff` edge-to-edge
/// definition, or an underflow in `ext_sum / r_eff`), NOT in the Schwarz table.
///
/// # SCOPE LIMIT — measured, not assumed
///
/// This anchor is NOT sensitive to an over-aggressive envelope, and saying so
/// is the point of this paragraph. MUTATION TESTED: an envelope mutated to
/// hard-zero its far tail (`decay < 1e-3 => 0.0`) — an outright invalid bound —
/// still PASSES this test. Two independent reasons, both structural:
///
/// * the pair lists screen on the diagonal `(ij|ij)`, where the envelope is
///   identically 1, so they are unaffected by any change to it; and
/// * LinK's inner test is `estimate * max_d < thresh`, which at `thresh = 0`
///   is `x < 0.0` — false for every non-negative `x`. Nothing is skipped no
///   matter how small the estimate gets.
///
/// So this test anchors the trivial limit (nothing is lost when screening is
/// off) and nothing more. Envelope VALIDITY is a separate question, covered by
/// `link_k_qqr_matches_schwarz_at_production_thresh` below, which runs at a
/// live threshold where the inner test actually fires.
#[test]
fn link_k_qqr_matches_dense_in_the_trivial_limit() {
    let mol = load_mol("alkane_8");
    let bs = basis::bundled("cc-pvdz").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let full_triangle = nsh * (nsh + 1) / 2;
    let d = converged_density(&mol, &bs, &prep);

    let k_dense = dense_k(&prep, &d, 0.0);
    let k_link = link_k(BoundKind::Qqr, &mol, &bs, &prep, &d, 0.0);
    let err = max_abs_diff(&k_link, &k_dense);

    let bound = make_bound(BoundKind::Qqr, &mol, &bs, &prep, Operator::coulomb());
    let retained = SignificantPairs::build(bound.as_dyn(), nsh, 0.0).total_pairs() / 2;

    eprintln!(
        "alkane_8/cc-pVDZ QQR trivial limit (thresh=0): max|K_link - K_dense| = {err:.4e}, \
         significant pairs {retained} / {full_triangle}"
    );

    assert!(
        err < 1e-10,
        "alkane_8 [QQR]: LinK at thresh=0 differs from the dense K by {err:.4e}. At threshold 0 \
         the screen must do NOTHING, and QQR's decay factor is a positive multiplier of a \
         positive Schwarz entry, so no quartet may drop out. Compare against \
         link_k_matches_dense_in_the_trivial_limit: if THAT still passes, the fault is in the \
         QQR envelope (crates/ferric-scf/src/qqr.rs), not the Schwarz table."
    );

    // QQR must not shrink the pair list relative to Schwarz — it CANNOT, since
    // both pair-list builders screen on the diagonal quartet (ij|ij) where the
    // envelope is identically 1 (pinned by tests/qqr_diagonal_noop.rs). Asserted
    // here so the equality is checked end-to-end through the real builder too.
    assert!(
        retained >= 5202,
        "alkane_8 [QQR]: only {retained} of {full_triangle} shell pairs survive at thresh=0, \
         below the 5202 the Schwarz arm retains. QQR is identical to Schwarz on the diagonal \
         quartets the pair list screens on, so these counts must match exactly."
    );
}

/// ENVELOPE VALIDITY: at a LIVE threshold, swapping Schwarz for QQR must not
/// change K by more than the threshold's own truncation error.
///
/// This is the test with teeth. Unlike the trivial-limit anchor above, it runs
/// where LinK's inner `estimate * max_d < thresh` test actually fires, so the
/// QQR envelope is genuinely load-bearing: every quartet QQR discards and
/// Schwarz keeps shows up as a difference in K.
///
/// QQR is a strictly tighter bound (Schwarz times a factor <= 1), so it can
/// only ever discard MORE. Those discards are legitimate only if the envelope
/// is a valid bound — an over-aggressive one throws away quartets that carry
/// real weight, and this is where that shows up.
///
/// # Mutation testing — including one mutant this does NOT catch
///
/// Measured baseline: max|dK| = 3.0345e-9. That is the real cost of the extra
/// 0.009% of quartets QQR screens on this system — small, but NOT zero.
///
/// ```text
///   mutant                                    trivial limit   this test
///   far tail zeroed (decay < 1e-3 => 0.0)     pass            PASS  3.0345e-9 (unchanged)
///   envelope 100x too aggressive              pass            FAIL  5.3525e-7
/// ```
///
/// The second mutant is caught with a 176x margin. The FIRST IS NOT, and that
/// is recorded rather than hidden: on alkane_8 the `decay < 1e-3` regime is
/// never reached by a quartet carrying measurable weight, so zeroing it changes
/// the answer by nothing at all. This test therefore catches envelopes that are
/// too aggressive in the ENGAGED intermediate zone, and is blind to the deep
/// tail on this system. A system long enough to populate that tail would be
/// needed to close the gap; alkane_8 does not.
///
/// The bar is 1e-7 — above the 3.0345e-9 baseline by ~33x (so ordinary
/// floating-point and threshold-boundary jitter cannot trip it) and below the
/// 5.3525e-7 mutant, so it discriminates rather than being fitted to whatever
/// the code currently emits.
#[test]
fn link_k_qqr_matches_schwarz_at_production_thresh() {
    let mol = load_mol("alkane_8");
    let bs = basis::bundled("cc-pvdz").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let d = converged_density(&mol, &bs, &prep);

    // A LIVE threshold: loose enough that the inner screen fires on a
    // substantial quartet population, which is what makes the envelope
    // load-bearing here and inert in the thresh=0 anchor.
    let thresh = 1e-8;
    let k_schwarz = link_k(BoundKind::Schwarz, &mol, &bs, &prep, &d, thresh);
    let k_qqr = link_k(BoundKind::Qqr, &mol, &bs, &prep, &d, thresh);
    let err = max_abs_diff(&k_schwarz, &k_qqr);

    eprintln!(
        "alkane_8/cc-pVDZ QQR vs Schwarz at thresh={thresh:.0e}: max|K_QQR - K_Schwarz| = {err:.4e}"
    );

    assert!(
        err < 1e-7,
        "alkane_8: LinK+QQR differs from LinK+Schwarz by max|dK| = {err:.4e} at thresh={thresh:.0e}. \
         QQR screens strictly more than Schwarz, so any difference is truncation — and it must stay \
         far below the threshold's own error. A failure here means the QQR envelope \
         (crates/ferric-scf/src/qqr.rs) is discarding quartets that carry real weight, i.e. it is \
         not a valid bound. Measured 3.0345e-9 when written; a 100x-too-aggressive envelope gave \
         5.3525e-7."
    );
}

/// INVARIANT: screening at the production `integral_thresh` must not move the
/// energy — and on these systems it now does not move it AT ALL.
///
/// This replaces the RED anchor `known_defect_screening_shifts_coulomb_energy_with_size`,
/// which pinned a size-divergent screening error while the invalid-Schwarz-bound
/// defect stood. That error is gone.
///
/// What is measured, on ONE fixed density per molecule, contracted twice —
/// once with the production screen and once with screening disabled:
///
/// ```text
///                                       before fix   after fix
/// alkane_4:  |E(1e-14) - E(0)|          5.0e-9       0.000e0  (bit-identical)
/// alkane_8:  |E(1e-14) - E(0)|          1.8e-4       0.000e0  (bit-identical)
/// ```
///
/// (alkane_4 contracts PySCF's density, alkane_8 ferric's own — see the code.
/// The choice is immaterial: each shift is a ferric-vs-ferric difference at two
/// thresholds on ONE fixed density, so the density's provenance cancels.)
///
/// Using one fixed density for both builds removes the SCF entirely from the
/// comparison: any difference is the screen and nothing else.
///
/// # Why the shift is now exactly zero, and what that does and does not mean
///
/// It does NOT mean Schwarz screening is exact in general. Schwarz-truncation
/// energy errors are EXTENSIVE — they scale linearly with system size (Hollman,
/// Schaefer & Valeev, Mol. Phys. 115, 2065-2076 (2017),
/// DOI 10.1080/00268976.2017.1346312: "the absolute energy errors ... scale
/// linearly with the size of the system") — so a large enough molecule at a
/// loose enough threshold will show a nonzero shift, correctly.
///
/// What it means here is narrower and is the actual point: at 1e-14 on systems
/// of this size, everything the screen discards is genuinely below double
/// precision, so the two builds agree bit-for-bit. Before the fix the screen
/// was additionally discarding quartets it had no license to discard — pairs
/// whose bound had been recorded as an invalid 0.0 — and THAT is what produced
/// the 1.8e-4. The prior sign observation (both shifts negative, making ferric's
/// alkane_8 total sit 1.46e-4 Ha under PySCF's and superficially resemble a
/// better variational solution) is moot now that the magnitude is zero, and was
/// only ever reported as measured on two systems, never as a general expectation.
///
/// The assertion is therefore an equality-to-zero on the SHIFT, not a tolerance:
/// a tolerance would quietly absorb a returning defect, whereas any nonzero
/// shift at this threshold and size is now a real signal worth looking at.
/// Should a future change make a genuinely-negligible nonzero shift appear here
/// (a different basis, a looser production threshold), the right response is to
/// re-derive what the screen is allowed to drop — not to widen the bar.
///
/// Mechanism, for the defect this guards against returning (see
/// `link_k_matches_dense_in_the_trivial_limit`): Q entries stored as exactly
/// 0.0 are invalid bounds — they UNDERestimate — and caused every quartet on
/// that shell pair to be screened at any threshold, including 0.
#[test]
fn screening_does_not_shift_the_energy_at_production_thresh() {
    let mut shifts = Vec::new();
    for tag in ["alkane_4", "alkane_8"] {
        let rec = DirectJkRef::load(tag);
        let mol = load_mol(tag);
        let bs = basis::bundled("cc-pvdz").expect("basis");
        let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
        let nbf = prep.nbasis();
        let op = Operator::coulomb();
        let bounds = SchwarzBounds::compute(op, &prep).expect("Schwarz bounds");

        // Use PySCF's density when the reference carries it (so the two
        // molecules' numbers are directly comparable to the cross-code test
        // above), and ferric's own converged density otherwise. Either works:
        // the comparison here is ferric-vs-ferric at two thresholds on ONE
        // fixed density, so the density's provenance is irrelevant as long as
        // it is the same on both sides of the subtraction.
        let d = if rec.has_matrices() {
            let d_pyscf = rec.square(&rec.density);
            let mut d = Array2::<f64>::zeros((nbf, nbf));
            for i in 0..nbf {
                for j in 0..nbf {
                    d[(i, j)] = d_pyscf[(rec.ao_permutation[i], rec.ao_permutation[j])];
                }
            }
            d
        } else {
            converged_density(&mol, &bs, &prep)
        };

        let h = ferric_integrals::oneelectron::hcore(&prep);
        let vnn = mol.nuclear_repulsion();
        let energy_at = |thresh: f64| -> f64 {
            let mut j = Array2::zeros((nbf, nbf));
            let mut k = Array2::zeros((nbf, nbf));
            build_jk(
                &ParallelContext::default(),
                &prep,
                &bounds,
                thresh,
                &d,
                &mut j,
                &mut k,
            )
            .expect("build_jk");
            let f = &h + &j - &(0.5 * &k);
            0.5 * (&d * &(&h + &f)).sum() + vnn
        };

        let e_screened = energy_at(PRODUCTION_INTEGRAL_THRESH);
        let e_exact = energy_at(0.0);
        let shift = (e_screened - e_exact).abs();
        eprintln!(
            "{tag}: E(thresh=1e-14) = {e_screened:.12}, E(thresh=0) = {e_exact:.12}, \
             |shift| = {shift:.3e} Ha"
        );
        shifts.push((tag, shift));
    }

    let (_, s4) = shifts[0];
    let (_, s8) = shifts[1];

    // Equality to zero, not a tolerance — see the note above on why widening
    // this bar would be the wrong response to it firing. Both systems measured
    // bit-identical (0.000e0) after the invalid-bound fix; before it they gave
    // 5.0e-9 and 1.8e-4.
    assert_eq!(
        s4, 0.0,
        "alkane_4: screening at the production threshold moved the energy by {s4:.3e} Ha; it was \
         bit-identical (0.0) when this invariant was written. At 1e-14 on a system this size the \
         screen should discard nothing that is above double precision."
    );
    assert_eq!(
        s8, 0.0,
        "alkane_8: screening at the production threshold moved the energy by {s8:.3e} Ha; it was \
         bit-identical (0.0) when this invariant was written. The predecessor defect \
         (invalid Q == 0.0 bounds, see link_k_matches_dense_in_the_trivial_limit) produced \
         1.8e-4 Ha here and grew with system size — check SCHWARZ_TABLE_PRECISION and \
         SCHWARZ_Q_FLOOR in crates/ferric-integrals/src/schwarz.rs before widening this bar."
    );
}

/// The QQR arm of [`BoundKind`] must stay constructible and usable, so the
/// follow-up PR that turns on QQR screening extends the case lists above
/// rather than discovering that the generic plumbing rotted.
///
/// Deliberately tiny (water/STO-3G): this checks WIRING, not physics — the
/// physics assertions for QQR are the sweep above, once it is enabled.
#[test]
fn qqr_bound_arm_is_wired() {
    let mol = Molecule::parse_xyz(
        "3\nwater\nO 0.000000 0.000000 0.117790\nH 0.000000 0.755453 -0.471161\nH 0.000000 -0.755453 -0.471161\n",
        0,
        1,
    )
    .unwrap();
    let bs = basis::bundled("sto-3g").expect("basis");
    let prep = PreparedBasis::new(&mol, &bs).expect("PreparedBasis");
    let nsh = prep.nshells();
    let op = Operator::coulomb();

    for kind in [BoundKind::Schwarz, BoundKind::Qqr] {
        let bound = make_bound(kind, &mol, &bs, &prep, op);
        // Negative threshold = the vacuous screen; see the longer note in
        // `significant_pairs_actually_screens_alkane_8` for why 0.0 is not it.
        let sp = SignificantPairs::build(bound.as_dyn(), nsh, -1.0);
        assert_eq!(
            sp.total_pairs(),
            nsh * nsh,
            "{}: a negative threshold must retain every ordered shell pair",
            kind.label()
        );
    }
}
