//! VALIDATION tier — VALIDATION.md rows "QM/MM", "Smeared charges" and
//! "KS QM/MM". The row "External potential in MP2 gradients" is in
//! `crates/ferric-mp2/tests/validation_qmmm_mp2_gradient.rs`.
//!
//! Runs only in the weekly `validation` CI job (and on demand):
//!
//! ```text
//! cargo nextest run -p ferric-scf --test validation_qmmm \
//!     --run-ignored only -E 'binary(/^validation_/)'
//! ```
//!
//! # What is compared
//!
//! ferric's electrostatic embedding (`ferric_scf::qmmm::QmmmSystem` →
//! `ExternalPotential` folded into hcore, `rhf_gradient`/`ks_gradient_closed`
//! for the QM nuclei, `mm_forces` for the MM sites) against PySCF 2.13
//! `pyscf.qmmm.mm_charge`, an independent implementation of the same model.
//! References: `testdata/reference/validation/qmmm/*.json`, generated by
//! `scripts/validation/gen_qmmm.py` from ferric's own bundled basis JSON and
//! ferric's geometry in Bohr (`scripts/validation/common.py`).
//!
//! | test | QM / basis | MM | method |
//! |---|---|---|---|
//! | `point_*` | H2O / cc-pVDZ, aug-cc-pVDZ | 10 charges: two H-bonded TIP3P waters, ±1 ions, ±0.3 | RHF |
//! | `point_ch3oh_tip3p501` | CH3OH / 6-31G | 501 TIP3P charges, seeded random shell (`testdata/molecules/validation/ch3oh_tip3p_shell.json`) | RHF |
//! | `smeared_*` | H2O / cc-pVDZ | the 10 sites, Gaussian width 0.5 / 1.0 / 2.0 Bohr | RHF |
//! | `ks_*` | CH3OH / def2-SVP | the 20 shell sites nearest the QM atoms | RKS B3LYP, PBE |
//!
//! Each case asserts the embedded total energy, the gas-phase energy, the
//! embedding SHIFT (their difference), the QM nuclear gradient and the force
//! on every MM site. No charge set has a symmetry, so every gradient
//! component is live.
//!
//! Like-for-like settings: exact four-centre J/K on both sides for HF AND for
//! KS (ferric `df_j_aux = df_k_aux = Some("")`; RI-J is ferric's KS default,
//! so leaving them unset would compare against the RI fitting error). KS grid:
//! (75,110) unpruned, Becke partition with Becke-1988 radii on both sides.
//! ferric's KS gradient includes the grid response, so it is compared against
//! PySCF `grid_response = True`; PySCF's `grid_response = False` gradient is
//! also recorded in the JSON and differs from it by up to 1.8e-3 Ha/Bohr on
//! these systems (the grid-weight derivative at (75,110)).
//!
//! # Smeared-charge unit convention (read from both sources)
//!
//! ferric `QmmmAtom::width` / `SmearedCharge::width` is in Bohr with
//! ζ = 1/width². PySCF `mm_charge(radii=)` reads the radius in the SAME unit
//! as the coordinates (`unit=`; the default is Angstrom), converts it to Bohr,
//! and sets ζ = 1/radius². So ferric width [Bohr] == PySCF radius with
//! `unit="Bohr"`. The generator checks this on the PySCF side: coordinates
//! and radii handed over in Angstrom reproduce the Bohr run to ≤ 3e-14 Ha,
//! and a Bohr number misread as Angstrom moves the energy by 5.9e-4 to
//! 8.6e-3 Ha (`unit_convention_check` in each JSON).
//!
//! # Physics hypothesis vs artifact hypothesis
//!
//! * If ferric's embedding is right: energies agree at the integral/SCF
//!   floor (~1e-11 Ha for HF, second order in the density error), gradients
//!   and MM forces at the first-order floor (~1e-9 Ha/Bohr).
//! * If the field is dropped or never reaches the SCF (the vacuum-test
//!   failure mode): ferric returns the gas-phase answer. The reference shifts
//!   are 8.4e-4 to 1.6e-2 Ha, so every energy assertion fails by ≥ 7 orders
//!   above the bar. Each test asserts this FIRST (the vacuum block of
//!   `check_case`).
//! * If a charge is mis-scaled (a unit or sign slip in the charge, a missing
//!   factor in the charge-nuclear term): the ×1.01 control moves the energy by
//!   7.6e-7 (KS/PBE) to 2.4e-4 Ha, so ferric must match PySCF's ×1.01 energy AND miss
//!   the ×1 reference.
//! * If the smearing convention were off (ζ = 1/(2w²), width read as Å, width
//!   ignored): the width-swap and point-limit controls differ from the
//!   reference by ≥ 1.0e-4 Ha (measured by the generator, refused below
//!   1e-5), so a wrong convention fails every smeared test.
//! * If the harness is broken (geometry constant, wrong basis file, wrong
//!   reference file): the nuclear-repulsion and AO-count assertions fail
//!   first, before any SCF.
//!
//! # TOLERANCES
//!
//! Each bar is set from the measured maximum recorded on its const.
//!
//! # NEGATIVE CONTROLS (asserted inside every test)
//!
//! * vacuum: ferric's gas-phase energy and gradient must MISS the embedded
//!   reference by `MISS_FACTOR` × the bar;
//! * charges × 1.01: ferric must reproduce PySCF's ×1.01 energy and MISS the
//!   ×1 reference;
//! * smeared: ferric with each OTHER width, and ferric with point charges,
//!   must MISS the reference;
//! * KS: ferric with the OTHER functional must MISS the reference.
//! MUTATIONS to run by hand (each must turn a test red): drop
//! `external_potential` from `cfg` in [`scf`]; flip the sign of `mm_forces`;
//! pass `width * ANGSTROM_TO_BOHR` in [`build_system`].
//!
//! A missing reference JSON is a HARD failure (panic naming the path).

use std::path::{Path, PathBuf};

use ferric_core::basis::{self, BasisSet};
use ferric_core::elements;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::gradient::rhf_gradient;
use ferric_scf::ks_gradient::ks_gradient_closed;
use ferric_scf::qmmm::{mm_forces, QmSelection, QmmmAtom, QmmmSystem};
use ferric_scf::rhf::{solve_rhf, RhfConfig};
use ferric_scf::screening::SchwarzBounds;
use ferric_scf::ScfResult;
use ndarray::Array2;
use serde_json::Value;

const ROW_DIR: &str = "testdata/reference/validation/qmmm";

/// HF total, gas-phase and embedding shift. Measured max 4.8e-12 Ha.
const TOL_E_HF: f64 = 5e-11;
/// HF QM gradient and MM force. Measured max 1.2e-10 / 4.4e-12 Ha/Bohr.
const TOL_G_HF: f64 = 1e-9;
const TOL_F_HF: f64 = 5e-11;
/// KS energies (exact J/K, matched grid). Measured max 4.1e-12 Ha. Must stay
/// below 1/10 of the PBE x1.01-charges gap (7.6e-7) for that control.
const TOL_E_KS: f64 = 1e-10;
/// KS QM gradient vs PySCF `grid_response=True`, and MM force. Measured max
/// 2.9e-9 / 1.8e-10 Ha/Bohr.
const TOL_G_KS: f64 = 3e-8;
const TOL_F_KS: f64 = 2e-9;
/// Smeared-width -> 0 anchor (ferric vs ferric). Measured 3.0e-12.
const TOL_ANCHOR_TINY_WIDTH: f64 = 1e-10;
const TOL_ENUC: f64 = 1e-9;
/// A control must miss the reference by this multiple of the bar it is
/// asserted against. The smallest control gap in the references is the PBE
/// ×1.01 case, 7.6e-7 Ha = 76 × `TOL_E_KS` (the 20 charges' first-order
/// electrostatic and second-order polarization terms nearly cancel in
/// dE/dq); every other gap is ≥ 2.3e-6 Ha. If `TOL_E_KS` is raised above
/// 7.6e-8 that control becomes unreachable and this test will say so.
const MISS_FACTOR: f64 = 10.0;

// ---------------------------------------------------------------------------
// Reference loading
// ---------------------------------------------------------------------------

fn workspace_root() -> PathBuf {
    let looks_like_root = |p: &Path| {
        p.join("Cargo.toml").is_file() && p.join("testdata").is_dir() && p.join("crates").is_dir()
    };
    if let Ok(cwd) = std::env::current_dir() {
        let mut here: Option<&Path> = Some(cwd.as_path());
        while let Some(p) = here {
            if looks_like_root(p) {
                return p.to_path_buf();
            }
            here = p.parent();
        }
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("ferric-scf manifest dir should be <root>/crates/ferric-scf")
        .to_path_buf()
}

fn reference(file_stem: &str) -> Value {
    let path = workspace_root()
        .join(ROW_DIR)
        .join(format!("{file_stem}.json"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing validation reference {} ({e}); regenerate with \
             scripts/validation/gen_qmmm.py — a missing reference is a failure, never a skip",
            path.display()
        )
    });
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: bad JSON: {e}", path.display()))
}

fn num(v: &Value, ptr: &str) -> f64 {
    v.pointer(ptr)
        .and_then(Value::as_f64)
        .unwrap_or_else(|| panic!("reference field {ptr} missing or not a number"))
}

fn xyz3(v: &Value) -> [f64; 3] {
    let a = v.as_array().expect("xyz array");
    [
        a[0].as_f64().unwrap(),
        a[1].as_f64().unwrap(),
        a[2].as_f64().unwrap(),
    ]
}

fn rows3(v: &Value, key: &str) -> Vec<[f64; 3]> {
    v[key]
        .as_array()
        .unwrap_or_else(|| panic!("reference field {key} missing"))
        .iter()
        .map(xyz3)
        .collect()
}

// ---------------------------------------------------------------------------
// ferric side
// ---------------------------------------------------------------------------

/// The full QM/MM structure as a user builds it: QM atoms first (with a
/// dummy MM charge that must be dropped because they are QM), then one
/// `QmmmAtom` per MM site. `q_scale` multiplies every MM charge; `width`
/// `Some(w)` makes every site a Gaussian of width `w` Bohr.
fn build_system(r: &Value, q_scale: f64, width: Option<f64>) -> QmmmSystem {
    let mut atoms: Vec<QmmmAtom> = r["atoms"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| {
            let sym = a["symbol"].as_str().unwrap();
            let z = elements::symbol_to_z(sym).unwrap();
            let [x, y, zz] = xyz3(&a["xyz_bohr"]);
            QmmmAtom::new(sym, z, x, y, zz, 99.0)
        })
        .collect();
    let nqm = atoms.len();
    for c in r["mm_charges"].as_array().unwrap() {
        let q = c["q"].as_f64().unwrap() * q_scale;
        let [x, y, z] = xyz3(&c["xyz_bohr"]);
        atoms.push(match width {
            None => QmmmAtom::new("X", 0, x, y, z, q),
            Some(w) => QmmmAtom::new_smeared("X", 0, x, y, z, q, w),
        });
    }
    let charge = r["charge"].as_i64().unwrap() as i32;
    let mult = r["multiplicity"].as_u64().unwrap() as usize;
    QmmmSystem::new(
        &atoms,
        QmSelection::Indices((0..nqm).collect()),
        charge,
        mult,
    )
    .unwrap()
}

struct Qm {
    mol: Molecule,
    bs: BasisSet,
    prep: PreparedBasis,
    bounds: SchwarzBounds,
}

/// QM molecule + basis, with the geometry and AO count asserted against the
/// reference before any SCF runs.
fn qm_part(r: &Value, sys: &QmmmSystem, ctx: &str) -> Qm {
    let mol = sys.to_qm_molecule();
    assert_eq!(
        mol.atoms.len(),
        r["atoms"].as_array().unwrap().len(),
        "{ctx}: QM atom count"
    );
    let enuc = mol.nuclear_repulsion();
    let enuc_ref = num(r, "/nuclear_repulsion");
    assert!(
        (enuc - enuc_ref).abs() < TOL_ENUC,
        "{ctx}: nuclear repulsion {enuc:.12} vs reference {enuc_ref:.12} — geometry/unit mismatch"
    );
    let basis_name = r["basis"].as_str().unwrap();
    let bs = basis::bundled(basis_name).unwrap();
    let prep = PreparedBasis::new(&mol, &bs).unwrap();
    let nao = ferric_integrals::oneelectron::overlap(&prep).nrows();
    assert_eq!(nao as u64, r["nao"].as_u64().unwrap(), "{ctx}: AO count");
    let bounds = SchwarzBounds::compute(Operator::coulomb(), &prep).unwrap();
    Qm {
        mol,
        bs,
        prep,
        bounds,
    }
}

/// ferric's spelling of the functional.
fn ferric_xc(xc: &str) -> &'static str {
    match xc {
        "b3lyp" => "B3LYP",
        "pbe" => "PBE",
        other => panic!("unknown functional {other}"),
    }
}

fn config(
    xc: Option<&str>,
    ext: Option<ferric_core::external_potential::ExternalPotential>,
) -> RhfConfig {
    match xc {
        None => RhfConfig {
            external_potential: ext,
            energy_conv: 1e-11,
            density_conv: 1e-10,
            max_iter: 300,
            ..Default::default()
        },
        Some(xc) => RhfConfig {
            xc: Some(ferric_xc(xc).into()),
            // Exact four-centre J and K, matching PySCF RKS without density_fit.
            df_j_aux: Some(String::new()),
            df_k_aux: Some(String::new()),
            external_potential: ext,
            energy_conv: 1e-10,
            density_conv: 1e-8,
            max_iter: 300,
            ..Default::default()
        },
    }
}

fn scf(qm: &Qm, sys: Option<&QmmmSystem>, xc: Option<&str>, ctx: &str) -> ScfResult {
    let ext = sys.map(|s| {
        s.to_external_potential()
            .unwrap_or_else(|| panic!("{ctx}: MM region produced no potential"))
    });
    let cfg = config(xc, ext);
    let res = solve_rhf(
        &ParallelContext::default(),
        &qm.mol,
        &qm.prep,
        Operator::coulomb(),
        &qm.bounds,
        &cfg,
    )
    .unwrap_or_else(|e| panic!("{ctx}: solve_rhf failed: {e:?}"));
    assert!(res.converged, "{ctx}: SCF not converged");
    res
}

fn gradient(qm: &Qm, res: &ScfResult, sys: Option<&QmmmSystem>, xc: Option<&str>) -> Array2<f64> {
    let ext = sys.and_then(|s| s.to_external_potential());
    match xc {
        None => rhf_gradient(
            &qm.mol,
            &qm.prep,
            Operator::coulomb(),
            &qm.bounds,
            res,
            ext.as_ref(),
        )
        .unwrap(),
        Some(xc) => ks_gradient_closed(
            &qm.mol,
            &qm.prep,
            &qm.bs,
            Operator::coulomb(),
            &qm.bounds,
            ferric_xc(xc),
            res,
            ext.as_ref(),
        )
        .unwrap(),
    }
}

// ---------------------------------------------------------------------------
// Assertions
// ---------------------------------------------------------------------------

fn check_close(ctx: &str, what: &str, got: f64, want: f64, tol: f64) {
    let d = (got - want).abs();
    eprintln!("{ctx}: {what:<22} ferric {got:+.12} ref {want:+.12} |d| {d:.2e} (tol {tol:.0e})");
    assert!(
        d < tol,
        "{ctx}: {what} {got:.12} vs reference {want:.12} (|d| {d:.2e} >= {tol:.0e})"
    );
}

fn check_misses(ctx: &str, what: &str, got: f64, want: f64, tol: f64) {
    let d = (got - want).abs();
    let bar = MISS_FACTOR * tol;
    eprintln!("{ctx}: CONTROL {what:<30} |d| {d:.2e} (must exceed {bar:.0e})");
    assert!(
        d > bar,
        "{ctx}: negative control '{what}' did NOT miss the reference (|d| {d:.2e} <= {bar:.0e}) \
         — the assertion cannot tell this arrangement from the real one"
    );
}

fn max_row_diff(a: &[[f64; 3]], b: &[[f64; 3]], sign_b: f64) -> (f64, usize, usize) {
    assert_eq!(a.len(), b.len());
    let mut worst = (0.0, 0, 0);
    for (i, (x, y)) in a.iter().zip(b.iter()).enumerate() {
        for k in 0..3 {
            let d = (x[k] - sign_b * y[k]).abs();
            if d > worst.0 {
                worst = (d, i, k);
            }
        }
    }
    worst
}

fn grad_rows(g: &Array2<f64>) -> Vec<[f64; 3]> {
    g.rows().into_iter().map(|r| [r[0], r[1], r[2]]).collect()
}

fn check_rows(ctx: &str, what: &str, got: &[[f64; 3]], want: &[[f64; 3]], sign: f64, tol: f64) {
    let (d, i, k) = max_row_diff(got, want, sign);
    eprintln!(
        "{ctx}: {what:<22} max|d| {d:.2e} at [{i}][{k}] over {} rows (tol {tol:.0e})",
        got.len()
    );
    assert!(
        d < tol,
        "{ctx}: {what}[{i}][{k}] ferric {} vs reference {} (|d| {d:.2e} >= {tol:.0e})",
        got[i][k],
        sign * want[i][k]
    );
}

struct Tols {
    e: f64,
    g: f64,
    f: f64,
}

const HF: Tols = Tols {
    e: TOL_E_HF,
    g: TOL_G_HF,
    f: TOL_F_HF,
};
const KS: Tols = Tols {
    e: TOL_E_KS,
    g: TOL_G_KS,
    f: TOL_F_KS,
};

/// One case: negative controls FIRST (vacuum, ×1.01), then the comparison.
/// Returns ferric's embedded energy.
fn check_case(file_stem: &str, width: Option<f64>, xc: Option<&str>, tol: &Tols) -> f64 {
    let r = reference(file_stem);
    let ctx = file_stem.to_string();
    let sys = build_system(&r, 1.0, width);
    let qm = qm_part(&r, &sys, &ctx);
    let n_mm = r["mm_charges"].as_array().unwrap().len();
    assert_eq!(
        sys.mm_charge_positions().len(),
        n_mm,
        "{ctx}: MM site count"
    );

    let e_ref = num(&r, "/energy");
    let e_gas_ref = num(&r, "/energy_gas_phase");
    // ferric's KS gradient includes the grid response (ferric-dft/src/gradient.rs),
    // so KS is compared against PySCF grid_response=True.
    let g_ref = rows3(
        &r,
        if xc.is_some() {
            "qm_gradient_grid_response"
        } else {
            "qm_gradient"
        },
    );
    let mm_grad_ref = rows3(&r, "mm_gradient");

    // --- gas phase + anti-vacuum control (FIRST: it licenses the rest) ----
    let gas = scf(&qm, None, xc, &format!("{ctx}/gas"));
    check_close(&ctx, "E gas phase", gas.energy, e_gas_ref, tol.e);
    check_misses(
        &ctx,
        "vacuum energy vs embedded ref",
        gas.energy,
        e_ref,
        tol.e,
    );
    let g_gas = grad_rows(&gradient(&qm, &gas, None, xc));
    let (dg_vac, _, _) = max_row_diff(&g_gas, &g_ref, 1.0);
    check_misses(&ctx, "vacuum gradient vs embedded ref", dg_vac, 0.0, tol.g);

    // --- embedded ----------------------------------------------------------
    let emb = scf(&qm, Some(&sys), xc, &ctx);
    check_close(&ctx, "E embedded", emb.energy, e_ref, tol.e);
    check_close(
        &ctx,
        "embedding shift",
        emb.energy - gas.energy,
        e_ref - e_gas_ref,
        tol.e,
    );
    let g = grad_rows(&gradient(&qm, &emb, Some(&sys), xc));
    check_rows(&ctx, "QM gradient", &g, &g_ref, 1.0, tol.g);
    let f = mm_forces(&sys, &qm.mol, &qm.prep, emb.density_total()).unwrap();
    // ferric returns the FORCE; the reference is dE/dR.
    check_rows(&ctx, "MM force", &f, &mm_grad_ref, -1.0, tol.f);

    // --- charges x 1.01: must match PySCF's x1.01 and miss the x1 ref ------
    let scale = num(&r, "/control_scaled_101/scale");
    let sys_s = build_system(&r, scale, width);
    let emb_s = scf(&qm, Some(&sys_s), xc, &format!("{ctx}/x{scale}"));
    check_close(
        &ctx,
        "E charges x1.01",
        emb_s.energy,
        num(&r, "/control_scaled_101/energy"),
        tol.e,
    );
    check_misses(&ctx, "charges x1.01 vs x1 ref", emb_s.energy, e_ref, tol.e);

    emb.energy
}

// ---------------------------------------------------------------------------
// "QM/MM": RHF, point charges
// ---------------------------------------------------------------------------

/// Exactness anchor: an MM region whose charges are all zero produces NO
/// potential (`None`, the literal gas-phase code path), and a smeared site
/// whose width goes to zero reproduces the point-charge energy. Both are
/// ferric-vs-ferric limits that a construction error would break before any
/// cross-code number is read.
#[test]
#[ignore = "validation: QM/MM"]
fn anchor_zero_charges_and_tiny_width() {
    let r = reference("h2o_q10_cc-pvdz");
    let ctx = "anchor/h2o_q10_cc-pvdz";
    let zero = build_system(&r, 0.0, None);
    assert!(
        zero.to_external_potential().is_none(),
        "{ctx}: all-zero MM charges must give no potential (the gas-phase path)"
    );
    let sys = build_system(&r, 1.0, None);
    let qm = qm_part(&r, &sys, ctx);
    let point = scf(&qm, Some(&sys), None, ctx);
    let tiny = build_system(&r, 1.0, Some(1e-4));
    let smeared = scf(&qm, Some(&tiny), None, &format!("{ctx}/w1e-4"));
    check_close(
        ctx,
        "E smeared w=1e-4 vs point",
        smeared.energy,
        point.energy,
        TOL_ANCHOR_TINY_WIDTH,
    );
}

#[test]
#[ignore = "validation: QM/MM"]
fn point_h2o_q10_ccpvdz() {
    check_case("h2o_q10_cc-pvdz", None, None, &HF);
}

#[test]
#[ignore = "validation: QM/MM"]
fn point_h2o_q10_augccpvdz() {
    check_case("h2o_q10_aug-cc-pvdz", None, None, &HF);
}

/// 501 TIP3P charges (167 waters) around methanol: the many-charge case.
#[test]
#[ignore = "validation: QM/MM"]
fn point_ch3oh_tip3p501_631g() {
    check_case("ch3oh_tip3p501_6-31g", None, None, &HF);
}

// ---------------------------------------------------------------------------
// "Smeared charges": RHF, Gaussian sites at three widths
// ---------------------------------------------------------------------------

const WIDTHS: [(&str, f64); 3] = [("0p5", 0.5), ("1", 1.0), ("2", 2.0)];

fn check_smeared(tag: &str, w: f64) {
    let stem = format!("h2o_q10_smeared_w{tag}_cc-pvdz");
    let r = reference(&stem);
    let ctx = stem.clone();
    // The file must be the width we think it is.
    for v in r["widths_bohr"].as_array().unwrap() {
        assert_eq!(v.as_f64().unwrap(), w, "{ctx}: reference width");
    }
    check_case(&stem, Some(w), None, &HF);
    let e_ref = num(&r, "/energy");

    // Point-charge limit of the same sites must MISS (smearing is live).
    let sys_p = build_system(&r, 1.0, None);
    let qm = qm_part(&r, &sys_p, &ctx);
    let point = scf(&qm, Some(&sys_p), None, &format!("{ctx}/point"));
    check_close(
        &ctx,
        "E point limit",
        point.energy,
        num(&r, "/control_point_limit/energy"),
        TOL_E_HF,
    );
    check_misses(
        &ctx,
        "point charges vs smeared ref",
        point.energy,
        e_ref,
        TOL_E_HF,
    );

    // Width swap: every OTHER width must MISS this reference (and match its own).
    for (other_tag, other_w) in WIDTHS {
        if other_w == w {
            continue;
        }
        let sys_o = build_system(&r, 1.0, Some(other_w));
        let e_o = scf(&qm, Some(&sys_o), None, &format!("{ctx}/w{other_tag}")).energy;
        check_close(
            &ctx,
            &format!("E width {other_w}"),
            e_o,
            num(&r, &format!("/control_widths/{other_w}/energy")),
            TOL_E_HF,
        );
        check_misses(
            &ctx,
            &format!("width {other_w} vs width {w} ref"),
            e_o,
            e_ref,
            TOL_E_HF,
        );
    }
    // Unit trap: a width given in Angstrom but read as Bohr (x 1.8897) is a
    // different Gaussian and must MISS.
    let ang2bohr = 1.0 / 0.529_177_210_92;
    let sys_t = build_system(&r, 1.0, Some(w * ang2bohr));
    let e_t = scf(&qm, Some(&sys_t), None, &format!("{ctx}/unit-trap")).energy;
    check_misses(&ctx, "width x 1/0.529 (unit trap)", e_t, e_ref, TOL_E_HF);
}

#[test]
#[ignore = "validation: Smeared charges"]
fn smeared_h2o_q10_width_0p5() {
    check_smeared("0p5", 0.5);
}

#[test]
#[ignore = "validation: Smeared charges"]
fn smeared_h2o_q10_width_1() {
    check_smeared("1", 1.0);
}

#[test]
#[ignore = "validation: Smeared charges"]
fn smeared_h2o_q10_width_2() {
    check_smeared("2", 2.0);
}

// ---------------------------------------------------------------------------
// "KS QM/MM": RKS, exact J/K, matched grid
// ---------------------------------------------------------------------------

fn check_ks(xc: &str, other: &str) {
    let stem = format!("ch3oh_q20_{xc}_def2-svp");
    let r = reference(&stem);
    assert_eq!(
        r["xc"].as_str().unwrap(),
        xc,
        "{stem}: reference functional"
    );
    // Functional swap: the SAME embedding with the other functional must miss
    // this reference (an ignored `xc` returns HF or a default functional).
    let sys = build_system(&r, 1.0, None);
    let qm = qm_part(&r, &sys, &stem);
    let swapped = scf(&qm, Some(&sys), Some(other), &format!("{stem}/{other}"));
    check_misses(
        &stem,
        &format!("{other} vs {xc} ref"),
        swapped.energy,
        num(&r, "/energy"),
        TOL_E_KS,
    );
    check_case(&stem, None, Some(xc), &KS);
}

#[test]
#[ignore = "validation: KS QM/MM"]
fn ks_ch3oh_q20_b3lyp_def2svp() {
    check_ks("b3lyp", "pbe");
}

#[test]
#[ignore = "validation: KS QM/MM"]
fn ks_ch3oh_q20_pbe_def2svp() {
    check_ks("pbe", "b3lyp");
}
