//! VALIDATION tier — VALIDATION.md row "SCF stability", range-separated block
//! (issue #292).
//!
//! Runs only in the weekly `validation` CI job (and on demand):
//!
//! ```text
//! cargo nextest run -p ferric-scf --test validation_rsh_stability \
//!     --run-ignored only -E 'binary(/^validation_/)'
//! ```
//!
//! The file name MUST keep the `validation_` prefix: the weekly job selects
//! with `-E 'binary(/^validation_/)'` and
//! `ci_validation_tier_guard::validation_ignores_live_only_in_validation_files`
//! fails CI for a `validation:` ignore anywhere else. A `#[cfg(test)]` unit test
//! inside `src/` escapes that guard but is ALSO never selected weekly, so the
//! measurement would simply never run — which is why these live here and reach
//! the crate through the `#[doc(hidden)]`
//! [`ferric_scf::rsh_response::rsh_uks_lowest_hessian_eigenvalue`] entry point
//! rather than by widening `rohf::FxcKernelStore`.
//!
//! # What is compared
//!
//! ferric's `uhf_internal_stability` λ_min for N2⁺ / def2-SVP / ωB97X-V with ω
//! overridden, against the dense `newton_ah.gen_g_hop_uhf` spectrum of a PySCF
//! `dft.UKS` at the same ω. The reference is generated by
//! `scripts/validation/gen_scf_stability.py` (`gen_rsh`, selected by the name
//! `rsh`) into `testdata/reference/validation/scf_stability/n2_plus_def2-svp.json`.
//!
//! Both constructions return the Hessian with NO overall factor — see that
//! generator's docstring, which proves the normalization inside PySCF itself.
//!
//! # Like-for-like recipe
//!
//! | piece | ferric (this file's config) | PySCF (generator) |
//! |---|---|---|
//! | J | exact — `uhf.rs` forces `j_aux_eff = None` for ω > 0 | exact 4-index |
//! | K | `c_SR·K^DF[erfc(ω)] + c_LR·K^DF[erf(ω)]`, jkfit aux | same, attenuated metric |
//! | grid | (75,110) Becke + Becke radii; VV10 (50,50) | same |
//! | ω | `RhfConfig::xc_omega` → libxc `_omega` AND the SR/LR split | `mf.omega` |
//! | cation state | default guess, NOT stability-followed | same (minao, not followed) |
//!
//! The J row matters and is the trap `omega_tuning::state_scf_config` names:
//! `solve_uhf` never density-fits J when ω > 0, while `solve_rhf` auto-selects
//! RI-J for a functional. Only the UKS cation is run here, so there is no
//! RKS-vs-UKS mismatch to make — but `df_j_aux = Some("")` is set explicitly
//! anyway, so the configuration states the intent instead of relying on the
//! solver's internal override.
//!
//! # Physics hypothesis vs artifact hypothesis
//!
//! * **If the SR/LR exchange response and the ω-aware f_xc kernel are both
//!   right:** λ_min matches PySCF at every ω to the DF-K/grid floor, and the
//!   sign flips across the 0.53–0.56 onset `validation_rsh_omega.rs` brackets.
//! * **If the exchange response were still plain-Coulomb** (the pre-#292 code):
//!   λ_min would miss the reference by orders of magnitude.
//!   `plain_coulomb_response_misses_the_pyscf_spectrum` is that negative
//!   control, and it constructs the old operator deliberately rather than
//!   asserting that a deleted branch would have failed.
//! * **If the ω override did not reach the functional:** every ω would give the
//!   same λ_min. The reference's `omega_override_anchor` block proves it reaches
//!   PySCF's; `lambda_min_actually_moves_with_omega` proves it reaches ferric's.
//!
//! # VV10 scope, stated rather than assumed
//!
//! ωB97X-V carries VV10 nonlocal correlation and NOTHING in this workspace has
//! a VV10 response kernel (`ferric_dft::fxc` has no VV10 term; `zvector_ks` and
//! `ferric_dft::lr_kernel::resolve_singlet_response_xc` both refuse VV10
//! functionals for that reason). `stability::ks_reference_is_analysable`
//! therefore REFUSES ωB97X-V via `StabilitySkip::Vv10Kernel`, and
//! `RhfConfig::check_stability` never produces these numbers.
//!
//! PySCF's reference omits the same term — its own provenance records
//! "PySCF KS response omits the VV10 kernel" — so this comparison is
//! like-for-like ON THAT OMISSION. It validates the SR/LR exchange response and
//! the ω-aware f_xc kernel. It does NOT establish that λ_min is the complete
//! second derivative of ωB97X-V's energy; it is not, on either side.

use std::path::{Path, PathBuf};

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_scf::rhf::RhfConfig;
use ferric_scf::screening::SchwarzBounds;
use serde_json::Value;

const ROW_DIR: &str = "testdata/reference/validation/scf_stability";
const MOL_DIR: &str = "testdata/molecules/validation";
const SYSTEM: &str = "n2_plus";
const BASIS: &str = "def2-svp";
const AUX: &str = "def2-universal-jkfit";
const FUNCTIONAL: &str = "wB97X-V";

/// Absolute bar on λ_min against PySCF.
///
/// MEASURED on this branch (N2⁺ / def2-SVP / ωB97X-V, both codes on the same
/// symmetric state, |ΔE| ≤ 1.65e-8 Ha):
///
/// ```text
///   omega   ferric lambda_min    PySCF lambda_min    |d|
///   0.40    +8.602627327e-3      +8.602813033e-3     1.86e-7
///   0.60    -1.116833188e-2      -1.116816528e-2     1.67e-7
/// ```
///
/// Bar = ~10x the measured max (1.857e-7), as #292 asks. Checked against the
/// mutation ledger: the smallest miss of any killed mutant on this comparison is
/// 3.57e-3 (xc_omega not threaded into the f_xc kernel), ~1800x this bar, and
/// the plain-Coulomb negative control misses by >= 2.9e-1.
const TOL_LAMBDA: f64 = 2e-6;
/// The negative control must miss by at least this multiple of the bar (#292).
const NEGATIVE_CONTROL_FACTOR: f64 = 10.0;

/// Workspace root, resolved at RUN time: `CARGO_MANIFEST_DIR` is baked in at
/// compile time and is wrong inside a `cargo nextest archive`.
fn workspace_root() -> PathBuf {
    let looks_like_root = |p: &Path| {
        p.join("Cargo.toml").is_file() && p.join("testdata").is_dir() && p.join("crates").is_dir()
    };
    if let Ok(cwd) = std::env::current_dir() {
        let mut here: Option<&Path> = Some(cwd.as_path());
        while let Some(p) = here {
            if looks_like_root(p) {
                return p.to_path_buf();
            }
            here = p.parent();
        }
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("ferric-scf manifest dir should be <root>/crates/ferric-scf")
        .to_path_buf()
}

/// Load the reference. Missing or unparsable is a HARD failure, never a skip.
fn reference() -> Value {
    let path = workspace_root()
        .join(ROW_DIR)
        .join(format!("{SYSTEM}_{BASIS}.json"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing validation reference {} ({e}); regenerate with \
             `scripts/validation/gen_scf_stability.py rsh` — a missing reference is a \
             failure, never a skip",
            path.display()
        )
    });
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: bad JSON: {e}", path.display()))
}

struct System {
    mol: Molecule,
    prep: PreparedBasis,
    bounds: SchwarzBounds,
    ctx: ParallelContext,
}

fn load_system(r: &Value) -> System {
    let charge = r["charge"].as_i64().expect("charge") as i32;
    let mult = r["multiplicity"].as_u64().expect("multiplicity") as usize;
    assert_eq!(
        r["functional"].as_str(),
        Some(FUNCTIONAL),
        "reference functional is not {FUNCTIONAL}"
    );
    assert_eq!(
        r["basis"].as_str(),
        Some(BASIS),
        "reference basis is not {BASIS}"
    );
    let xyz = workspace_root().join(MOL_DIR).join(format!("{SYSTEM}.xyz"));
    let mol = Molecule::load_xyz_with_charge(xyz.to_str().unwrap(), charge, mult)
        .unwrap_or_else(|e| panic!("{}: {e:?}", xyz.display()));
    // Geometry like-for-like FIRST, so a unit or constant slip fails here as a
    // geometry defect rather than later as an unexplained lambda_min offset.
    let enuc_ref = r["nuclear_repulsion"].as_f64().expect("nuclear_repulsion");
    let enuc = mol.nuclear_repulsion();
    assert!(
        (enuc - enuc_ref).abs() < 1e-9,
        "geometry mismatch: E_nn ferric {enuc:.12} vs reference {enuc_ref:.12}"
    );
    let bs = basis::bundled(BASIS).unwrap();
    let prep = PreparedBasis::new(&mol, &bs).unwrap();
    assert_eq!(
        prep.nbasis() as u64,
        r["nao"].as_u64().expect("nao"),
        "basis size mismatch"
    );
    let bounds = SchwarzBounds::compute(Operator::coulomb(), &prep).unwrap();
    System {
        mol,
        prep,
        bounds,
        ctx: ParallelContext::default(),
    }
}

/// The SCF configuration of the like-for-like table in the module doc.
fn rsh_config(omega: f64) -> RhfConfig {
    RhfConfig {
        xc: Some(FUNCTIONAL.into()),
        xc_omega: Some(omega),
        // Explicit exact J. `solve_uhf` would force this anyway for omega > 0
        // (`j_aux_eff`), but stating it keeps the configuration self-describing
        // and matches `omega_tuning::state_scf_config`.
        df_j_aux: Some(String::new()),
        df_k_aux: Some(AUX.into()),
        energy_conv: 1e-10,
        density_conv: 1e-7,
        max_iter: 500,
        ..Default::default()
    }
}

/// The reference's ω scan, as `(omega, pyscf_lambda_min, pyscf_energy)`.
fn reference_points(r: &Value) -> Vec<(f64, f64, f64)> {
    let pts = r["rsh_uks_omega_scan"]
        .as_array()
        .expect("reference rsh_uks_omega_scan");
    assert!(
        pts.len() >= 2,
        "the reference must carry at least two omega to bracket the onset"
    );
    pts.iter()
        .map(|p| {
            (
                p["omega"].as_f64().expect("omega"),
                p["hessian"]["lowest"][0].as_f64().expect("lowest[0]"),
                p["energy"].as_f64().expect("energy"),
            )
        })
        .collect()
}

/// **The PySCF comparison.** λ_min at every reference ω, within [`TOL_LAMBDA`].
///
/// The SCF energy is checked first and at a tighter bar: if the two codes were
/// on different states, λ_min agreement would be meaningless and energy
/// disagreement is the signal that says so.
#[test]
#[ignore = "validation: SCF stability"]
fn n2_cation_rsh_lambda_min_matches_pyscf() {
    let r = reference();
    let sys = load_system(&r);
    let mut worst_lambda = 0.0f64;
    let mut worst_energy = 0.0f64;
    for (omega, lam_ref, e_ref) in reference_points(&r) {
        let cfg = rsh_config(omega);
        let (lam, resid, conv, e) = ferric_scf::rsh_response::rsh_uks_lowest_hessian_eigenvalue(
            &sys.ctx,
            &sys.mol,
            &sys.prep,
            &sys.bounds,
            &cfg,
            false,
        )
        .expect("RSH UKS lambda_min");
        let d_lam = (lam - lam_ref).abs();
        let d_e = (e - e_ref).abs();
        eprintln!(
            "omega {omega:.2}:  lambda_min ferric {lam:+.9e}  PySCF {lam_ref:+.9e}  \
             |d| {d_lam:.2e}   E ferric {e:.10} PySCF {e_ref:.10} |dE| {d_e:.2e}  \
             (Davidson resid {resid:.1e}, converged {conv})"
        );
        // An iteration-starved eigensolve returning a wrong lambda would look
        // like success.
        assert!(
            conv,
            "omega {omega}: the Davidson eigensolve did NOT converge (residual \
             {resid:.3e}); an unconverged lambda_min is not a stability verdict"
        );
        // Same state first.
        assert!(
            d_e < 1e-7,
            "omega {omega}: the SCF energies differ by {d_e:.3e} Ha, so the two codes are \
             not on the same state and a lambda_min comparison says nothing"
        );
        assert!(
            d_lam < TOL_LAMBDA,
            "omega {omega}: lambda_min {lam:+.9e} vs PySCF {lam_ref:+.9e} \
             (|d| {d_lam:.3e} >= {TOL_LAMBDA:.0e})"
        );
        worst_lambda = worst_lambda.max(d_lam);
        worst_energy = worst_energy.max(d_e);
    }
    eprintln!(
        "worst |d lambda_min| = {worst_lambda:.3e} (bar {TOL_LAMBDA:.0e}); \
         worst |dE| = {worst_energy:.3e}"
    );
}

/// **#292's verdict control.** N2⁺ must be STABLE at ω = 0.40 and UNSTABLE at
/// ω = 0.60, bracketing the 0.53–0.56 onset `validation_rsh_omega.rs` measures.
///
/// The REFERENCE is checked to straddle zero first. Asserting only that
/// ferric's two signs differ would be arithmetic if the underlying quantity did
/// not actually change sign there.
#[test]
#[ignore = "validation: SCF stability"]
fn n2_cation_is_stable_below_the_onset_and_unstable_above() {
    let r = reference();
    let pts = reference_points(&r);
    let (w_lo, ref_lo, _) = pts[0];
    let (w_hi, ref_hi, _) = *pts.last().unwrap();
    assert!(
        w_lo < 0.53 && w_hi > 0.56,
        "the reference omega do not bracket the onset"
    );
    assert!(
        ref_lo > 0.0 && ref_hi < 0.0,
        "the REFERENCE itself does not straddle zero ({ref_lo:+.3e} at {w_lo}, \
         {ref_hi:+.3e} at {w_hi}); this control cannot discriminate and must be \
         redesigned, not relaxed"
    );

    let sys = load_system(&r);
    let mut got = Vec::new();
    for (omega, lam_ref, _) in [pts[0], *pts.last().unwrap()] {
        let (lam, _, conv, _) = ferric_scf::rsh_response::rsh_uks_lowest_hessian_eigenvalue(
            &sys.ctx,
            &sys.mol,
            &sys.prep,
            &sys.bounds,
            &rsh_config(omega),
            false,
        )
        .expect("RSH UKS lambda_min");
        assert!(conv, "omega {omega}: eigensolve did not converge");
        eprintln!(
            "omega {omega:.2}: ferric lambda_min {lam:+.9e} ({})  PySCF {lam_ref:+.9e} ({})",
            if lam > 0.0 { "STABLE" } else { "UNSTABLE" },
            if lam_ref > 0.0 { "STABLE" } else { "UNSTABLE" }
        );
        got.push((omega, lam, lam_ref));
    }
    // Each side with its own margin, derived from the reference magnitude on
    // that side rather than guessed, so eigensolver noise cannot flip it.
    let (w0, lam0, r0) = got[0];
    let (w1, lam1, r1) = got[1];
    assert!(
        lam0 > 0.1 * r0.abs(),
        "omega {w0}: lambda_min {lam0:+.6e} is not clearly POSITIVE (PySCF {r0:+.6e}); \
         without this side the sign-flip claim is arithmetic"
    );
    assert!(
        lam1 < -0.1 * r1.abs(),
        "omega {w1}: lambda_min {lam1:+.6e} is not clearly NEGATIVE (PySCF {r1:+.6e})"
    );
}

/// **The negative control (#292).** The pre-#292 construction — the exchange
/// response from the plain Coulomb kernel scaled by the single `k_mix.sr` —
/// must miss the PySCF spectrum by at least `NEGATIVE_CONTROL_FACTOR ×
/// TOL_LAMBDA`.
///
/// Built deliberately here (`rsh: None`, `k_mix_sr = k_mix.sr`) rather than
/// asserted about a deleted branch: a negative control that cannot be run is
/// not a control. This is the test that would have passed before the fix and
/// must fail now, so it is also the mutation that proves the comparison above
/// is sensitive to the thing #292 changed.
#[test]
#[ignore = "validation: SCF stability"]
fn plain_coulomb_response_misses_the_pyscf_spectrum() {
    let r = reference();
    let sys = load_system(&r);
    let mut closest_ratio = f64::INFINITY;
    for (omega, lam_ref, _) in reference_points(&r) {
        let cfg = rsh_config(omega);
        // Same converged state, same omega-aware f_xc kernel, ONLY the exchange
        // response swapped for the pre-#292 one.
        let (lam_bad, _, conv, _) = ferric_scf::rsh_response::rsh_uks_lowest_hessian_eigenvalue(
            &sys.ctx,
            &sys.mol,
            &sys.prep,
            &sys.bounds,
            &cfg,
            true,
        )
        .expect("plain-Coulomb control lambda_min");
        assert!(conv, "omega {omega}: control eigensolve did not converge");
        let miss = (lam_bad - lam_ref).abs();
        let ratio = miss / TOL_LAMBDA;
        eprintln!(
            "omega {omega:.2}: PLAIN-COULOMB lambda_min {lam_bad:+.9e} vs PySCF \
             {lam_ref:+.9e} -> miss {miss:.3e} = {ratio:.1}x the bar"
        );
        closest_ratio = closest_ratio.min(ratio);
    }
    assert!(
        closest_ratio >= NEGATIVE_CONTROL_FACTOR,
        "the plain-Coulomb response is only {closest_ratio:.1}x the bar away from the \
         PySCF spectrum at its CLOSEST omega, under the required \
         {NEGATIVE_CONTROL_FACTOR}x. Either the bar is too loose to discriminate, or the \
         SR/LR split is not what distinguishes the two constructions here -- and either \
         way the comparison above is not evidence."
    );
    eprintln!(
        "negative control: the plain-Coulomb response misses by >= {closest_ratio:.1}x the \
         bar at every reference omega (required {NEGATIVE_CONTROL_FACTOR}x)"
    );
}

/// **The ω-reaches-the-response control.** λ_min must MOVE with ω.
///
/// If `RhfConfig::xc_omega` did not reach the SR/LR split or the f_xc kernel,
/// every ω would return the same λ_min and the comparison above would be
/// satisfied by a construction that ignores ω entirely. The reference's own
/// `omega_override_anchor` block makes the matching statement for PySCF.
#[test]
#[ignore = "validation: SCF stability"]
fn lambda_min_actually_moves_with_omega() {
    let r = reference();
    // The reference side of the anchor, re-asserted here so a regenerated
    // reference that lost it cannot pass silently.
    let anchor = &r["omega_override_anchor"];
    let d_pub = anchor["abs_e_override_at_published_minus_default"]
        .as_f64()
        .expect("published-omega no-op");
    let d_other = anchor["abs_e_override_plus_0p1_minus_default"]
        .as_f64()
        .expect("shifted-omega effect");
    assert!(
        d_pub <= 1e-9 && d_other >= 1e-5,
        "the reference's own omega-override anchor is not satisfied \
         (published {d_pub:.2e}, shifted {d_other:.2e})"
    );

    let sys = load_system(&r);
    let pts = reference_points(&r);
    let (w0, _, _) = pts[0];
    let (w1, _, _) = *pts.last().unwrap();
    let lam = |w: f64| {
        ferric_scf::rsh_response::rsh_uks_lowest_hessian_eigenvalue(
            &sys.ctx,
            &sys.mol,
            &sys.prep,
            &sys.bounds,
            &rsh_config(w),
            false,
        )
        .expect("RSH UKS lambda_min")
        .0
    };
    let (l0, l1) = (lam(w0), lam(w1));
    let spread = (l0 - l1).abs();
    eprintln!(
        "omega {w0:.2} -> {w1:.2}: lambda_min {l0:+.6e} -> {l1:+.6e}, spread {spread:.3e} \
         (must exceed the {TOL_LAMBDA:.0e} bar by a wide margin)"
    );
    assert!(
        spread > 100.0 * TOL_LAMBDA,
        "lambda_min barely moves with omega (spread {spread:.3e}); the omega override may \
         not be reaching the exchange response or the f_xc kernel, in which case agreement \
         with PySCF at one omega proves nothing about the split"
    );
}
