[package]
name = "ferric-tensors"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
rayon = { workspace = true }
openblas-src = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
sprs = "0.11"
log = "0.4"
ferric-core = { path = "../ferric-core" }
ferric-tensor-macro = { path = "../ferric-tensor-macro" }
