[package]
name = "ferric-pcm"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ferric-core = { path = "../ferric-core" }
ferric-integrals = { path = "../ferric-integrals" }
ferric-dft = { path = "../ferric-dft" }
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
openblas-src = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
toml = { workspace = true }
