//! Regression tests for `electric_field_at_atoms`: sign check on H2 and
//! component-wise PySCF reference on H2O / cc-pVDZ.

#![allow(clippy::needless_range_loop)] // index loops over tensor/array axes read clearer with explicit indices

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_rpa::properties::electric_field_at_atoms;
use ferric_scf::rhf::{solve_rhf, RhfConfig};
use ferric_scf::screening::SchwarzBounds;

#[test]
fn h2_electric_field_symmetry_and_sign() {
    // H2 at 1.4 Bohr along z, cc-pVDZ.  Bond is exactly along the z axis,
    // so by symmetry:
    //  * E_x = E_y = 0 at both protons
    //  * E_z(H1) = -E_z(H2)  (antisymmetric under reflection)
    //
    // PySCF reference (mol r=1.4 Bohr, cc-pVDZ):
    //   E(H1) = [0, 0, -0.017597606]
    //   E(H2) = [0, 0, +0.017597606]
    let xyz = "2\nH2\nH 0 0 0\nH 0 0 0.74083\n";
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let ctx = ParallelContext::default();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let rhf = solve_rhf(&ctx, &mol, &obs, op, &bounds, &RhfConfig::default()).unwrap();

    let ef = electric_field_at_atoms(&mol, &obs, rhf.density_r()).unwrap();
    assert_eq!(ef.len(), 2);

    // Transverse components must vanish by symmetry.
    for a in 0..2 {
        assert!(
            ef[a][0].abs() < 1e-8,
            "H2 E_x[{a}] = {} not ~0 (symmetry)",
            ef[a][0]
        );
        assert!(
            ef[a][1].abs() < 1e-8,
            "H2 E_y[{a}] = {} not ~0 (symmetry)",
            ef[a][1]
        );
    }
    // Antisymmetric z component.
    assert!(
        (ef[0][2] + ef[1][2]).abs() < 1e-8,
        "H2 E_z asymmetric: {} vs {}",
        ef[0][2],
        ef[1][2]
    );

    // Magnitude vs PySCF reference (FD on int1e_rinv, h=1e-4 → ~6 digits).
    let ref_ez = 0.017597606415_f64;
    // H1 is at lower z; PySCF gives E_z(H1) = -|ref|, E_z(H2) = +|ref|.
    assert!(
        (ef[0][2] - (-ref_ez)).abs() < 1e-5,
        "H2 E_z(H1) = {}, expected ~{}",
        ef[0][2],
        -ref_ez
    );
    assert!(
        (ef[1][2] - (ref_ez)).abs() < 1e-5,
        "H2 E_z(H2) = {}, expected ~{}",
        ef[1][2],
        ref_ez
    );
}

#[test]
fn h2o_electric_field_matches_pyscf() {
    // H2O / cc-pVDZ reference generated by scripts/gen_pyscf_rpa_props.py.
    // Each component within 1e-5 a.u.
    let mol = Molecule::load_xyz("../../testdata/molecules/water.xyz").unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let ctx = ParallelContext::default();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let rhf = solve_rhf(&ctx, &mol, &obs, op, &bounds, &RhfConfig::default()).unwrap();

    let ef = electric_field_at_atoms(&mol, &obs, rhf.density_r()).unwrap();
    assert_eq!(ef.len(), 3);

    // From testdata/reference/h2o_cc-pvdz_rpa_props.json.
    let reference: [[f64; 3]; 3] = [
        [0.0, 0.0, 0.10028568513674779],
        [0.0, 0.00637878419285709, -0.0014567112351517864],
        [0.0, -0.006378784192857534, -0.0014567112351520084],
    ];
    let tol = 1e-5;
    for a in 0..3 {
        for d in 0..3 {
            let diff = (ef[a][d] - reference[a][d]).abs();
            assert!(
                diff < tol,
                "H2O E[{a}][{d}] = {} vs PySCF {} (diff {})",
                ef[a][d],
                reference[a][d],
                diff
            );
        }
    }
}

#[test]
fn nh3_electric_field_matches_pyscf() {
    // NH3 / cc-pVDZ reference generated by scripts/gen_pyscf_rpa_props.py
    // (testdata/reference/nh3_cc-pvdz_rpa_props.json), same geometry as
    // testdata/molecules/nh3.xyz.  Second molecule beyond H2O widening the
    // "H2O only" ESP/field caveat in docs/VALIDATION.md.
    let mol = Molecule::load_xyz("../../testdata/molecules/nh3.xyz").unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let ctx = ParallelContext::default();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let rhf = solve_rhf(&ctx, &mol, &obs, op, &bounds, &RhfConfig::default()).unwrap();

    let ef = electric_field_at_atoms(&mol, &obs, rhf.density_r()).unwrap();
    assert_eq!(ef.len(), 4);

    // From testdata/reference/nh3_cc-pvdz_rpa_props.json.
    let reference: [[f64; 3]; 4] = [
        [6.149594722337781e-16, 1.0121253063953561e-08, 0.07482084126223729],
        [8.359198749863239e-17, 0.0038790388780505225, -0.0006504748095846891],
        [0.0033593986247020258, -0.001939640641403284, -0.0006505764809733305],
        [-0.0033593986247020258, -0.0019396406414035061, -0.0006505764809732195],
    ];
    let tol = 1e-5;
    for a in 0..4 {
        for d in 0..3 {
            let diff = (ef[a][d] - reference[a][d]).abs();
            assert!(
                diff < tol,
                "NH3 E[{a}][{d}] = {} vs PySCF {} (diff {})",
                ef[a][d],
                reference[a][d],
                diff
            );
        }
    }
}
