//! Smoke + consistency tests for U-PDEP-RPA (C4).
//!
//! Two test families:
//!
//!   1. Internal consistency: closed-shell molecule (H2O) run via U-PDEP-RPA
//!      using a UHF (spin-symmetric) reference must reproduce closed-shell
//!      run_pdep_rpa to ≤1e-8 Ha. This catches sign/factor errors in the
//!      α+β summation without needing a PySCF reference for open-shell.
//!
//!   2. Open-shell sanity: H atom and OH radical produce finite, negative
//!      RPA correlation. Not pinned to PySCF until a U-RI-RPA reference
//!      script lands (see [[pyscf-ri-rpa-convention]]).
use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_core::parallel::ParallelContext;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::operator::Operator;
use ferric_rpa::config::{Eigensolver, QuadratureConfig, QuadratureScheme};
use ferric_rpa::{run_pdep_rpa, run_u_pdep_rpa, PdepRpaConfig};
use ferric_scf::rhf::{solve_rhf, RhfConfig};
use ferric_scf::rohf::{solve_rohf, RohfConfig};
use ferric_scf::screening::SchwarzBounds;
use ferric_scf::uhf::{solve_uhf, UhfConfig};

/// Config that keeps every PDEP eigenmode (trunc_thresh=0) so the
/// dielectric is the full naux×naux matrix. Used here for internal-
/// consistency tests (closed-shell-via-UHF ≡ closed-shell-via-RHF)
/// where any truncation would be a confound. 20-point Gauss-Legendre,
/// u0=0.5: those are the PySCF RI-RPA defaults, kept here so future
/// PySCF U-RI-RPA references plug in without re-tuning quadrature.
fn cfg_full_basis() -> PdepRpaConfig {
    PdepRpaConfig {
        quadrature: QuadratureConfig {
            scheme: QuadratureScheme::GaussLegendre,
            n_points: 20,
            u0: 0.5,
        },
        frozen_core: 0,
        trunc_thresh: 0.0,
        eigensolver_conv_thresh: 1e-9,
        ..Default::default()
    }
}

#[test]
fn u_pdep_rpa_matches_closed_shell_on_h2o() {
    // H2O via UHF with mult=1 → α and β orbitals coincide → U-PDEP-RPA
    // should match closed-shell PDEP-RPA bit-for-bit (modulo Davidson noise).
    let ctx = ParallelContext::default();
    let xyz = "3\nh2o\nO 0 0 0.117790\nH 0 0.755453 -0.471161\nH 0 -0.755453 -0.471161\n";
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();

    let cfg = cfg_full_basis();

    // Closed-shell reference.
    let rhf = solve_rhf(&ctx, &mol, &obs, op, &bounds, &RhfConfig::default()).unwrap();
    let e_closed = run_pdep_rpa(&mol, &obs, &dfbs, op, &rhf, &cfg).unwrap().e_rpa;

    // UHF (spin-symmetric) → U-RPA.
    let uhf_cfg = UhfConfig {
        energy_conv: 1e-10,
        density_conv: 1e-8,
        max_iter: 200,
        ..Default::default()
    };
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds, &uhf_cfg).unwrap();
    assert!((uhf.energy - rhf.energy).abs() < 1e-7, "UHF/RHF energy disagreement on closed-shell H2O");

    let e_unrestricted = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg).unwrap().e_rpa;
    let dev = (e_closed - e_unrestricted).abs();
    assert!(
        dev < 1e-7,
        "U-RPA on spin-symmetric UHF must match closed-shell RPA: \
         e_closed={e_closed:.10}, e_unrestricted={e_unrestricted:.10}, dev={dev:.2e}"
    );
}

#[test]
fn u_pdep_rpa_h_atom_matches_pyscf() {
    // H atom / cc-pVDZ, cc-pVDZ-RI: pinned to PySCF U-RI-RPA reference
    // generated by scripts/gen_pyscf_u_rpa_ref.py.
    // PySCF (eigh(F,S) — see note in that script): E_scf=-0.4992784034,
    // E_c = -0.0096018190.
    let ctx = ParallelContext::default();
    let xyz = "1\nh\nH 0 0 0\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let uhf_cfg = UhfConfig {
        energy_conv: 1e-10,
        density_conv: 1e-8,
        max_iter: 200,
        ..Default::default()
    };
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds, &uhf_cfg).unwrap();
    let cfg = cfg_full_basis();
    let r = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg).unwrap();
    // SCF reference: -0.4992784034. Allow 1e-6 for SCF convergence noise.
    assert!((uhf.energy - (-0.4992784034)).abs() < 1e-5,
            "UHF E disagree: ferric {}, pyscf -0.4992784", uhf.energy);
    // RPA correlation: -0.0096018190. Allow 1e-5 for quadrature + Davidson noise.
    assert!((r.e_rpa - (-0.0096018190)).abs() < 1e-5,
            "U-RPA E_c disagree: ferric {}, pyscf -0.00960", r.e_rpa);
}

#[test]
fn u_pdep_rpa_oh_matches_pyscf() {
    // OH / cc-pVDZ pinned to PySCF U-RI-RPA reference.
    // PySCF: E_scf = -75.3938389266, E_c = -0.1845116418.
    let ctx = ParallelContext::default();
    let xyz = "2\noh\nO 0 0 0\nH 0 0 0.97\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let uhf_cfg = UhfConfig {
        energy_conv: 1e-10,
        density_conv: 1e-8,
        max_iter: 200,
        ..Default::default()
    };
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds, &uhf_cfg).unwrap();
    let cfg = cfg_full_basis();
    let r = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg).unwrap();
    assert!((uhf.energy - (-75.3938389266)).abs() < 1e-4,
            "UHF E disagree: ferric {}, pyscf -75.39384", uhf.energy);
    assert!((r.e_rpa - (-0.1845116418)).abs() < 1e-4,
            "U-RPA E_c disagree: ferric {}, pyscf -0.18451", r.e_rpa);
}

#[test]
fn u_pdep_rpa_ch3_matches_pyscf() {
    // CH3 methyl radical (planar D3h, C-H=1.079 A) / cc-pVDZ, pinned to
    // PySCF U-RI-RPA reference (testdata/reference/ch3_cc-pvdz_u-rpa.json,
    // scripts/gen_pyscf_u_rpa_ref.py). Same geometry as the U-G0W0 row's
    // PySCF cross-check (scripts/gw100/geom_radicals/ch3.xyz) -- widens
    // U-PDEP-RPA past H-atom/OH to a multi-atom, heavier-center-atom system.
    // PySCF: E_scf = -39.5638067649, E_c = -0.1732762583.
    let ctx = ParallelContext::default();
    let xyz = "4\nch3\nC 0 0 0\nH 1.079 0 0\nH -0.5395 0.934441 0\nH -0.5395 -0.934441 0\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let uhf_cfg = UhfConfig {
        energy_conv: 1e-10,
        density_conv: 1e-8,
        max_iter: 200,
        ..Default::default()
    };
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds, &uhf_cfg).unwrap();
    let cfg = cfg_full_basis();
    let r = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg).unwrap();
    assert!((uhf.energy - (-39.5638067649)).abs() < 1e-4,
            "UHF E disagree: ferric {}, pyscf -39.56381", uhf.energy);
    assert!((r.e_rpa - (-0.1732762583)).abs() < 1e-4,
            "U-RPA E_c disagree: ferric {}, pyscf -0.17328", r.e_rpa);
}

#[test]
fn u_pdep_rpa_rohf_reference_runs() {
    // ROHF-RPA: same dispatch as U-RPA (per-spin α and β MO blocks), just
    // using the spin-pure Guest-Saunders ROHF reference instead of UHF.
    // OH radical / cc-pVDZ: doublet, 9 electrons (5α, 4β).
    let ctx = ParallelContext::default();
    let xyz = "2\noh\nO 0 0 0\nH 0 0 0.97\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let rohf_cfg = RohfConfig {
        energy_conv: 1e-10,
        density_conv: 1e-8,
        max_iter: 200,
        ..Default::default()
    };
    let rohf = solve_rohf(&ctx, &mol, &obs, op, &bounds, &rohf_cfg).unwrap();
    let cfg = cfg_full_basis();
    let r = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &rohf, &cfg).unwrap();
    assert!(r.e_rpa.is_finite(), "ROHF-RPA correlation non-finite");
    assert!(r.e_rpa < 0.0, "ROHF-RPA correlation should be negative, got {}", r.e_rpa);
    // Sanity bound: OH/cc-pVDZ RPA correlation is O(-0.2 to -0.3) Ha.
    assert!(r.e_rpa > -0.5 && r.e_rpa < -0.05,
            "ROHF-RPA OH/cc-pVDZ correlation = {} Ha, outside expected band", r.e_rpa);
}

#[test]
fn u_pdep_rpa_uhf_vs_rohf_close_on_doublet() {
    // OH is a clean doublet — UHF and ROHF should produce similar but not
    // identical RPA correlation energies (ROHF uses Guest-Saunders coupling,
    // UHF allows spin contamination). Bound the gap loosely.
    let ctx = ParallelContext::default();
    let xyz = "2\noh\nO 0 0 0\nH 0 0 0.97\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let cfg = cfg_full_basis();

    let uhf_cfg = UhfConfig {
        energy_conv: 1e-10,
        density_conv: 1e-8,
        max_iter: 200,
        ..Default::default()
    };
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds, &uhf_cfg).unwrap();
    let rohf_cfg = RohfConfig {
        energy_conv: 1e-10,
        density_conv: 1e-8,
        max_iter: 200,
        ..Default::default()
    };
    let rohf = solve_rohf(&ctx, &mol, &obs, op, &bounds, &rohf_cfg).unwrap();
    let e_u = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg).unwrap().e_rpa;
    let e_r = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &rohf, &cfg).unwrap().e_rpa;
    assert!(e_u.is_finite() && e_r.is_finite());
    let gap = (e_u - e_r).abs();
    assert!(gap < 0.05,
            "UHF vs ROHF U-RPA on OH gap = {gap:.4} Ha; expected <50 mHa for clean doublet");
}

#[test]
fn u_ri_drpa_diagnostic_h_atom_matches_pyscf() {
    // Bypass Davidson/Lanczos: build α and β B_ov directly, run U-RI-dRPA
    // diagnostic (full-basis dielectric, no PDEP truncation). If this
    // matches PySCF, the bug in u_pdep_rpa_h_atom_matches_pyscf is in
    // the eigensolver path, not the spin-summed dielectric.
    use ferric_mp2::rimp2::{compute_rpa_intermediates_spin, RiMp2Config};
    use ferric_rpa::diagnostics::u_ri_drpa_energy;
    use ferric_rpa::quadrature::build_quadrature;
    use ferric_rpa::config::{QuadratureConfig, QuadratureScheme};

    let ctx = ParallelContext::default();
    let xyz = "1\nh\nH 0 0 0\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds,
        &UhfConfig { max_iter: 200, ..Default::default() }).unwrap();

    let mp2_cfg = RiMp2Config { frozen_core: 0, memory_budget_bytes: None, ..Default::default() };
    let ia = compute_rpa_intermediates_spin(&mol, &obs, &dfbs, op, &uhf, &mp2_cfg, true).unwrap();
    let ib = compute_rpa_intermediates_spin(&mol, &obs, &dfbs, op, &uhf, &mp2_cfg, false).unwrap();

    let eps_occ_a: Vec<f64> = uhf.eps_a()[..ia.nocc].to_vec();
    let eps_vir_a: Vec<f64> = uhf.eps_a()[ia.nocc_total..ia.nocc_total + ia.nvir].to_vec();
    let eps_occ_b: Vec<f64> = uhf.eps_b()[..ib.nocc].to_vec();
    let eps_vir_b: Vec<f64> = uhf.eps_b()[ib.nocc_total..ib.nocc_total + ib.nvir].to_vec();

    let (freqs, weights) = build_quadrature(&QuadratureConfig {
        scheme: QuadratureScheme::GaussLegendre, n_points: 20, u0: 0.5,
    });

    let chan_a = ferric_rpa::channel::RpaChannel::new(&ia.b_ov, &eps_occ_a, &eps_vir_a);
    let chan_b = ferric_rpa::channel::RpaChannel::new(&ib.b_ov, &eps_occ_b, &eps_vir_b);
    let e_c = u_ri_drpa_energy(&chan_a, &chan_b, &freqs, &weights).unwrap();

    assert!((e_c - (-0.0096018190)).abs() < 1e-5,
        "U-RI-dRPA diag E_c = {}, pyscf -0.00960", e_c);
}

#[test]
fn closed_shell_rpa_laplace_chebyshev_matches_dense_h2o() {
    // ChebyshevTan ω-grid keeps Laplace in its safe regime (bounded ω),
    // so the fallback runs only at the highest-ω points (if at all).
    // This validates the actual Laplace path under the Eshuis quadrature.
    use ferric_rpa::config::{Chi0Backend, QuadratureScheme, QuadratureConfig};
    use ferric_rpa::run_pdep_rpa;
    use ferric_scf::rhf::{solve_rhf, RhfConfig};
    let ctx = ParallelContext::default();
    let xyz = "3\nh2o\nO 0 0 0.117790\nH 0 0.755453 -0.471161\nH 0 -0.755453 -0.471161\n";
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let rhf = solve_rhf(&ctx, &mol, &obs, op, &bounds, &RhfConfig::default()).unwrap();

    // Dense w/ default GL quadrature — reference number.
    let e_dense = run_pdep_rpa(&mol, &obs, &dfbs, op, &rhf, &cfg_full_basis()).unwrap().e_rpa;

    // ChebyshevTan + Laplace.
    let mut cfg = cfg_full_basis();
    cfg.quadrature = QuadratureConfig {
        scheme: QuadratureScheme::ChebyshevTan, n_points: 20, u0: 0.5,
    };
    // n_quad=20 is not tabulated ({3,5,7} only); the old code silently fell
    // back to the 7-point table, so request 7 explicitly (numerics unchanged).
    cfg.chi0_backend = Chi0Backend::Laplace { n_quad: 7 };
    let e_cheb_lap = run_pdep_rpa(&mol, &obs, &dfbs, op, &rhf, &cfg).unwrap().e_rpa;

    let dev = (e_dense - e_cheb_lap).abs();
    assert!(dev < 5e-4,
        "ChebTan+Laplace ≠ GL+Dense H2O: dense={e_dense}, cheb_lap={e_cheb_lap}, dev={dev}");
}

#[test]
fn closed_shell_rpa_laplace_matches_dense_h2o() {
    // Sanity check the *closed-shell* Laplace χ₀ path through run_pdep_rpa,
    // which had no prior end-to-end test (only synthetic in laplace_chi0).
    use ferric_rpa::config::Chi0Backend;
    use ferric_rpa::run_pdep_rpa;
    use ferric_scf::rhf::{solve_rhf, RhfConfig};
    let ctx = ParallelContext::default();
    let xyz = "3\nh2o\nO 0 0 0.117790\nH 0 0.755453 -0.471161\nH 0 -0.755453 -0.471161\n";
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let rhf = solve_rhf(&ctx, &mol, &obs, op, &bounds, &RhfConfig::default()).unwrap();
    let e_dense = run_pdep_rpa(&mol, &obs, &dfbs, op, &rhf, &cfg_full_basis()).unwrap().e_rpa;
    let mut cfg_l = cfg_full_basis();
    // n_quad=20 is not tabulated; old silent fallback was the 7-point table.
    cfg_l.chi0_backend = Chi0Backend::Laplace { n_quad: 7 };
    let e_lap = run_pdep_rpa(&mol, &obs, &dfbs, op, &rhf, &cfg_l).unwrap().e_rpa;
    let dev = (e_dense - e_lap).abs();
    assert!(dev < 1e-4,
        "closed-shell Laplace ≠ Dense: dense={e_dense}, laplace={e_lap}, dev={dev}");
}

#[test]
fn u_pdep_rpa_laplace_matches_dense_closed_shell_h2o() {
    // Closed-shell-via-UHF + U-Laplace ≡ closed-shell RHF + RPA (Dense)
    use ferric_rpa::config::Chi0Backend;
    use ferric_rpa::run_pdep_rpa;
    use ferric_scf::rhf::{solve_rhf, RhfConfig};
    let ctx = ParallelContext::default();
    let xyz = "3\nh2o\nO 0 0 0.117790\nH 0 0.755453 -0.471161\nH 0 -0.755453 -0.471161\n";
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();

    let rhf = solve_rhf(&ctx, &mol, &obs, op, &bounds, &RhfConfig::default()).unwrap();
    let e_closed = run_pdep_rpa(&mol, &obs, &dfbs, op, &rhf, &cfg_full_basis()).unwrap().e_rpa;

    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds,
        &UhfConfig { max_iter: 200, ..Default::default() }).unwrap();
    let mut cfg = cfg_full_basis();
    // n_quad=20 is not tabulated ({3,5,7} only); the old code silently fell
    // back to the 7-point table, so request 7 explicitly (numerics unchanged).
    cfg.chi0_backend = Chi0Backend::Laplace { n_quad: 7 };
    let e_u_lap = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg).unwrap().e_rpa;

    let dev = (e_closed - e_u_lap).abs();
    assert!(dev < 1e-4,
        "U-Laplace on closed-shell-via-UHF ≠ closed-shell RPA: closed={e_closed}, u_lap={e_u_lap}, dev={dev}");
}

#[test]
fn u_laplace_dielectric_matches_u_dense_at_omega_zero_oh() {
    // What U-Laplace *does* correctly: dielectric matrix at ω=0 (no cosine
    // modulation). This pins the spin-summation factor and per-spin Laplace
    // accumulator independently of the full-ω trace-log integration that
    // remains broken (see ignored tests above).
    use ferric_rpa::laplace_chi0::{build_laplace_for_gaps, dielectric_matrix_laplace_unrestricted};
    use ferric_rpa::sternheimer::dielectric_matrix_unrestricted;
    use ferric_mp2::rimp2::{compute_rpa_intermediates_spin, RiMp2Config};
    use ndarray::Array2;

    let ctx = ParallelContext::default();
    let xyz = "2\noh\nO 0 0 0\nH 0 0 0.97\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds,
        &UhfConfig { max_iter: 200, ..Default::default() }).unwrap();

    let mp2_cfg = RiMp2Config { frozen_core: 0, memory_budget_bytes: None, ..Default::default() };
    let ia = compute_rpa_intermediates_spin(&mol, &obs, &dfbs, op, &uhf, &mp2_cfg, true).unwrap();
    let ib = compute_rpa_intermediates_spin(&mol, &obs, &dfbs, op, &uhf, &mp2_cfg, false).unwrap();
    let eo_a: Vec<f64> = uhf.eps_a()[..ia.nocc].to_vec();
    let ev_a: Vec<f64> = uhf.eps_a()[ia.nocc_total..ia.nocc_total + ia.nvir].to_vec();
    let eo_b: Vec<f64> = uhf.eps_b()[..ib.nocc].to_vec();
    let ev_b: Vec<f64> = uhf.eps_b()[ib.nocc_total..ib.nocc_total + ib.nvir].to_vec();

    let naux = ia.naux;
    let v = Array2::<f64>::eye(naux);

    let chan_a = ferric_rpa::channel::RpaChannel::new(&ia.b_ov, &eo_a, &ev_a);
    let chan_b = ferric_rpa::channel::RpaChannel::new(&ib.b_ov, &eo_b, &ev_b);
    let dense = dielectric_matrix_unrestricted(&v, &chan_a, &chan_b, 0.0);

    // n_quad=20 is not tabulated ({3,5,7} only); the old code silently fell
    // back to the 7-point table, so request 7 explicitly (numerics unchanged).
    let qa = build_laplace_for_gaps(&eo_a, &ev_a, 7).unwrap();
    let qb = build_laplace_for_gaps(&eo_b, &ev_b, 7).unwrap();
    let lap = dielectric_matrix_laplace_unrestricted(
        &v, &chan_a, &qa, &chan_b, &qb, 0.0,
    );

    let max_err = dense.iter().zip(lap.iter()).map(|(a,b)| (a-b).abs()).fold(0.0f64, f64::max);
    assert!(max_err < 1e-4,
        "U-Laplace vs U-Dense dielectric at ω=0 disagree: max_err={max_err:.3e}");
}

#[test]
fn u_pdep_rpa_laplace_matches_dense_oh() {
    // C8: U-Laplace χ₀ on OH/cc-pVDZ must match the Dense U-RPA E_c to
    // within Laplace quadrature tolerance (7-point minimax table; only {3,5,7}
    // are tabulated — the previous "n_quad=20" silently used this same table).
    use ferric_rpa::config::Chi0Backend;
    let ctx = ParallelContext::default();
    let xyz = "2\noh\nO 0 0 0\nH 0 0 0.97\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds,
        &UhfConfig { max_iter: 200, ..Default::default() }).unwrap();

    let mut cfg_dense = cfg_full_basis();
    cfg_dense.chi0_backend = Chi0Backend::Dense;
    let e_dense = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg_dense).unwrap().e_rpa;

    let mut cfg_lap = cfg_full_basis();
    // n_quad=20 is not tabulated; old silent fallback was the 7-point table.
    cfg_lap.chi0_backend = Chi0Backend::Laplace { n_quad: 7 };
    let e_lap = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg_lap).unwrap().e_rpa;

    let dev = (e_dense - e_lap).abs();
    assert!(dev < 1e-5,
            "U-Laplace ≠ Dense U-RPA on OH: dense={e_dense:.10}, laplace={e_lap:.10}, dev={dev:.2e}");
}

#[test]
fn u_polarizability_matches_closed_shell_on_h2o() {
    // pdep_polarizability_static dispatches to open-shell SMW for UHF refs.
    // On a closed-shell singlet, spin-symmetric UHF must give the same α
    // tensor as the closed-shell path. This pins the 2×2 spin-block SMW
    // with the outer-factor-2 TDDFT convention.
    use ferric_rpa::properties::pdep_polarizability_static;
    use ferric_rpa::PdepRpaConfig;
    use ferric_scf::rhf::{solve_rhf, RhfConfig};
    let ctx = ParallelContext::default();
    let xyz = "3\nh2o\nO 0 0 0.117790\nH 0 0.755453 -0.471161\nH 0 -0.755453 -0.471161\n";
    let mol = Molecule::parse_xyz(xyz, 0, 1).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let rhf = solve_rhf(&ctx, &mol, &obs, op, &bounds, &RhfConfig::default()).unwrap();
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds,
        &UhfConfig { max_iter: 200, ..Default::default() }).unwrap();

    let cfg = PdepRpaConfig::default();
    let alpha_rhf = pdep_polarizability_static(&mol, &obs, &dfbs, &rhf, op, &cfg).unwrap();
    let alpha_uhf = pdep_polarizability_static(&mol, &obs, &dfbs, &uhf, op, &cfg).unwrap();

    let dev_iso = (alpha_rhf.iso - alpha_uhf.iso).abs();
    eprintln!("α_iso(H2O): closed={:.6}, U-via-UHF={:.6}", alpha_rhf.iso, alpha_uhf.iso);
    assert!(dev_iso < 1e-5,
        "U-α on closed-shell-via-UHF ≠ closed-shell α: dev_iso={dev_iso:.2e}");
}

#[test]
fn u_polarizability_oh_matches_pyscf() {
    // PySCF dRPA reference for OH/cc-pVDZ via the 2×2 spin-block (A+B):
    //   α_iso = 2.1204
    use ferric_rpa::properties::pdep_polarizability_static;
    use ferric_rpa::PdepRpaConfig;
    let ctx = ParallelContext::default();
    let xyz = "2\noh\nO 0 0 0\nH 0 0 0.97\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds,
        &UhfConfig { max_iter: 200, ..Default::default() }).unwrap();
    let cfg = PdepRpaConfig::default();
    let pol = pdep_polarizability_static(&mol, &obs, &dfbs, &uhf, op, &cfg).unwrap();
    eprintln!("OH α_iso ferric={:.6}, pyscf=2.1204", pol.iso);
    // 1e-3 tolerance: SMW via RI vs full MO (A+B); aux-basis truncation
    // accounts for ~mHa-level drift.
    assert!((pol.iso - 2.1204).abs() < 1e-2,
        "OH U-α: ferric {:.6} vs pyscf 2.1204", pol.iso);
}

#[test]
fn u_pdep_rpa_lanczos_matches_davidson() {
    // Internal consistency: Lanczos and Davidson eigensolvers on the same
    // U-PDEP-RPA dielectric must produce the same correlation energy.
    let ctx = ParallelContext::default();
    let xyz = "1\nh\nH 0 0 0\n";
    let mol = Molecule::parse_xyz(xyz, 0, 2).unwrap();
    let obs_bs = basis::bundled("cc-pvdz").unwrap();
    let dfbs_bs = basis::bundled("cc-pvdz-ri").unwrap();
    let op = Operator::coulomb();
    let obs = PreparedBasis::new(&mol, &obs_bs).unwrap();
    let dfbs = PreparedBasis::new(&mol, &dfbs_bs).unwrap();
    let bounds = SchwarzBounds::compute(op, &obs).unwrap();
    let uhf_cfg = UhfConfig {
        energy_conv: 1e-10,
        density_conv: 1e-8,
        max_iter: 200,
        ..Default::default()
    };
    let uhf = solve_uhf(&ctx, &mol, &obs, &bounds, &uhf_cfg).unwrap();

    let mut cfg_d = cfg_full_basis();
    cfg_d.eigensolver = Eigensolver::Davidson;
    let e_davidson = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg_d).unwrap().e_rpa;

    let mut cfg_l = cfg_full_basis();
    cfg_l.eigensolver = Eigensolver::Lanczos;
    let e_lanczos = run_u_pdep_rpa(&mol, &obs, &dfbs, op, &uhf, &cfg_l).unwrap().e_rpa;

    let dev = (e_davidson - e_lanczos).abs();
    assert!(dev < 1e-7, "Davidson vs Lanczos U-RPA disagree: {dev:.2e}");
}
