[package]
name = "ferric-scf"
version = "0.1.0"
edition = "2021"

[dependencies]
ferric-core = { path = "../ferric-core" }
ferric-dft = { path = "../ferric-dft" }
ferric-integrals = { path = "../ferric-integrals" }
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
openblas-src = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
mpi = { version = "0.7", optional = true }

[features]
default = []
mpi = ["dep:mpi", "ferric-core/mpi"]

[dev-dependencies]
ferric-dft = { path = "../ferric-dft" }
serde = { workspace = true }
serde_json = { workspace = true }
