//! Grimme D3 dispersion with Becke-Johnson damping, implemented natively in Rust.
//!
//! DFT with a semilocal functional has no long-range correlation, so it misses
//! London dispersion entirely. D3(BJ) adds it back as a parameterised pairwise
//! sum over atoms. It is the dominant attractive term in ligand binding and in
//! any halogen or CF3 substituent comparison, so a "DFT" energy without it is
//! not comparable between conformers or between substituents.
//!
//! # The model
//!
//! ```text
//! E_disp = - sum_{A<B} [ s6 * C6_AB / (R_AB^6 + f(R0_AB)^6)
//!                      + s8 * C8_AB / (R_AB^8 + f(R0_AB)^8) ]
//! ```
//!
//! with the Becke-Johnson rational damping radius `f(R0) = a1 * R0_AB + a2`
//! and `R0_AB = sqrt(C8_AB / C6_AB)`.
//!
//! `C6_AB` is not a constant: it is interpolated from tabulated reference
//! values by the two atoms' **coordination numbers**, which is what makes D3
//! sensitive to hybridisation (an sp3 carbon and an sp2 carbon get different
//! C6). The coordination number is a smooth, differentiable count,
//!
//! ```text
//! CN_A = sum_{B != A} 1 / (1 + exp(-k * ((Rcov_A + Rcov_B) / R_AB - 1)))
//! ```
//!
//! and the reference interpolation is a Gaussian weighting in `CN`:
//!
//! ```text
//! C6_AB(CN_A, CN_B) = sum_{i,j} C6ref_ij * W_i(CN_A) * W_j(CN_B) / sum_{i,j} W_i W_j
//! W_i(CN) = exp(-wf * (CN - CNref_i)^2)
//! ```
//!
//! `C8_AB = 3 * C6_AB * sqrt(Q_A * Q_B)` with `Q_A = sqrt(Z_A) * <r^4>/<r^2>_A / 2`.
//!
//! # Scope (be precise about what this does and does not do)
//!
//! Implemented and validated: the **two-body** D3(BJ) energy, for elements
//! Z = 1..103, for any molecular geometry.
//!
//! NOT implemented: the Axilrod-Teller-Muto three-body term (`s9`), analytic
//! gradients, and periodic boundary conditions. These are absent rather than
//! approximated -- there is no `s9` knob that silently does nothing.
//!
//! ## Size of the omitted three-body term (MEASURED, not estimated)
//!
//! The ATM term GROWS with system size, so a single small-molecule number
//! would understate it. Measured against simple-dftd3 1.6.0 as a fraction of
//! the two-body energy (`tests/vs_reference_dftd3.rs`, worst functional of
//! PBE/PBE0/BLYP/B3LYP per row):
//!
//! ```text
//!   water        0.0001 %      argon dimer  0.0000 %
//!   methane      0.0039 %      Br2          0.0000 %
//!   water dimer  0.0458 %      benzene      0.1003 %
//! ```
//!
//! So: negligible for an isolated small molecule, but already 0.1% at benzene
//! and TRENDING UPWARD with atom count. Do not assume it stays negligible for
//! a drug-sized ligand or a stacked complex -- that regime has NOT been
//! measured here, and the trend above is the reason to doubt an extrapolation
//! rather than to trust one. For ranking conformers of one molecule the term
//! largely cancels; for absolute binding energies of large systems it may not.
//!
//! # Provenance of the reference data
//!
//! `tables.rs` is GENERATED by `generate_tables.py` from the upstream
//! s-dftd3 Fortran (<https://github.com/dftd3/simple-dftd3>, LGPL-3.0-or-later),
//! which in turn carries the data published in Grimme et al., JCP 132, 154104
//! (2010) and the BJ-damping paper JCC 32, 1456 (2011). Nothing is
//! hand-transcribed.
//!
//! # Validation
//!
//! MEASURED against the `dftd3` Python package (simple-dftd3 1.6.0) -- an
//! INDEPENDENT implementation, not the source of this code's arithmetic -- on
//! water, methane, benzene and an argon dimer, agreeing to <1e-12 Ha with the
//! three-body term switched off on both sides. See
//! `tests/vs_reference_dftd3.rs` and the generated reference JSON.

pub mod params;
pub mod tables;

pub use params::{d3bj_params_for_functional, D3Params};

use ferric_core::FerricError;

/// Steepness of the coordination-number counting function (upstream `default_kcn`).
const KCN: f64 = 16.0;
/// Gaussian weighting factor for the reference interpolation (upstream `wf_default`).
const WF: f64 = 4.0;
/// Angstrom -> Bohr. Matches upstream mctc-lib's `aatoau`.
const AA_TO_AU: f64 = 1.0 / 0.52917721092;
/// Upstream scales the 2009 covalent radii by 4/3 to build the D3 CN.
const COV_SCALE: f64 = 4.0 / 3.0;

/// Covalent radius used by the coordination-number counting function, in Bohr.
fn rcov(z: usize) -> f64 {
    COV_SCALE * AA_TO_AU * tables::COVALENT_RAD[z - 1]
}

/// `Q_A = sqrt(Z) * <r^4>/<r^2> / 2`, the per-element factor in `C8 = 3 C6 sqrt(Q_A Q_B)`.
///
/// Upstream folds this into `sqrt_z_r4_over_r2` as `sqrt(0.5 * r4r2 * sqrt(Z))`;
/// that stored quantity is `sqrt(Q)`, so `C8 = 3 * C6 * sqrt(Q_A) * sqrt(Q_B)`
/// there. Here the square root is taken once, at the same place, so the two
/// forms are algebraically identical.
fn sqrt_q(z: usize) -> f64 {
    (0.5 * tables::R4R2[z - 1] * (z as f64).sqrt()).sqrt()
}

/// Packed lower-triangular index for an element pair, matching upstream's
/// `get_c6` addressing.
///
/// Returns the flat pair index and whether the (iref, jref) axes must be
/// swapped, because upstream stores only one triangle.
fn pair_index(zi: usize, zj: usize) -> (usize, bool) {
    if zi > zj {
        (zj + zi * (zi - 1) / 2 - 1, false)
    } else {
        (zi + zj * (zj - 1) / 2 - 1, true)
    }
}

/// A tabulated reference C6 for a given pair of reference systems.
fn reference_c6(iref: usize, jref: usize, zi: usize, zj: usize) -> f64 {
    let (ic, swap) = pair_index(zi, zj);
    let (a, b) = if swap { (jref, iref) } else { (iref, jref) };
    tables::REFERENCE_C6[a + tables::MAX_REF * (b + tables::MAX_REF * ic)]
}

/// Validate atomic numbers and return them as `usize`, erroring on anything
/// outside the D3 parameterisation.
///
/// This is deliberately an error and not a skip: silently dropping an
/// unparameterised atom would return a smaller-magnitude dispersion energy
/// that still looks like a number, which is exactly the fabricated-neutral
/// value this repo's conventions forbid.
fn checked_numbers(numbers: &[u8]) -> Result<Vec<usize>, FerricError> {
    numbers
        .iter()
        .map(|&z| {
            let z = z as usize;
            if z == 0 || z > tables::MAX_ELEM {
                Err(FerricError::General(format!(
                    "D3 dispersion has no reference data for atomic number {z}; \
                     the D3 parameterisation covers Z = 1..{}. Refusing to return a \
                     dispersion energy that silently omits this atom.",
                    tables::MAX_ELEM
                )))
            } else {
                Ok(z)
            }
        })
        .collect()
}

/// Smooth, differentiable coordination numbers for every atom.
///
/// `CN_A = sum_{B != A} 1 / (1 + exp(-k ((Rcov_A + Rcov_B)/R_AB - 1)))`
fn coordination_numbers(z: &[usize], coords: &[[f64; 3]]) -> Vec<f64> {
    let n = z.len();
    let mut cn = vec![0.0; n];
    for i in 0..n {
        for j in 0..i {
            let r = distance(&coords[i], &coords[j]);
            // A zero separation would divide by zero; two atoms on top of each
            // other is a broken geometry, so saturate the count rather than
            // producing a NaN that propagates silently into the energy.
            let count = if r <= f64::EPSILON {
                1.0
            } else {
                let rc = rcov(z[i]) + rcov(z[j]);
                1.0 / (1.0 + (-KCN * (rc / r - 1.0)).exp())
            };
            cn[i] += count;
            cn[j] += count;
        }
    }
    cn
}

fn distance(a: &[f64; 3], b: &[f64; 3]) -> f64 {
    let (dx, dy, dz) = (a[0] - b[0], a[1] - b[1], a[2] - b[2]);
    (dx * dx + dy * dy + dz * dz).sqrt()
}

/// Gaussian weights over an element's reference systems at a given CN.
///
/// Returned unnormalised; the normalisation cancels in the C6 interpolation
/// only if it is applied to both the numerator and denominator, so it is done
/// explicitly by the caller.
fn reference_weights(z: usize, cn: f64) -> Vec<f64> {
    let nref = tables::NUMBER_OF_REFERENCES[z - 1] as usize;
    (0..nref)
        .map(|iref| {
            let cnref = tables::REFERENCE_CN[iref + tables::MAX_REF * (z - 1)];
            let d = cn - cnref;
            (-WF * d * d).exp()
        })
        .collect()
}

/// Interpolated `C6_AB` at the two atoms' coordination numbers.
fn c6_interpolated(zi: usize, zj: usize, cni: f64, cnj: f64) -> f64 {
    let wi = reference_weights(zi, cni);
    let wj = reference_weights(zj, cnj);
    let mut num = 0.0;
    let mut den = 0.0;
    for (iref, &a) in wi.iter().enumerate() {
        for (jref, &b) in wj.iter().enumerate() {
            let w = a * b;
            num += reference_c6(iref, jref, zi, zj) * w;
            den += w;
        }
    }
    // Far from every reference CN all weights underflow to zero. Upstream
    // handles this by falling back to the nearest reference; here the
    // denominator guard keeps the result finite rather than NaN.
    if den > 1e-300 {
        num / den
    } else {
        // Nearest-reference fallback: pick the single closest reference CN on
        // each side. This is the wf -> infinity limit of the same expression.
        let near = |z: usize, cn: f64| {
            let nref = tables::NUMBER_OF_REFERENCES[z - 1] as usize;
            (0..nref)
                .min_by(|&a, &b| {
                    let da = (cn - tables::REFERENCE_CN[a + tables::MAX_REF * (z - 1)]).abs();
                    let db = (cn - tables::REFERENCE_CN[b + tables::MAX_REF * (z - 1)]).abs();
                    da.partial_cmp(&db).unwrap_or(std::cmp::Ordering::Equal)
                })
                .unwrap_or(0)
        };
        reference_c6(near(zi, cni), near(zj, cnj), zi, zj)
    }
}

/// Two-body D3(BJ) dispersion energy, in Hartree.
///
/// `numbers` are atomic numbers, `coords` are Cartesian coordinates in **Bohr**
/// (ferric's internal convention -- see `ferric_core::Molecule`).
///
/// Returns an error rather than a number if any atom lies outside the D3
/// parameterisation, if `numbers` and `coords` disagree in length, or if two
/// atoms sit at the same position.
///
/// Fewer than two atoms returns `Ok(0.0)`, which is exact rather than a
/// fallback: the two-body sum runs over pairs and there are none. A caller for
/// which an empty input is a MISTAKE rather than a zero-dispersion system must
/// reject it before calling -- `d3bj_energy_for_molecule` does exactly that for
/// a molecule of only ghost centres.
pub fn d3bj_energy(
    numbers: &[u8],
    coords: &[[f64; 3]],
    params: &D3Params,
) -> Result<f64, FerricError> {
    if numbers.len() != coords.len() {
        return Err(FerricError::General(format!(
            "D3: {} atomic numbers but {} coordinates",
            numbers.len(),
            coords.len()
        )));
    }
    let z = checked_numbers(numbers)?;
    let n = z.len();
    if n < 2 {
        // Fewer than two atoms means no PAIRS, so the two-body sum is empty.
        // An empty sum is exactly 0.0 -- arithmetic, not a fallback, and this
        // primitive keeps that identity (pinned by exactness_anchor.rs).
        //
        // Whether an empty input is MEANINGFUL is a caller question, not an
        // arithmetic one, so it is answered one level up: see
        // `d3bj_energy_for_molecule`, which rejects a molecule whose atoms are
        // all ghosts because that is a configuration mistake rather than a
        // zero-dispersion system.
        return Ok(0.0);
    }

    let cn = coordination_numbers(&z, coords);

    let mut energy = 0.0;
    for i in 0..n {
        for j in 0..i {
            let r = distance(&coords[i], &coords[j]);
            if r <= f64::EPSILON {
                return Err(FerricError::General(format!(
                    "D3: atoms {i} and {j} are at the same position; \
                     the dispersion energy diverges."
                )));
            }
            let c6 = c6_interpolated(z[i], z[j], cn[i], cn[j]);
            // C8 = 3 C6 sqrt(Q_A Q_B), and R0 = sqrt(C8/C6) = sqrt(3 sqrt(Q_A Q_B)).
            let qq = sqrt_q(z[i]) * sqrt_q(z[j]);
            let c8 = 3.0 * c6 * qq;
            let r0 = (c8 / c6).sqrt();

            let f = params.a1 * r0 + params.a2;
            let f2 = f * f;
            let f6 = f2 * f2 * f2;
            let f8 = f6 * f2;

            let r2 = r * r;
            let r6 = r2 * r2 * r2;
            let r8 = r6 * r2;

            energy -= params.s6 * c6 / (r6 + f6) + params.s8 * c8 / (r8 + f8);
        }
    }
    Ok(energy)
}

/// Two-body D3(BJ) energy for a [`ferric_core::mol::Molecule`].
///
/// Convenience wrapper: ferric molecules already carry atomic numbers and
/// Bohr coordinates, so this is the form every caller inside ferric wants.
///
/// **Ghost atoms are excluded.** A ghost centre carries basis functions but no
/// nucleus and no electrons, so it has no polarisable density to disperse with.
/// Including one would add a spurious attraction and, in a counterpoise
/// calculation, would put dispersion energy on the very centres whose only job
/// is to supply basis functions -- turning a BSSE correction into a physics
/// error. ECP atoms ARE included at their full `z`, because the D3 reference
/// data is indexed by element, not by the number of explicitly treated
/// electrons.
pub fn d3bj_energy_for_molecule(
    mol: &ferric_core::mol::Molecule,
    params: &D3Params,
) -> Result<f64, FerricError> {
    let numbers: Vec<u8> = mol
        .atoms
        .iter()
        .filter(|a| !a.ghost)
        .map(|a| a.z as u8)
        .collect();
    let coords: Vec<[f64; 3]> = mol
        .atoms
        .iter()
        .filter(|a| !a.ghost)
        .map(|a| [a.x, a.y, a.zpos])
        .collect();
    // A molecule with atoms, ALL of which are ghosts, filters down to nothing.
    // `d3bj_energy` would correctly report the empty sum as 0.0, but at THIS
    // level that zero is indistinguishable from a computed correction, and it
    // is almost certainly a mis-specified counterpoise input rather than a
    // system anyone meant to correct. Refuse it here, where "all my atoms were
    // ghosts" is a statement that can be made.
    //
    // A genuinely empty molecule (no atoms at all) still returns 0.0 through
    // the primitive: there is nothing to warn anyone about.
    if numbers.is_empty() && !mol.atoms.is_empty() {
        return Err(FerricError::General(format!(
            "D3: all {} centres in this molecule are ghosts, so there are no              real atoms to correct. A ghost carries basis functions but no              nucleus, so this is a configuration error, not a zero dispersion              correction.",
            mol.atoms.len()
        )));
    }
    d3bj_energy(&numbers, &coords, params)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The packed pair index must be a bijection onto `0..N_PAIRS` and must be
    /// symmetric under exchange, or every C6 lookup reads the wrong element.
    #[test]
    fn pair_index_is_symmetric_and_in_range() {
        for zi in 1..=tables::MAX_ELEM {
            for zj in 1..=tables::MAX_ELEM {
                let (a, _) = pair_index(zi, zj);
                let (b, _) = pair_index(zj, zi);
                assert_eq!(a, b, "pair index must be symmetric for ({zi}, {zj})");
                assert!(a < tables::N_PAIRS, "pair index {a} out of range");
            }
        }
    }

    /// `reference_c6` must be symmetric under simultaneous exchange of the
    /// element and reference axes.
    #[test]
    fn reference_c6_is_symmetric() {
        for (zi, zj) in [(1usize, 6usize), (6, 8), (8, 1), (17, 35), (6, 6)] {
            let ni = tables::NUMBER_OF_REFERENCES[zi - 1] as usize;
            let nj = tables::NUMBER_OF_REFERENCES[zj - 1] as usize;
            for i in 0..ni {
                for j in 0..nj {
                    let a = reference_c6(i, j, zi, zj);
                    let b = reference_c6(j, i, zj, zi);
                    assert_eq!(a, b, "C6 asymmetry at ({zi},{i}) ({zj},{j})");
                }
            }
        }
    }

    /// Coordination numbers must be chemically sensible: carbon in methane has
    /// ~4 neighbours, each hydrogen ~1. This is the check that would catch a
    /// wrong covalent-radius scale factor, which no energy test pins down on
    /// its own (a wrong scale shifts C6 smoothly rather than breaking it).
    #[test]
    fn methane_coordination_numbers_are_chemical() {
        // CH4, Bohr, tetrahedral, r(CH) = 2.06 Bohr.
        let d = 2.06 / 3f64.sqrt();
        let z = vec![6usize, 1, 1, 1, 1];
        let coords = [
            [0.0, 0.0, 0.0],
            [d, d, d],
            [-d, -d, d],
            [d, -d, -d],
            [-d, d, -d],
        ];
        let cn = coordination_numbers(&z, &coords);
        assert!(
            (cn[0] - 4.0).abs() < 0.15,
            "carbon in methane must have CN ~ 4, got {}",
            cn[0]
        );
        for (i, &c) in cn.iter().enumerate().skip(1) {
            assert!(
                (c - 1.0).abs() < 0.15,
                "hydrogen {i} in methane must have CN ~ 1, got {c}"
            );
        }
    }

    /// A mismatched numbers/coords length is a caller bug and must error, not
    /// silently use the shorter of the two.
    #[test]
    fn mismatched_lengths_error() {
        let p = D3Params {
            s6: 1.0,
            s8: 0.7875,
            a1: 0.4289,
            a2: 4.4407,
        };
        assert!(d3bj_energy(&[1, 1], &[[0.0, 0.0, 0.0]], &p).is_err());
    }

    /// Ghost (basis-only) centres must be EXCLUDED from the dispersion sum.
    ///
    /// A ghost carries basis functions but no nucleus and no electrons, so it
    /// has nothing to disperse with. Including one would put dispersion energy
    /// on exactly the centres a counterpoise calculation adds to correct BSSE,
    /// turning a basis-set correction into a physics error.
    ///
    /// This test exists because a mutation that deleted the ghost filter was
    /// NOT caught by any other test in this crate (mutation ledger, entry 13).
    #[test]
    fn ghost_centres_are_excluded_from_the_dispersion_sum() {
        let p = D3Params {
            s6: 1.0,
            s8: 0.7875,
            a1: 0.4289,
            a2: 4.4407,
        };
        // Water alone.
        let water = "3\nwater\nO 0.0 0.0 0.0623\nH 0.0 0.7572 -0.4923\nH 0.0 -0.7572 -0.4923\n";
        let mol = ferric_core::mol::Molecule::parse_xyz(water, 0, 1).unwrap();
        let e_plain = d3bj_energy_for_molecule(&mol, &p).unwrap();

        // The SAME water, plus a ghost carbon close enough that, if it were
        // counted, it would contribute a large dispersion term. It must not
        // change the energy AT ALL.
        let with_ghost = "4\nwater + ghost C\nO 0.0 0.0 0.0623\nH 0.0 0.7572 -0.4923\n\
                          H 0.0 -0.7572 -0.4923\n@C 0.0 0.0 3.0\n";
        let mol_g = ferric_core::mol::Molecule::parse_xyz(with_ghost, 0, 1).unwrap();
        assert!(mol_g.atoms[3].ghost, "the 4th centre must parse as a ghost");
        let e_ghost = d3bj_energy_for_molecule(&mol_g, &p).unwrap();

        assert_eq!(
            e_plain, e_ghost,
            "a ghost centre must not change the dispersion energy at all: \
             {e_plain:e} without vs {e_ghost:e} with"
        );

        // Vacuity guard: a REAL carbon at the same position MUST change the
        // energy, else the assertion above would pass for a function that
        // ignores the 4th atom for any reason.
        let with_real = "4\nwater + real C\nO 0.0 0.0 0.0623\nH 0.0 0.7572 -0.4923\n\
                         H 0.0 -0.7572 -0.4923\nC 0.0 0.0 3.0\n";
        let mol_r = ferric_core::mol::Molecule::parse_xyz(with_real, 0, 1).unwrap();
        let e_real = d3bj_energy_for_molecule(&mol_r, &p).unwrap();
        assert!(
            (e_real - e_plain).abs() > 1e-6,
            "a REAL carbon at the ghost's position must change the energy, else \
             the ghost test is vacuous: {e_plain:e} vs {e_real:e}"
        );
    }

    /// A molecule of ONLY ghost centres must ERROR, not report a zero
    /// correction.
    ///
    /// This is the one case where the ghost filter and the "no silent zeros"
    /// rule collide: filtering every atom out leaves an empty list, and the
    /// empty two-body sum is arithmetically 0.0. But 0.0 here means "you
    /// configured a system with no real atoms", which is a mistake, and it is
    /// indistinguishable from a genuine zero once returned. So it raises.
    #[test]
    fn a_ghost_only_molecule_errors_instead_of_reporting_zero() {
        let p = D3Params {
            s6: 1.0,
            s8: 0.7875,
            a1: 0.4289,
            a2: 4.4407,
        };
        let all_ghost = "3\nall ghosts\n@O 0.0 0.0 0.0623\n@H 0.0 0.7572 -0.4923\n\
                         @H 0.0 -0.7572 -0.4923\n";
        let mol = ferric_core::mol::Molecule::parse_xyz(all_ghost, 0, 1).unwrap();
        assert!(
            mol.atoms.iter().all(|a| a.ghost),
            "every centre must parse as a ghost, else this tests nothing"
        );
        let err = d3bj_energy_for_molecule(&mol, &p)
            .expect_err("a ghost-only molecule must error, not return 0.0");
        let msg = err.to_string();
        assert!(
            msg.contains("ghost") || msg.contains("no real atoms"),
            "the error must say WHY, so a user can fix the input; got: {msg}"
        );

        // Vacuity guard: the same three centres as REAL atoms must succeed.
        // Without this, the assertion above would also pass if
        // `d3bj_energy_for_molecule` errored for some unrelated reason.
        let real = "3\nwater\nO 0.0 0.0 0.0623\nH 0.0 0.7572 -0.4923\nH 0.0 -0.7572 -0.4923\n";
        let mol_r = ferric_core::mol::Molecule::parse_xyz(real, 0, 1).unwrap();
        assert!(
            d3bj_energy_for_molecule(&mol_r, &p).is_ok(),
            "the same centres as real atoms must compute fine"
        );
    }

    /// A SINGLE atom is the one legitimate `Ok(0.0)`: the two-body sum runs
    /// over pairs and one atom has none. This pins that the empty-list error
    /// above did not overreach into the one-atom case.
    #[test]
    fn a_single_atom_is_an_exact_zero_not_an_error() {
        let p = D3Params {
            s6: 1.0,
            s8: 0.7875,
            a1: 0.4289,
            a2: 4.4407,
        };
        let e = d3bj_energy(&[8], &[[0.0, 0.0, 0.0]], &p)
            .expect("one atom has no pairs; that is an exact zero, not an error");
        assert_eq!(e, 0.0, "a lone atom's two-body dispersion is exactly zero");
    }

    /// The unsupported-element ERROR must propagate out of the public entry
    /// point, not be swallowed somewhere in between.
    ///
    /// The exactness anchor checks that an out-of-table Z errors. This checks
    /// the complementary thing the anchor cannot: that the error survives the
    /// `?` in `d3bj_energy` rather than being discarded, and that it still
    /// errors when the bad atom is NOT first (a loop that validated only
    /// `numbers[0]` would pass the anchor).
    #[test]
    fn unsupported_element_error_propagates_from_any_position() {
        let p = D3Params {
            s6: 1.0,
            s8: 0.7875,
            a1: 0.4289,
            a2: 4.4407,
        };
        let coords = [[0.0, 0.0, 0.0], [0.0, 0.0, 3.0], [0.0, 3.0, 0.0]];
        // Bad element in each position in turn.
        for pos in 0..3 {
            let mut z = [6u8, 6, 6];
            z[pos] = 104;
            let r = d3bj_energy(&z, &coords, &p);
            assert!(
                r.is_err(),
                "an out-of-table element at position {pos} must error, got {r:?}"
            );
            let msg = r.unwrap_err().to_string();
            assert!(
                msg.contains("104"),
                "the error must name the offending atomic number: {msg}"
            );
        }
        // Z = 0 is not an element either.
        assert!(d3bj_energy(&[0, 6], &coords[..2], &p).is_err());
    }

    /// Two atoms at the same point is a broken geometry; the energy diverges,
    /// so it must error rather than return an infinity or a NaN.
    #[test]
    fn coincident_atoms_error() {
        let p = D3Params {
            s6: 1.0,
            s8: 0.7875,
            a1: 0.4289,
            a2: 4.4407,
        };
        let r = d3bj_energy(&[6, 6], &[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], &p);
        assert!(r.is_err(), "coincident atoms must error, got {r:?}");
    }
}
