//! VALIDATION tier — VALIDATION.md row "ferric-mm vs OpenMM".
//!
//! Runs only in the weekly `validation` CI job (and on demand):
//!
//! ```text
//! cargo nextest run -p ferric-mm --test validation_mm \
//!     --run-ignored only -E 'binary(/^validation_/)'
//! ```
//!
//! # What is compared
//!
//! `ferric_mm::gradient` (AMBER-form bonds, angles, periodic torsions,
//! Lorentz-Berthelot LJ, bare Coulomb, bond-graph exclusions, global 1-4
//! scaling; no cutoff, no periodicity) against OpenMM 8.6's Reference platform
//! (double precision) on REAL ff14SB / TIP3P parameters. References:
//! `testdata/reference/validation/mm/*.json`, generated by
//! `scripts/validation/gen_mm.py`. The parameters in each JSON are the output
//! of `tools/active_site/mm_topology.py::topology_from_system` (the production
//! extraction code) and go through `MmTopology::from_amber_units` here, the
//! same path the Python `MmTopology` takes. ferric derives its OWN exclusions
//! and 1-4 pairs from the bond list; OpenMM uses the force field's per-pair
//! exceptions, which the JSON also carries so the two pair sets are compared
//! directly.
//!
//! | system | atoms | what it exercises |
//! |---|---|---|
//! | `ala_ala` | 23 | zwitterionic ALA-ALA (`tools/active_site/tests/ala_ala.pdb`) |
//! | `ace_phe_nme` | 32 | capped dipeptide; 6-ring (para 1-4, meta excluded) |
//! | `trp_pro_asp` | 53 | zwitterion, net charge -1; fused indole bicycle, proline 5-ring |
//! | `ace_phe_nme_3wat` | 41 | + 3 flexible TIP3P waters (H eps = 0, intermolecular pairs) |
//! | `ace_phe_nme_phase37` | 32 | SYNTHETIC: every torsion phase + 37 degrees |
//!
//! Each system is evaluated at three geometries: the committed PDB (relaxed,
//! near a minimum) and two seeded random perturbations (sigma 0.03 and
//! 0.10 Angstrom per component; max |dE/dR| up to 0.56 Ha/Bohr).
//!
//! Per term (bond, angle, torsion, coulomb, lj) and for the total: the energy
//! and the gradient on every atom. ferric returns one combined gradient, so a
//! per-term ferric gradient is taken from a copy of the topology with every
//! other term switched off (other lists emptied, charges or epsilons zeroed;
//! bonds are kept with k = 0 wherever the exclusions must survive), and the
//! per-term gradients are asserted to sum to the full `gradient()` output.
//!
//! # The Coulomb constant
//!
//! ferric's Coulomb constant is exactly 1 Hartree*Bohr. OpenMM's
//! e^2/(4 pi eps0) = 138.93545764438198 kJ/mol*nm (CODATA 2018) converted with
//! ferric's own constants (4.184 kJ/kcal, 627.509474 kcal/mol/Ha,
//! 0.52917721092 A/Bohr) is 1 + 6.62e-11. So every reference Coulomb energy and
//! force is larger than ferric's by that ratio (the generator measures it and
//! records it as `provenance.coulomb_constant.openmm_in_hartree_bohr`). This
//! test (a) asserts that the RAW Coulomb disagreement IS that offset, to
//! `TOL_E_REL`, and (b) multiplies ferric's Coulomb energy and gradient by the
//! ratio before every other comparison, so the remaining bars are set by
//! arithmetic, not by a constants mismatch.
//!
//! # Physics hypothesis vs artifact hypothesis
//!
//! * If ferric-mm is right: every term agrees at double-precision roundoff
//!   (a numpy transcription of `energy.rs` fed the same JSON reproduces the
//!   reference energies to <= 6.5e-13 relative per term), and the pair sets
//!   are identical.
//! * If a 1-4 scale is wrong (swapped, or 1): Coulomb and LJ both move by
//!   percent-level amounts. Controls 1 and 2.
//! * If a parameter reaches the wrong atom (an index/ordering slip in the
//!   extraction or in `from_amber_units`): the charge-swap and LJ-swap
//!   controls show the size of such a slip.
//! * If the combining rule were geometric instead of Lorentz for sigma: not
//!   expressible in the input; it is the documented MUTATION below.
//! * If the dihedral sign convention were flipped: ff14SB phases are all 0 or
//!   180 degrees, where cos(n*phi - delta) is even in phi, so the four real
//!   systems CANNOT see it (asserted: negating every phase leaves their
//!   torsion energy unchanged). `ace_phe_nme_phase37` exists for this; there
//!   the negated-phase control must miss.
//! * If the harness is broken (wrong file, units, atom order): the
//!   exclusion/1-4 set comparison and the bond term fail first.
//!
//! # NEGATIVE CONTROLS (at every geometry of every system; each edits the INPUT
//! topology, so it runs through ferric's real code path)
//!
//! 1. `with_scales(1.0, 1.0)` (1-4 pairs unscaled): Coulomb AND LJ must miss.
//! 2. scales swapped, `with_scales(1/1.2, 0.5)`: Coulomb AND LJ must miss.
//! 3. the charges of the two atoms with the most different charges swapped:
//!    Coulomb must miss.
//! 4. the LJ (sigma, epsilon) of the two atoms with the most different sigma
//!    swapped: LJ must miss.
//! 5. every torsion phase negated: must MISS on `ace_phe_nme_phase37`, must
//!    NOT move the torsion energy on the ff14SB systems (the blind spot).
//!
//! "Miss" = relative error above `MISS_FACTOR` x the bar.
//!
//! # MUTATIONS (each must turn a test red)
//!
//! Run 2026-09-25; each mutation turned every listed test red.
//!
//! * `crates/ferric-mm/src/energy.rs`, `mix()`:
//!   `sigma: 0.5 * (a.sigma + b.sigma),` -> `sigma: (a.sigma * b.sigma).sqrt(),`
//!   (geometric sigma combining rule) -> the LJ energy of every system misses.
//! * `crates/ferric-mm/src/energy.rs`, `dihedral_and_gradient()`:
//!   `if dot(r_ij, n) < 0.0 {` -> `if dot(r_ij, n) > 0.0 {` (flipped dihedral
//!   sign) -> all five systems fail: the torsion GRADIENT flips sign
//!   (relative error 2.0) wherever a torsion is off 0°/180°, although the
//!   torsion ENERGY of the four ff14SB systems cannot see it (the blind spot
//!   above; only `ace_phe_nme_phase37` misses in the energy).
//! * `crates/ferric-mm/src/topology.rs`:
//!   `DEFAULT_SCALE_COUL_14: f64 = 1.0 / 1.2;` -> `0.5` -> every system fails
//!   (the scale check and the Coulomb term).
//!
//! A missing reference JSON is a HARD failure (panic naming the path).

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use ferric_mm::topology::{DEFAULT_SCALE_COUL_14, DEFAULT_SCALE_LJ_14};
use ferric_mm::{energy, gradient, MmTopology};
use ndarray::Array2;
use serde_json::Value;

const ROW_DIR: &str = "testdata/reference/validation/mm";

/// ferric's Å -> Bohr (crates/ferric-mm/src/units.rs).
const ANGSTROM_TO_BOHR: f64 = 1.0 / 0.529_177_210_92;

/// Per-term energy, relative to |E_ref| (total: relative to the sum of the
/// |per-term| reference energies, since the total is a cancellation). After
/// the Coulomb-constant rescaling.
// Measured max 1.75e-12 (ace_phe_nme).
const TOL_E_REL: f64 = 1e-11;
/// Per-term gradient: max |dg| over all atoms and components, relative to the
/// max |g_ref| of that term. After the Coulomb-constant rescaling.
// Measured max 8.5e-11 (ace_phe_nme).
const TOL_G_REL: f64 = 1e-9;
/// Sum of ferric's per-term gradients vs its full `gradient()` (same code,
/// different summation order), relative to max |g|.
// Measured max 1.6e-14 (trp_pro_asp).
const TOL_DECOMP_REL: f64 = 1e-13;
/// OpenMM's 1-4 scales, measured from its exceptions, vs ferric's defaults.
const TOL_SCALE: f64 = 1e-14;
/// A control must miss by this multiple of the bar it is judged against.
const MISS_FACTOR: f64 = 100.0;

const TERMS: [&str; 5] = ["bond", "angle", "torsion", "coulomb", "lj"];

// ---------------------------------------------------------------------------
// Reference loading
// ---------------------------------------------------------------------------

fn workspace_root() -> PathBuf {
    let looks_like_root = |p: &Path| {
        p.join("Cargo.toml").is_file() && p.join("testdata").is_dir() && p.join("crates").is_dir()
    };
    if let Ok(cwd) = std::env::current_dir() {
        let mut here: Option<&Path> = Some(cwd.as_path());
        while let Some(p) = here {
            if looks_like_root(p) {
                return p.to_path_buf();
            }
            here = p.parent();
        }
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("ferric-mm manifest dir should be <root>/crates/ferric-mm")
        .to_path_buf()
}

fn reference(system: &str) -> Value {
    let path = workspace_root()
        .join(ROW_DIR)
        .join(format!("{system}.json"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing validation reference {} ({e}); regenerate with \
             scripts/validation/gen_mm.py — a missing reference is a failure, never a skip",
            path.display()
        )
    });
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: bad JSON: {e}", path.display()))
}

fn num(v: &Value, ptr: &str) -> f64 {
    v.pointer(ptr)
        .and_then(Value::as_f64)
        .unwrap_or_else(|| panic!("reference field {ptr} missing or not a number"))
}

fn arr<'a>(v: &'a Value, ptr: &str) -> &'a Vec<Value> {
    v.pointer(ptr)
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("reference field {ptr} missing or not an array"))
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("number array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn idx(v: &Value) -> usize {
    v.as_u64().expect("index") as usize
}

fn rows(v: &Value) -> Array2<f64> {
    let r = v.as_array().expect("rows");
    let mut out = Array2::<f64>::zeros((r.len(), 3));
    for (i, row) in r.iter().enumerate() {
        let x = f64s(row);
        assert_eq!(x.len(), 3, "coordinate/gradient row of length {}", x.len());
        for (c, v) in x.into_iter().enumerate() {
            out[(i, c)] = v;
        }
    }
    out
}

fn pair_set(v: &Value, ptr: &str) -> HashSet<(usize, usize)> {
    arr(v, ptr)
        .iter()
        .map(|p| {
            let p = p.as_array().expect("pair");
            (idx(&p[0]), idx(&p[1]))
        })
        .collect()
}

/// The production path: `topology_from_system`'s dict -> `from_amber_units`.
fn build_topology(r: &Value) -> MmTopology {
    let t = &r["topology"];
    let charges = f64s(&t["charges"]);
    let lj: Vec<(f64, f64)> = f64s(&t["sigmas_angstrom"])
        .into_iter()
        .zip(f64s(&t["epsilons_kcal"]))
        .collect();
    let bonds = arr(t, "/bonds")
        .iter()
        .map(|b| {
            let b = b.as_array().unwrap();
            (
                idx(&b[0]),
                idx(&b[1]),
                b[2].as_f64().unwrap(),
                b[3].as_f64().unwrap(),
            )
        })
        .collect();
    let angles = arr(t, "/angles")
        .iter()
        .map(|a| {
            let a = a.as_array().unwrap();
            (
                idx(&a[0]),
                idx(&a[1]),
                idx(&a[2]),
                a[3].as_f64().unwrap(),
                a[4].as_f64().unwrap(),
            )
        })
        .collect();
    let torsions = arr(t, "/torsions")
        .iter()
        .map(|d| {
            let d = d.as_array().unwrap();
            (
                idx(&d[0]),
                idx(&d[1]),
                idx(&d[2]),
                idx(&d[3]),
                d[4].as_u64().unwrap() as u32,
                d[5].as_f64().unwrap(),
                d[6].as_f64().unwrap(),
            )
        })
        .collect();
    MmTopology::from_amber_units(charges, lj, bonds, angles, torsions)
        .expect("from_amber_units on the exported ff14SB topology")
}

fn coords_bohr(geom: &Value) -> Array2<f64> {
    rows(&geom["coords_angstrom"]) * ANGSTROM_TO_BOHR
}

// ---------------------------------------------------------------------------
// ferric side: per-term energies and gradients
// ---------------------------------------------------------------------------

/// A copy of `top` in which only `term` is live. Bonds stay (with k = 0 when
/// the bond term itself is off) so the derived exclusions/1-4 pairs survive.
fn only(top: &MmTopology, term: &str) -> MmTopology {
    let mut t = top.clone();
    if term != "bond" {
        for b in &mut t.bonds {
            b.k = 0.0;
        }
    }
    if term != "angle" {
        t.angles.clear();
    }
    if term != "torsion" {
        t.torsions.clear();
    }
    if term != "coulomb" {
        t.charges.iter_mut().for_each(|q| *q = 0.0);
    }
    if term != "lj" {
        t.lj.iter_mut().for_each(|p| p.epsilon = 0.0);
    }
    t
}

fn term_energy(e: &ferric_mm::MmEnergy, term: &str) -> f64 {
    match term {
        "bond" => e.bond,
        "angle" => e.angle,
        "torsion" => e.torsion,
        "coulomb" => e.coulomb,
        "lj" => e.lj,
        "total" => e.total,
        _ => unreachable!(),
    }
}

fn max_abs(a: &Array2<f64>) -> f64 {
    a.iter().fold(0.0_f64, |m, x| m.max(x.abs()))
}

fn rel_e(e: f64, e_ref: f64) -> f64 {
    (e - e_ref).abs() / e_ref.abs().max(1e-300)
}

fn rel_g(g: &Array2<f64>, g_ref: &Array2<f64>) -> f64 {
    max_abs(&(g - g_ref)) / max_abs(g_ref).max(1e-300)
}

/// Energy of one term with ferric's Coulomb constant replaced by OpenMM's.
fn ferric_term_energy(top: &MmTopology, x: &Array2<f64>, term: &str, ke: f64) -> f64 {
    let e = energy(top, x).unwrap();
    let v = term_energy(&e, term);
    if term == "coulomb" {
        v * ke
    } else {
        v
    }
}

// ---------------------------------------------------------------------------
// The check
// ---------------------------------------------------------------------------

#[derive(Default)]
struct Worst {
    e: f64,
    g: f64,
    decomp: f64,
    ke_offset: f64,
    min_control_gap: f64,
}

fn check_structure(sys: &str, r: &Value, top: &MmTopology) {
    let n = r["n_atoms"].as_u64().unwrap() as usize;
    assert_eq!(top.n_atoms(), n, "{sys}: atom count");

    // OpenMM's 1-4 scales (measured from its exceptions) must be the ones
    // ferric applies globally.
    let s_lj = num(r, "/exception_scales/scale_lj_14");
    let s_c = num(r, "/exception_scales/scale_coul_14");
    assert!(
        (s_lj - DEFAULT_SCALE_LJ_14).abs() < TOL_SCALE
            && (top.scale_lj_14 - s_lj).abs() < TOL_SCALE,
        "{sys}: OpenMM 1-4 LJ scale {s_lj} vs ferric {}",
        top.scale_lj_14
    );
    assert!(
        (s_c - DEFAULT_SCALE_COUL_14).abs() < TOL_SCALE
            && (top.scale_coul_14 - s_c).abs() < TOL_SCALE,
        "{sys}: OpenMM 1-4 Coulomb scale {s_c} vs ferric {}",
        top.scale_coul_14
    );

    // ferric's BFS-derived pair sets vs the force field's exceptions.
    // "ambiguous" exceptions are zero whether excluded or scaled, so either
    // classification is acceptable for them.
    let excl = pair_set(r, "/exceptions/excluded");
    let p14 = pair_set(r, "/exceptions/scaled14");
    let amb = pair_set(r, "/exceptions/ambiguous");
    let f_excl: HashSet<_> = top.exclusions().iter().copied().collect();
    let f_14: HashSet<_> = top.pairs14().iter().copied().collect();
    let miss_excl: Vec<_> = excl.difference(&f_excl).collect();
    let miss_14: Vec<_> = p14.difference(&f_14).collect();
    let extra_excl: Vec<_> = f_excl
        .difference(&excl)
        .filter(|p| !amb.contains(p))
        .collect();
    let extra_14: Vec<_> = f_14.difference(&p14).filter(|p| !amb.contains(p)).collect();
    assert!(
        miss_excl.is_empty() && miss_14.is_empty() && extra_excl.is_empty() && extra_14.is_empty(),
        "{sys}: pair sets differ from OpenMM's exceptions: excluded by OpenMM only {miss_excl:?}, \
         1-4 in OpenMM only {miss_14:?}, excluded by ferric only {extra_excl:?}, \
         1-4 in ferric only {extra_14:?}"
    );
    assert!(
        !excl.is_empty() && !p14.is_empty(),
        "{sys}: an empty pair set would make the comparison vacuous"
    );
}

/// Relative error of `term` for a CONTROL topology, judged the same way as
/// the real comparison.
fn control_rel(top: &MmTopology, x: &Array2<f64>, term: &str, e_ref: f64, ke: f64) -> f64 {
    rel_e(ferric_term_energy(top, x, term, ke), e_ref)
}

fn check_system(sys: &str) {
    let r = reference(sys);
    let top = build_topology(&r);
    check_structure(sys, &r, &top);
    let ke = num(&r, "/provenance/coulomb_constant/openmm_in_hartree_bohr");
    assert!(
        (ke - 1.0).abs() < 1e-9,
        "{sys}: OpenMM Coulomb constant in ferric units is {ke}; a unit slip, not a CODATA offset"
    );
    let phases_even = r["all_torsion_phases_0_or_180"].as_bool().unwrap();

    let parts: Vec<(&str, MmTopology)> = TERMS.iter().map(|&t| (t, only(&top, t))).collect();
    let mut w = Worst {
        min_control_gap: f64::INFINITY,
        ..Default::default()
    };

    for geom in arr(&r, "/geometries") {
        let label = geom["label"].as_str().unwrap();
        let tag = format!("{sys}/{label}");
        let x = coords_bohr(geom);

        let (e_full, g_full) = gradient(&top, &x).unwrap();
        assert_eq!(
            e_full,
            energy(&top, &x).unwrap(),
            "{tag}: energy()/gradient() disagree"
        );

        // --- per term -------------------------------------------------------
        let mut g_sum = Array2::<f64>::zeros(g_full.raw_dim());
        let mut g_total_scaled = Array2::<f64>::zeros(g_full.raw_dim());
        let mut e_total_scaled = 0.0;
        let mut scale_total = 0.0;
        for (term, t) in &parts {
            let (e_t, g_t) = gradient(t, &x).unwrap();
            let e_t = term_energy(&e_t, term);
            assert_eq!(
                e_t,
                term_energy(&e_full, term),
                "{tag}: {term} energy from the term-only topology != full topology"
            );
            g_sum += &g_t;
            let k = if *term == "coulomb" { ke } else { 1.0 };
            let e_ref = num(geom, &format!("/energy_hartree/{term}"));
            let g_ref = rows(&geom["gradient_hartree_bohr"][*term]);

            if *term == "coulomb" {
                // The raw disagreement IS the Coulomb-constant offset.
                let raw = (e_ref - e_t) / e_ref;
                let off = (raw - (1.0 - 1.0 / ke)).abs();
                w.ke_offset = w.ke_offset.max(off);
                assert!(
                    off < TOL_E_REL,
                    "{tag}: raw Coulomb rel. difference {raw:.3e} is not the constant offset \
                     {:.3e} (residual {off:.3e})",
                    1.0 - 1.0 / ke
                );
            }

            let de = rel_e(k * e_t, e_ref);
            let dg = rel_g(&(&g_t * k), &g_ref);
            eprintln!("{tag:34} {term:8} E_ref {e_ref:+.10e}  dE_rel {de:.2e}  dG_rel {dg:.2e}");
            w.e = w.e.max(de);
            w.g = w.g.max(dg);
            assert!(de < TOL_E_REL, "{tag}: {term} energy rel. error {de:.3e}");
            assert!(dg < TOL_G_REL, "{tag}: {term} gradient rel. error {dg:.3e}");

            e_total_scaled += k * e_t;
            g_total_scaled += &(&g_t * k);
            scale_total += e_ref.abs();
        }

        let decomp = rel_g(&g_sum, &g_full);
        w.decomp = w.decomp.max(decomp);
        assert!(
            decomp < TOL_DECOMP_REL,
            "{tag}: per-term gradients do not sum to gradient(): {decomp:.3e}"
        );

        // --- total ------------------------------------------------------------
        let e_ref_tot = num(geom, "/energy_hartree/total");
        let de_tot = (e_total_scaled - e_ref_tot).abs() / scale_total;
        let dg_tot = rel_g(
            &g_total_scaled,
            &rows(&geom["gradient_hartree_bohr"]["total"]),
        );
        eprintln!(
            "{tag:34} total    E_ref {e_ref_tot:+.10e}  dE_rel {de_tot:.2e}  dG_rel {dg_tot:.2e}"
        );
        w.e = w.e.max(de_tot);
        w.g = w.g.max(dg_tot);
        assert!(
            de_tot < TOL_E_REL,
            "{tag}: total energy rel. error {de_tot:.3e}"
        );
        assert!(
            dg_tot < TOL_G_REL,
            "{tag}: total gradient rel. error {dg_tot:.3e}"
        );

        // --- negative controls ---------------------------------------------
        let e_ref = |t: &str| num(geom, &format!("/energy_hartree/{t}"));
        let bar = MISS_FACTOR * TOL_E_REL;
        let mut expect_miss = |what: &str, t: &MmTopology, term: &str| {
            let gap = control_rel(t, &x, term, e_ref(term), ke);
            eprintln!("{tag:34} control {what}: {term} rel. gap {gap:.2e}");
            w.min_control_gap = w.min_control_gap.min(gap);
            assert!(
                gap > bar,
                "{tag}: control '{what}' reproduced the reference {term} (gap {gap:.3e} <= {bar:.1e}); \
                 the comparison cannot see that defect"
            );
        };

        let unscaled = top.clone().with_scales(1.0, 1.0);
        expect_miss("1-4 scales = 1", &unscaled, "coulomb");
        expect_miss("1-4 scales = 1", &unscaled, "lj");

        let swapped = top
            .clone()
            .with_scales(DEFAULT_SCALE_COUL_14, DEFAULT_SCALE_LJ_14);
        expect_miss("1-4 scales swapped", &swapped, "coulomb");
        expect_miss("1-4 scales swapped", &swapped, "lj");

        let (a, b) = most_different(&top.charges);
        let mut qswap = top.clone();
        qswap.charges.swap(a, b);
        expect_miss(&format!("charges {a}<->{b} swapped"), &qswap, "coulomb");

        let sigmas: Vec<f64> = top.lj.iter().map(|p| p.sigma).collect();
        let (a, b) = most_different(&sigmas);
        let mut ljswap = top.clone();
        ljswap.lj.swap(a, b);
        expect_miss(&format!("LJ {a}<->{b} swapped"), &ljswap, "lj");

        let mut neg = top.clone();
        neg.torsions.iter_mut().for_each(|d| d.phase = -d.phase);
        if phases_even {
            // The blind spot, asserted: phases 0/180 make the torsion energy
            // even in phi, so a dihedral sign error is invisible here.
            let d = control_rel(&neg, &x, "torsion", e_ref("torsion"), ke);
            assert!(
                d < TOL_E_REL,
                "{tag}: negating 0/180-degree phases moved the torsion energy ({d:.3e})"
            );
        } else {
            expect_miss("torsion phases negated", &neg, "torsion");
        }
    }

    eprintln!(
        "MEASURED {sys}: max dE_rel {:.2e}, max dG_rel {:.2e}, decomposition {:.2e}, \
         Coulomb-offset residual {:.2e}, smallest control gap {:.2e}",
        w.e, w.g, w.decomp, w.ke_offset, w.min_control_gap
    );
}

/// The index pair with the largest |v[a] - v[b]| (first found on ties).
fn most_different(v: &[f64]) -> (usize, usize) {
    let (mut lo, mut hi) = (0, 0);
    for (i, &x) in v.iter().enumerate() {
        if x < v[lo] {
            lo = i;
        }
        if x > v[hi] {
            hi = i;
        }
    }
    assert!(
        v[hi] > v[lo],
        "all values equal; the swap control would be a no-op"
    );
    (lo.min(hi), lo.max(hi))
}

#[test]
#[ignore = "validation: ferric-mm vs OpenMM"]
fn ala_ala_vs_openmm() {
    check_system("ala_ala");
}

#[test]
#[ignore = "validation: ferric-mm vs OpenMM"]
fn ace_phe_nme_vs_openmm() {
    check_system("ace_phe_nme");
}

#[test]
#[ignore = "validation: ferric-mm vs OpenMM"]
fn trp_pro_asp_vs_openmm() {
    check_system("trp_pro_asp");
}

#[test]
#[ignore = "validation: ferric-mm vs OpenMM"]
fn ace_phe_nme_3wat_vs_openmm() {
    check_system("ace_phe_nme_3wat");
}

#[test]
#[ignore = "validation: ferric-mm vs OpenMM"]
fn ace_phe_nme_phase37_vs_openmm() {
    check_system("ace_phe_nme_phase37");
}
