//! Cross-validate `ferric-mm` against OpenMM's Reference (double-precision)
//! platform on the same explicit-parameter toy topologies.
//!
//! References generated by `scripts/gen_openmm_mm_refs.py` into
//! `testdata/reference/mm_{ethane,ethanol}_openmm.json`: an OpenMM `System`
//! built from HarmonicBondForce/HarmonicAngleForce/PeriodicTorsionForce/
//! NonbondedForce with explicit per-1-2/1-3/1-4 exceptions, matching exactly
//! the AMBER-convention parameters `MmTopology::from_amber_units` takes
//! (k_openmm = 2 * k_amber for the harmonic terms; PeriodicTorsionForce
//! already matches ferric-mm's `k(1+cos(n*phi-delta))` form).
//!
//! `energy_kcal.nonbonded` in the JSON is OpenMM's NonbondedForce total
//! (LJ + Coulomb together, since both live in one Force object / force
//! group); compared against ferric's `lj + coulomb` sum.

use ferric_mm::topology::{Angle, Bond, LjParams, Torsion};
use ferric_mm::{energy, gradient, MmTopology};
use ndarray::Array2;
use serde::Deserialize;
use std::path::PathBuf;

const KCAL_PER_MOL_TO_HARTREE: f64 = 1.0 / 627.509_474;
const ANGSTROM_TO_BOHR: f64 = 1.0 / 0.529_177_210_92;

#[derive(Debug, Deserialize)]
struct EnergyKcal {
    bond: f64,
    angle: f64,
    torsion: f64,
    nonbonded: f64,
    total: f64,
}

// Only `total` is used: ferric-mm returns one combined analytic gradient (no
// per-term breakdown), so the per-group (bond/angle/torsion/nonbonded)
// forces in the reference JSON have no ferric-side counterpart to check
// against here — `#[serde(rename_all = ...)]` isn't relevant, this is a
// deliberate partial deserialization via `#[allow(dead_code)]`-free field
// omission (serde ignores JSON keys with no matching field by default).
#[derive(Debug, Deserialize)]
struct ForcesKcal {
    total: Vec<[f64; 3]>,
}

#[derive(Debug, Deserialize)]
struct OpenMmRef {
    n_atoms: usize,
    coordinates_angstrom: Vec<[f64; 3]>,
    charges: Vec<f64>,
    lj_sigma_angstrom: Vec<f64>,
    lj_epsilon_kcal: Vec<f64>,
    bonds: Vec<(usize, usize, f64, f64)>,
    angles: Vec<(usize, usize, usize, f64, f64)>,
    torsions: Vec<(usize, usize, usize, usize, u32, f64, f64)>,
    scale_lj_14: f64,
    scale_coul_14: f64,
    energy_kcal: EnergyKcal,
    forces_kcal_per_angstrom: ForcesKcal,
}

fn load(name: &str) -> OpenMmRef {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("testdata/reference")
        .join(format!("mm_{name}_openmm.json"));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
}

/// Convert OpenMM's force convention (`F = -dE/dR`) to ferric's gradient
/// convention (`dE/dR`) for a like-for-like comparison against `gradient()`.
fn forces_to_gradient_ha_bohr(forces_kcal_ang: &[[f64; 3]]) -> Array2<f64> {
    let n = forces_kcal_ang.len();
    let mut g = Array2::<f64>::zeros((n, 3));
    // dE/dR [Ha/Bohr] = -F [kcal/mol/Angstrom] * (Ha/kcal) / (Bohr/Angstrom)
    //                  = -F * KCAL_PER_MOL_TO_HARTREE / ANGSTROM_TO_BOHR
    let scale = KCAL_PER_MOL_TO_HARTREE / ANGSTROM_TO_BOHR;
    for (i, f) in forces_kcal_ang.iter().enumerate() {
        for c in 0..3 {
            g[(i, c)] = -f[c] * scale;
        }
    }
    g
}

fn build_topology(r: &OpenMmRef) -> MmTopology {
    let lj: Vec<LjParams> = r
        .lj_sigma_angstrom
        .iter()
        .zip(r.lj_epsilon_kcal.iter())
        .map(|(&sigma, &eps)| LjParams { sigma: sigma * ANGSTROM_TO_BOHR, epsilon: eps * KCAL_PER_MOL_TO_HARTREE })
        .collect();
    let bonds: Vec<Bond> = r
        .bonds
        .iter()
        .map(|&(i, j, k, r0)| Bond {
            i,
            j,
            k: k * KCAL_PER_MOL_TO_HARTREE / (ANGSTROM_TO_BOHR * ANGSTROM_TO_BOHR),
            r0: r0 * ANGSTROM_TO_BOHR,
        })
        .collect();
    let angles: Vec<Angle> = r
        .angles
        .iter()
        .map(|&(i, j, k, k_theta, theta0_deg)| Angle {
            i,
            j,
            k,
            k_theta: k_theta * KCAL_PER_MOL_TO_HARTREE,
            theta0: theta0_deg.to_radians(),
        })
        .collect();
    let torsions: Vec<Torsion> = r
        .torsions
        .iter()
        .map(|&(i, j, k, l, periodicity, k_phi, phase_deg)| Torsion {
            i,
            j,
            k,
            l,
            periodicity,
            k_phi: k_phi * KCAL_PER_MOL_TO_HARTREE,
            phase: phase_deg.to_radians(),
        })
        .collect();

    MmTopology::new(r.charges.clone(), lj, bonds, angles, torsions)
        .unwrap()
        .with_scales(r.scale_lj_14, r.scale_coul_14)
}

fn coords_bohr(r: &OpenMmRef) -> Array2<f64> {
    let mut c = Array2::<f64>::zeros((r.n_atoms, 3));
    for (i, xyz) in r.coordinates_angstrom.iter().enumerate() {
        for k in 0..3 {
            c[(i, k)] = xyz[k] * ANGSTROM_TO_BOHR;
        }
    }
    c
}

const ENERGY_TOL_HARTREE: f64 = 1e-6 / 627.509_474; // 1e-6 kcal/mol
const FORCE_TOL_HARTREE_BOHR: f64 = (1e-6 / 627.509_474) / (1.0 / 0.529_177_210_92); // 1e-6 kcal/mol/Angstrom

fn check_case(name: &str) {
    let r = load(name);
    let top = build_topology(&r);
    let coords = coords_bohr(&r);

    let (e, g) = gradient(&top, &coords).unwrap();
    assert_eq!(e, energy(&top, &coords).unwrap(), "{name}: energy()/gradient() must agree");

    let e_bond_ha = r.energy_kcal.bond * KCAL_PER_MOL_TO_HARTREE;
    let e_angle_ha = r.energy_kcal.angle * KCAL_PER_MOL_TO_HARTREE;
    let e_torsion_ha = r.energy_kcal.torsion * KCAL_PER_MOL_TO_HARTREE;
    let e_nonbonded_ha = r.energy_kcal.nonbonded * KCAL_PER_MOL_TO_HARTREE;
    let e_total_ha = r.energy_kcal.total * KCAL_PER_MOL_TO_HARTREE;

    assert!((e.bond - e_bond_ha).abs() < ENERGY_TOL_HARTREE, "{name}: bond {} vs OpenMM {}", e.bond, e_bond_ha);
    assert!((e.angle - e_angle_ha).abs() < ENERGY_TOL_HARTREE, "{name}: angle {} vs OpenMM {}", e.angle, e_angle_ha);
    assert!(
        (e.torsion - e_torsion_ha).abs() < ENERGY_TOL_HARTREE,
        "{name}: torsion {} vs OpenMM {}",
        e.torsion,
        e_torsion_ha
    );
    let e_nonbonded_ferric = e.lj + e.coulomb;
    assert!(
        (e_nonbonded_ferric - e_nonbonded_ha).abs() < ENERGY_TOL_HARTREE,
        "{name}: lj+coulomb {} vs OpenMM nonbonded {}",
        e_nonbonded_ferric,
        e_nonbonded_ha
    );
    assert!(
        (e.total - e_total_ha).abs() < ENERGY_TOL_HARTREE,
        "{name}: total {} vs OpenMM {}",
        e.total,
        e_total_ha
    );

    // Compare the TOTAL gradient (sum of all per-group forces) against
    // ferric's single combined analytic gradient — per-group force
    // decomposition isn't reproduced separately (ferric doesn't expose a
    // per-term gradient split), so this is the apples-to-apples check.
    let g_ref = forces_to_gradient_ha_bohr(&r.forces_kcal_per_angstrom.total);
    let mut max_err = 0.0_f64;
    for i in 0..r.n_atoms {
        for c in 0..3 {
            max_err = max_err.max((g[(i, c)] - g_ref[(i, c)]).abs());
        }
    }
    assert!(max_err < FORCE_TOL_HARTREE_BOHR, "{name}: max gradient err {max_err:.3e} Ha/Bohr vs OpenMM");
}

#[test]
fn ethane_matches_openmm_per_term_and_gradient() {
    check_case("ethane");
}

#[test]
fn ethanol_matches_openmm_per_term_and_gradient() {
    check_case("ethanol");
}
