//! Validation of ferric's native D3(BJ) against an INDEPENDENT implementation.
//!
//! The reference is the `dftd3` Python package (simple-dftd3 1.6.0), a separate
//! Fortran codebase. This matters for the repo's "consistency is not
//! corroboration" rule: agreeing with an independent CONSTRUCTION of the same
//! model is real evidence, in a way that agreeing with a second copy of my own
//! arithmetic would not be.
//!
//! What is compared: ferric's two-body D3(BJ) energy against the reference's
//! **two-body** energy (`get_pairwise_dispersion`'s additive term), because
//! ferric does not implement the ATM three-body term. Comparing against the
//! reference TOTAL would silently fold ferric's missing three-body term into
//! the tolerance and hide a real two-body disagreement behind it.
//!
//! The reference JSON is generated by `testdata/../../../..` -- see
//! `d3bj_reference.json`'s own `source` field -- and is checked in so this test
//! does not need the Python package at run time.

use ferric_d3::{d3bj_energy, d3bj_params_for_functional, D3Params};

/// Minimal JSON reader for the reference file.
///
/// A hand-rolled reader rather than a `serde_json` dependency: the file's shape
/// is fixed and generated by this repo, and adding a dependency to a test is
/// not worth it. It is deliberately strict -- a missing key panics rather than
/// defaulting, so a malformed reference file fails loudly instead of silently
/// testing nothing.
mod json {
    #[derive(Debug)]
    pub struct System {
        pub numbers: Vec<u8>,
        pub coords: Vec<[f64; 3]>,
        /// (functional, e_two_body, e_three_body)
        pub functionals: Vec<(String, f64, f64)>,
    }

    fn find_after(hay: &str, needle: &str, from: usize) -> Option<usize> {
        hay[from..].find(needle).map(|i| from + i + needle.len())
    }

    fn number_at(s: &str, at: usize) -> (f64, usize) {
        let b = s.as_bytes();
        let mut i = at;
        while i < b.len() && (b[i] as char).is_whitespace() {
            i += 1;
        }
        let start = i;
        while i < b.len() && matches!(b[i] as char, '0'..='9' | '-' | '+' | '.' | 'e' | 'E') {
            i += 1;
        }
        (s[start..i].parse().expect("number"), i)
    }

    /// Parse the reference file into one entry per named system.
    pub fn parse(text: &str) -> Vec<(String, System)> {
        let mut out = Vec::new();
        let sys_start = text.find("\"systems\"").expect("no \"systems\" key");
        // Each system is `"<name>": { "numbers": [...], "coords_bohr": [[...]], ... }`
        let mut cursor = sys_start;
        for name in [
            "water",
            "methane",
            "argon_dimer",
            "water_dimer",
            "br2",
            "benzene",
        ] {
            let key = format!("\"{name}\":");
            let at = text[cursor..]
                .find(&key)
                .map(|i| cursor + i)
                .unwrap_or_else(|| panic!("system {name} missing from reference"));

            // numbers
            let nb = find_after(text, "\"numbers\":", at).expect("numbers");
            let nb_open = text[nb..].find('[').unwrap() + nb + 1;
            let nb_close = text[nb_open..].find(']').unwrap() + nb_open;
            let numbers: Vec<u8> = text[nb_open..nb_close]
                .split(',')
                .map(|s| s.trim().parse().expect("Z"))
                .collect();

            // coords: a list of 3-element lists
            let cb = find_after(text, "\"coords_bohr\":", at).expect("coords");
            let cb_open = text[cb..].find('[').unwrap() + cb + 1;
            let mut coords = Vec::new();
            let mut i = cb_open;
            for _ in 0..numbers.len() {
                let row = text[i..].find('[').unwrap() + i + 1;
                let (x, j) = number_at(text, row);
                let (y, k) = number_at(text, j + 1);
                let (z, l) = number_at(text, k + 1);
                coords.push([x, y, z]);
                i = l;
            }

            // functionals: each has e_two_body / e_three_body
            let mut functionals = Vec::new();
            let fstart = find_after(text, "\"functionals\":", at).expect("functionals");
            for f in ["pbe", "b3lyp", "blyp", "pbe0"] {
                let fk = format!("\"{f}\":");
                let fat = text[fstart..].find(&fk).map(|i| fstart + i).expect("func");
                let e2at = find_after(text, "\"e_two_body\":", fat).expect("e2");
                let (e2, _) = number_at(text, e2at);
                let e3at = find_after(text, "\"e_three_body\":", fat).expect("e3");
                let (e3, _) = number_at(text, e3at);
                functionals.push((f.to_string(), e2, e3));
            }

            out.push((
                name.to_string(),
                System {
                    numbers,
                    coords,
                    functionals,
                },
            ));
            cursor = at + 1;
        }
        out
    }
}

fn reference_text() -> String {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/d3bj_reference.json");
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read the D3 reference file {path}: {e}"))
}

/// The load-bearing test: ferric's two-body D3(BJ) must reproduce an
/// independent implementation's two-body D3(BJ) to numerical precision.
///
/// Tolerance is 1e-12 Ha ABSOLUTE. That is not a physics tolerance, it is a
/// "same arithmetic, different code" tolerance: both sides evaluate the same
/// closed-form sum in f64, so anything above rounding noise means a real
/// difference in the model (a wrong table entry, a wrong index, a wrong
/// damping form), not an approximation.
#[test]
fn two_body_energy_matches_simple_dftd3() {
    let text = reference_text();
    let systems = json::parse(&text);
    assert_eq!(systems.len(), 6, "reference must carry all 6 systems");

    let mut checked = 0usize;
    let mut worst = 0.0f64;
    let mut worst_label = String::new();

    for (name, sys) in &systems {
        for (fname, e2_ref, _e3) in &sys.functionals {
            let params = d3bj_params_for_functional(fname).unwrap_or_else(|e| {
                panic!("ferric has no parameters for {fname}, which the reference covers: {e}")
            });
            let e = d3bj_energy(&sys.numbers, &sys.coords, &params)
                .unwrap_or_else(|e| panic!("{name}/{fname}: {e}"));
            let diff = (e - e2_ref).abs();
            if diff > worst {
                worst = diff;
                worst_label = format!("{name}/{fname}");
            }
            assert!(
                diff < 1e-12,
                "{name}/{fname}: ferric {e:.14e} vs simple-dftd3 {e2_ref:.14e}, \
                 |diff| = {diff:.3e} exceeds 1e-12 Ha"
            );
            checked += 1;
        }
    }
    assert_eq!(checked, 24, "must have checked 6 systems x 4 functionals");
    println!("MEASURED: worst |diff| = {worst:.3e} Ha at {worst_label} over {checked} cases");
}

/// ferric's hardcoded damping parameters must equal the reference's, per
/// functional. This is separate from the energy test on purpose: the energy
/// test would also pass if BOTH the parameters and the reference were wrong in
/// the same way, because the reference JSON records the parameters that were
/// used to produce it. Comparing ferric's INDEPENDENT table against them
/// catches a transcription slip in `params.rs`.
#[test]
fn damping_parameters_match_the_reference_file() {
    let text = reference_text();
    // The reference file records the (s6, s8, a1, a2) it used under each
    // functional's "params" key.
    for (fname, s6, s8, a1, a2) in [
        ("pbe", 1.0, 0.7875, 0.4289, 4.4407),
        ("b3lyp", 1.0, 1.9889, 0.3981, 4.4211),
        ("blyp", 1.0, 2.6996, 0.4298, 4.2359),
        ("pbe0", 1.0, 1.2177, 0.4145, 4.8593),
    ] {
        // Confirm the reference file really used these numbers, so this test is
        // pinned to the file rather than to a second copy of my own table.
        let marker = format!("\"s8\": {s8}");
        assert!(
            text.contains(&marker),
            "the reference file does not record s8 = {s8} for {fname}; \
             the parameter table and the reference have drifted apart"
        );
        let p = d3bj_params_for_functional(fname).unwrap();
        assert_eq!(p, D3Params { s6, s8, a1, a2 }, "{fname} parameters");
    }
}

/// The three-body (ATM) term ferric omits must be small enough that omitting it
/// is a documented scope limit rather than a silent error.
///
/// This test does not assert that ferric is CORRECT -- it quantifies what is
/// MISSING, so `lib.rs`'s scope table is measured rather than asserted.
///
/// The bound below (0.15%) is set just above the measured worst case
/// (0.1003%, benzene/PBE0) so that it PINS the documented table: if the
/// reference data or the system set changes such that the omitted term grows,
/// this fails and the scope note must be revised rather than quietly drifting
/// out of date.
///
/// Note the trend, which is the actually interesting result: the fraction rises
/// monotonically with system size across these systems (water 0.0001% ->
/// benzene 0.1003%). That is why `lib.rs` declines to extrapolate the term's
/// size to drug-scale ligands.
#[test]
fn omitted_three_body_term_is_quantified() {
    let text = reference_text();
    let systems = json::parse(&text);
    let mut worst_frac = 0.0f64;
    let mut worst = String::new();
    for (name, sys) in &systems {
        for (fname, e2, e3) in &sys.functionals {
            if e2.abs() < 1e-14 {
                continue;
            }
            let frac = e3.abs() / e2.abs();
            if frac > worst_frac {
                worst_frac = frac;
                worst = format!("{name}/{fname}");
            }
        }
    }
    println!(
        "MEASURED: the omitted ATM three-body term is at most {:.4}% of the \
         two-body energy over the reference systems (worst: {worst})",
        100.0 * worst_frac
    );
    assert!(
        worst_frac < 1.5e-3,
        "the omitted three-body term reached {:.4}% of the two-body energy at \
         {worst}, above the 0.15% bound lib.rs's scope table documents; \
         revise the table rather than loosening this bound",
        100.0 * worst_frac
    );
}

/// A heavy-element pair (Br2) must work, not just first-row organics.
///
/// Halogen substituents are one of the stated motivations for having
/// dispersion at all, and heavier elements exercise a different part of the
/// reference table (higher packed pair indices, more reference systems), so a
/// first-row-only test would not cover the indexing.
#[test]
fn heavy_elements_are_covered() {
    let params = d3bj_params_for_functional("pbe").unwrap();
    let e = d3bj_energy(&[35, 35], &[[0.0, 0.0, 0.0], [0.0, 0.0, 4.31]], &params).unwrap();
    assert!(
        e < 0.0 && e.abs() > 1e-5,
        "Br2 must have a substantial attractive dispersion energy, got {e:e}"
    );
    // Iodine and a 5th-row metal, to exercise the far end of the table.
    for z in [53u8, 79] {
        let e = d3bj_energy(&[z, z], &[[0.0, 0.0, 0.0], [0.0, 0.0, 6.0]], &params).unwrap();
        assert!(e < 0.0, "Z={z} dimer must be attractive, got {e:e}");
    }
}

/// Naming a functional and passing its parameters explicitly must give the
/// SAME energy, bit for bit.
///
/// This is what the reference file's former `param_crosscheck_water` block
/// claimed to record, and it did not: its three `abs_diff` entries were
/// bit-identical (2.3256504914134085e-10) across pbe/b3lyp/blyp, which cannot
/// happen for three functionals with different s8/a1/a2 unless the two sides
/// were not actually the two things being compared. Those numbers were also
/// dead -- no test read them. Computing the comparison live is both honest and
/// stronger: a stale recorded difference cannot detect a lookup that starts
/// returning the wrong functional's parameters, whereas this does.
///
/// The bar is EXACT equality, not a tolerance. Both paths run the identical
/// arithmetic on identical inputs; the only difference is where the four
/// numbers came from. Any difference at all is a lookup defect.
#[test]
fn lookup_by_name_matches_explicit_parameters_exactly() {
    let text = reference_text();
    let systems = json::parse(&text);
    let (_, water) = systems
        .iter()
        .find(|(n, _)| n == "water")
        .expect("reference must carry water");

    let mut checked = 0usize;
    for (fname, s6, s8, a1, a2) in [
        ("pbe", 1.0, 0.7875, 0.4289, 4.4407),
        ("b3lyp", 1.0, 1.9889, 0.3981, 4.4211),
        ("blyp", 1.0, 2.6996, 0.4298, 4.2359),
        ("pbe0", 1.0, 1.2177, 0.4145, 4.8593),
    ] {
        let by_name = d3bj_energy(
            &water.numbers,
            &water.coords,
            &d3bj_params_for_functional(fname).unwrap(),
        )
        .unwrap();
        let by_params =
            d3bj_energy(&water.numbers, &water.coords, &D3Params { s6, s8, a1, a2 }).unwrap();
        assert_eq!(
            by_name.to_bits(),
            by_params.to_bits(),
            "{fname}: lookup-by-name gave {by_name:.17e} but the same parameters \
             passed explicitly gave {by_params:.17e}; the name -> parameter \
             lookup is returning something other than the published fit"
        );
        checked += 1;
    }
    assert_eq!(checked, 4);

    // A reachability check, so the equality above is not vacuous: DIFFERENT
    // functionals must give DIFFERENT energies on this same molecule. Without
    // this, a lookup that returned one constant set for every name would pass
    // the loop above four times over.
    let e_pbe = d3bj_energy(
        &water.numbers,
        &water.coords,
        &d3bj_params_for_functional("pbe").unwrap(),
    )
    .unwrap();
    let e_blyp = d3bj_energy(
        &water.numbers,
        &water.coords,
        &d3bj_params_for_functional("blyp").unwrap(),
    )
    .unwrap();
    assert!(
        (e_pbe - e_blyp).abs() > 1e-9,
        "pbe and blyp gave indistinguishable D3(BJ) energies ({e_pbe:.6e} vs \
         {e_blyp:.6e}); the per-functional lookup is not discriminating and \
         the equality assertions above are vacuous"
    );
}
