[molecule]
xyz = "testdata/molecules/water.xyz"

[basis]
name = "cc-pvdz"

[method]
kind = "scs-mp2-2terfc"

[mp2]
auxbasis = "cc-pvdz-ri"
r0_bonded = 0.75       # Angstrom
r0_nonbonded = 1.05    # Angstrom
c_os = 1.27
c_ss = 4.05
