"""Tests for tools/active_site/mm_topology.py::topology_from_openmm — the
parameter ASSIGNMENT path (a real force field, amber14-all.xml, applied to a
real structure) feeding ferric-mm's explicit-parameter MmTopology.

Requires OpenMM (installed dev-only into the project venv, see
scripts/gen_openmm_mm_refs.py's module docstring for the install command).
Skips itself with an actionable message if OpenMM is not importable, per the
repo convention for optional-dependency test files.
"""
from pathlib import Path

import pytest

openmm = pytest.importorskip("openmm", reason="OpenMM not installed — see scripts/gen_openmm_mm_refs.py docstring")

from tools.active_site.mm_topology import topology_from_openmm

FIXTURE = Path(__file__).parent / "ala_ala.pdb"

KCAL_TO_KJ = 4.184
ANGSTROM_TO_NM = 0.1


def test_topology_from_openmm_returns_explicit_parameters_for_ala_ala():
    result = topology_from_openmm(FIXTURE)

    # ala_ala.pdb was generated by OpenMM's own Modeller.addHydrogens with
    # amber14-all.xml (see the commit that added the fixture): 2 ALA
    # residues, N-terminal NH3+ (3 H) + C-terminal COO- (OXT) = 23 atoms.
    assert result["n_atoms"] == 23
    assert len(result["charges"]) == 23
    assert len(result["sigmas_angstrom"]) == 23
    assert len(result["epsilons_kcal"]) == 23

    # Every bond/angle/torsion index must be in range, and k/r0 must be
    # POSITIVE, finite AMBER-convention values (the 1/2 OpenMM->AMBER
    # undoing is the thing most likely to be silently wrong — a sign flip
    # or missed factor of 2 would still "parse", so check magnitudes are
    # sane rather than just "present").
    assert len(result["bonds"]) > 0
    for i, j, k, r0 in result["bonds"]:
        assert 0 <= i < 23 and 0 <= j < 23
        assert k > 0
        assert 0.3 < r0 < 2.5  # a chemically sane bond length in Angstrom

    assert len(result["angles"]) > 0
    for i, j, k, k_theta, theta0 in result["angles"]:
        assert 0 <= i < 23 and 0 <= j < 23 and 0 <= k < 23
        assert k_theta > 0
        assert 60.0 < theta0 < 180.0

    assert len(result["torsions"]) > 0
    for i, j, k, l, periodicity, k_phi, phase in result["torsions"]:
        assert 0 <= i < 23 and 0 <= j < 23 and 0 <= k < 23 and 0 <= l < 23
        assert periodicity >= 1
        assert k_phi >= 0.0


def test_topology_from_openmm_bond_k_r0_match_openmm_exactly():
    # Cross-check: rebuild an OpenMM System from the SAME fixture/force
    # field independently, undo the 1/2 by hand, and require an EXACT match
    # against topology_from_openmm's output (same units, same atom order) —
    # this is the real regression guard for the unit/convention bridge.
    from openmm import app, unit

    result = topology_from_openmm(FIXTURE)

    pdb = app.PDBFile(str(FIXTURE))
    ff = app.ForceField("amber14-all.xml")
    system = ff.createSystem(pdb.topology, nonbondedMethod=app.NoCutoff)

    bond_force = next(f for f in system.getForces() if isinstance(f, openmm.HarmonicBondForce))
    expected_bonds = []
    for b in range(bond_force.getNumBonds()):
        i, j, r0, k = bond_force.getBondParameters(b)
        r0_ang = r0.value_in_unit(unit.angstrom)
        k_amber = 0.5 * k.value_in_unit(unit.kilocalorie_per_mole / unit.angstrom**2)
        expected_bonds.append((i, j, k_amber, r0_ang))

    assert len(result["bonds"]) == len(expected_bonds)
    got_sorted = sorted(result["bonds"], key=lambda t: (t[0], t[1]))
    want_sorted = sorted(expected_bonds, key=lambda t: (t[0], t[1]))
    for got, want in zip(got_sorted, want_sorted):
        assert got[0] == want[0] and got[1] == want[1]
        assert got[2] == pytest.approx(want[2], rel=1e-10)
        assert got[3] == pytest.approx(want[3], rel=1e-10)


def test_topology_from_openmm_charges_sum_to_the_net_system_charge():
    # ALA-ALA built as a free (uncapped) dipeptide has a net charge of 0
    # (NH3+ cancels COO-) under amber14-all.xml. This is a real physical
    # check (not just "parses"), and it would fail if particle charges were
    # read from the wrong NonbondedForce slot or index-shifted.
    result = topology_from_openmm(FIXTURE)
    assert sum(result["charges"]) == pytest.approx(0.0, abs=1e-6)


def test_topology_from_openmm_feeds_ferric_mm_topology():
    # End-to-end: the dict this function returns must be directly usable by
    # ferric.MmTopology.from_amber_units without any further conversion.
    import ferric

    result = topology_from_openmm(FIXTURE)
    top = ferric.MmTopology.from_amber_units(
        charges=result["charges"],
        sigmas_angstrom=result["sigmas_angstrom"],
        epsilons_kcal=result["epsilons_kcal"],
        bonds=result["bonds"],
        angles=result["angles"],
        torsions=result["torsions"],
    )
    assert top.n_atoms() == 23
