[package]
name = "ferric-quadrature"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ferric-core = { path = "../ferric-core" }
ndarray = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
