[package]
name = "ferric-dft"
version = "0.1.0"
edition = "2021"

[dependencies]
ferric-core = { path = "../ferric-core" }
ferric-integrals = { path = "../ferric-integrals" }
ndarray = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
ferric-scf = { path = "../ferric-scf" }
