#!/usr/bin/env python3
"""Parse freshly re-run TS `.stdout` files (post-G8 vol_free fix) and emit a
JSON map {basis: {molecule: ts_c6}}.

Why this exists: scripts/dosd/results.csv, scripts/dosd2/results.csv, and
scripts/dosd3/results.md were all generated BEFORE commit ab8ba38 (G8, merged
eeda789, 2026-07-17) removed the scale-mismatched vol_free hardcoded-table
fallback from the TS-C6 CLI path. G8's own commit message demonstrates the
size of the effect on silicon: SiH4 TS C6 dropped from a stale 823.9-885.0
a.u. (+140% to +157% vs DOSD 343.9) to a fresh 442.6 a.u. (+29%) once the live
free-atom SCF (already the PRIMARY path) stopped being able to fall back to
the removed table on failure. The old table fallback was silently exercised
by at least Si (confirmed) in the committed dosd/dosd2/dosd3 CSVs; other
elements may or may not have been affected (Cl/CCl4 barely moved: 1993.9 ->
1997.4, ~0.2%, so the table fallback was evidently NOT hit for Cl at DZ).

Rather than guess which rows are stale, every TS TOML in dosd/dosd2/dosd3 was
re-run against a freshly rebuilt release binary. This script parses those
re-run stdouts (`Computed TS C6: ... molecular C6 = X a.u.`) into a JSON map
consumed by consolidate.py, so the paired test uses only fresh, current-code
TS numbers. RPA@PBE numbers are NOT re-run: G8 only touches the TS
free-atom-volume path, RPA@PBE has no free-atom reference at all, and the RPA
sweep is far more expensive (full RPA solve vs a handful of free-atom SCFs)
-- the existing committed RPA@PBE numbers in results.csv are retained
unchanged.

USAGE NOTE (2026-07-19 statistical-verdict task): the `*_ts.stdout` files
this script reads are deliberately NOT committed (scripts/README.md: raw
stdout logs are scratch, not permanent record). The current
`fresh_ts_c6.json` in this directory was hand-transcribed from the actual
sweep's terminal output rather than generated by this exact script run, for
the same reason. To regenerate `fresh_ts_c6.json` from scratch: rebuild the
release binary, re-run every `scripts/dosd*/runs/*/*_ts.toml` with output
redirected to `<toml-stem>.stdout` in the SAME directory (see the "Reproduce"
section of docs/rpa-vs-ts-statistical-verdict.md for the exact loop and the
worktree-path caveat), then run this script, then delete the `.stdout` files
again before committing.
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]

C6_RE = re.compile(r"molecular C6\s*=\s*([\d.]+)\s*a\.u\.")


def parse_stdout(path: Path):
    text = path.read_text()
    m = C6_RE.search(text)
    if not m:
        return None
    return float(m.group(1))


def main():
    out = {}
    for round_dir in ["dosd", "dosd2", "dosd3"]:
        for stdout_path in sorted((ROOT / "scripts" / round_dir / "runs").glob("*/*_ts.stdout")):
            basis = stdout_path.parent.name
            mol = stdout_path.stem.replace("_ts", "")
            val = parse_stdout(stdout_path)
            out.setdefault(round_dir, {}).setdefault(basis, {})[mol] = val

    with open(HERE / "fresh_ts_c6.json", "w") as f:
        json.dump(out, f, indent=2, sort_keys=True)

    for round_dir, bases in out.items():
        for basis, mols in bases.items():
            print(f"{round_dir}/{basis}: {len(mols)} molecules")
            for mol, val in sorted(mols.items()):
                print(f"  {mol:12s} {val}")


if __name__ == "__main__":
    main()
