#!/usr/bin/env python3
"""Bisect the B and T crossings vs the terf/terfc range-separation cutoff r0
(Å at the CLI boundary -- 2026-07-21 fix, see crates/ferric-cli/src/config.rs's
r0 doc), at aug-cc-pVQZ, across all 4 A24-subset dimers (idx 2 H2O-H2O, 5
NH3-NH3, 14 C2H4-C2H4, 19 CH4-CH4).

Companion to scripts/bisect_a24_aqz_crossing.py (which bisects the erf/erfc
omega parameter instead) -- same aQZ basis, same bisection-toward-CCSD(T)
logic, same benchmarks/a24-subset/out/ shared output dir and geometry files
(geom_a24-{idx}_{dimer,mA_cp,mB_cp}.xyz, already generated by
scripts/run_a24_omega_check.py -- reused here, not regenerated).

WHY r0 not omega: terf/terfc is the tempered (Dutoi/Goldey) attenuator, exact
via 2D interpolation tables (terf-tables/), as opposed to erf/erfc's
closed-form Boys-function attenuation. r0 -> inf (equivalently the derived
omega = 1/(r0*sqrt(2)) -> 0) recovers plain MP2 in the terfc limit; r0 -> 0
recovers MP2 + dRPA[Coulomb]. r0 is the single physical knob here -- never
set omega directly for a terf/terfc job (see
scripts/run_ethylene_terfc_sweep.py's omega_of() for the exact relation,
duplicated below since this script is standalone by the same convention as
every other script this session: no cross-script imports, so a single script
can be handed off, re-run, or read in isolation without chasing dependencies
across the repo).

trunc_thresh = 1e-3 (2026-07-21): per Matt's decision this session, PDEP
truncation now applies everywhere, including this validation-style bisection
-- see scripts/bisect_a24_aqz_crossing.py's docstring for the full rationale
and the superseded memory [[no-pdep-trunc-in-method-grid]] this departs from.

PREFLIGHT runs first and ABORTS if the binary rejects the terf stanza or
silently falls back to erf (same safeguard as run_ethylene_terfc_sweep.py) --
never record "terf" numbers that are secretly erf.

Usage:
  python3 scripts/bisect_a24_aqz_terfc_r0.py                # all 4 systems, B+T
  python3 scripts/bisect_a24_aqz_terfc_r0.py 14              # one system, B+T
  python3 scripts/bisect_a24_aqz_terfc_r0.py 14 B             # one system, B only

Env tunables: same convention as bisect_a24_aqz_crossing.py
  (BIS_FERRIC_MAX_GB, BIS_FERRIC_HIGH_GB, BIS_MEMORY_BUDGET_GB, BIS_GATE_GB,
   BIS_WAIT_S, BIS_TIMEOUT, BIS_R0_TOL, BIS_KCAL_TOL, BIS_MAX_ITERS)
  plus BIS_TABLE_DIR (terf-tables override, same as ET_TABLE_DIR).
"""
from pathlib import Path
import math
import os
import re
import subprocess
import sys
import time

ROOT = str(Path(__file__).resolve().parents[1])
os.chdir(ROOT)

OUT = "benchmarks/a24-subset/out"
BIN = "target/release/ferric-cli"
FERRIC_LIMITED = "scripts/ferric-limited"
K = 627.509474

RAYON_NUM_THREADS = os.environ.get("BIS_RAYON_THREADS", "8")
_LD_LIBRARY_PATH = os.pathsep.join(
    p for p in [os.path.expanduser("~/.local/lib"), os.environ.get("LD_LIBRARY_PATH", "")] if p)

_TERF_DIR = os.environ.get("BIS_TABLE_DIR", "")
if not _TERF_DIR or not os.path.exists(os.path.join(_TERF_DIR, "16_4_2.bin")):
    for cand in (f"{ROOT}/terf-tables"):
        if os.path.exists(os.path.join(cand, "16_4_2.bin")):
            _TERF_DIR = cand
            break

ENV = dict(os.environ, OPENBLAS_NUM_THREADS="1", RAYON_NUM_THREADS=RAYON_NUM_THREADS,
           OMP_NUM_THREADS="1", MKL_NUM_THREADS="1", LD_LIBRARY_PATH=_LD_LIBRARY_PATH,
           FERRIC_TERF_TABLE_DIR=_TERF_DIR)

FERRIC_MAX_GB = os.environ.get("BIS_FERRIC_MAX_GB", "16")
FERRIC_HIGH_GB = os.environ.get("BIS_FERRIC_HIGH_GB", "14")
MEMORY_BUDGET_GB = os.environ.get("BIS_MEMORY_BUDGET_GB", "4.0")
GATE_GB = float(os.environ.get("BIS_GATE_GB", "6"))
WAIT_S = int(os.environ.get("BIS_WAIT_S", "20"))
TIMEOUT = int(os.environ.get("BIS_TIMEOUT", "1800"))

R0_TOL = float(os.environ.get("BIS_R0_TOL", "0.02"))
KCAL_TOL = float(os.environ.get("BIS_KCAL_TOL", "0.01"))
MAX_ITERS = int(os.environ.get("BIS_MAX_ITERS", "8"))

BASIS, AUX = "aug-cc-pvqz", "aug-cc-pvqz-rifit"

# A24-subset systems in this codebase's established 4-dimer convention
# (benchmarks/a24-subset/run_a24.py, scripts/run_a24_omega_check.py):
# idx -> (name, CCSD(T)/CBS interaction energy, kcal/mol)
SYSTEMS = {
    2:  ("H2O-H2O", -5.014),
    5:  ("NH3-NH3", -3.157),
    14: ("C2H4-C2H4", -1.110),
    19: ("CH4-CH4", -0.538),
}

FORMS = {
    "B": "delta-lr",
    "T": "coupled-rings",
}

# Initial r0 bracket (Å -- 2026-07-21: [mp2] r0 is Å at the CLI boundary,
# fixed from Bohr, see crates/ferric-cli/src/config.rs's r0 doc) per
# formulation. r0->inf is the plain-MP2 limit, r0->0 is the MP2+dRPA[Coulomb]
# limit, so a wide bracket is needed the first time any given system is
# bisected -- these are generic starting brackets, not pre-computed seeds
# (unlike the omega script, no prior aTZ/aQZ r0 data exists yet to seed
# from). 0.1588 and 6.3501 Å (= 0.3 and 12.0 Bohr) mirror the ethylene terfc
# sweep's tested range (scripts/run_ethylene_terfc_sweep.py R0_DEFAULT).
# NOTE: crates/ferric-mp2/src/rimp2.rs:1178's terfc monotonicity test shows
# r0=2.0 A already recovers >95% of the full-Coulomb limit -- most of this
# bracket's upper range is past the physically discriminating region; for an
# A24-WIDE (not per-system) scan focused on that 0-2 A window, prefer
# scripts/scan_a24_aqz_terfc_r0_mae.py instead.
INITIAL_BRACKET = {
    "B": (0.1588, 6.3501),
    "T": (0.1588, 6.3501),
}


def ts():
    return time.strftime("%Y-%m-%d %H:%M:%S")


def log(m):
    print(f"[{ts()}] {m}", flush=True)


def mem_available_gb():
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemAvailable:"):
                    return int(line.split()[1]) / (1024 * 1024)
    except Exception:
        pass
    return 0.0


BOHR_INV_PER_ANG_INV = 1.0 / 1.8897259886  # crates/ferric-mp2/src/attenuated.rs:142


def omega_of(r0_ang):
    """Angstrom^-1 log label only (this script never feeds it back into an
    erf TOML omega= field, only prints it) -- matches run_ethylene_terfc_
    sweep.py's omega_of() convention after its 2026-07-21 unit fixes (both
    the omega_of Bohr-input bug AND the separate [mp2] r0 Bohr->Å CLI
    boundary change), so cross-referencing logs between scripts isn't
    misleading. r0_ang converts to Bohr first (the terf r0<->omega relation
    itself, main.rs:691, is computed in Bohr), then the resulting Bohr^-1
    omega converts to Å^-1."""
    r0_bohr = r0_ang * 1.8897259886
    omega_bohr = 1.0 / (r0_bohr * math.sqrt(2.0))
    return omega_bohr / BOHR_INV_PER_ANG_INV


def fc_count(xyz):
    n = 0
    for ln in open(xyz).read().splitlines()[2:]:
        if not ln.strip():
            continue
        s = ln.split()[0]
        if s.startswith("@") or s.upper().startswith("H"):
            continue
        n += 1
    return n


def terf_toml(xyz, r0, form, fc):
    # [mp2] r0 is Å at the CLI boundary (2026-07-21 fix, see
    # crates/ferric-cli/src/config.rs) -- r0 passed straight through, no
    # conversion needed here.
    return f"""[molecule]
xyz = "{xyz}"
[basis]
name = "{BASIS}"
[scf]
df_j_aux = "def2-universal-jkfit"
df_k_aux = "def2-universal-jkfit"
max_iter = 400
[method]
kind = "rs-mp2-rpa"
[mp2]
auxbasis = "{AUX}"
attenuator = "terf"
r0 = {r0}
formulation = "{form}"
frozen_core = {fc}
[rpa]
trunc_thresh = 1e-3
n_quad = 12
[memory]
budget_gb = {MEMORY_BUDGET_GB}
"""


def out_path(key):
    return f"{OUT}/{key}.out"


TOT_RE = re.compile(r'Total energy\s*=\s*(-?[0-9.]+)')


def grab_total(key):
    p = out_path(key)
    if not os.path.exists(p):
        return None
    m = TOT_RE.search(open(p).read())
    return float(m.group(1)) if m else None


def wait_for_gate(key):
    while True:
        avail = mem_available_gb()
        if avail >= GATE_GB:
            return
        log(f"[gate] {key}: {avail:.1f}GB avail (<{GATE_GB}); waiting {WAIT_S}s")
        time.sleep(WAIT_S)


def run_one(key, toml):
    op = out_path(key)
    if os.path.exists(op) and "Total energy" in open(op).read():
        return "skip", 0.0
    wait_for_gate(key)
    toml_path = f"{OUT}/{key}.toml"
    open(toml_path, "w").write(toml)
    cmd = [FERRIC_LIMITED, f"--max={FERRIC_MAX_GB}G", f"--high={FERRIC_HIGH_GB}G",
           "--", BIN, toml_path]
    t0 = time.monotonic()
    try:
        with open(op, "w") as f, open(op + ".err", "w") as e:
            subprocess.run(cmd, stdout=f, stderr=e, env=ENV, timeout=TIMEOUT)
    except subprocess.TimeoutExpired:
        return "TIMEOUT", time.monotonic() - t0
    ok = os.path.exists(op) and "Total energy" in open(op).read()
    return ("ok" if ok else "FAIL"), time.monotonic() - t0


def preflight():
    """Verify the binary accepts attenuator='terf' + r0 (not a silent erf
    fallback) before spending any real bisection compute. Uses the smallest
    A24 system (idx 19, CH4-CH4) at aQZ, a single cheap monomer-scale probe
    would be even cheaper, but reusing an already-staged dimer geometry and
    the real job path (same TOML shape as production jobs) is a stronger
    check than a synthetic minimal case."""
    xyz = f"{OUT}/geom_a24-19_mA.xyz"
    if not os.path.exists(xyz):
        log(f"PREFLIGHT FAIL: geometry {xyz} missing -- run "
            "scripts/run_a24_omega_check.py first to stage A24 geometries.")
        return False
    if not _TERF_DIR:
        log("PREFLIGHT FAIL: terf-tables directory not found. Set BIS_TABLE_DIR.")
        return False
    fc = fc_count(xyz)
    tp = f"{OUT}/_preflight_terf_a24-19.toml"
    open(tp, "w").write(terf_toml(xyz, 1.0, "delta-lr", fc))  # 1.0 A, mid-bracket probe
    cmd = [FERRIC_LIMITED, f"--max={FERRIC_MAX_GB}G", f"--high={FERRIC_HIGH_GB}G",
           "--", BIN, tp]
    r = subprocess.run(cmd, capture_output=True, text=True, env=ENV, timeout=600)
    combined = (r.stdout or "") + (r.stderr or "")
    if r.returncode != 0 or "Total energy" not in combined:
        log("PREFLIGHT FAIL: terf stanza rejected or job errored. Output tail:")
        for ln in combined.strip().splitlines()[-15:]:
            log(f"    | {ln}")
        return False
    low = combined.lower()
    if "attenuator" in low and "terf" not in low.split("attenuator", 1)[1][:40]:
        log("PREFLIGHT FAIL: binary ran but attenuator is not 'terf' -- likely "
            "silent erf-fallback. Refusing to sweep.")
        return False
    log("PREFLIGHT OK: terf stanza accepted at aQZ, CH4 monomer ran to 'Total energy'.")
    return True


def evaluate_r0(idx, r0, form, tag):
    frags = {"dimer": f"{OUT}/geom_a24-{idx}_dimer.xyz",
             "mA_cp": f"{OUT}/geom_a24-{idx}_mA_cp.xyz",
             "mB_cp": f"{OUT}/geom_a24-{idx}_mB_cp.xyz"}
    results = {}
    for fr, xyz in frags.items():
        if not os.path.exists(xyz):
            log(f"  missing geometry {xyz}")
            return None
        fc = fc_count(xyz)
        key = f"a24-{idx}_aqz_terf_r0{r0}_{tag}_{fr}"
        status, dt = run_one(key, terf_toml(xyz, r0, form, fc))
        log(f"  [{status:8s}] {dt:7.1f}s  {key}  (omega={omega_of(r0):.4f})")
        if status not in ("ok", "skip"):
            return None
        results[fr] = grab_total(key)
    if None in results.values():
        return None
    return (results["dimer"] - results["mA_cp"] - results["mB_cp"]) * K


def next_point(lo, hi):
    r1, e1 = lo
    r2, e2 = hi
    # bisect in log(r0) space: r0 spans multiple orders of magnitude (0.3 to
    # 12.0) and the physically meaningful step size scales with r0 itself,
    # not additively -- unlike omega, which the companion script bisects
    # linearly over a narrow O(0.1-0.8) range.
    l1, l2 = math.log(r1), math.log(r2)
    ccsdt = CCSDT_CURRENT
    f1, f2 = e1 - ccsdt, e2 - ccsdt
    if f2 == f1:
        l_interp = (l1 + l2) / 2.0
    else:
        l_interp = l1 - f1 * (l2 - l1) / (f2 - f1)
        span = abs(l2 - l1)
        if min(abs(l_interp - l1), abs(l_interp - l2)) < 0.05 * span:
            l_interp = (l1 + l2) / 2.0
    return math.exp(l_interp)


def bisect(idx, tag):
    name, ccsdt = SYSTEMS[idx]
    global CCSDT_CURRENT
    CCSDT_CURRENT = ccsdt
    form = FORMS[tag]
    log(f"=== A24-{idx} ({name}) {tag} ({form}) aQZ terf r0-bisection: "
        f"target {ccsdt} kcal/mol ===")
    r_lo0, r_hi0 = INITIAL_BRACKET[tag]
    e_lo = evaluate_r0(idx, r_lo0, form, tag)
    if e_lo is None:
        log(f"A24-{idx} {tag}: seed point at r0={r_lo0} FAILED -- aborting.")
        return
    log(f"A24-{idx} {tag}: r0={r_lo0} -> binding={e_lo:.4f} kcal/mol "
        f"(delta={e_lo - ccsdt:+.4f})")
    e_hi = evaluate_r0(idx, r_hi0, form, tag)
    if e_hi is None:
        log(f"A24-{idx} {tag}: seed point at r0={r_hi0} FAILED -- aborting.")
        return
    log(f"A24-{idx} {tag}: r0={r_hi0} -> binding={e_hi:.4f} kcal/mol "
        f"(delta={e_hi - ccsdt:+.4f})")
    lo, hi = (r_lo0, e_lo), (r_hi0, e_hi)

    if (lo[1] - ccsdt) * (hi[1] - ccsdt) > 0:
        log(f"A24-{idx} {tag}: seed bracket [{lo[0]}, {hi[0]}] does not straddle "
            f"zero (errs {lo[1]-ccsdt:+.4f}, {hi[1]-ccsdt:+.4f}) -- widening "
            "needed, stopping this system/formulation for manual re-seeding.")
        return

    log(f"=== A24-{idx} {tag} bisection: bracket [{lo[0]}, {hi[0]}] -> "
        f"[{lo[1]:.4f}, {hi[1]:.4f}] kcal/mol, target {ccsdt} ===")
    best = None
    for it in range(1, MAX_ITERS + 1):
        if abs(hi[0] - lo[0]) <= R0_TOL:
            log(f"A24-{idx} {tag}: bracket width <= {R0_TOL} -- converged.")
            break
        r0 = round(next_point(lo, hi), 4)
        if r0 in (lo[0], hi[0]) or r0 <= 0:
            log(f"A24-{idx} {tag}: next point {r0} collides with bracket "
                "endpoint or is non-physical -- stopping.")
            break
        log(f"A24-{idx} {tag} iter {it}: probing r0={r0}")
        e = evaluate_r0(idx, r0, form, tag)
        if e is None:
            log(f"A24-{idx} {tag} iter {it}: a leg FAILED at r0={r0} -- aborting.")
            return
        best = (r0, e)
        log(f"A24-{idx} {tag} iter {it}: r0={r0} -> binding={e:.4f} kcal/mol "
            f"(target {ccsdt}, delta={e - ccsdt:+.4f})")
        if abs(e - ccsdt) <= KCAL_TOL:
            log(f"A24-{idx} {tag}: |binding - CCSDT| <= {KCAL_TOL} -- "
                f"converged at r0={r0}.")
            break
        if (e - ccsdt) * (lo[1] - ccsdt) > 0:
            lo = (r0, e)
        else:
            hi = (r0, e)
    else:
        log(f"A24-{idx} {tag}: MAX_ITERS ({MAX_ITERS}) reached without converging.")
    if best is not None:
        log(f"A24-{idx} {tag}: best point r0={best[0]} (omega={omega_of(best[0]):.4f}) "
            f"-> binding={best[1]:.4f} kcal/mol (delta={best[1] - ccsdt:+.4f})")
    log(f"A24-{idx} {tag}: final bracket [{lo[0]}, {hi[0]}] -> "
        f"[{lo[1]:.4f}, {hi[1]:.4f}] kcal/mol")


CCSDT_CURRENT = None


def main():
    os.makedirs(OUT, exist_ok=True)
    args = sys.argv[1:]
    idx_args = [a for a in args if a.isdigit()]
    tag_args = [a for a in args if a in ("B", "T")]
    idxs = [int(a) for a in idx_args] or list(SYSTEMS)
    tags = tag_args or ["B", "T"]
    log(f"aQZ terf r0-bisection: systems={idxs}, forms={tags}")
    if not preflight():
        log("ABORT: preflight failed.")
        return
    for idx in idxs:
        for tag in tags:
            bisect(idx, tag)
    log("done.")


if __name__ == "__main__":
    main()
