[package]
name = "ferric-rpa"
version = "0.1.0"
edition = "2021"

[dependencies]
ferric-core = { path = "../ferric-core" }
ferric-integrals = { path = "../ferric-integrals" }
ferric-scf = { path = "../ferric-scf" }
ferric-mp2 = { path = "../ferric-mp2" }
ferric-quadrature = { path = "../ferric-quadrature" }
ferric-export = { path = "../ferric-export" }
serde = { workspace = true }
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
openblas-src = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
