// LANL2DZ exponents such as 0.318 are basis data, not approximations of 1/pi.
#![allow(clippy::approx_constant)]
//! ferric-owned ECP quadrature ([`ferric_integrals::ecp_quad`], the
//! `EcpBackend::Quadrature` backend) — FINDINGS "Iteration 25".
//!
//! Oracles (pinned, never called at test time): PySCF 2.13 `ECPscalar_sph`
//! with the 1e-3 zero-weight screen guard, an independent radial × Lebedev
//! quadrature, mpmath Bessel values, and the Python prototype's own values —
//! all in `testdata/reference/ecp_quadrature_refs.json`, generated by
//! `OPENBLAS_NUM_THREADS=1 /home/matt/qc/ferric/.venv/bin/python scripts/gen_ecp_quadrature_refs.py`.
//! Fixtures: HI/LANL2DZ (100 triples: 5 × 5 shells, 4 ECP centres incl. one
//! ON the bra I shells) and AuH/def2-SVP + def2-ECP (675 triples, f shells, 3
//! centres incl. on-Au).
//!
//! Bars come from the prototype's measurements (FINDINGS tables) with
//! headroom; every accuracy test has a negative control that must FAIL it
//! (libecpint, or a deliberately broken construction via `QuadKnobs`).

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_integrals::ecp::{
    ecp_block_deriv_spherical_with_backend, ecp_block_spherical_quadrature_knobs,
    ecp_block_spherical_with_backend, ecp_deriv_atom_ids, ecp_matrix_deriv_spherical_with_backend,
    ecp_matrix_spherical_with_backend, gto_norm, EcpBackend, EcpCenter, EcpGaussianShell,
};
use ferric_integrals::ecp_quad::bessel::ktil;
use ferric_integrals::ecp_quad::{semi_local_cart, Mutation, QuadKnobs, RadialRule};
use serde::Deserialize;
use std::sync::OnceLock;

const Q: EcpBackend = EcpBackend::Quadrature;
const LIB: EcpBackend = EcpBackend::Libecpint;

// ------------------------------------------------------------ pinned references

#[derive(Deserialize, Clone)]
struct ShellJ {
    l: i32,
    center: [f64; 3],
    exps: Vec<f64>,
    coefs: Vec<f64>,
}

#[derive(Deserialize, Clone)]
struct EcpJ {
    center: [f64; 3],
    ams: Vec<i32>,
    ns: Vec<i32>,
    exps: Vec<f64>,
    coefs: Vec<f64>,
}

#[derive(Deserialize)]
struct Fixture {
    bra: Vec<ShellJ>,
    ket: Vec<ShellJ>,
    ecps: Vec<EcpJ>,
    pyscf: Vec<Vec<f64>>,
    proto: Vec<Vec<f64>>,
}

#[derive(Deserialize)]
struct Tiny {
    bra: ShellJ,
    ket: ShellJ,
    ecp: EcpJ,
    lebedev: Vec<f64>,
    pyscf: Vec<f64>,
}

#[derive(Deserialize)]
struct Bessel {
    z: Vec<f64>,
    nmax: usize,
    values: Vec<Vec<f64>>,
}

#[derive(Deserialize)]
struct Refs {
    hi: Fixture,
    auh: Fixture,
    tiny: Tiny,
    bessel: Bessel,
}

fn refs() -> &'static Refs {
    static R: OnceLock<Refs> = OnceLock::new();
    R.get_or_init(|| {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../testdata/reference/ecp_quadrature_refs.json"
        );
        let text = std::fs::read_to_string(path).unwrap_or_else(|e| {
            panic!("read {path}: {e}\nrun scripts/gen_ecp_quadrature_refs.py first")
        });
        serde_json::from_str(&text).expect("parse ecp_quadrature_refs.json")
    })
}

fn shell(s: &ShellJ) -> EcpGaussianShell {
    EcpGaussianShell {
        l: s.l,
        center: s.center,
        exponents: s.exps.clone(),
        coefficients: s.coefs.clone(),
    }
}

fn ecp(e: &EcpJ) -> EcpCenter {
    EcpCenter {
        center: e.center,
        ams: e.ams.clone(),
        ns: e.ns.clone(),
        exponents: e.exps.clone(),
        coefficients: e.coefs.clone(),
    }
}

/// A fixture as (bra, ket, ecps) plus its triples `(a, b, u, index)` in the
/// pinned order (u fastest).
struct Fx {
    bra: Vec<EcpGaussianShell>,
    ket: Vec<EcpGaussianShell>,
    ecps: Vec<EcpCenter>,
}

impl Fx {
    fn from(f: &Fixture) -> Self {
        Self {
            bra: f.bra.iter().map(shell).collect(),
            ket: f.ket.iter().map(shell).collect(),
            ecps: f.ecps.iter().map(ecp).collect(),
        }
    }
    fn triples(&self) -> Vec<(usize, usize, usize, usize)> {
        let (nk, ne) = (self.ket.len(), self.ecps.len());
        (0..self.bra.len() * nk * ne)
            .map(|t| (t / (nk * ne), (t / ne) % nk, t % ne, t))
            .collect()
    }
}

fn hi() -> Fx {
    Fx::from(&refs().hi)
}

fn auh() -> Fx {
    Fx::from(&refs().auh)
}

/// Spherical block of ONE triple.
fn val(b: EcpBackend, sa: &EcpGaussianShell, sb: &EcpGaussianShell, e: &EcpCenter) -> Vec<f64> {
    ecp_block_spherical_with_backend(
        b,
        std::slice::from_ref(sa),
        std::slice::from_ref(sb),
        std::slice::from_ref(e),
        None,
    )
    .unwrap()
}

fn val_knobs(
    sa: &EcpGaussianShell,
    sb: &EcpGaussianShell,
    e: &EcpCenter,
    k: &QuadKnobs,
) -> Vec<f64> {
    ecp_block_spherical_quadrature_knobs(
        std::slice::from_ref(sa),
        std::slice::from_ref(sb),
        std::slice::from_ref(e),
        None,
        k,
    )
    .unwrap()
}

fn maxdiff(a: &[f64], b: &[f64]) -> f64 {
    assert_eq!(a.len(), b.len());
    a.iter()
        .zip(b)
        .fold(0.0_f64, |m, (x, y)| m.max((x - y).abs()))
}

fn amax(v: &[f64]) -> f64 {
    v.iter().fold(0.0_f64, |m, x| m.max(x.abs()))
}

fn dist(a: [f64; 3], b: [f64; 3]) -> f64 {
    (0..3).map(|k| (a[k] - b[k]).powi(2)).sum::<f64>().sqrt()
}

fn moved_shell(s: &EcpGaussianShell, x: usize, d: f64) -> EcpGaussianShell {
    let mut t = s.clone();
    t.center[x] += d;
    t
}

fn moved_ecp(e: &EcpCenter, x: usize, d: f64) -> EcpCenter {
    let mut t = e.clone();
    t.center[x] += d;
    t
}

/// Copy of `e` keeping only the listed channels (others' coefficients zeroed;
/// the local channel keeps its max-am tag).
fn only_channels(e: &EcpCenter, keep: &[i32]) -> EcpCenter {
    let mut t = e.clone();
    for (k, c) in t.coefficients.iter_mut().enumerate() {
        if !keep.contains(&e.ams[k]) {
            *c = 0.0;
        }
    }
    t
}

/// Richardson-extrapolated central FD `(4 FD(h/2) − FD(h))/3`.
fn richardson(f: &dyn Fn(f64) -> Vec<f64>, h: f64) -> Vec<f64> {
    let fd = |hh: f64| -> Vec<f64> {
        let (p, m) = (f(hh), f(-hh));
        p.iter()
            .zip(&m)
            .map(|(a, b)| (a - b) / (2.0 * hh))
            .collect()
    };
    let (f1, f2) = (fd(h), fd(0.5 * h));
    f1.iter()
        .zip(&f2)
        .map(|(a, b)| (4.0 * b - a) / 3.0)
        .collect()
}

// ============================================================ building blocks

/// k̃_n(z) = e^{−z} i_n(z) vs 40-digit mpmath, n ≤ 16, every regime edge
/// (0, 1e-8, the 4n switch points) and z ∈ [1e-300, 1e5]; each n_max the
/// kernel is called with. Bar 1e-14 relative (prototype measured ≤ 2.3e-15 for
/// n ≤ 12); an absolute 1e-300 floor covers subnormal results.
#[test]
fn bessel_matches_pinned_mpmath_table() {
    let b = &refs().bessel;
    assert_eq!(b.nmax, 16);
    let mut out = [0.0; 17];
    let mut worst = 0.0_f64;
    let mut at = (0usize, 0usize, 0.0f64);
    let mut checked = 0usize;
    for nm in [0usize, 1, 3, 6, 9, 12, 16] {
        for (iz, &z) in b.z.iter().enumerate() {
            ktil(nm, z, &mut out);
            for n in 0..=nm {
                let r = b.values[iz][n];
                let d = (out[n] - r).abs();
                checked += 1;
                if d <= 1e-300 {
                    continue;
                }
                let rel = if r != 0.0 { d / r.abs() } else { f64::INFINITY };
                if rel > worst {
                    worst = rel;
                    at = (nm, n, z);
                }
            }
        }
    }
    eprintln!(
        "ktil vs mpmath: {checked} values, worst relative {worst:.2e} (n_max {}, n {}, z {:e})",
        at.0, at.1, at.2
    );
    assert!(checked > 5000, "vacuous table");
    assert!(worst < 1e-14, "{worst:e} at {at:?}");
}

/// Production (radial tensor R + one angular contraction) vs forming
/// F^A_lm(r), F^B_lm(r) at every node and contracting Σ_m F^A F^B — an
/// independent contraction of the same projections (prototype ≤ 1.9e-13).
#[test]
fn radial_tensor_form_equals_explicit_projections() {
    let f = auh();
    let sel = [0usize, 6, 9, 11, 14];
    let mut worst = 0.0_f64;
    let mut n = 0;
    for (k, (a, b, u)) in sel
        .iter()
        .flat_map(|&a| {
            sel.iter()
                .flat_map(move |&b| (0..3).map(move |u| (a, b, u)))
        })
        .enumerate()
    {
        if k % 2 == 1 {
            continue;
        }
        let v1 = semi_local_cart(&f.bra[a], &f.ket[b], &f.ecps[u], false).unwrap();
        let v2 = semi_local_cart(&f.bra[a], &f.ket[b], &f.ecps[u], true).unwrap();
        worst = worst.max(maxdiff(&v1, &v2) / amax(&v2).max(1e-3));
        n += 1;
    }
    eprintln!("radial-tensor vs explicit F contraction: {n} triples, worst {worst:.2e}");
    assert!(worst < 1e-12, "{worst:e}");
}

/// Screening skips (primitive pair, term) windows whose bound is < 1e-16:
/// on the AuH f-shell fixture it changes no element by more than 1e-20
/// (prototype 8.6e-24).
#[test]
fn screening_changes_nothing_measurable() {
    let f = auh();
    let off = QuadKnobs {
        screen: false,
        ..QuadKnobs::default()
    };
    let sel = [0usize, 9, 11, 14];
    let mut worst = 0.0_f64;
    for &a in &sel {
        for &b in &sel {
            for e in &f.ecps {
                let on = val(Q, &f.bra[a], &f.ket[b], e);
                let of = val_knobs(&f.bra[a], &f.ket[b], e, &off);
                worst = worst.max(maxdiff(&on, &of));
            }
        }
    }
    eprintln!("screen on vs off: max |Δ| {worst:.2e}");
    assert!(worst < 1e-20, "{worst:e}");
}

// ============================================================ values vs oracles

/// `(max |ours − pyscf|, max over |pyscf| > 1e-6, max |ours − prototype|)`.
fn fixture_vs_refs(f: &Fx, r: &Fixture) -> (f64, f64, f64, usize) {
    let (mut all, mut big, mut proto, mut n) = (0.0_f64, 0.0_f64, 0.0_f64, 0usize);
    for (a, b, u, t) in f.triples() {
        let v = val(Q, &f.bra[a], &f.ket[b], &f.ecps[u]);
        for ((x, p), q) in v.iter().zip(&r.pyscf[t]).zip(&r.proto[t]) {
            let d = (x - p).abs();
            all = all.max(d);
            if p.abs() > 1e-6 {
                big = big.max(d);
            }
            proto = proto.max((x - q).abs());
            n += 1;
        }
    }
    (all, big, proto, n)
}

/// HI/LANL2DZ, 100 triples / 324 elements (elements up to 1.5), incl. the
/// on-centre bra I shells: bar 1e-12 (prototype 4.3e-14; libecpint is
/// 2e-7..7e-7 off — see `quadrature_backend_matches_libecpint_within_its_error`).
#[test]
fn hi_values_match_pinned_pyscf() {
    let (all, big, proto, n) = fixture_vs_refs(&hi(), &refs().hi);
    eprintln!(
        "HI/LANL2DZ: {n} elements, max |ours − PySCF| {all:.2e} (|V| > 1e-6: {big:.2e}); \
         max |ours − prototype| {proto:.2e}"
    );
    assert!(n == 324, "fixture size {n}");
    assert!(all < 1e-12, "{all:e}");
}

/// AuH/def2-SVP + def2-ECP (f shells, on- and off-centre), 675 triples:
/// elements > 1e-6 bar 1e-12 (prototype 1.4e-13); all elements 2e-12 (the
/// 7.3e-13 residue is PySCF's own floor on ~2e-12 elements, see
/// `tiny_element_matches_lebedev_where_pyscf_is_off`).
#[test]
fn auh_values_match_pinned_pyscf_f_shells() {
    let (all, big, proto, n) = fixture_vs_refs(&auh(), &refs().auh);
    eprintln!(
        "AuH/def2-SVP: {n} elements, max |ours − PySCF| {all:.2e} (|V| > 1e-6: {big:.2e}); \
         max |ours − prototype| {proto:.2e}"
    );
    assert!(n > 4000, "fixture size {n}");
    assert!(big < 1e-12, "{big:e}");
    assert!(all < 2e-12, "{all:e}");
}

/// Au s(tight) – Au d_L around the ECP at the H end (elements ~2e-12): the
/// independent radial × Lebedev value (1202 × 200/interval) agrees with ours
/// to ≤ 1e-15, and PySCF is > 1e-13 off it (so that disagreement is PySCF's).
#[test]
fn tiny_element_matches_lebedev_where_pyscf_is_off() {
    let t = &refs().tiny;
    let v = val(Q, &shell(&t.bra), &shell(&t.ket), &ecp(&t.ecp));
    let d_ours = maxdiff(&v, &t.lebedev);
    let d_pyscf = maxdiff(&t.pyscf, &t.lebedev);
    eprintln!(
        "tiny element (max |V| {:.2e}): |ours − Lebedev| {d_ours:.2e}, |PySCF − Lebedev| {d_pyscf:.2e}",
        amax(&t.lebedev)
    );
    assert!(amax(&t.lebedev) > 1e-12, "vacuous");
    assert!(d_ours < 1e-15, "{d_ours:e}");
    assert!(
        d_pyscf > 1e-13,
        "the oracle disagreement vanished: {d_pyscf:e}"
    );
}

/// Backend parity on the HI fixture: quadrature vs libecpint within
/// libecpint's own error. On THIS fixture the backends differ by up to
/// 3.51e-5 (max |V| 1.48; measured 2026-09-27), while the quadrature matches
/// the pinned PySCF values to <= 1e-12 (`hi_values_match_pinned_pyscf`), so the
/// 3.5e-5 is libecpint's error here (larger than the 2.3e-6..7e-7 recorded in
/// FINDINGS "clean-band discrepancy" on other elements). The bar 1e-4 only
/// guards a gross error in either backend; libecpint's floor is printed.
#[test]
fn quadrature_backend_matches_libecpint_within_its_error() {
    let f = hi();
    let mut worst = 0.0_f64;
    let mut scale = 0.0_f64;
    for (a, b, u, _) in f.triples() {
        let q = val(Q, &f.bra[a], &f.ket[b], &f.ecps[u]);
        let l = val(LIB, &f.bra[a], &f.ket[b], &f.ecps[u]);
        worst = worst.max(maxdiff(&q, &l));
        scale = scale.max(amax(&q));
    }
    eprintln!("HI: max |quadrature − libecpint| {worst:.2e} (max |V| {scale:.2})");
    assert!(scale > 0.1, "vacuous");
    assert!(worst < 1e-4, "{worst:e}");
}

// ============================================================ molecular paths

struct Mol {
    shells: Vec<EcpGaussianShell>,
    shell_atom: Vec<usize>,
    centres: Vec<EcpCenter>,
    groups: Vec<usize>,
    atoms: Vec<[f64; 3]>,
}

/// HI/def2-SVP (+ def2-ECP on I; d shells), shells atom by atom exactly as
/// `oneelectron::build_ecp_inputs` builds them.
fn hi_def2svp() -> Mol {
    let bs = basis::bundled("def2-svp").unwrap();
    let mut mol = Molecule::parse_xyz("2\n\nH 0.1 0.2 0.0\nI -0.1 0.05 1.61\n", 0, 1).unwrap();
    mol.apply_ecp(&bs);
    let mut m = Mol {
        shells: vec![],
        shell_atom: vec![],
        centres: vec![],
        groups: vec![],
        atoms: vec![],
    };
    for (ia, a) in mol.atoms.iter().enumerate() {
        let c = [a.x, a.y, a.zpos];
        m.atoms.push(c);
        for sh in bs.for_element(a.z).unwrap() {
            m.shells.push(EcpGaussianShell {
                l: sh.l,
                center: c,
                exponents: sh.exponents.clone(),
                coefficients: sh
                    .exponents
                    .iter()
                    .zip(&sh.coefficients)
                    .map(|(&x, &cc)| cc * gto_norm(sh.l, x))
                    .collect(),
            });
            m.shell_atom.push(ia);
        }
        if let Some(def) = bs.ecp_for_element(a.z) {
            let mut e = EcpCenter {
                center: c,
                ams: vec![],
                ns: vec![],
                exponents: vec![],
                coefficients: vec![],
            };
            for ch in &def.shells {
                for t in &ch.terms {
                    e.ams.push(ch.angular_momentum);
                    e.ns.push(t.r_exp);
                    e.exponents.push(t.gexp);
                    e.coefficients.push(t.coef);
                }
            }
            m.centres.push(e);
            m.groups.push(ia);
        }
    }
    m
}

/// The molecular matrix (upper triangle, mirrored) ≡ the square block with
/// every triple enabled, symmetric, and within libecpint's error of
/// libecpint's molecular matrix (5e-6 relative to the largest element:
/// libecpint's s-projector bias is ~2e-6 relative; triiodobenzene measured
/// 2.07e-7 max).
#[test]
fn molecular_matrix_equals_square_block_and_parity_with_libecpint() {
    let m = hi_def2svp();
    let v = ecp_matrix_spherical_with_backend(Q, &m.shells, &m.centres).unwrap();
    let blk = ecp_block_spherical_with_backend(Q, &m.shells, &m.shells, &m.centres, None).unwrap();
    let lib = ecp_matrix_spherical_with_backend(LIB, &m.shells, &m.centres).unwrap();
    let n = (v.len() as f64).sqrt() as usize;
    let mut asym = 0.0_f64;
    for i in 0..n {
        for j in 0..n {
            asym = asym.max((v[i * n + j] - v[j * n + i]).abs());
        }
    }
    let (d_blk, d_lib, sc) = (maxdiff(&v, &blk), maxdiff(&v, &lib), amax(&v));
    eprintln!(
        "HI/def2-SVP V_ECP ({n}×{n}, max {sc:.3}): |matrix − block| {d_blk:.2e}, asym {asym:.2e}, \
         |quadrature − libecpint| {d_lib:.2e}"
    );
    assert!(sc > 0.1, "vacuous");
    assert!(d_blk < 1e-13 * sc.max(1.0), "{d_blk:e}");
    assert!(asym < 1e-13 * sc.max(1.0), "{asym:e}");
    assert!(d_lib < 5e-6 * sc.max(1.0), "{d_lib:e}");
}

/// The existing single-iodine PySCF reference (`iodine_def2svp_ecpscalar.json`,
/// no screen guard) at the bar the libecpint backend meets (1e-8); printed.
#[test]
fn molecular_matrix_matches_the_iodine_pyscf_reference() {
    #[derive(Deserialize)]
    struct Sh {
        l: i32,
        center: [f64; 3],
        exps: Vec<f64>,
        coefs: Vec<f64>,
    }
    #[derive(Deserialize)]
    struct E {
        center: [f64; 3],
        ams: Vec<i32>,
        ns: Vec<i32>,
        exps: Vec<f64>,
        coefs: Vec<f64>,
    }
    #[derive(Deserialize)]
    struct R {
        shells: Vec<Sh>,
        ecp: E,
        ref_matrix: Vec<Vec<f64>>,
    }
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/reference/iodine_def2svp_ecpscalar.json"
    );
    let r: R = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    let shells: Vec<EcpGaussianShell> = r
        .shells
        .iter()
        .map(|s| EcpGaussianShell {
            l: s.l,
            center: s.center,
            exponents: s.exps.clone(),
            coefficients: s.coefs.clone(),
        })
        .collect();
    let e = EcpCenter {
        center: r.ecp.center,
        ams: r.ecp.ams.clone(),
        ns: r.ecp.ns.clone(),
        exponents: r.ecp.exps.clone(),
        coefficients: r.ecp.coefs.clone(),
    };
    let v = ecp_matrix_spherical_with_backend(Q, &shells, &[e]).unwrap();
    let want: Vec<f64> = r.ref_matrix.iter().flatten().copied().collect();
    let d = maxdiff(&v, &want);
    eprintln!("I/def2-SVP V_ECP: max |quadrature − PySCF| {d:.2e}");
    assert!(d < 1e-8, "{d:e}");
}

/// Molecular derivative (quadrature) ≡ the per-atom fold of the block
/// derivative (to roundoff: triangle-mirrored vs full), and within
/// libecpint's error of libecpint's molecular derivative (atom ids mapped by
/// `ecp_deriv_atom_ids`, the shared contract). Parity bar 1e-5 relative to
/// the largest element: libecpint's clean-band derivative error is ~1e-5
/// relative (FINDINGS), its molecular FD plateau 1.4e-7..2.2e-7.
#[test]
fn molecular_deriv_is_the_block_fold_and_parity_with_libecpint() {
    let m = hi_def2svp();
    let (dq, nat_q) = ecp_matrix_deriv_spherical_with_backend(Q, &m.shells, &m.centres).unwrap();
    let (dl, nat_l) = ecp_matrix_deriv_spherical_with_backend(LIB, &m.shells, &m.centres).unwrap();
    assert_eq!(nat_q, nat_l);
    let ids = ecp_deriv_atom_ids(&m.shells, &m.centres, &m.atoms).unwrap();
    let natoms = m.atoms.len();
    let d = ecp_block_deriv_spherical_with_backend(
        Q, &m.shells, &m.shells, &m.centres, None, &m.groups, natoms,
    )
    .unwrap();
    let n = d.nrow;
    let on: Vec<Vec<bool>> = (0..natoms)
        .map(|ia| {
            m.shells
                .iter()
                .zip(&m.shell_atom)
                .flat_map(|(s, &a)| std::iter::repeat_n(a == ia, (2 * s.l + 1) as usize))
                .collect()
        })
        .collect();
    let (mut w_fold, mut w_lib, mut sc) = (0.0_f64, 0.0_f64, 0.0_f64);
    for (k, &ia) in ids.iter().enumerate() {
        for x in 0..3 {
            let fold: Vec<f64> = (0..n * n)
                .map(|e| {
                    let (i, j) = (e / n, e % n);
                    let mut v = d.centre[ia][x][e];
                    if on[ia][i] {
                        v += d.bra[x][e];
                    }
                    if on[ia][j] {
                        v += d.ket[x][e];
                    }
                    v
                })
                .collect();
            w_fold = w_fold.max(maxdiff(&dq[3 * k + x], &fold));
            w_lib = w_lib.max(maxdiff(&dq[3 * k + x], &dl[3 * k + x]));
            sc = sc.max(amax(&fold));
        }
    }
    eprintln!(
        "HI/def2-SVP dV/dR (max {sc:.3}): |molecular − block fold| {w_fold:.2e}, \
         |quadrature − libecpint| {w_lib:.2e}"
    );
    assert!(sc > 0.1, "vacuous");
    assert!(w_fold < 1e-12 * sc.max(1.0), "{w_fold:e}");
    assert!(w_lib < 1e-5 * sc.max(1.0), "{w_lib:e}");
}

// ============================================================ smoothness

/// Max |residual| of a least-squares cubic through `(h, v)`.
fn cubic_residual(hs: &[f64], v: &[f64]) -> f64 {
    let hmax = hs.iter().fold(0.0_f64, |m, h| m.max(h.abs()));
    let t: Vec<f64> = hs.iter().map(|h| h / hmax).collect();
    let mut a = [[0.0_f64; 5]; 4];
    for (ti, vi) in t.iter().zip(v) {
        let p = [1.0, *ti, ti * ti, ti * ti * ti];
        for r in 0..4 {
            for c in 0..4 {
                a[r][c] += p[r] * p[c];
            }
            a[r][4] += p[r] * vi;
        }
    }
    for c in 0..4 {
        let piv = (c..4)
            .max_by(|&x, &y| a[x][c].abs().total_cmp(&a[y][c].abs()))
            .unwrap();
        a.swap(c, piv);
        for r in 0..4 {
            if r != c {
                let f = a[r][c] / a[c][c];
                for k in c..5 {
                    a[r][k] -= f * a[c][k];
                }
            }
        }
    }
    let coef: Vec<f64> = (0..4).map(|r| a[r][4] / a[r][r]).collect();
    t.iter()
        .zip(v)
        .map(|(ti, vi)| {
            let fit = coef[0] + ti * (coef[1] + ti * (coef[2] + ti * coef[3]));
            (vi - fit).abs()
        })
        .fold(0.0, f64::max)
}

/// One element over 41 points in ±5e-4 Bohr, moving the ECP centre along `x`.
fn scan(
    b: EcpBackend,
    sa: &EcpGaussianShell,
    sb: &EcpGaussianShell,
    e: &EcpCenter,
    x: usize,
    elem: usize,
) -> (f64, f64) {
    let hs: Vec<f64> = (-20..=20).map(|k| k as f64 * 2.5e-5).collect();
    let v: Vec<f64> = hs
        .iter()
        .map(|&h| val(b, sa, sb, &moved_ecp(e, x, h))[elem])
        .collect();
    (cubic_residual(&hs, &v), v[20].abs())
}

/// Cubic-fit scatter over ±5e-4 Bohr (41 points) of the worst off-centre
/// elements (FINDINGS smoothness table): HI MID (I p(1)–I p(1)_L, ECP at
/// I0 + (1.5, −1.2, 0.8), centre x, element (0, 2)), the same with the d
/// projector only, and AuH f–f_L (centre y, element (2, 3)). Bar 1e-12
/// (prototype 1.8e-16 / 2.6e-18 / 2.1e-14). NEGATIVE CONTROL: libecpint's
/// scatter on the two HI elements is 6.9e-7 (FINDINGS) — asserted > 1e-10, so
/// the scan can see the defect it guards against.
#[test]
fn values_are_smooth_in_geometry_and_libecpint_is_not() {
    let (h, a) = (hi(), auh());
    // hi: bra[4] = I p(1) at I0, ket[4] = I p(1) at I0 + LV, ecps[3] = the far centre
    let mid = &h.ecps[3];
    let dproj = only_channels(mid, &[2]);
    let cases: [(
        &str,
        &EcpGaussianShell,
        &EcpGaussianShell,
        EcpCenter,
        usize,
        usize,
    ); 3] = [
        ("HI MID", &h.bra[4], &h.ket[4], mid.clone(), 0, 2),
        ("HI MID d-projector only", &h.bra[4], &h.ket[4], dproj, 0, 2),
        // auh: bra[11] = Au f at Au0, ket[11] = Au f at Au0 + L, ecps[1] = U@Au+L+(.3,.2,−.25)
        (
            "AuH f–f_L",
            &a.bra[11],
            &a.ket[11],
            a.ecps[1].clone(),
            1,
            2 * 7 + 3,
        ),
    ];
    for (k, (name, sa, sb, e, x, elem)) in cases.iter().enumerate() {
        let (r, mag) = scan(Q, sa, sb, e, *x, *elem);
        eprintln!("smoothness {name}: |V| {mag:.2e}, cubic residual {r:.2e}");
        assert!(mag > 1e-4, "{name}: vacuous element {mag:e}");
        assert!(r < 1e-12, "{name}: {r:e}");
        if k < 2 {
            let (rl, _) = scan(LIB, sa, sb, e, *x, *elem);
            eprintln!("    libecpint (negative control): cubic residual {rl:.2e}");
            assert!(rl > 1e-10, "{name}: libecpint unexpectedly smooth ({rl:e})");
        }
    }
}

// ============================================================ derivatives

/// Per-triple slot checks, bra / ket / centre vs Richardson FD (h = 1e-3) of
/// the quadrature's OWN values, in EVERY distance band INCLUDING on-centre
/// (the FD then moves the shell THROUGH its centre — libecpint cannot).
/// Blocks with max |dV| > 1e-6: relative ≤ 1e-8 (prototype 9.7e-10 worst, the
/// FD floor); smaller blocks: absolute ≤ 1e-11.
#[test]
fn derivatives_match_fd_of_own_values_in_all_bands() {
    let (h, a) = (hi(), auh());
    let mut work: Vec<(&EcpGaussianShell, &EcpGaussianShell, &EcpCenter)> = h
        .triples()
        .into_iter()
        .step_by(3)
        .map(|(x, y, u, _)| (&h.bra[x], &h.ket[y], &h.ecps[u]))
        .collect();
    let sel = [6usize, 9, 11, 14];
    let au: Vec<_> = sel
        .iter()
        .flat_map(|&x| {
            sel.iter()
                .flat_map(move |&y| (0..3).map(move |u| (x, y, u)))
        })
        .collect();
    work.extend(
        au.iter()
            .step_by(5)
            .map(|&(x, y, u)| (&a.bra[x], &a.ket[y], &a.ecps[u])),
    );
    // bands: 0 on-centre, 1 < 1 Bohr, 2 >= 1 Bohr; (worst rel, worst abs small, blocks)
    let mut bands = [(0.0_f64, 0.0_f64, 0usize); 3];
    let fd_h = 1e-3;
    for (sa, sb, e) in work {
        let an = ecp_block_deriv_spherical_with_backend(
            Q,
            std::slice::from_ref(sa),
            std::slice::from_ref(sb),
            std::slice::from_ref(e),
            None,
            &[0],
            1,
        )
        .unwrap();
        let dmin = dist(sa.center, e.center).min(dist(sb.center, e.center));
        let band = if dmin < 1e-9 {
            0
        } else if dmin < 1.0 {
            1
        } else {
            2
        };
        for x in 0..3 {
            let fb = |d: f64| val(Q, &moved_shell(sa, x, d), sb, e);
            let fk = |d: f64| val(Q, sa, &moved_shell(sb, x, d), e);
            let fc = |d: f64| val(Q, sa, sb, &moved_ecp(e, x, d));
            for (f, slot) in [
                (&fb as &dyn Fn(f64) -> Vec<f64>, &an.bra[x]),
                (&fk, &an.ket[x]),
                (&fc, &an.centre[0][x]),
            ] {
                let fd = richardson(f, fd_h);
                let (d, sc) = (maxdiff(slot, &fd), amax(slot));
                let b = &mut bands[band];
                b.2 += 1;
                if sc > 1e-6 {
                    b.0 = b.0.max(d / sc);
                } else {
                    b.1 = b.1.max(d);
                }
            }
        }
    }
    for (name, b) in ["ON centre", "< 1 Bohr", ">= 1 Bohr"].iter().zip(&bands) {
        eprintln!(
            "deriv vs FD {name:10}: {:4} slot-blocks, worst rel (|dV| > 1e-6) {:.2e}, worst abs (small) {:.2e}",
            b.2, b.0, b.1
        );
    }
    assert!(
        bands.iter().all(|b| b.2 >= 30),
        "a band is too thin: {bands:?}"
    );
    for b in &bands {
        assert!(b.0 < 1e-8, "{bands:?}");
        assert!(b.1 < 1e-11, "{bands:?}");
    }
}

/// ∂/∂B_z ⟨H1s|U_I|H1s_L⟩, L = (0, 0, 7), ECP at I0 (FINDINGS Iteration 22
/// (2b)): target −6.658296236e-3 (independent quadrature). Prototype 4.4e-13;
/// libecpint 1.8e-8 off, PySCF ipnuc 1.1e-7. Bar 5e-12.
#[test]
fn quadrature_target_element() {
    const TARGET: f64 = -6.658296236e-3;
    let h = hi();
    // hi bra[0] = H STO-3G at H0, ecps[0] = I LANL2DZ at I0
    let sa = h.bra[0].clone();
    let mut sb = sa.clone();
    sb.center[2] += 7.0;
    let e = h.ecps[0].clone();
    assert!(dist(e.center, [0.9, -0.4, 3.3]) < 1e-12 && dist(sa.center, [0.3, 0.2, 0.4]) < 1e-12);
    let d = ecp_block_deriv_spherical_with_backend(Q, &[sa], &[sb], &[e], None, &[0], 1).unwrap();
    let v = d.ket[2][0];
    eprintln!(
        "dB_z <H1s|U_I|H1s_L>: {v:.12e}, |Δ target| {:.1e}",
        (v - TARGET).abs()
    );
    assert!((v - TARGET).abs() < 5e-12, "{v:e}");
}

/// bra + ket + Σ_g centre = 0 element-wise over a masked, two-group call,
/// and the masked multi-centre block ≡ the sum of its enabled triples.
#[test]
fn translation_invariance_and_masked_block_bookkeeping() {
    let h = hi();
    let bra: Vec<_> = h.bra[..3].to_vec();
    let ket: Vec<_> = h.ket[2..].to_vec();
    let ecps: Vec<_> = h.ecps[..3].to_vec();
    let nt = bra.len() * ket.len() * ecps.len();
    let mask: Vec<u8> = (0..nt).map(|k| u8::from(k % 3 != 0)).collect();
    let d = ecp_block_deriv_spherical_with_backend(
        Q,
        &bra,
        &ket,
        &ecps,
        Some(mask.as_slice()),
        &[0, 1, 0],
        2,
    )
    .unwrap();
    let (mut worst, mut scale) = (0.0_f64, 0.0_f64);
    for x in 0..3 {
        for k in 0..d.nrow * d.ncol {
            let s = d.bra[x][k] + d.ket[x][k] + d.centre[0][x][k] + d.centre[1][x][k];
            worst = worst.max(s.abs());
            scale = scale.max(d.bra[x][k].abs());
        }
    }
    let v = ecp_block_spherical_with_backend(Q, &bra, &ket, &ecps, Some(mask.as_slice())).unwrap();
    let nsph = |s: &EcpGaussianShell| (2 * s.l + 1) as usize;
    let ncol: usize = ket.iter().map(nsph).sum();
    let mut refv = vec![0.0; v.len()];
    let mut r0 = 0;
    for (ia, sa) in bra.iter().enumerate() {
        let mut c0 = 0;
        for (ib, sb) in ket.iter().enumerate() {
            for (iu, e) in ecps.iter().enumerate() {
                if mask[(ia * ket.len() + ib) * ecps.len() + iu] == 0 {
                    continue;
                }
                let t = val(Q, sa, sb, e);
                for p in 0..nsph(sa) {
                    for q in 0..nsph(sb) {
                        refv[(r0 + p) * ncol + c0 + q] += t[p * nsph(sb) + q];
                    }
                }
            }
            c0 += nsph(sb);
        }
        r0 += nsph(sa);
    }
    let dv = maxdiff(&v, &refv);
    eprintln!("bra + ket + centre: max {worst:.1e} (max |bra| {scale:.2e}); masked block vs triples {dv:.1e}");
    assert!(scale > 1e-3, "vacuous");
    assert!(worst < 1e-14 * scale.max(1.0), "{worst:e}");
    assert!(dv < 1e-15, "{dv:e}");
}

// ============================================================ negative controls

/// Worst |value − PySCF| over every 4th HI triple under `k`.
fn hi_worst(k: &QuadKnobs) -> f64 {
    let f = hi();
    let r = &refs().hi;
    f.triples()
        .into_iter()
        .step_by(4)
        .map(|(a, b, u, t)| maxdiff(&val_knobs(&f.bra[a], &f.ket[b], &f.ecps[u], k), &r.pyscf[t]))
        .fold(0.0, f64::max)
}

/// The same measure under production knobs passes its bar, and each broken
/// construction fails it by orders of magnitude (prototype: > 1e-3, > 1e-3,
/// > 1e-10).
#[test]
fn negative_controls_fail_the_value_bar() {
    let prod = hi_worst(&QuadKnobs::default());
    let trunc = hi_worst(&QuadKnobs {
        mutation: Mutation::TruncateLambda,
        ..QuadKnobs::default()
    });
    let power = hi_worst(&QuadKnobs {
        mutation: Mutation::RadialPowerShift,
        ..QuadKnobs::default()
    });
    let coarse = hi_worst(&QuadKnobs {
        rule: RadialRule {
            gl_max: 16,
            gl_min: 16,
            gh: 8,
        },
        ..QuadKnobs::default()
    });
    eprintln!(
        "vs PySCF: production {prod:.2e}; λ > l dropped {trunc:.2e}; r^(n−1) {power:.2e}; \
         GL-16/GH-8 {coarse:.2e}"
    );
    assert!(prod < 1e-12, "{prod:e}");
    assert!(
        trunc > 1e-3,
        "truncated plane-wave expansion passed: {trunc:e}"
    );
    assert!(power > 1e-3, "wrong radial power passed: {power:e}");
    assert!(
        coarse > 1e-10,
        "under-resolved radial grid passed: {coarse:e}"
    );
}

/// Long-distance element, NEGATIVE CONTROL for the exp-scaled Bessel
/// functions: ⟨H1s (STO-3G, 12 Bohr from the centre)|U_I|I p(1) (ON the
/// centre)⟩, I LANL2DZ, element (s, p_x) ≈ 2.0e-12 (prototype 1.969e-12).
/// Screening OFF so every (primitive pair, term) window is evaluated: the
/// tight H primitive's windows reach z = 2α|a|r ≈ 981. With
/// `k̃_n = e^{−z} i_n` they are finite and the element equals the screened
/// production value (prototype: identical); with unscaled `i_n` × the
/// unfactored Gaussians the same windows are e^{981} × e^{−772}, i.e.
/// inf × 0, and the element is NaN. (With screening ON those windows are
/// skipped, so the screen — not the scaling — would hide the defect; this
/// pins the construction itself.)
#[test]
fn unscaled_bessel_fails_the_long_distance_element() {
    let h = hi();
    let e = h.ecps[0].clone(); // I LANL2DZ at I0
    let mut sa = h.bra[0].clone(); // H STO-3G
    sa.center = [e.center[0] + 12.0, e.center[1], e.center[2]];
    let sb = h.bra[4].clone(); // I p(1) at I0 (on the centre)
    assert!(dist(sb.center, e.center) < 1e-12);
    let off = QuadKnobs {
        screen: false,
        ..QuadKnobs::default()
    };
    let prod = val(Q, &sa, &sb, &e)[0];
    let scaled = val_knobs(&sa, &sb, &e, &off)[0];
    let unscaled = val_knobs(
        &sa,
        &sb,
        &e,
        &QuadKnobs {
            mutation: Mutation::UnscaledBessel,
            ..off
        },
    )[0];
    eprintln!(
        "12-Bohr element: production {prod:.9e}, screen-off {scaled:.9e}, unscaled {unscaled:e}"
    );
    assert!((prod - 1.969e-12).abs() < 1e-14, "element moved: {prod:e}");
    assert!(
        scaled.is_finite() && (scaled - prod).abs() < 1e-20,
        "{scaled:e}"
    );
    assert!(
        !unscaled.is_finite() || (unscaled - prod).abs() > 1e-6 * prod.abs(),
        "unscaled Bessel construction survived: {unscaled:e}"
    );
}

/// Argument checks specific to the quadrature backend: a semi-local channel
/// above l = 5 or a negative r-power errors, never computes.
#[test]
fn quadrature_rejects_out_of_range_ecp_channels() {
    let h = hi();
    let mut e = h.ecps[0].clone();
    // make l = 6 a semi-local channel by adding a local channel at l = 7
    e.ams.extend([6, 7]);
    e.ns.extend([2, 2]);
    e.exponents.extend([1.0, 1.0]);
    e.coefficients.extend([1.0, 1.0]);
    assert!(ecp_block_spherical_with_backend(Q, &h.bra[..1], &h.ket[..1], &[e], None).is_err());
    let mut e = h.ecps[0].clone();
    e.ns[0] = -1;
    assert!(ecp_block_spherical_with_backend(Q, &h.bra[..1], &h.ket[..1], &[e], None).is_err());
}
