//! Unit 2 validation: the libecpint ECP shim (+ Cartesian→spherical transform)
//! must reproduce PySCF's spherical `ECPscalar` matrix element-by-element for a
//! single ECP atom (iodine, def2-SVP + def2-ECP).
//!
//! Reference generated by `scripts/gw100/gen_ecp_ref.py` into
//! `testdata/reference/iodine_def2svp_ecpscalar.json` (spherical — the
//! production convention, matching libint's spherical AO basis).

use ferric_integrals::ecp::{ecp_matrix_spherical, EcpCenter, EcpGaussianShell};
use serde::Deserialize;

#[derive(Deserialize)]
struct ShellRef {
    l: i32,
    center: [f64; 3],
    exps: Vec<f64>,
    coefs: Vec<f64>,
}

#[derive(Deserialize)]
struct EcpRef {
    #[allow(dead_code)]
    n_core: i32,
    center: [f64; 3],
    ams: Vec<i32>,
    ns: Vec<i32>,
    exps: Vec<f64>,
    coefs: Vec<f64>,
}

#[derive(Deserialize)]
struct Reference {
    nsph: usize,
    shells: Vec<ShellRef>,
    ecp: EcpRef,
    ref_matrix: Vec<Vec<f64>>,
}

#[test]
fn ecp_matrix_iodine_matches_pyscf() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/reference/iodine_def2svp_ecpscalar.json"
    );
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {path}: {e}\nrun scripts/gw100/gen_ecp_ref.py first"));
    let r: Reference = serde_json::from_str(&text).expect("parse reference JSON");

    let shells: Vec<EcpGaussianShell> = r
        .shells
        .iter()
        .map(|s| EcpGaussianShell {
            l: s.l,
            center: s.center,
            exponents: s.exps.clone(),
            coefficients: s.coefs.clone(),
        })
        .collect();

    let ecp = EcpCenter {
        center: r.ecp.center,
        ams: r.ecp.ams.clone(),
        ns: r.ecp.ns.clone(),
        exponents: r.ecp.exps.clone(),
        coefficients: r.ecp.coefs.clone(),
    };

    let vecp = ecp_matrix_spherical(&shells, &[ecp]).expect("ecp_matrix_spherical");
    let n = r.nsph;
    assert_eq!(vecp.len(), n * n, "matrix size mismatch");

    let mut max_abs_err = 0.0f64;
    let mut argmax = (0usize, 0usize);
    for i in 0..n {
        for j in 0..n {
            let got = vecp[i * n + j];
            let want = r.ref_matrix[i][j];
            let err = (got - want).abs();
            if err > max_abs_err {
                max_abs_err = err;
                argmax = (i, j);
            }
        }
    }
    let (mi, mj) = argmax;
    eprintln!(
        "max |V_ECP(ferric) - V_ECP(pyscf)| = {max_abs_err:.3e} at ({mi},{mj}): \
         got {:.10} want {:.10}",
        vecp[mi * n + mj],
        r.ref_matrix[mi][mj]
    );
    assert!(
        max_abs_err < 1e-8,
        "ECP matrix disagrees with PySCF by {max_abs_err:.3e} (> 1e-8) at ({mi},{mj})"
    );
}
