//! `ferric-mp2/src/canonical.rs` computes only the ~1/8 of shell quartets with
//! `s1 >= s2`, `s3 >= s4`, `(s1,s2) >= (s3,s4)` and reconstructs the other 7
//! permutation partners from the SAME computed buffer via index arithmetic
//! (see its `idx` array building `[(mu,nu,la,sg), (nu,mu,la,sg), ...]`). That
//! reconstruction is only correct if the *engine itself* actually produces the
//! same values when called with the permuted shell arguments directly -- i.e.
//! if libint2's real-Gaussian ERI kernel truly respects
//!
//!     (ij|kl) = (ji|kl) = (ij|lk) = (ji|lk) = (kl|ij) = (lk|ij) = (kl|ji) = (lk|ji)
//!
//! No test anywhere in this codebase called `Engine::compute_quartet` with
//! permuted shell indices and compared the results -- every existing engine
//! test (`compute_quartet` in `engine.rs`) only ever probes the identity
//! quartet `(0,0,0,0)`, where all 8 permutations coincide trivially and a
//! bra/ket or bra-exchange bug would be invisible. A wrong index convention in
//! the FFI shim, a transposed shell-pair loop, or a libint2 upgrade that
//! changes function ordering within a shell would silently corrupt every
//! energy in the codebase that relies on the 8-fold reconstruction (MP2, all
//! CC variants, RPA, GW's AO integrals) without tripping any existing test,
//! because they all compare against literature energies that are themselves
//! insensitive to a *symmetric* corruption of the ERI tensor.
//!
//! This test computes real shell quartets directly (not via the canonical
//! reconstruction) with all 8 index permutations passed independently to
//! `Engine::compute_quartet`, and checks the returned values agree
//! element-wise.

use ferric_core::basis;
use ferric_core::mol::Molecule;
use ferric_integrals::basis_bridge::PreparedBasis;
use ferric_integrals::engine::Engine;
use ferric_integrals::operator::Operator;

/// CO / STO-3G: the smallest fixture in this crate's test suite that has both
/// s and p shells on distinct atoms (C: 1s,2s,2p -> 3 shells; O: 1s,2s,2p -> 3
/// shells; 6 shells, 10 basis functions total). Large enough to exercise
/// s-s-s-s, mixed s/p, and p-p-p-p quartets; small enough that even the full
/// O(n^4) shell-quartet loop below is a handful of libint2 calls.
fn co_sto3g() -> PreparedBasis {
    let mol = Molecule::parse_xyz("2\nCO\nC 0 0 -0.6442\nO 0 0 0.4828\n", 0, 1).unwrap();
    let bs = basis::bundled("sto-3g").unwrap();
    PreparedBasis::new(&mol, &bs).unwrap()
}

/// Fetch the shell quartet `(s1,s2,s3,s4)` as an owned `Vec<f64>` (owned so
/// repeated calls on the same `Engine` -- which reuse one internal scratch
/// buffer -- don't alias). Panics if the quartet screens to zero; callers
/// only invoke this on quartets already confirmed nonzero.
fn quartet(eng: &mut Engine, prep: &PreparedBasis, s1: usize, s2: usize, s3: usize, s4: usize) -> Vec<f64> {
    eng.compute_quartet(prep, s1, s2, s3, s4)
        .unwrap_or_else(|| panic!("shell quartet ({s1},{s2},{s3},{s4}) unexpectedly screened to zero"))
        .to_vec()
}

/// Index into a flat shell-quartet buffer with dimensions `(n1,n2,n3,n4)`,
/// row-major with the first index slowest -- the SAME convention
/// `ferric-mp2/src/canonical.rs` uses to unpack `compute_quartet`'s buffer:
/// `q[((a * n2 + b) * n3 + c) * n4 + d]`.
fn at(buf: &[f64], n2: usize, n3: usize, n4: usize, a: usize, b: usize, c: usize, d: usize) -> f64 {
    buf[((a * n2 + b) * n3 + c) * n4 + d]
}

/// For real (non-complex) Gaussian basis functions the 2-electron Coulomb
/// integral is invariant under all 8 index permutations generated by bra
/// exchange (i<->j), ket exchange (k<->l), and bra-ket exchange
/// ((ij)<->(kl)). This test calls `Engine::compute_quartet` once per
/// permutation -- 8 independent libint2 evaluations per shell quartet, not
/// one evaluation reindexed -- so a bug in the FFI shim's argument handling,
/// a wrong function-ordering assumption inside a shell, or a genuine libint2
/// regression would show up as a mismatch here even though `canonical.rs`'s
/// reconstruction (which never re-calls the engine) would happily propagate
/// the corruption downstream undetected.
#[test]
fn eri_quartet_is_invariant_under_all_8_index_permutations() {
    let prep = co_sto3g();
    let dims = prep.shell_dims().to_vec();
    let nsh = prep.nshells();
    assert!(nsh >= 4, "fixture must have at least 4 shells to exercise mixed s/p quartets, got {nsh}");

    let mut eng = Engine::new_2e(Operator::coulomb(), &prep, 1e-14).unwrap();

    // Tolerance: all 8 permutations are the SAME analytic integral computed
    // by the SAME libint2 kernel, just with the 4 shell-index arguments
    // reordered -- there is no algorithmic difference (no truncation, no
    // different quadrature) between the branches, so any difference above
    // double-precision round-off is a real bug, not numerical noise. 1e-12
    // is tight relative to typical ERI magnitudes here (~1e-2 to ~5) while
    // leaving 2-3 orders of headroom over machine epsilon accumulation
    // through libint2's Boys-function recursion.
    let tol = 1e-12;

    let mut n_checked = 0usize;
    for s1 in 0..nsh {
        for s2 in 0..nsh {
            for s3 in 0..nsh {
                for s4 in 0..nsh {
                    // Only check each unordered quartet once.
                    if !(s1 >= s2 && s3 >= s4 && (s1, s2) >= (s3, s4)) {
                        continue;
                    }
                    let Some(canonical) = eng.compute_quartet(&prep, s1, s2, s3, s4).map(|s| s.to_vec()) else {
                        continue; // screened to zero; nothing to compare
                    };
                    let (n1, n2, n3, n4) = (dims[s1], dims[s2], dims[s3], dims[s4]);
                    assert_eq!(canonical.len(), n1 * n2 * n3 * n4);

                    let ji_kl = quartet(&mut eng, &prep, s2, s1, s3, s4); // bra exchange
                    let ij_lk = quartet(&mut eng, &prep, s1, s2, s4, s3); // ket exchange
                    let ji_lk = quartet(&mut eng, &prep, s2, s1, s4, s3); // both
                    let kl_ij = quartet(&mut eng, &prep, s3, s4, s1, s2); // bra-ket exchange
                    let lk_ij = quartet(&mut eng, &prep, s4, s3, s1, s2);
                    let kl_ji = quartet(&mut eng, &prep, s3, s4, s2, s1);
                    let lk_ji = quartet(&mut eng, &prep, s4, s3, s2, s1);

                    for a in 0..n1 {
                        for b in 0..n2 {
                            for c in 0..n3 {
                                for d in 0..n4 {
                                    let v0 = at(&canonical, n2, n3, n4, a, b, c, d);

                                    let checks: [(&str, f64); 7] = [
                                        ("(ji|kl)", at(&ji_kl, n1, n3, n4, b, a, c, d)),
                                        ("(ij|lk)", at(&ij_lk, n2, n4, n3, a, b, d, c)),
                                        ("(ji|lk)", at(&ji_lk, n1, n4, n3, b, a, d, c)),
                                        ("(kl|ij)", at(&kl_ij, n4, n1, n2, c, d, a, b)),
                                        ("(lk|ij)", at(&lk_ij, n3, n1, n2, d, c, a, b)),
                                        ("(kl|ji)", at(&kl_ji, n4, n2, n1, c, d, b, a)),
                                        ("(lk|ji)", at(&lk_ji, n3, n2, n1, d, c, b, a)),
                                    ];

                                    for (name, v) in checks {
                                        assert!(
                                            (v0 - v).abs() < tol,
                                            "8-fold ERI symmetry broken for shells ({s1},{s2},{s3},{s4}) fn ({a},{b},{c},{d}): \
                                             (ij|kl) = {v0:.15e} vs {name} = {v:.15e}, diff = {:.3e}",
                                            (v0 - v).abs()
                                        );
                                    }
                                    n_checked += 1;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    assert!(n_checked > 0, "no nonzero shell quartets were found to check -- fixture is degenerate");
}
